### ISSUE TITLE
Server with multiple IPs. How to force SMPP Client use non-default IP ? Proposed solution

### ISSUE THREAD

**Issue by dctikan** [jookies/jasmin#1005]
Hi, 
It appears that SMPP Client is always using a default IP when it established TCP IP connection. It creates an issue when a server has multiple IPs and SMPP connection must be made from a particular (non-default) IP address.

Is there a way to make force SMPP Client use non-default server IP ? 

If not, then maybe jasmin needs a new [smpp-client] config section with BIND and PORT options.

In the code 

It looks like in
SMPPClientFactory(ClientFactory):
is using reactor.connectTCP to establish connection

according to Reactor Connect definition it accepts bindAddress
connectTCP(host, port, factory, timeout=30, bindAddress=None):
bindAddress is a (host, port) tuple of local address to bind to, or None. 
So we just need access config values and pass them into connectTCP.

**Comment by dctikan** [comment]
BTW if multiple client connectors need to be listening on the same IP then it is probably better to have IP and PORT as client connector configuration (not config file).

**Comment by magojr** [comment]
Hi @dctikan,
I'm not sure to understand exactly your point: if you have multiple IP setted up on the box, you may want Jasmin use a different IP for outgoing connection than (for example) smtp, web services and so on. It seems you found a way to do so by the config file, isn't it? 
If you connect to 10 different SMSC you should use the same IP, it's not a "must" but it should be the practice.
If you would like to assign a dedicated IP to different client/customer connecting to jour jasmin you can easily create a port forwarding NAT on the 2775 from the IP you want to the IP used from Jasmin in the box (I easily managed it with a single pfSense and it works well, it should be the same in any router).

**Comment by dctikan** [comment]
I am sorry if I was not clear.
We have a vendor which we need to connect over SMPP to be able to send and receive message. However, this vendor requires IPSEC to be setup which will be used to connect to their SMPP server. So we setup IPSEC tunnel on the server on a dedicated IP (not default IP on the server). However, as you may know, IPSEC is policy based (not routing) so any build in networking tools (like routing table, NAT, IP rewrite) to reroute IPs over IPSEC tunnel do not work and network connections must be make from the correct IP to be routed over the tunnel.

Unfortunatey Jasmin's SMSC does NOT allow up to specify local IP which will used to establish connection and it always using the default server IP.

To address the issue we had to modify factory.py SMPPClientFactory _connect method to pass a desired IP using (IP:PORT) tuple.

That is why I proposed an additional IP PORT options for SMSC

**Comment by tarikogut** [comment]
contact me on skype tarikogut i will help you
