### ISSUE TITLE
Receiving SMS - Unicode

### ISSUE THREAD

**Issue by geethupendra** [jookies/jasmin#1014]
Hello,

Anyone using https://docs.jasminsms.com/en/latest/programming-examples/index.html#receiving-sms for data save as Unicode message in DB.
I have tried (Sinhala Unicode - https://it.wikipedia.org/wiki/Sinhala_(Unicode)) but it's blank.

Message receiving like...

Eg:
\r\x85 --> අ
\r\x87 --> ඇ 

anyone can support it?

Thanks
Geeth

**Comment by farirat** [comment]
You can receive the message content in hex format using the hex-content parameter: https://docs.jasminsms.com/en/latest/apis/ja-http/index.html

**Comment by geethupendra** [comment]
Thanks
