### ISSUE TITLE
[Question] Does Jasmin support ShortCode over SMPP Protocol?

### ISSUE THREAD

**Issue by Daniel3356** [jookies/jasmin#1015]
I'm looking for a solution for sending short code SMS over SMPP protocol. I have a GSM modem and I was wondering if it's possible to do it with Jasmin? 

If it's possible are they any documentation to follow along? 
Thanks

**Comment by tarikogut** [comment]
use it kannel. or gammu

**Comment by DanielAbsi** [comment]
That's not what I ask for.

**Comment by farirat** [comment]
Jasmin has smpp upstream only, commercial support can provide plugin to allow multi-protocol upstreams (including gsm, http, ss7, etc ..)

**Comment by AnythingLinux** [comment]
@DanielAbsi yes you can use jasmin to set a Short Code as a Sender ID on an SMPP connection for some listed countries. For more check International support for Alphanumeric Sender ID 

https://support.twilio.com/hc/en-us/articles/223133767-International-support-for-Alphanumeric-Sender-ID
