### ISSUE TITLE
service_type not available in SMPP Config

### ISSUE THREAD

**Issue by gamefia** [jookies/jasmin#1017]
There is a service_type parameter for SMPP config. However, this is not part of the documentation. The closest is 'systype': 'systemType'.

How do I set the service_type?

**Comment by farirat** [comment]
can you reference where i can find the "service_type" parameter in the smpp 3.x specs ?

**Comment by gamefia** [comment]
Please check section 5.2.11 on page 120  of https://smpp.org/SMPP_v3_4_Issue1_2.pdf

**Comment by farirat** [comment]
this is a message parameter unlike the system_type which is a bind parameter.
you are limited to the http params when sending sms through http api, and you are free when using smpp.

**Comment by gamefia** [comment]
Alright
