### ISSUE TITLE
Documentation Issue - Installing Jasmin SMS on Windows

### ISSUE THREAD

**Issue by amaajemyfren** [jookies/jasmin#1024]
Hi,

since Jasmin SMS is written in Python - potentially it could run on Windows - please provide documentation on how to install it and run it in windows. If it is not possible to run it as a service in Windows either directly or with [sc](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc754599(v=ws.11)), [nssm](http://nssm.cc/) etc then please advise so.

**Comment by tarikogut** [comment]
have 2 way
1. way install wsl ubuntu and use it
2. use docker

amaajemyfren ***@***.***>, 6 Şub 2022 Paz, 13:59 tarihinde
şunu yazdı:

**Comment by farirat** [comment]
@amaajemyfren your contrib is most welcome :) start by a pr and things will follow +1
