### ISSUE TITLE
SMS submitted but not received by client

### ISSUE THREAD

**Issue by jaur-jaur** [jookies/jasmin#1029]
I use Jasmin 0.10.9 and HTTP API to send sms to mobile users. When I request with http://my@Ip:1401/send?username=foo&password=bae&from=sender&to=xxxxx&content="est%20423247" I got success output. 
---success "998c5af3-7846-4bf7-97c2-9fcd6294e0d3"
But in messages.log  I have that :
2022-02-23 23:22:32 INFO     338437 SMS-MT [cid:Net4-bf] [queue-msgid:998c5af3-7846-4bf7-97c2-9fcd6294e0d3] [smpp-msgid:b'3550b803'] [status:CommandStatus.ESME_ROK] [prio:0] [dlr:RegisteredDeliveryReceipt.SMSC_DELIVERY_RECEIPT_REQUESTED] [validity:none] [from:b'sender'] [to:b'xxx78000198'] [content:b'est%20423247']
While I'm observing submit_sm_count updated in smpp connector used when sending the sms, It is still **not received** by the destinate

<<I would know also why these fields content;to;from are preceded by b''

Please Do anyone know what is wrong 
>>

**Comment by farirat** [comment]
hey @jaur-jaur 

since your message were forwarded (in messages.log) and you have a msgid from your upstream ([smpp-msgid:b'3550b803']) then this is out of jasmin's scope.

you can ask your provider where did the message with msg_id:3550b803 land on ?

**Comment by jaur-jaur** [comment]
Right  It's done
Thanks a lot !
