### ISSUE TITLE
Changing user password in jcli to some user - breaks user authentication

### ISSUE THREAD

**Issue by texpert** [jookies/jasmin#103]
In jasmin 0.6b3 - if a user is already in the list with some password, and I run:

user -u username
password somepassword
ok

-> then sending SMS-MT by http brings Authentication error...

Removing the user with user -r user, and then adding the same user with the desired new password - makes it OK

**Comment by fourat** [comment]
Aurel, i've tryed to reproduce the scenario and i've got nothing to claim about, i set my password, checked that i can authenticate to http api, then updated it and when i reload the url again i get:

    Error "Authentication failure for username:fourat"

Can you please provide your steps-to-reproduce ?

**Comment by fourat** [comment]
@texpert any update ? can you please confirm or not this issue ?

**Comment by texpert** [comment]
Yes, Fourat, confirming it, though had no time yet for comprehensive testing, but the scenario is like this - I have tried it yesterday again with Jasmin 0.6b4:

Add an user 'user -a someuser' with some password '1st_password"
Send an SMS through http API - brings Success
Then changing the user's password 'user -u someuser; password 2nd_password; ok'
Send an SMS through http API with the same user and 2nd_password - Authentication error

Will test it better when more time will appear.

**Comment by fourat** [comment]
Bug confirmed
