### ISSUE TITLE
Failed to send my first SMS message using docker-compose installation.

### ISSUE THREAD

**Issue by Vccxx** [jookies/jasmin#1035]
I'm following the official tutorial [here](https://docs.jasminsms.com/en/latest/installation/index.html) to install jasmin client and server to send message to my own phone.

I followed the tutorial step by step and everything seems works fine until I found I can't receive any message after I got the feedback which should means success:
![image](https://user-images.githubusercontent.com/21141761/156826685-56135fcf-a5eb-433b-b7f9-6d317f911f74.png)

I check the output of ` cat /var/log/jasmin/jcli.log ` and found the config file `'/etc/jasmin/store/jcli-prod.filters` and `/etc/jasmin/store/jcli-prod.httpccs` seems missing:

![1646420937(1)](https://user-images.githubusercontent.com/21141761/156826445-ab014c2d-390c-4eb2-a4f1-7dcd6d993f68.png)

And the `/var/log/jasmin/messages.log` keep saying that "SMPPC is not connected":

![image](https://user-images.githubusercontent.com/21141761/156827158-4ced11b3-07a6-40be-a685-462242573130.png)

I don't think is the conection problem because I can ping my server from jasmin client docker container and  I didn't receive any connection on the jasmin server . But FYI , I use the same docker and same step on my server with a /etc/jasmin/jasmin.cfg file in which I uncomment the [smpp-server] config like this , and I use this docker as smpp-server (run on different machine and the network is fine.)

![image](https://user-images.githubusercontent.com/21141761/156827469-fdf522c5-acd4-4ec9-a2ec-8f7b8dc54cec.png)

I wonder if there is anything I misunderstood about the smpp client and server deployment, I would appreciate it if you can offer any help.

**Comment by farirat** [comment]
What's in your default-smpps_01.log (smpp server side) and default-DEMO_CONNECTOR.log (smpp client side) ?

**Comment by Vccxx** [comment]
The content of /var/log/jasmin/default-smpps_01.log on the server side is:
![image](https://user-images.githubusercontent.com/21141761/156872919-9013d960-1c32-4dce-830b-89fc77ee63df.png)
The content of /var/log/jasmin/default-DEMO_CONNECTOR.log on the client side is:
![image](https://user-images.githubusercontent.com/21141761/156873535-ee39fa48-e823-470f-96a1-8199ff063e38.png)
It seems that it's the "Invalid password" issue , I notice that in this [link](https://docs.jasminsms.com/en/latest/apis/smpp-server/index.html) you have written about the `system_id` and `password` to bind to the server , but I can't figure out where to config these two  parameters.

**Comment by farirat** [comment]
On smpp server side you may manage your users with jcli's user and group modules, and on smpp client side, you set username and password of the connector when creating/updating it with jcli's smppccm module.

**Comment by Vccxx** [comment]
@farirat What you mean is that I should configure the same group and username/password on the server using jcli just like what I do on the client side?
![image](https://user-images.githubusercontent.com/21141761/156873974-b7f43257-3983-483c-b82c-60e6a4047c74.png)

**Comment by Vccxx** [comment]
@farirat  I have solved the connection problem , Thanks for your help. But there still no SMS message sent to my phone. I check the `/var/log/jasmin/default-smpps_01.log` and it says that something wrong with the router module:
![image](https://user-images.githubusercontent.com/21141761/156876473-ff15b3ef-5c6d-4392-ad8a-b98922b98412.png)

**Comment by farirat** [comment]
you have to set mtroute to allow routing of your submit through your provider.
