### ISSUE TITLE
jcli command not found in the jookies/jasmin:0.10 docker container

### ISSUE THREAD

**Issue by wandermonk** [jookies/jasmin#1038]
I am trying to use the docker compose yaml file to configure user and password to use the REST API. when i try to execute jcli.

docker exec -it 41569eb946ef /bin/bash
root@41569eb946ef:/usr/jasmin# jcli
bash: jcli: command not found

jcli command is not found.

**Comment by sebin** [comment]
From the [documentation](https://docs.jasminsms.com/en/latest/management/jcli/index.html#first-connection-authentication):

```
In order to connect to jCli, initiate a telnet session with the hostname/ip and port of jCli as set in [Configuration](https://docs.jasminsms.com/en/latest/management/jcli/index.html#configuration-jcli):

telnet 127.0.0.1 8990
```
