### ISSUE TITLE
Unknown sender id | DELIVER_SM not sent by SMSC

### ISSUE THREAD

**Issue by jaur-jaur** [jookies/jasmin#1039]
I try to test DLR reception by sending sms through Jasmin HTTP API and face to two issues :
1. the recipient got the sms with no unknown sender 
2. I can see [dlr:SMSC_DELIVERY_RECEIPT_REQUESTED] in my log file but the provider do not respond to the DLR request 

I found an alternative to test the DLR reception by using smpp client to send an sms. Otherwise, I didn't found a way to
request DLR using SMPP Client in the same way that http with dlr dlr-level and dlr-url parameters. 

--HTTP Request
http://xx.xx.xx.x:1401/send?username=smsuser&password=xxxx&dlr=yes&dlr-level=2&from=INFO NET&to=xxxxx&content=xxxxxxxxxxxxx

--SMPP Client used
![smpp tester](https://user-images.githubusercontent.com/53447559/158880631-f4cba23b-caa0-4b9c-9e0c-ace419c6a1f8.jpg)

Does anyone can support me in searching a way to end up with this situation.
Why recipients got sms with unknown sender whereas a sender value is set in the HTTP request ?
Is the sms provider fault to deliver me receipt ? 
Is it possible to request DLR using a SMPP client ?

Thank you in advance

**Comment by magojr** [comment]
Hi jaur-jaur,
I think you should ask these questions to your upstream provider.
Jasmin itself send the SMS to the upstream provider... if it comes to your phone, it's working.
If the connection is active (or upon a new connection) you should recevive DLR if the upstream provider supply them and if their supplier send it back to him (so there are a lot of ring in the chain and it's probably not in your jasmin box the issue).
About the sender there are specific "country restriction" based on local laws created to avoid phishing. Here in my country there are a list of "registered sender" and local terminating operators don't permit to use them except from who registered the sender... Also the upstream provider usually has a blacklist for specific word often used for spam and phishing and "INFO NET" is quite general to let me think it may be the case. Try with a "Test" sender.
As the web api codes correctly the message, it should not be a coding issue.
Anyway i soggest you to url-encode the url so using %20 unstead spaces (the browser should do it for you but... give it a try).

**Comment by farirat** [comment]
I see no **dlr-url** parameter in your http request ?

**Comment by jaur-jaur** [comment]
@magojr  I GOT your suggestions. I will come you back whith the results when available. Meanwhile where can I find a SMPP Client with DLR request feature ?

**Comment by jaur-jaur** [comment]
Hi @farirat, I did not put that cause I just certify that they send me DELIVER_SM. So, I have captured packets to looking for a DELIVER_SM PDU. Thus, I could confirm I receive DLR from the provider. Besides, I have possibility to see it in JCLI with **deliver_sm_count** item from stats command on smpp connector.

**Comment by farirat** [comment]
If you dont put dlr-url then jasmin will not ask for dlr from provider even if you set dlr=yes and dlr-level=3/2/1

**Comment by jaur-jaur** [comment]
@farirat, I tried this simple script but not received DLR when browsing the page.

`<?php`
`$MO_SMS=$_GET; `
`//extract variable`
`extract($MO_SMS);`
`//display values`
`echo "<pre>";`
`var_dump($MO_SMS);`
`echo "</pre>";`
`// acking reception`
`echo "ACK/Jasmin";`
`?>`

--parameter added to previous request
dlr-url=host/dlr-request.php

-- http log file
 "GET /dlr-request.php HTTP/1.1" 200 34

Am I missing something ?
