### ISSUE TITLE
Jasmin Web-hook (dlr-url) | how to script in php

### ISSUE THREAD

**Issue by jaur-jaur** [jookies/jasmin#1043]
Hi, 
I am using the script below to try retrieving DLR from SMSC.  When I browse the php page, There are nothing displayed.

-My http request is
http://xx.xx.xx.x:1401/send?username=smsuser&password=xxxx&dlr=yes&dlr-level=2dlr-url=http://host/dlr-request.php&dlr-method=POST&from=INFO NET&to=xxxxx&content=xxxxxxxxxxxxx

---dlr-request.php
```
<?php
$MO_SMS=$_POST;
//extract variable
extract($MO_SMS);
//display values
echo "<pre>";
var_dump($MO_SMS);
echo "</pre>";
// acking reception
echo "ACK/Jasmin";
?>

```
![image](https://user-images.githubusercontent.com/53447559/159527318-4369c3b0-2b7e-49ab-9a1a-6ddf1ee738dc.png)

Can I get any help to just testing retrieving DLR

Thanks in advance

**Comment by kiswend** [comment]
Jasmin expect your page to return the content ACK/Jasmin. It's the only echo you should have I the page.

Your are free to use The POST or GET data your receive. You may trigger an action or save in a database.
