### ISSUE TITLE
DLR and DELIVER_SM

### ISSUE THREAD

**Issue by jaur-jaur** [jookies/jasmin#1048]
HI Everyone,

After sending sms, I am able to see DLR in dlrlookupd-messages.log but not **DELIVER_SM** in default-smpps_01.log
INFO     3408003 DLR [cid:Net4] [smpp-msgid:516D3A7A] [status:DELIVRD] [submit date:2204121657] [done date:2204121657] [sub/dlvrd messages:ND/ND] [err:000] [content:'']

Are  there a difference beetween DLR and DELIVER_SM logs ?
what I do not receive DELIVER_SM as I see DLR in dlrlookupd-messages.log ?

Thanks in advance guys !

**Comment by magojr** [comment]
For what I know, default-smpps_01.log logs the connection task/error to external smpp connector....
It logs information like: connected to connectorAAA; bind bind_transceiver to...;  connection lost for...; etc... it doesn't log any PDU that pass in the connector (I'm not sure if you set DEBUG level it may also log that...).
The deliver_sm  PDU generate a DLR that is managed from dlrlookupd and logged at apoplication level in dlrlookupd-messages.log. That's it.
Why you should have the "protocol level" log (DELIVER_SM) when  dlrlookupd  "decode" it for you and give you a correct  readable format for it in default-smpps_01.log ?

**Comment by jaur-jaur** [comment]
Before all, Thank you for answer me @magojr ,
I don't catch you your last sentence when you say dlrlookupd give me a correct readable format in default-smpps_01.log. 
By the way, Above you said dlrlookupd logs DLR(which is generated by DELIVER_SM PDU) in dlrlookupd-messages.log.

Anyway, I have been requested to use DELIVER_SM provided by default-smpps_01.log instead of DLR coming from dlrlookupd-messages.log.
