### ISSUE TITLE
A numeric password set through jCli will cause an exception when trying to bind

### ISSUE THREAD

**Issue by fourat** [jookies/jasmin#105]
As reported by Shirvan:

2015-02-28 01:17:24 ERROR    20126 Bind failed [[Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'int' object has no attribute 'encode'
/home/fourat/workspace/jasmin/jasmin/vendor/smpp/twisted/protocol.py:714:bindAsTransceiver
/home/fourat/workspace/jasmin/jasmin/vendor/smpp/twisted/protocol.py:609:bind
/home/fourat/workspace/jasmin/jasmin/vendor/smpp/twisted/protocol.py:365:sendBindRequest
/home/fourat/workspace/jasmin/jasmin/vendor/smpp/twisted/protocol.py:368:sendRequest
--- <exception caught here> ---
/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py:139:maybeDeferred
/home/fourat/workspace/jasmin/jasmin/protocols/smpp/protocol.py:224:doSendRequest
/home/fourat/workspace/jasmin/jasmin/vendor/smpp/twisted/protocol.py:377:doSendRequest
/home/fourat/workspace/jasmin/jasmin/vendor/smpp/twisted/protocol.py:356:sendPDU
/home/fourat/workspace/jasmin/jasmin/vendor/smpp/pdu/pdu_encoding.py:919:encode
/home/fourat/workspace/jasmin/jasmin/vendor/smpp/pdu/pdu_encoding.py:978:encodeBody
/home/fourat/workspace/jasmin/jasmin/vendor/smpp/pdu/pdu_encoding.py:1015:encodeRequiredParams
/home/fourat/workspace/jasmin/jasmin/vendor/smpp/pdu/pdu_encoding.py:85:encode
/home/fourat/workspace/jasmin/jasmin/vendor/smpp/pdu/pdu_encoding.py:210:_encode
]]. Disconnecting...

**Comment by MohammadShirvan** [comment]
Thanks fourat
