### ISSUE TITLE
DLR issue please help

### ISSUE THREAD

**Issue by boris1971** [jookies/jasmin#1061]
Hi all,
If anyone can help me I need a suggestion, I have to set dlr in jasmin to wait provider result, specifically, I send sms form jasmine to provider, now once jasmin deliver the sms to the provider is creating dlr itself say delivered but this is a fake dlr because it's not waiting the dlr result from provider.
How to set jasmin to wait dlr form provider?
Thanks for your help
Boris

**Comment by Carlos314159** [comment]
Are you generating your SMS from HTTP API? You can use dlr=yes, dlr-level=2 and other dlr related parameters.
Else you can enforce DLR receipt here:
https://docs.jasminsms.com/en/latest/interception/index.html?highlight=dlr%20level#enforcing-dlr

However, you will always rely on the truthness of your provider, if they decide to send you fake DLR, Jasmin cannot do much about it.

**Comment by agossouvi** [comment]
@farirat, we miss you here...

**Comment by mexicarne** [comment]
So, am I right that you actually got two DLRs for every PDU? Fake one from upstream provider (instantly) and real one from actual mobile device (when and if reached)? 

If you only get the fake one, all you can do is to ask the provider to fix thier stuff, or just switch to another provider.
