### ISSUE TITLE
smpp incoming sms

### ISSUE THREAD

**Issue by javad-zobeidi** [jookies/jasmin#1062]
i created SMPPCCM 

now i want to log incoming SMS 

how i can check the incoming SMS in PHP I need SMS incoming longer in PHP

**Comment by farirat** [comment]
checkout the sms logger example from the documentation or this basic script here: https://github.com/jookies/jasmin/tree/master/misc/scripts

it is still to be ccustomized anyway, but getting the idea: logging messages is consuming from message queues, more on this: https://docs.jasminsms.com/en/latest/messaging/index.html
