### ISSUE TITLE
Issue with docker-compose file

### ISSUE THREAD

**Issue by poirazis** [jookies/jasmin#1075]
When i try to spin up a container using the given https://github.com/jookies/jasmin/blob/master/docker-compose.grafana.yml file, i get an error from docker 

`ERROR: Cannot locate specified Dockerfile: ./docker/Dockerfile.dev`

Can anyone help me to set this up ?
Is there another docker-compose file ?

Thanks in advance!

**Comment by lauer** [comment]
So this Docker composer file expect the whole repo to be checked out.

It can't just be ran using this file alone. Then you need to modified it to fetch an already build image, and also setting up some configurations.

**Comment by poirazis** [comment]
Thank you @lauer !
I there a standard / default docker config file i could use to do this ?

**Comment by farirat** [comment]
Hello @poirazis 
That dockerfile is intended to be used with jasmin's repo in place, but you can replace the **build:** block with:
**image: jookies/jasmin**.

**Comment by poirazis** [comment]
Thank you @farirat !

**Comment by farirat** [comment]
@poirazis thank you for reporting the issue, you are right, the install documentation must include a docker-compose requiring no dev environment, i've fixed this in the docs and will release in 0.10.13
