### ISSUE TITLE
Webhook

### ISSUE THREAD

**Issue by az-z** [jookies/jasmin#1076]
Hello,
 any chance you can enable a webhook for release events, please?
Thank you

**Comment by farirat** [comment]
Hello @az-z 
For which use cases ? can you explain ?

**Comment by az-z** [comment]
I was thinking to subscribe to the release events, so that I can receive
notifications and build automation based off that.

**Comment by farirat** [comment]
A lot of solutions here: https://stackoverflow.com/questions/20839622/notifications-for-new-github-project-releases

**Comment by az-z** [comment]
yes, as a human :) i can be notified about the releases: https://stackoverflow.com/questions/18685796/watching-new-tags-on-github

it appears I misunderstood how webhooks work: https://docs.github.com/en/developers/webhooks-and-events/webhooks/about-webhooks.
I'll probably just configure a scheduler to pull git tags and parse the output looking for a new release tag.
