### ISSUE TITLE
Monitoring metrics update

### ISSUE THREAD

**Issue by Integration-IT** [jookies/jasmin#1082]
Hi,

http://127.0.0.1:1401/metrics is down in some case, because the package has not been updated like git repo version.

The curl command returns 404 in case package does not have server.py updated with metrics path and if metrics.py is not in endpoints path.

The last trouble is http://127.0.0.1:1401/metrics is not compliant with prometheus because the datasource will call http://127.0.0.1:1401/metrics/api/v1/query to get stats and not http://127.0.0.1:1401/metrics.

Regards,
MonkeyTester.

**Comment by farirat** [comment]
Hello @Integration-IT 

Please provide further information: which package ? pypi/rpm/deb ? and which os version ?

As for the prometheus metrics, i'm getting what it's supposed to provide, here's a grafana dashboard i'm working on actually:
<img width="1246" alt="Screen Shot 2022-10-17 at 11 19 22 PM" src="https://user-images.githubusercontent.com/1020111/196294393-34ca53d1-179c-4b5a-b011-5ffc00b7e08d.png">

**Comment by Integration-IT** [comment]
hello @farirat ,

This is my lab env:

- Installed from packagecloud, but probably before your last update
- Ubuntu 22.04.1 LTS
- apt upgrade with last upgrade
- jasmin 0.10.12 last upgrade + pip upgrade

Now all files are clean and get release integrity.

```curl 127.0.0.1:1401/metrics``` results are correct.

But still can't understand how did you configure your grafana.

- Need install local prometheus collector on 9090 ?
- Need custom yaml prometheus configuration ?
- How did you link prometheus /metrics/api/v1/query to /metric ?
- Do you have a /etc/prometheus/prometheus.yml sample ?

In my case i am using Prometheus Data Source - Native Plugin from external server to get remote metrics directly from target url on port 1401.

**Comment by farirat** [comment]
This is my prometheus config:

```
scrape_configs:
  - job_name: jasmin
    static_configs:
      - targets:
          - 'jasmin:1401'
  - job_name: rabbitmq
    static_configs:
      - targets:
          - 'rabbit-mq:15692'
````

**Comment by Integration-IT** [comment]
- Last upgrade + pip upgrade
- Flushed new simple prometheus config

Fully worked.
