### ISSUE TITLE
how to change the source adress random to a concatenated sms.   It is not applying the change to all parts.

### ISSUE THREAD

**Issue by mrsanvicente** [jookies/jasmin#1126]
Hello Everyone

Has anyone changed the source address random for concatenated sms?

Doing the change on the interceptor does not work,  as it only changes the first part.

routable.pdu.params['source_addr'] = 'xxxxxxxxx'

I have also tried to do the change at protocols.py at
# Iterate through parted PDUs
But it is not working.

Any suggestion?

Thanks alot!

**Comment by farirat** [comment]
Checkout #1122 for reference.
