### ISSUE TITLE
jcli terminating when trying to show old users

### ISSUE THREAD

**Issue by texpert** [jookies/jasmin#116]
When doing user -s username on users, created some weeks ago, jcli is silently terminating.

I think this maybe got broken when fixing https://github.com/jookies/jasmin/issues/103 in this commit https://github.com/jookies/jasmin/commit/bf3568e76ffff5210a56e243401633319f2fa552  in jasmin/protocols/cli/usersm.py

jasmin-0.6b6, 0.6b7

**Comment by fourat** [comment]
You're right, that commit will cause regression when upgrading and having already setup users.

As it is still in beta, upgrades will be risky.

Maybe next time will be issuing a note for upgrades.
