### ISSUE TITLE
Error on receiving message on smpp connector

### ISSUE THREAD

**Issue by texpert** [jookies/jasmin#117]
Hello, Fourat!

Have connected to a new gate, binding and sending to it is working OK, but receiving DLRs is not possible - something's going wrong:

2015-03-11 12:44:46 INFO     30070 SMPP Client received PDU [command: deliver_sm, sequence_number: 1, command_status: ESME_ROK]
2015-03-11 12:44:46 DEBUG    30070 Received PDU: PDU [command: deliver_sm, sequence_number: 1, command_status: ESME_ROK
service_type: ''
source_addr_ton: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f90fc674b90>, 6, 'INTERNATIONAL')
source_addr_npi: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f90fc6790d0>, 9, 'ISDN')
source_addr: 'XXXXXXXXXXX'
dest_addr_ton: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f90fc674b90>, 5, 'ALPHANUMERIC')
dest_addr_npi: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f90fc6790d0>, 4, 'UNKNOWN')
destination_addr: ' XXXXXXXXXXX'
esm_class: EsmClass[mode: DEFAULT, type: SMSC_DELIVERY_RECEIPT, gsmFeatures: set([])]
protocol_id: 0
priority_flag: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f90fc6792d0>, 0, 'LEVEL_0')
schedule_delivery_time: None
validity_period: None
registered_delivery: RegisteredDelivery[receipt: NO_SMSC_DELIVERY_RECEIPT_REQUESTED, smeOriginatedAcks: set([]), intermediateNotification: False]
replace_if_present_flag: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f90fc679590>, 0, 'DO_NOT_REPLACE')
data_coding: DataCoding[scheme: DEFAULT, schemeData: SMSC_DEFAULT_ALPHABET]
sm_default_msg_id: 0
short_message: 'id:66447499-9ec1-4898-af55-ae24c6d193f1 sub:001 dlvrd:000 submit date:1503111106 done date:1503111106 stat:UNDELIV err:0 text:'
message_state: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f90fc5ff250>, 1, 'UNDELIVERABLE')
receipted_message_id: '66447499-9ec1-4898-af55-ae24c6d193f1'
network_error_code: '\x03\x00\x00'
]
2015-03-11 12:44:46 WARNING  30070 SMPP XXX.XX.XX.XXX disconnected from port XXXXX: [Failure instance: Traceback (failure with no frames): <type 'exceptions.ValueError'>: Value (^C^@^@) size 3 does not match expected 37
]
2015-03-11 12:44:46 ERROR    30070 Connection lost. Reason: [Failure instance: Traceback (failure with no frames): <type 'exceptions.ValueError'>: Value (^C^@^@) size 3 does not match expected 37
]

jasmin-0.6b6, b7

**Comment by fourat** [comment]
It seems related to network_error_code, i'm checking

**Comment by fourat** [comment]
@texpert let's discuss this issue, please drop me a message on fourat@gmail.com

**Comment by texpert** [comment]
It is remote gateways fault, closing this.

**Comment by ed-irwane** [comment]
I'm running Jasmin version 0.6b9, and described issue still persists. Regardless of how this TLV ended up in deliver_sm PDU, application shouldn't fail like that, since it causes connection to drop. Do let me know should more details be required so I can provide it to you.

**Comment by zoufou** [comment]
Can you please provide a tcp trace ? and debug log snapshot showing the error.
Please send the trace to support@jasminsms.com

**Comment by zoufou** [comment]
As reported by Erwin, issue reopened
