### ISSUE TITLE
message routing possibilities 

### ISSUE THREAD

**Issue by sah-anshu** [jookies/jasmin#118]
Hi,

I have seen the following message routing via the configuration. 
========
MT message is routed to smpp_1 OR smpp_2 if:
Its destination address matches the regular expression “^+33d+”
MT message is routed to smpp_4 if:
Its sent by a user in group G2 and in working hours interval (8pm to 6am)
MT message is routed to smpp_3 if:
Its sent by a user in group G2

========
Kindly advise if these are possible currently:
- To Scrub destination address from specific table/3rd Party API Call. 
- To Match Sender name specific to the sending user.
- To Send from SMPP_1 if SMPP_2 is currently in UNBIND STATE
========
Additionally
What if We wish to send via multiple SMPP Uplinks parallelly.

Regards

**Comment by fourat** [comment]
Hi,

1. What do you mean by "scrubbing destination address" ? do you need to delete a route ?
2. If i understand you, you need to stick a user to a sender name, in this case you update user through jcli to:
  1. fix the sender name: **mt_messaging_cred defaultvalue src_addr SENDERNAME**
  2. revoke the right to change the sender name: **mt_messaging_cred authorization src_addr False**
3. "Multiple uplinks", do you mean multiple SMPP Server instances (multiple ports) ?

**Comment by sah-anshu** [comment]
Hi

I shall explain these 3 possibilities.

*1. Scrubbing Destination address means.*

While Sending SMS, Companies want to filter some "don't disturb number" .
aka *DND*. To filter those number, We keep those data in specific Database
and run lookup query everytime we send SMS.  We can't keep those numbers in
cache because they are in millions.

*Challenge: Realtime lookup will slowdown our SMS Acceptance SPEED from
uplinks*.



*2. Stick to SenderID*

Sticking to SenderID means is not exactly we stick to specific senderID.
While we should allow some possible number of SenderID eg. sender1, sender2
for customer1

While customer1 choose to send apart from those senderid, either system
will choose to send via default senderid or reject with generic nack.


*3. Multiple Uplinks*
No Its not the parallel port. Its the parallel SMSC uplinks from which we
are sending SMS.


*[CUSTOMER1]     |________[Jasmin] ------------------------[Uplink1] *
*[CUSTOMER 2]    |                               |______________ [Uplink2]*


*i.e Parally sending from both uplink.*


--

__
Regards,

Sudhanshu KumarMultiplesystem NetworksSCF 56 LEVEL 2 PHASE 6 MOHALI (Pb.) - IN

MOBILE: (+91) *9216217231, *(+91) *9790197346
*SKYPE: anshusah

*It’s easier saving paper than planting trees. Skip a print and make this
message go viral instead.*

**Comment by fourat** [comment]
Hi,

1. This is possible by using a dynamic filter (filter type is **EvalPyFilter**) which can execute a script to decide whether to pass or not a specific message, there's a short doc on it in http://docs.jasminsms.com/en/latest/management/jcli/modules.html , i would love to get your contribution in writing an example on how to use this powerful filter.
2. At the moment, jasmin will give authorization to user for defining its own source_address or to fix it to  one unique source_address (and not a set of addresses), i will put this as a feature in future releases.
3. You can use an unlimited number of smppc uplinks, the **roundrobinmtroute** can send messages using X connectors, is it what you're looking for ?

**Comment by sah-anshu** [comment]
Hi

Thanks for your attention.
1. *EvalPyFilter *seems th exact solutions which i am looking for. But Just
worried about any sample code with few variables or parameters of sender,
receiver, connector(uplink), messageText. Then it will be easy to acheive.

2. If i get the variable *sender *in *EvalPyFilter *then we don't need
to develop that feature.
3. I will goahead and test *roundrobinmtroute.*

*Thanks*







--

__
Regards,

Sudhanshu KumarMultiplesystem NetworksSCF 56 LEVEL 2 PHASE 6 MOHALI (Pb.) - IN

MOBILE: (+91) *9216217231, *(+91) *9790197346
*SKYPE: anshusah

*It’s easier saving paper than planting trees. Skip a print and make this
message go viral instead.*

**Comment by fourat** [comment]
*From the doc:*

    Using EvalPyFilter is as simple as the shown example, when the python script is called it will get the following global variables set:

    1. routable: one of the jasmin.routing.Routables.Routable inheriters ([Routable](http://docs.jasminsms.com/en/latest/routing/index.html#route-routable) for more details)
    2. result: (default to False) It will be read by Jasmin router at the end of the script execution to check if the filter is matching the message passed through the routable variable, matched=True / unmatched=False

So your python script will have a *routable* global variable, it is an instance of **RoutableDeliverSm** if you're playing with a MO Route and it will be an instance of **RoutableSubmitSm** if you're considering it with a MT Route.

In order to implement your specific filter, you have to know [all the attributes these objects are providing](http://docs.jasminsms.com/en/latest/routing/index.html#route-routable), here's some examples:

Dont pass messages from specific user:

    if routable.user == 'specific_user':
        result = False
    else:
        result = True

Pass messages with text not longer than 40 characters:

    if len(routable.PDU.params['short_message']) <= 40:
        result = True
    else:
        result = False

The **EvalPyFilter** offers a wide range of possibilities when filtering messages, and as shown in the above examples, all you need to set is a boolean variable **result**, when True the filter is passing, and False will be blocking.
You can add **logging** and more features, but pay attention to performance, your logic must not take too much time because it will impact the router throughput.

For your case, you can edit a filter as below (there may be some syntax errors, didnt run it):

    # This can be extracted from a database or a config file:
    controlled_users = ['fourat', 'sah']
    permitted_src_addresses = {'fourat': ['86566', 'Foo'],
                                                  'sah': ['2765', 'Bar', 'Hello'],
                                                 }

    # Filter is passing by default
    result = True

    # Now let's check for source addresses
    if routable.user in controlled_users:
        if routable.PDU.params['source_addr'] not in permitted_src_addresses[routable.user]:
            result = False

**Comment by sah-anshu** [comment]
Hi zoufou 
Can you please help me to develop a sample code.  I have an Existing table of PgSQL where i have to filter mobile numbers. and different table to match the sender name for the respective SMPP Login.

**Comment by tarikogut** [comment]
which language
??

2015-05-22 1:03 GMT+03:00 Sah, Anshu <notifications@github.com>:

**Comment by sah-anshu** [comment]
Python Using EvalPyFilter

- I have a doubt . I wish to maintain sync database connection using dbpool where this external filter process doesn't slow down the message routing possibility.

**Comment by zoufou** [comment]
You can use a connection pooling to DB, and implement some caching layer so wont ask the database for the same number or prefix many time in a timelapse ... just an idea for tuning your filter.

**Comment by sah-anshu** [comment]
yes, can you plz help me with any possible source code to start with.

**Comment by zoufou** [comment]
Express what do you expect exactly from your filter ?

**Comment by sah-anshu** [comment]
I wish to filter 2 values wrt to the smpp account. 
- 1- "receiver" :  we can match with the database  that the smpp account will not be able to send to those receivers.

-2 - "Sender" :  we shall be able to send from those allowed sender values only.

**Comment by zoufou** [comment]
@sah-anshu checkout these F.A.Q. questions:

* http://docs.jasminsms.com/en/stable/faq/index.html#can-you-provide-an-example-of-how-to-use-evalpyfilter
* http://docs.jasminsms.com/en/stable/faq/index.html#how-to-set-an-evalpyfilter-for-a-mt-route

And by the way, make sure you update to 0.6b17 for better api stability
