### ISSUE TITLE
PDUParseError

### ISSUE THREAD

**Issue by fabed2k11** [jookies/jasmin#120]
Hi,
Am trying to receive MO message but i got the following error:
PDUParseError: Optional Parameter not allowed: Invalid option source_network_type

Can you help? Please...

Thanks,

**Comment by fourat** [comment]
Please activate debug level in connector's log and paste the error from the log here

**Comment by fabed2k11** [comment]
Here you are

Optional Parameter not allowed: Invalid option source_network_type
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/jasmin/vendor/smpp/twisted/protocol.py", line 195, in rawMessageReceived
    pdu = self.encoder.decode(StringIO.StringIO(message))
  File "/usr/local/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 927, in decode
    self.decodeBody(file, pdu, headerParams['command_length'] - self.HEADER_LEN)
  File "/usr/local/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 960, in decodeBody
    optionalParams = self.decodeOptionalParams(pdu.optionalParams, file, bodyLength - mParamsLen)
  File "/usr/local/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 1010, in decodeOptionalParams
    raise PDUParseError("Invalid option %s" % optionName, pdu_types.CommandStatus.ESME_ROPTPARNOTALLWD)
PDUParseError: Optional Parameter not allowed: Invalid option source_network_type

Thanks,

**Comment by fourat** [comment]
that's the traceback of the error, i need the smpp log where i can see the PDU causing the error, it seems you are using a vendor specific value of source_network_type.

Please send debug logs, or a tcp capture (using tcpdump or wireshark) of the traffic where i can see the submit_sm PDU

**Comment by fabed2k11** [comment]
Received unparsable PDU 0000004500000005000000000000000100020135393232393631383600040933373435320000000000000000000000000e00010100060001010424000848692066696b7279

**Comment by fourat** [comment]
Ok i've reproduced the error and it seems you a have a vendor specific case, your SMS provider is using a non standard SMPP protocol when using **source_network_type** and **dest_network_type** optional parameters in DeliverSm pdu (these parameters are only for DataSm pdu).

Anyway, Jasmin can handle this, i need more information about your provider gateway if possible.

Please drop me a message on fourat@gmail.com to discuss this further more.

**Comment by mrsanvicente** [comment]
Hello,  
I have the same issue,  i noticed that the solutions was added to class DeliverSM(PDUDataRequest).

Please add also the solution to class SubmitSM(PDUDataRequest)  I did it manually and it works fine.

Thank you very much
