### ISSUE TITLE
Request for feature - update jcli command for routers and filters

### ISSUE THREAD

**Issue by texpert** [jookies/jasmin#126]
It is very annoying remove routes and recreate them just because you have to add or change some filters

**Comment by fourat** [comment]
True, it is not easy doing it through jcli, created #127 for it.

But anyway, jcli is intended for basic administration, it is a "human" interface to twisted's perspective broker api which provide everything for someone who knows how to use it, next step is to build a web management panel on top of perspective broker, in this case jcli would be kept as is, a simple tool for doing simple things ...
