### ISSUE TITLE
There is a chance to implement hardware support?

### ISSUE THREAD

**Issue by reinaldorauch** [jookies/jasmin#133]
By hardware I mean gsm modems

**Comment by zoufou** [comment]
It is possible, but not planned in near releases.

I dont thin gsm modem connectivity using AT commands will be planned, but an android app. bridge for sending/receiving messages will be designed.

**Comment by reinaldorauch** [comment]
If someone implements the AT commands module, that can be merged?

**Comment by sah-anshu** [comment]
it's a good idea . We can implement python-gsmmodem module for same . It
can work as smsc uplink for mo and mt

**Comment by reinaldorauch** [comment]
that can do @sah-anshu

**Comment by sah-anshu** [comment]
Even i had been planning that Lets do @Reinaldo I am sure if it is tested
correctly it will be merged.

**Comment by tarikogut** [comment]
jasmin sms working on rasppery pi2 :) i tested. gsm modems

**Comment by zoufou** [comment]
Ongoing project for an android application to act as a bridge for sending messages through a phone.

**Comment by sah-anshu** [comment]
Shimply mail
            
                img{ display:block; }
                #outlook a{ padding:0; }
                body{ width:100% !important; }
                body{ margin:0; padding:0; }
                img{ border:none; outline:none; text-decoration:none; }
                body{ background-repeat:repeat; background-position:top left; }
                #container{ background-repeat:repeat; background-position:top left;height:100%; width:100%; }
                .title{ color:#202020; font-family:Helvetica; font-size:46px; font-weight:bold; }
                .subTitle{ color:#202020; font-family:Helvetica; font-size:24px; font-weight:bold;  }
                #preheader{ color:#505050; font-family:Helvetica; font-size:12px; line-height:150%; text-align:center; }
                #preheader a:link,#preheader a:visited{ color:#505050; font-weight:bold; text-decoration:underline; }
                #templateHeader{ -moz-border-radius:5px; -webkit-border-radius:5px; -moz-box-shadow:0px 0px 5px #CCCCCC; -webkit-box-shadow:0px 0px 5px #CCCCCC;
                                 background-color:#f9f6f4; background-image:url("https://www.shimply.com/images/email/bg_header.png");
                                 background-repeat:repeat-x; background-position:bottom left; border:1px solid #CBC6B5; border-radius:5px; box-shadow:0px 0px 5px #CCCCCC; }
                #templateHeader{ color:#252525; font-family:Helvetica; font-size:36px; }
                #headerImage{ text-align:center; }
                #headerImage img{ max-width:530px; }
                #upperContent{ -moz-border-radius:5px; -webkit-border-radius:5px; -moz-box-shadow:0px 0px 5px #CCCCCC; -webkit-box-shadow:0px 0px 5px #CCCCCC; background-color:#f9f6f4;
                               border:1px solid #CBC6B5; border-radius:5px; box-shadow:0px 0px 5px #CCCCCC; text-align:left; }
                #upperContentImage img{ display:inline; height:auto; max-width:250px; }
                .upperContentCopy,.upperContentFileInfo{ color:#555555; font-family:Helvetica; font-size:14px; line-height:180%; }
                .upperContentCopy a:link,.upperContentCopy a:visited,.upperContentFileInfo a:link,.upperContentFileInfo a:visited{ color:#505050;  font-weight:normal; text-decoration:underline; }
                #upperContent .button{ -moz-border-radius:5px; -webkit-border-radius:5px;  background-color:#ff5c36;
                                       border:2px solid #3F3F41; border-radius:5px; color:#FFFFFF; font-size:16px; font-family:Arial; line-height:100%; text-align:center; }
                #upperContent .button a:link,#upperContent .button a:visited{ color:#FFFFFF; font-weight:bold; text-decoration:none; text-shadow:1px 2px 2px #303030; }
                #lowerContent{ -moz-border-radius:5px; -webkit-border-radius:5px; -moz-box-shadow:0px 0px 5px #CCCCCC; -webkit-box-shadow:0px 0px 5px #CCCCCC; background-color:#f9f6f4; border:1px solid #CBC6B5;
                               border-radius:5px; box-shadow:0px 0px 5px #CCCCCC; text-align:left; }
                .lowerContentImage{ height:auto; max-width:135px; }
                .lowerContentCopy,.lowerContentFileInfo{ color:#555555; font-family:Helvetica; font-size:12px; }
                .lowerContentCopy a:link,.lowerContentCopy a:visited,.lowerContentFileInfo a:link,.lowerContentFileInfo a:visited{ color:#505050; font-weight:normal; text-decoration:underline; }
                .lowerContentCopy img{ max-width:325px; }
                #lowerContent .button{ -moz-border-radius:5px; -webkit-border-radius:5px;  background-color:#ff5c36;  border-radius:5px; color:#FFFFFF; font-size:14px; font-family:Helvetica;  text-align:center; }
                #lowerContent .button a:link,#lowerContent .button a:visited{ color:#FFFFFF; font-weight:bold; text-decoration:none; text-shadow:1px 2px 2px #303030; }
                #utility{ color:#202020; font-family:Helvetica; font-size:11px; text-align:center; }
                #utility a:link,#utility a:visited{ -moz-border-radius:5px; -webkit-border-radius:5px; background-color:#CAC6B5; border-radius:5px; color:#202020; font-weight:bold; margin:0 2px; padding:6px 12px;
                                                    text-decoration:none; }
                #utility img{ border:none; display:inline; vertical-align:middle; }
                #templateFooter{ color:#303030; font-family:Helvetica; font-size:10px; line-height:150%; }
                #templateFooter a:link,#templateFooter a:visited{ color:#404040; font-weight:normal; text-decoration:underline; }
                .view_more{ width:auto; height:auto; float:left; font-size:16px; color:#3f89e4; text-decoration:none; margin-top:5px;}
                .view_more:hover{ font-size:16px; color:#3f89e4; text-decoration:underline;}
                .social_header{ width:100%; height:auto; float:left; margin-top:5px;}
                .social_icon{ width:auto; height:auto; float:right; cursor:pointer;}
                .sub_heading{ width:100%; height:40px; float:left; font-size:14px; color:#555555; line-height: 15px; margin-top: 5px;}
                .menu{ width:100%; height:auto; float:left; margin-top: 10px;}
                .menu_category{ height:20px;  float:left; color:#3f89e4; text-decoration:none; font-size:14px; font-weight: normal; padding:0px 7px 0px 7px; border-right:1px #3f89e4 solid; line-height:15px; margin-top:7px; cursor:pointer;}
                .menu_category a:link{  color:#3f89e4; text-decoration:none; font-size:14px; line-height:15px; margin-top:7px; cursor:pointer;}
                .menu_category a:visited{ color:#3f89e4; text-decoration:none; font-size:14px; line-height:15px; margin-top:7px; cursor:pointer;}
                .menu_category a:hover{ color:#3f89e4; text-decoration:none; font-size:14px; line-height:15px; margin-top:7px; cursor:pointer;}
                .menu_category a:active{color:#3f89e4; text-decoration:none; font-size:14px; line-height:15px; margin-top:7px; cursor:pointer;}
                .footer_link{color:#3f89e4; font-size:12px; text-decoration:none; cursor:pointer; }
                .footer_link a:link{text-decoration:none; color:#3f89e4;}
                .footer_link a:hover{text-decoration:none; color:#3f89e4;}
                .footer_link a:visited{text-decoration:none; color:#3f89e4;}
                .footer_link a:active{text-decoration:none; color:#3f89e4;}
                .mail_heading_content{ width:100%; height:auto; float:left; margin-bottom: 15px; border-bottom:1px #cccccc solid; }
                .mail_heading_content_text{ width:auto; height:auto; float:left; padding:0px 20px 0px 20px; border-bottom:2px #ff5c36 solid; font-size:20px; color:#3f89e4; font-weight:bold;}
                @media only screen and (max-width: 140pt;){
                    img[class="flexibleimage"]{height:auto !important; width:100% !important;}
                }

            
    
    
        
            
                
                    
                        
                        
                            
                                
                                    
                                        
                                            
                                                
                                            
                                            
                                                
                                                    
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                          
                                                


                                                
                                                India को Try करके देखो - Ultimate Destination For Authentic Products

                                                
                                                    
                            Women Apparels
                            Jewellery & Accessories
                            Men
                            Home Decor
                            Health
                            Foods
                            Books
                          
                                                
                                            
                                            
                                                
                                            
                                        
                                    
                                
                            

                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                
                                            
                                          	
                                        
                                        Get ready for Summer Shopping  
                                        
                                        
                                            
                                                
                                                    
                                                        
                                                              
                                                                  
                                                              
                                                          
                                                          
                                                        
                                                              
                                                                  
                                                              
                                                          
                                                          
                                                        
                                                              
                                                                  
                                                              
                                                          
                                                          
                                                            
                                                            
                                                        
                                                              
                                                                  
                                                              
                                                          
                                                          
                                                        
                                                              
                                                                  
                                                              
                                                          
                                                          
                                                        
                                                              
                                                                  
                                                              
                                                          
                                                          
                                                            
                                                            
                                                        
                                                              
                                                                  
                                                              
                                                          
                                                          
                                                        
                                                              
                                                                  
                                                              
                                                          
                                                          
                                                        
                                                              
                                                                  
                                                              
                                                          
                                                          
                                                            
                                                            
                                                    

                                                
                                            
                                        

                                        
                                            
                                        

                                        
                                            Bringing you 1.7 crore Authentic Indian Products
                                        


                                    

                                    
                                        
                                            
                                            
                                            
                                                Update subscription preferences  Twitter  Facebook  Download App  
                                            
                                            
                                        
                                    
                                    
                                        
                                            
                                                
                                                    
                                                        
                                                            Shimply is your ultimate online destination for authentic Indian products, sourced from their state of origin. The very essence of India lies is in its unity in diversity. At Shimply, we have made a sincere effort to bring to you this very idea of India by uniting its diverse cultural heritage on one platform, thus making it accessible to you. Be it the colours of Rajasthan or the flavour of Assam, the simplicity of Himachal or the elegance of Kerala - Shimply provides you an opportunity to explore them all, thanks to the exclusive works of those master artisans who pour their heart and soul in preserving this diverse tradition of incredible India. You may not know them personally but their craft speaks for their immense dedication and is a true reflection of their own self. 
                                                        
                                                        
                                                            So if you want to possess something unique, one of its kind, come and experience the temptation of making one of these beautifully crafted products your own. Shop for Long skirts and Kota sarees from Rajasthan, Uppada and Gadwal handloom sarees from Andhra Pradesh, Moradabad Brass Art from Uttar Pradesh, Hyderabadi pearl jewellery from Telangana, Tanjore Paintings from Tamil Nadu, Bengal Tant Sarees from West Bengal, Cane & bamboo handicrafts from Assam, Kolhapuri chappals from Maharashtra, books in Malayalam and so on.
                                                        
                                                    
                                                

                                            

                                            
                                                
                                                    
                                                         Copyright © 2014-2015 Shimply, Inc , All rights reserved.
                                                            Our mailing address is: G9, 1st floor, Preet Vihar, New Delhi, India - 110092
                                                            
                                                            This email has been sent to you as a Shimply user. If you like to stop receiving these emails
                                                            click here to unsubscribe
                                                            . Please do not reply to this email, as we are unable to respond from this address.
                                                            If you need help, please contact us

**Comment by sah-anshu** [comment]
@tarikogut pl advice how did you connected GSM Modems port to rasppery pi2
