### ISSUE TITLE
Jasmin installation getting failed!

### ISSUE THREAD

**Issue by Bujail** [jookies/jasmin#135]
pi install jasmin gives the following error:

Downloading/unpacking jasmin
  Running setup.py egg_info for package jasmin
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/root/build/jasmin/setup.py", line 44, in <module>
        install_reqs = parse_requirements('install-requirements', session = session)
    TypeError: parse_requirements() got an unexpected keyword argument 'session'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/root/build/jasmin/setup.py", line 44, in <module>

    install_reqs = parse_requirements('install-requirements', session = session)

TypeError: parse_requirements() got an unexpected keyword argument 'session'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /root/build/jasmin
Storing complete log in /root/.pip/pip.log

**Comment by zoufou** [comment]
What python version are you usung ?

**Comment by Bujail** [comment]
Hi Zougou, Thanks for your replay. I am using Python 2.7.3.

**Comment by zoufou** [comment]
Please update pip by issuing this command:

sudo pip install --upgrade pip

**Comment by Bujail** [comment]
Hi, 
Thanks for your replay, I have updated pip using the given command. But I found there is multiple pip like pip: /usr/bin/pip /usr/local/bin/pip2.7 /usr/local/bin/pip. So I used /usr/local/bin/pip to install jasmin. Its works.  

After installation I have edited jasmin.cfg as per the document specified (http://docs.jasminsms.com/en/latest/management/jcli/#configuration-jcli) and restarted jasmin service. But I cant connect via telnet 127.0.0.1 8990. Connection getting refused. 
Please help.

**Comment by zoufou** [comment]
@Bujail please drop me a message on fourat@gmail.com so i can support you

**Comment by fjmalan** [comment]
@Bujail you can install the latest pip like this :
wget -c https://bootstrap.pypa.io/get-pip.py
python get-pip.py

That should solve your problem
