### ISSUE TITLE
Digit-only username not supported by jcli and http API

### ISSUE THREAD

**Issue by texpert** [jookies/jasmin#136]
Hello, Fourat!

When entering a digit-only username in jcli, the following error is fired on ok command:

> username 1111
> password 1111
> gid clients
> uid 1111
> ok
Error: __str__ returned non-string (type int)

This could be avoided wrapping the username with quotes, but the uid got set without quotes and now i have a user, which could not be removed 

jcli : user -l
#User id          Group id         Username         Balance MT SMS Throughput
#jsm22            clients          jsm22            ND      ND     ND/ND   
#669081625818923  clients          "669081625818923" ND      ND     ND/ND   
#"1111"           clients          "1111"           ND      ND     ND/ND   
Total Users: 3
jcli : user -r 669081625818923
Unknown User: 669081625818923
jcli : user -r "669081625818923"
Unknown User: "669081625818923"

Also, an authentication error is fired when trying to send SMS via http API with this user.

**Comment by zoufou** [comment]
Your fix is now merged, you can close this comment by yourself ;)

Please think about covering your fix by some tests.
