### ISSUE TITLE
Jasmin Installation on CentOS

### ISSUE THREAD

**Issue by sotoz** [jookies/jasmin#137]
Hi,

jasmind cannot find log_daemon_msg and start-stop-daemon command on CentOS (6.6).

    #./jasmind start
    ./jasmind: line 106: log_daemon_msg: command not found
    ./jasmind: line 58: start-stop-daemon: command not found
    ./jasmind: line 109: log_end_msg: command not found

I have installed the redhat-lsb package with all its dependencies but with no luck. Is it possible to rewrite the script without the start-stop-daemon command?

**Comment by texpert** [comment]
Hi!

CentOS 6 init scripts should be slightly different - http://techarena51.com/index.php/how-to-create-an-init-script-on-centos-6/

**Comment by sotoz** [comment]
Alright, I wasn't sure if I was missing something else during the installation, but I guess I just have to rewrite the init script for centos. I will push it to the repository when I'm done so you can check it as well. I'll try to reproduce the same output as the original init script. Anything crucial that I should be aware of?

**Comment by tarikogut** [comment]
i can help tarikogut add skype

2015-04-11 22:50 GMT+03:00 Sotiris Ganouris <notifications@github.com>:

**Comment by zoufou** [comment]
@sotoz this is good news to get RHEL/CentOS 6 init script, i think it **setup.py** must check for the linux distro before installing to decide which init script to deploy.

**Comment by d4xdragon** [comment]
I managed to installed jasmin but still unable to start it, using centos 7, 
If you have managed to create the startup script for centos, can you please share that? 

thanks

**Comment by sotoz** [comment]
Hi
I hadn't the time to develop the startup script for centos yet, but I suppose I will do it sometime this week. 
You can always start jasmine manually though.

**Comment by d4xdragon** [comment]
I am not very good at Linux .. so not sure how to start the jasmin manually.
I tried to run 

/usr/bin/jasmind.py

but that gave me a lot of errors like 
/usr/bin/jasmind.py: line 1: import: command not found

Can  you please advise how to manually start jasmin?

Thank You.

**Comment by sotoz** [comment]
Are you sure you are trying to execute jasmin with Python 2.7? If you have both pythons installed (2.6 and 2.7) try doing something like

# python2.7 /usr/local/bin/jasmind.py --username jcliadmin --password jclipwd

**Comment by d4xdragon** [comment]
Great, thank you, I was missing the starting python2.7. 
i was taking it as a shell script which was totally wrong..

thanks again
