### ISSUE TITLE
need configuration to send deliver_sm instead of data_sm for SMPP delivery receipt

### ISSUE THREAD

**Issue by sumeetb** [jookies/jasmin#139]
I configured Jasmin gateway to talk to SMPP client. I am using this as Jasmin server and for MT i have simulators running. I observed that Jasmin gatway is responding in data_sm for delivery receipts which somehow my SMPP client(MO) is not able to understand. Is there any configuration changes i can do to gateway so that it can respond delivery receipts in deliver_sm instead of data_sm?

**Comment by zoufou** [comment]
Not for the current release, receipts are sent through data_sm pdus

**Comment by sumeetb** [comment]
Thanks for the information. But i can see on home page that SMPP server support deliver_sm? (Text from Home page: SMPP Server supported PDUs right now are bind_receiver, bind_transceiver, bind_transmitter, unbind, submit_sm, deliver_sm and enquire_link.). 
If still it does not support do you know when is the plan to have this support in SMPP server mode?

**Comment by zoufou** [comment]
deliver_sm is supported for delivering mobile-originated messages and not for receipts.

**Comment by sumeetb** [comment]
is there any plan to have deliver_sm support for receipts?

**Comment by sumeetb** [comment]
Thanks! Also, in data_sm pdu for receipts, i don't see other delivery receipts status other than delivered and accepted even though my SMSC simulator is responding different statues like UNDELIV, EXPIRED, DELETED etc. Is this issue or i am missing something over here?

**Comment by zoufou** [comment]
Am looking for possibilities of making deliver_sm receipts, will get back to you soon.

As for the receipt status, can you please provide a tcpdump file ? drop it to fourat@gmail.com

**Comment by sumeetb** [comment]
Thanks! Sure, will capture and send it to you

**Comment by zoufou** [comment]
deliver_sm pdu must contain the **message_payload** parameter.
