### ISSUE TITLE
pip install jasmin failed on CentOS

### ISSUE THREAD

**Issue by d4xdragon** [jookies/jasmin#141]
I tried to install jasmin using pip as advised but failed.

here is the complete log of installation.

----------------------------

[root@jasmin Python-2.7.6]# pip install jasmin
/usr/local/lib/python2.7/site-packages/pip-6.1.1-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Collecting jasmin
/usr/local/lib/python2.7/site-packages/pip-6.1.1-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading jasmin-0.6b9.tar.gz (1.2MB)
    100% |████████████████████████████████| 1.2MB 231kB/s
Collecting pyasn1>=0.1.7 (from jasmin)
  Downloading pyasn1-0.1.7.tar.gz (68kB)
    100% |████████████████████████████████| 69kB 723kB/s
Collecting txAMQP>=0.6.2 (from jasmin)
  Downloading txAMQP-0.6.2.tar.gz
Collecting txredisapi>=1.0 (from jasmin)
  Downloading txredisapi-1.2.tar.gz
Collecting pyOpenSSL>=0.13 (from jasmin)
  Downloading pyOpenSSL-0.15.1-py2.py3-none-any.whl (102kB)
    100% |████████████████████████████████| 106kB 96kB/s
Collecting twisted>=13.0.0 (from jasmin)
  Downloading Twisted-15.1.0.tar.bz2 (4.5MB)
    100% |████████████████████████████████| 4.5MB 92kB/s
Collecting pyparsing>=2.0.0 (from jasmin)
  Downloading pyparsing-2.0.3-py2.py3-none-any.whl
Collecting python-dateutil>=2.0 (from jasmin)
  Downloading python_dateutil-2.4.2-py2.py3-none-any.whl (188kB)
    100% |████████████████████████████████| 192kB 208kB/s
Collecting service-identity>=14.0.0 (from jasmin)
  Downloading service_identity-14.0.0-py2.py3-none-any.whl
Collecting six>=1.5.2 (from pyOpenSSL>=0.13->jasmin)
  Downloading six-1.9.0-py2.py3-none-any.whl
Collecting cryptography>=0.7 (from pyOpenSSL>=0.13->jasmin)
  Downloading cryptography-0.8.2.tar.gz (268kB)
    100% |████████████████████████████████| 270kB 389kB/s
Collecting zope.interface>=3.6.0 (from twisted>=13.0.0->jasmin)
  Downloading zope.interface-4.1.2.tar.gz (919kB)
    100% |████████████████████████████████| 921kB 193kB/s
Collecting characteristic>=14.0.0 (from service-identity>=14.0.0->jasmin)
  Downloading characteristic-14.3.0-py2.py3-none-any.whl
Collecting pyasn1-modules (from service-identity>=14.0.0->jasmin)
  Downloading pyasn1-modules-0.0.5.tar.gz
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/site-packages/setuptools-15.1-py2.7.egg (from cryptography>=0.7->pyOpenSSL>=0.13->jasmin)
Collecting enum34 (from cryptography>=0.7->pyOpenSSL>=0.13->jasmin)
  Downloading enum34-1.0.4.tar.gz
Collecting cffi>=0.8 (from cryptography>=0.7->pyOpenSSL>=0.13->jasmin)
  Downloading cffi-0.9.2.tar.gz (209kB)
    100% |████████████████████████████████| 212kB 526kB/s
Collecting pycparser (from cffi>=0.8->cryptography>=0.7->pyOpenSSL>=0.13->jasmin)
  Downloading pycparser-2.10.tar.gz (206kB)
    100% |████████████████████████████████| 208kB 302kB/s
Installing collected packages: pyasn1, zope.interface, twisted, txAMQP, txredisapi, six, enum34, pycparser, cffi, cryptography, pyOpenSSL, pyparsing, python-dateutil, characteristic, pyasn1-modules, service-identity, jasmin
  Running setup.py install for pyasn1
  Running setup.py install for zope.interface
  Running setup.py install for twisted
  Running setup.py install for txAMQP
  Running setup.py install for txredisapi
  Running setup.py install for enum34
  Running setup.py install for pycparser
  Running setup.py install for cffi
    Complete output from command /usr/local/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-pSuAl9/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-FX9nZ4-record/install-record.txt --single-version-externally-managed --compile:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/cffi
    copying cffi/commontypes.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/gc_weakref.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/verifier.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/lock.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/api.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/model.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/ffiplatform.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/__init__.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/cparser.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/vengine_gen.py -> build/lib.linux-x86_64-2.7/cffi
    running build_ext
    building '_cffi_backend' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/c
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/local/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
    c/_cffi_backend.c:13:17: error: ffi.h: No such file or directory
    In file included from c/_cffi_backend.c:61:
    c/malloc_closure.h:81: error: expected specifier-qualifier-list before ‘ffi_closure’
    c/malloc_closure.h: In function ‘more_core’:
    c/malloc_closure.h:117: warning: division by zero
    c/malloc_closure.h:149: error: ‘union mmaped_block’ has no member named ‘next’
    c/malloc_closure.h: At top level:
    c/malloc_closure.h:158: error: expected ‘)’ before ‘*’ token
    c/malloc_closure.h:166: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
    c/_cffi_backend.c:234: error: expected specifier-qualifier-list before ‘ffi_cif’
    c/_cffi_backend.c: In function ‘cdataowninggc_dealloc’:
    c/_cffi_backend.c:1551: error: ‘ffi_closure’ undeclared (first use in this function)
    c/_cffi_backend.c:1551: error: (Each undeclared identifier is reported only once
    c/_cffi_backend.c:1551: error: for each function it appears in.)
    c/_cffi_backend.c:1551: error: ‘closure’ undeclared (first use in this function)
    c/_cffi_backend.c:1551: error: expected expression before ‘)’ token
    c/_cffi_backend.c:1554: warning: implicit declaration of function ‘cffi_closure_free’
    c/_cffi_backend.c: In function ‘cdataowninggc_traverse’:
    c/_cffi_backend.c:1571: error: ‘ffi_closure’ undeclared (first use in this function)
    c/_cffi_backend.c:1571: error: ‘closure’ undeclared (first use in this function)
    c/_cffi_backend.c:1571: error: expected expression before ‘)’ token
    c/_cffi_backend.c: In function ‘cdataowninggc_clear’:
    c/_cffi_backend.c:1591: error: ‘ffi_closure’ undeclared (first use in this function)
    c/_cffi_backend.c:1591: error: ‘closure’ undeclared (first use in this function)
    c/_cffi_backend.c:1591: error: expected expression before ‘)’ token
    c/_cffi_backend.c: In function ‘cdataowninggc_repr’:
    c/_cffi_backend.c:1720: error: ‘ffi_closure’ undeclared (first use in this function)
    c/_cffi_backend.c:1720: error: expected expression before ‘)’ token
    c/_cffi_backend.c: At top level:
    c/_cffi_backend.c:2270: error: expected declaration specifiers or ‘...’ before ‘ffi_abi’
    c/_cffi_backend.c: In function ‘cdata_call’:
    c/_cffi_backend.c:2404: error: ‘ffi_abi’ undeclared (first use in this function)
    c/_cffi_backend.c:2404: error: expected ‘;’ before ‘fabi’
    c/_cffi_backend.c:2446: error: ‘fabi’ undeclared (first use in this function)
    c/_cffi_backend.c:2450: error: too many arguments to function ‘fb_prepare_cif’
    c/_cffi_backend.c:2455: error: ‘cif_description_t’ has no member named ‘exchange_size’
    c/_cffi_backend.c:2465: error: ‘cif_description_t’ has no member named ‘exchange_offset_arg’
    c/_cffi_backend.c:2495: error: ‘cif_description_t’ has no member named ‘exchange_offset_arg’
    c/_cffi_backend.c:2500: warning: implicit declaration of function ‘ffi_call’
    c/_cffi_backend.c:2500: error: ‘cif_description_t’ has no member named ‘cif’
    c/_cffi_backend.c: In function ‘b_new_primitive_type’:
    c/_cffi_backend.c:3423: error: ‘ffi_type’ undeclared (first use in this function)
    c/_cffi_backend.c:3423: error: ‘ffitype’ undeclared (first use in this function)
    c/_cffi_backend.c:3444: error: ‘ffi_type_sint8’ undeclared (first use in this function)
    c/_cffi_backend.c:3445: error: ‘ffi_type_sint16’ undeclared (first use in this function)
    c/_cffi_backend.c:3446: error: ‘ffi_type_sint32’ undeclared (first use in this function)
    c/_cffi_backend.c:3447: error: ‘ffi_type_sint64’ undeclared (first use in this function)
    c/_cffi_backend.c:3453: error: ‘ffi_type_float’ undeclared (first use in this function)
    c/_cffi_backend.c:3455: error: ‘ffi_type_double’ undeclared (first use in this function)
    c/_cffi_backend.c:3457: error: ‘ffi_type_longdouble’ undeclared (first use in this function)
    c/_cffi_backend.c:3463: error: ‘ffi_type_uint8’ undeclared (first use in this function)
    c/_cffi_backend.c:3464: error: ‘ffi_type_uint16’ undeclared (first use in this function)
    c/_cffi_backend.c:3465: error: ‘ffi_type_uint32’ undeclared (first use in this function)
    c/_cffi_backend.c:3466: error: ‘ffi_type_uint64’ undeclared (first use in this function)
    c/_cffi_backend.c: At top level:
    c/_cffi_backend.c:4025: error: expected specifier-qualifier-list before ‘ffi_type’
    c/_cffi_backend.c:4044: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
    c/_cffi_backend.c: In function ‘fb_build’:
    c/_cffi_backend.c:4178: error: ‘struct funcbuilder_s’ has no member named ‘atypes’
    c/_cffi_backend.c:4178: error: ‘ffi_type’ undeclared (first use in this function)
    c/_cffi_backend.c:4178: error: expected expression before ‘)’ token
    c/_cffi_backend.c:4179: error: ‘struct funcbuilder_s’ has no member named ‘nargs’
    c/_cffi_backend.c:4182: error: ‘struct funcbuilder_s’ has no member named ‘rtype’
    c/_cffi_backend.c:4182: warning: implicit declaration of function ‘fb_fill_type’
    c/_cffi_backend.c:4190: error: ‘cif_description_t’ has no member named ‘exchange_offset_arg’
    c/_cffi_backend.c:4193: error: ‘struct funcbuilder_s’ has no member named ‘rtype’
    c/_cffi_backend.c:4194: error: ‘ffi_arg’ undeclared (first use in this function)
    c/_cffi_backend.c:4204: error: ‘atype’ undeclared (first use in this function)
    c/_cffi_backend.c:4217: error: ‘struct funcbuilder_s’ has no member named ‘atypes’
    c/_cffi_backend.c:4218: error: ‘struct funcbuilder_s’ has no member named ‘atypes’
    c/_cffi_backend.c:4221: error: ‘cif_description_t’ has no member named ‘exchange_offset_arg’
    c/_cffi_backend.c:4228: error: ‘cif_description_t’ has no member named ‘exchange_size’
    c/_cffi_backend.c: In function ‘fb_build_name’:
    c/_cffi_backend.c:4250: error: ‘struct funcbuilder_s’ has no member named ‘nargs’
    c/_cffi_backend.c:4259: error: ‘struct funcbuilder_s’ has no member named ‘fct’
    c/_cffi_backend.c:4261: error: ‘struct funcbuilder_s’ has no member named ‘fct’
    c/_cffi_backend.c: In function ‘fb_prepare_ctype’:
    c/_cffi_backend.c:4302: error: ‘struct funcbuilder_s’ has no member named ‘fct’
    c/_cffi_backend.c:4312: error: ‘struct funcbuilder_s’ has no member named ‘fct’
    c/_cffi_backend.c: At top level:
    c/_cffi_backend.c:4332: error: expected declaration specifiers or ‘...’ before ‘ffi_abi’
    c/_cffi_backend.c: In function ‘fb_prepare_cif’:
    c/_cffi_backend.c:4359: warning: implicit declaration of function ‘ffi_prep_cif’
    c/_cffi_backend.c:4359: error: ‘cif_description_t’ has no member named ‘cif’
    c/_cffi_backend.c:4359: error: ‘fabi’ undeclared (first use in this function)
    c/_cffi_backend.c:4359: error: ‘struct funcbuilder_s’ has no member named ‘nargs’
    c/_cffi_backend.c:4360: error: ‘struct funcbuilder_s’ has no member named ‘rtype’
    c/_cffi_backend.c:4360: error: ‘struct funcbuilder_s’ has no member named ‘atypes’
    c/_cffi_backend.c:4360: error: ‘FFI_OK’ undeclared (first use in this function)
    c/_cffi_backend.c: In function ‘b_new_function_type’:
    c/_cffi_backend.c:4377: error: ‘FFI_DEFAULT_ABI’ undeclared (first use in this function)
    c/_cffi_backend.c:4410: error: too many arguments to function ‘fb_prepare_cif’
    c/_cffi_backend.c:4424: error: ‘struct funcbuilder_s’ has no member named ‘nargs’
    c/_cffi_backend.c:4434: error: ‘struct funcbuilder_s’ has no member named ‘nargs’
    c/_cffi_backend.c: In function ‘convert_from_object_fficallback’:
    c/_cffi_backend.c:4458: error: ‘ffi_arg’ undeclared (first use in this function)
    c/_cffi_backend.c: At top level:
    c/_cffi_backend.c:4530: error: expected ‘)’ before ‘*’ token
    c/_cffi_backend.c: In function ‘b_callback’:
    c/_cffi_backend.c:4601: error: ‘ffi_closure’ undeclared (first use in this function)
    c/_cffi_backend.c:4601: error: ‘closure’ undeclared (first use in this function)
    c/_cffi_backend.c:4622: error: ‘ffi_arg’ undeclared (first use in this function)
    c/_cffi_backend.c:4640: warning: implicit declaration of function ‘cffi_closure_alloc’
    c/_cffi_backend.c:4658: warning: implicit declaration of function ‘ffi_prep_closure’
    c/_cffi_backend.c:4658: error: ‘cif_description_t’ has no member named ‘cif’
    c/_cffi_backend.c:4659: error: ‘invoke_callback’ undeclared (first use in this function)
    c/_cffi_backend.c:4659: error: ‘FFI_OK’ undeclared (first use in this function)
    c/_cffi_backend.c: In function ‘init_cffi_backend’:
    c/_cffi_backend.c:5794: error: ‘FFI_DEFAULT_ABI’ undeclared (first use in this function)
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
    Command "/usr/local/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-pSuAl9/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-FX9nZ4-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-pSuAl9/cffi

Can you please advise.
Thanks
Ali

**Comment by zoufou** [comment]
Hey, are you sure you followed the installation doc ? ;)

From the outcome you posted, it seems you forgot to install libffi-dev package.

There's a buch of requirements to meet before executing pip install, checkout this: http://docs.jasminsms.com/en/latest/installation/index.html#prerequisites

**Comment by tarikogut** [comment]
pip install jasmin -pre


2015-04-20 22:06 GMT+03:00 zoufou <notifications@github.com>:
