### ISSUE TITLE
Services don´t start unless jasmin.cfg is missing or commented

### ISSUE THREAD

**Issue by pguillem** [jookies/jasmin#144]
Started from a blank install. Everything came up OK.

Whenever i modify the /etc/jasmin/jasmin.cfg file to configure the services at will, uncommenting anything will stop the services from starting.

For example, if i modify the jCli parameters, the jCli server will not bind to port 8990 nor localhost.

If i uncomment all the defaults, no services will start... only the redis and broker.
Debug files don´t seem to output any errors.

Is everything OK with the config file parser?

**Comment by pguillem** [comment]
Update... another symptom is jasmin.py is not storing anything (users, groups, etc).
If i restart the service, the previously saved data saved via jCli is lost.

I did set the directory permissions in the prerequisites page... but it seems its not storing.

**Comment by asgarciap** [comment]
Hi @pguillem , you have to type the command "persist" to save your changes.

**Comment by pguillem** [comment]
Great. one down. Thanks @asgarciap

**Comment by pguillem** [comment]
I wonder why the config file issue keeps happening. Any ideas?

**Comment by zoufou** [comment]
Confirmed bug, i'll provide an update fixing this.

**Comment by zoufou** [comment]
@pguillem the issue is closed, please update Jasmin to 0.6b10 and test again.

Don't forget to type in **persist** whenever you need your config to be loaded on next Jasmin restart.

**Comment by pguillem** [comment]
Thanks @zoufou , will try and report back.
Great project!
