### ISSUE TITLE
Start script must indicate if Jasmin cannot bind to some defined ports

### ISSUE THREAD

**Issue by ishr00m** [jookies/jasmin#152]
Sorry for posting here but i was'nt be able to post at google groups. I just installed jasmind and can't access to telnet jcli. 

My config of jCli is: 
```
[jcli]
bind             = 127.0.0.1
port             = 8990
authentication   = True
admin_username   = ishr00m
# MD5 password digest hex encoded
admin_password   = 7b997f10ce078*********
log_level        = INFO
log_file         = /var/log/jasmin/jcli.log
log_format       = %(asctime)s %(levelname)-8s %(process)d %(message)s
log_date_format  = %Y-%m-%d %H:%M:%S
```
After i install i changed default value to following, then restarted jasmind by "sudo service jasmind restart" (i tried also stop and start). Then i try to connect to jcli via telnet: 

```
telnet 127.0.0.1 8990
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
```

netstat | grep "8990" shows nothing and log folder contains amqp-client.log  and redis-client.log.
Could anybody tell me please what i doing wrong?

Many thanks in advance.

**Comment by texpert** [comment]
Have you checked with "ps ax" if jasmin is running?

Try to start it with:

sudo /etc/init.d/jasmind start

**Comment by ishr00m** [comment]
Yes it's running.

ps ax | grep jasmin
```
10604 ?        S      0:02 /usr/bin/python /usr/local/bin/jasmind.py --username jcliadmin --password jclipwd
```

**Comment by texpert** [comment]
It's running with the standard credentials "--username jcliadmin --password jclipwd"

You should edit the /etc/init.d/jasmind 

COMMAND_ARGS='--username jcliadmin --password jclipwd'

**Comment by ishr00m** [comment]
Should it be with md5 there or just plain text? I tried both ways, both are not working... 
in ps ax i see it with new credentials.

**Comment by ishr00m** [comment]
It seems that i can speak russian with you :)

**Comment by texpert** [comment]
I haven't tried to change the credential - no such experience :)
Maybe tried without credentials at all?

Yes, russian is my second native language :)

**Comment by ishr00m** [comment]
I just commented this line but same situation. May be i can call you via skype or viber and you can bit help me with it? Russian is my native lang as well. I can pay some money for help. May also explain what i need from jasminsms.

**Comment by texpert** [comment]
My Skype nick is tvorogov - you're welcome! Though, let's chat, not talk, I'm in the office at my job.

Also, I don't think I could be of much help here, moreover for the money :) Better to ask Fourat, the author of jasmin.

**Comment by ishr00m** [comment]
Thanks, i added you. Anyway thread is open while problem is not solved. I will post here when it's solved. Any suggestions are welcomed.

**Comment by zoufou** [comment]
Hello guys !

Can you please return the outcome of:

    netstat -anp --tcp|grep 8990

And then, stop the service and start Jasmin manually to **check if there's any issue**:

    # Stop service:
    sudo /etc/init.d/jasmind start
    # Start jasmin manually
    sudo /usr/bin/python /usr/local/bin/jasmind.py --username jcliadmin --password jclipwd

**Comment by ishr00m** [comment]
Hi @zoufou. Thanks for involvement. 
```sudo netstat -anp --tcp|grep 8990```
output is empty.

I did stop and start it manually - same result.

**Comment by zoufou** [comment]
Since you get an empty outcome from  netstat you're in trouble, you have to ensure **redis-server** and **rabbitmq-server** service are started before (or after) Jasmin is started.

    # For ubuntu
    /etc/init.d/redis-server start
    /etc/init.d/rabbitmq-server start

**Comment by tarikogut** [comment]
change ubuntu start priority

2015-05-15 15:19 GMT+03:00 zoufou <notifications@github.com>:

**Comment by zoufou** [comment]
@ishr00m any news ?

**Comment by ishr00m** [comment]
Guys I'm finish my work day and will continue at Monday. Thanks for help and have nice weekend!

**Comment by pguillem** [comment]
I experienced a similar situation with issue 144, which i think was solved and commited last week.

Do other services also fail to start when you uncomment their section in the config file?

I recall the only way i could run the app was to leave the config file empty or untouched.

Cheers
Pedro g

**Comment by zoufou** [comment]
@pguillem this issue seems to be a different one from #144, let's wait for @ishr00m for more details.

**Comment by ishr00m** [comment]
Actually I moved to kannel but jasmin is still installed on my test server, I will check soon everything and reply. Btw I tried to install jasminsms to 2 servers with fresh installed debian 7. In both cases I've got a some result 

Отправлено с моего ASUS

-------- Исходное сообщение --------
Отправитель:pguillem <notifications@github.com>
Отправленные:Mon, 18 May 2015 03:23:06 +0500
Получатель:jookies/jasmin <jasmin@noreply.github.com>
Копия:ishr00m <nikita@shesterikov.pro>
Тема:Re: [jasmin] Telnet issue (#152)

>I experienced a similar situation with issue 144, which i think was solved and commited last week.
>
>Do other services also fail to start when you uncomment their section in the config file?
>
>I recall the only way i could run the app was to leave the config file empty or untouched.
>
>Cheers
>Pedro g
>
>
>Sent from my iPhone
>

**Comment by zoufou** [comment]
Issue closed for not return.

**Comment by texpert** [comment]
Guys, I found the problem with this issue - the port 2775 being already in use, jasmind is starting, but refusing telnet connections.

Changing the port in /etc/jasmin/jasmin.cfg [smpp-server] section, just to other non-used port, - have solved the issue.

I think jasmin should check the port availability and fail to start throwing an error, if the port is in use.

**Comment by zoufou** [comment]
Hi @texpert !

You didnt get any error in logs saying the port is already in use ?

**Comment by texpert** [comment]
Double-checked it - no, not a word in logs
