### ISSUE TITLE
Updating Jasmin

### ISSUE THREAD

**Issue by pguillem** [jookies/jasmin#156]
This might sound dull, but, Is there a way to fetch the latest commit via pip?
I'm a full time python newbie.

Thanks in advance

**Comment by zoufou** [comment]
pip install --pre --upgrade jasmin

**Comment by asgarciap** [comment]
Hi!
I got this error when I tried to upgrade jasmin:

```bash
Collecting pycparser (from cffi>=0.8->cryptography>=0.7->pyOpenSSL>=0.13->jasmin)
  Using cached pycparser-2.13.tar.gz
Installing collected packages: jasmin, idna, setuptools, ipaddress, pycparser, cffi, cryptography
  Found existing installation: jasmin 0.6b9
    Uninstalling jasmin-0.6b9:
      Successfully uninstalled jasmin-0.6b9
  Running setup.py install for jasmin
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-O5D6tr/jasmin/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-BHYB0u-record/install-record.txt --single-version-externally-managed --compile:
    /etc/jasmin/resource does not exist !
    
    ----------------------------------------
    Rolling back uninstall of jasmin
    Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-O5D6tr/jasmin/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-BHYB0u-record/install-record.txt --single-version-externally-managed --compile" failed with error code 2 in /tmp/pip-build-O5D6tr/jasmin
```

I actually have a directory named /etc/jasmin/resource/

```
root@jasmingw:/# ls -la  /etc/jasmin/resource/
total 160
drwxr-xr-x 2 root root   4096 may 20 08:52 .
drwxr-xr-x 6 root root   4096 may 20 08:52 ..
-rw-r--r-- 1 root root  32058 abr 23 01:22 amqp0-8.stripped.rabbitmq.xml
-rw-r--r-- 1 root root 119305 abr 23 01:22 amqp0-9-1.xml
```

Thanks!

**Comment by zoufou** [comment]
Try to uninstall then install, it seems to be an issue with the installer.

**Comment by asgarciap** [comment]
But ... my configuration data (routing, etc). I will lost them.

**Comment by zoufou** [comment]
Everything is in /etc/jasmin/store, you can save it anywhere before uninstalling.

But pay attention, you may run into troubles as your persisted data can be obsolete for some releases.

Jasmin is still in Beta, there's no backward compatibility checking for the moment.

**Comment by asgarciap** [comment]
Hi,
After run ```pip uninstall jasmin``` the next directories remain in the host machine:

```bash
/etc/jasmin
/etc/jasmin/init-d
/var/log/jasmin
/etc/jasmin/store
```
In order to install again I had to create the directories:

```bash
/var/run/jasmin
/etc/jasmin/init-script
/etc/jasmin/resource
```

I think **all directories** should be marked to remove when uninstalling.
Besides that, after reinstall jasmin started OK.
Thanks.

**Comment by zoufou** [comment]
pip installation is no more considered for production, you may use rpm/deb packages.

pip remains for developers.
