### ISSUE TITLE
Is it wise to filter ports 4369 and 25672 (beam/epmd)?

### ISSUE THREAD

**Issue by pguillem** [jookies/jasmin#158]
It just came to my attention both erlang and rabbitmq listen to ports on the public net by default.
is it safe for jasmin to config their behavior to remain in localhost only?

**Comment by zoufou** [comment]
Hi @pguillem, i know RabbitMQ is listening on 5672 by default and this is not something Jasmin can change, checkout how to configure it: https://www.rabbitmq.com/configure.html

**Comment by pguillem** [comment]
Great! thanks!
