### ISSUE TITLE
Make Jasmin compatible with Python3

### ISSUE THREAD

**Issue by farirat** [jookies/jasmin#171]

**Comment by farirat** [comment]
This issue is blocked waiting on porting python-twisted to py3: https://twistedmatrix.com/trac/milestone/Python-3.x

**Comment by terrycain** [comment]
Correct me if I'm wrong but I believe twisted is now python3 compatible. I think all the parts jasmin uses have been ported, I think its now waiting on txAMQP. (At least according to [this](http://fedora.portingdb.xyz/pkg/python-txamqp/) page, which may or may not be up to date)

**Comment by farirat** [comment]
Fixed in v0.10
