### ISSUE TITLE
getting same message id while connecting smpp server with kannel

### ISSUE THREAD

**Issue by sah-anshu** [jookies/jasmin#175]
I tried submitting sms via kannel to jasmin smpp server but i got same message id for all messages sent. 
I guess, I am missing something in configuration.

Kindly advise.
kannel configuration is below:
================
group=smsc
smsc=smpp
smsc-id=dead
allowed-smsc-id = dead
host = XXXXXXXXXX
port = 2775
transceiver-mode = 1
receive-port = 2775	
log-file = "dead.log"
log-level = 0
alt-charset = "ASCII"
smsc-username = anshu1
smsc-password = anshuman
#msg-id-type = 0x00
source-addr-ton = 5
source-addr-npi = 9
dest-addr-ton = 1
dest-addr-npi = 1
enquire-link-interval = 30
system-type = smpp
reconnect-delay = 40
throughput=50

**Comment by sah-anshu** [comment]
please advice i am getting same message-id in submit_sm

Thanks in advance

**Comment by zoufou** [comment]
@sah-anshu i cant reproduce your issue !

Please check kannel logs attached below, you can see every message have its own msgid.

[raw.log | uploaded via ZenHub](https://files.zenhub.io/556f7954b282af931c501854)

[JASMIN.log | uploaded via ZenHub](https://files.zenhub.io/556f7955b282af931c501855)
