### ISSUE TITLE
Cyrillic characters in message

### ISSUE THREAD

**Issue by xamaxmacko** [jookies/jasmin#176]
Hello Team!  I've encoutered a problem with sending cyrillic characters.  I've sent message via HTTP-API with "coding" parameter set to 8 accodring to SMPP v3.4 spec, but have got just some random symbols  
Here is my request:  http://myserver:1401/send?username=foo&password=bar&from=TestSender&to=my_phone_number&content=Привет&coding=8 

Please advise how can i send cyrilliic characters.  Thanks in advance

**Comment by sah-anshu** [comment]
please try with encoded value for "content" parameter this shall be solved.

**Comment by zoufou** [comment]
@xamaxmacko welcome on board !

The http api is built just like the smpp one, it doesnt do any transformation/encoding/decoding on your message, so if you need to send cyrillic chars you just need to send cyrillic encoded chars and they will get delivered as is.

In your example, **Привет** is a utf8 encoded string.

Hope it's clear ..

**Comment by xamaxmacko** [comment]
Thanks for the help. Url encoding in UTF-16 has solved the problem
