### ISSUE TITLE
Changing persistence_timer_secs to 30 and authentication to True will block connections to Jasmin

### ISSUE THREAD

**Issue by zoufou** [jookies/jasmin#186]
As reported by Wakibi:

When I change some parameters in the configuration file e.g persistence_timer_secs = 30 under [router] and authentication         = True under [jcli], I stop connecting to Jasmin, both through JCLI and PB API. Any clues on what am doing wrong?

**Comment by zoufou** [comment]
Unable to reproduce error, can you provide more information to help reproducing the issue ? any log files ?

**Comment by wakibi** [comment]
Zoufou, 

I am still getting the errors. however, when I try to find the open ports on my host, all ports used by jasmin seem to be open in both scenarios. Probably it's a config file issue?
![screenshot from 2015-06-12 19 36 31](https://cloud.githubusercontent.com/assets/12862946/8135162/a8522b40-113d-11e5-820b-bcc8d3231059.png)

Logs are below:
![screenshot from 2015-06-12 20 00 00](https://cloud.githubusercontent.com/assets/12862946/8135205/fc565de2-113d-11e5-9fdf-5671ea163462.png)
and 
![screenshot from 2015-06-12 20 00 10](https://cloud.githubusercontent.com/assets/12862946/8135209/04a1491c-113e-11e5-81e7-84381549ad05.png)

**Comment by zoufou** [comment]
What do you get in **jcli.log** when you try to telnet into 8990 ?

**Comment by wakibi** [comment]
Nothing, Nothing ever shows up there. Find jcli.log here in:
chris:/home/chris # chris@chris:~> telnet localhost 8990
chris@chris:~: command not found
chris:/home/chris # telnet localhost 8990
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
chris:/home/chris # tail -f /var/log/jasmin/jcli.log 
2015-06-12 19:27:10 DEBUG    14268 [sref:4] Received AUTH Password: *******
2015-06-12 19:27:10 DEBUG    14268 [sref:4] Send data: Welcome to Jasmin console
Type help or ? to list commands.

2015-06-12 19:27:10 DEBUG    14268 [sref:4] Send data: Session ref: 4
2015-06-12 19:27:10 DEBUG    14268 [sref:4] Send data: None
2015-06-12 19:31:27 DEBUG    14268 [sref:4] Received line: quit
2015-06-12 19:31:27 DEBUG    14268 [sref:4] Parsed line returns: cmd=quit, agr=, line=quit
2015-06-12 19:31:27 DEBUG    14268 [sref:4] Running do_quit with arg:
2015-06-12 19:31:27 INFO     14268 [sref:4] Session stopped (Connection was closed cleanly.).
^C
chris:/home/chris # ps aux | grep jasmi
root     15909  0.4  0.3 121088 31312 ?        S    20:14   0:00 /usr/bin/python /usr/bin/jasmind.py --username jcliadmin --password jclipwd
root     15983  0.0  0.0   9264  1604 pts/3    S+   20:15   0:00 grep --color=auto jasmi
chris:/home/chris # 

Please note that what is appearing as a successful connection (in jcli.log) was the last one I had, prior to changing the config file to re-produce the failure.

**Comment by zoufou** [comment]
please provide outcome of the following commands:

    netstat -anp|grep 8990
    iptables -L
    telnet 127.0.0.1 8990

**Comment by wakibi** [comment]
Find here in:

chris:/home/chris # iptables -L
Chain INPUT (policy DROP)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate ESTABLISHED
ACCEPT     icmp --  anywhere             anywhere             ctstate RELATED
input_ext  all  --  anywhere             anywhere            
LOG        all  --  anywhere             anywhere             limit: avg 3/min burst 5 LOG level warning tcp-options ip-options prefix "SFW2-IN-ILL-TARGET "
DROP       all  --  anywhere             anywhere            

Chain FORWARD (policy DROP)
target     prot opt source               destination         
LOG        all  --  anywhere             anywhere             limit: avg 3/min burst 5 LOG level warning tcp-options ip-options prefix "SFW2-FWD-ILL-ROUTING "

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            

Chain forward_ext (0 references)
target     prot opt source               destination         

Chain input_ext (1 references)
target     prot opt source               destination         
ACCEPT     udp  --  anywhere             anywhere             PKTTYPE = broadcast udp dpt:bootps
DROP       all  --  anywhere             anywhere             PKTTYPE = broadcast
ACCEPT     icmp --  anywhere             anywhere             icmp source-quench
ACCEPT     icmp --  anywhere             anywhere             icmp echo-request
LOG        tcp  --  anywhere             anywhere             limit: avg 3/min burst 5 tcp dpt:ssh flags:FIN,SYN,RST,ACK/SYN LOG level warning tcp-options ip-options prefix "SFW2-INext-ACC-TCP "
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootps
DROP       all  --  anywhere             anywhere             PKTTYPE = multicast
DROP       all  --  anywhere             anywhere             PKTTYPE = broadcast
LOG        tcp  --  anywhere             anywhere             limit: avg 3/min burst 5 tcp flags:FIN,SYN,RST,ACK/SYN LOG level warning tcp-options ip-options prefix "SFW2-INext-DROP-DEFLT "
LOG        icmp --  anywhere             anywhere             limit: avg 3/min burst 5 LOG level warning tcp-options ip-options prefix "SFW2-INext-DROP-DEFLT "
LOG        udp  --  anywhere             anywhere             limit: avg 3/min burst 5 ctstate NEW LOG level warning tcp-options ip-options prefix "SFW2-INext-DROP-DEFLT "
DROP       all  --  anywhere             anywhere            

Chain reject_func (0 references)
target     prot opt source               destination         
REJECT     tcp  --  anywhere             anywhere             reject-with tcp-reset
REJECT     udp  --  anywhere             anywhere             reject-with icmp-port-unreachable
REJECT     all  --  anywhere             anywhere             reject-with icmp-proto-unreachable

chris:/home/chris # telnet 127.0.0.1 8990
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
chris:/home/chris # netstat -anp | grep 8990

The above is with authorisation = True (Uncommented)
And below with authorisation = True commented

Connection closed by foreign host.
chris:/home/chris # netstat -anp | grep 8990
tcp        0      0 127.0.0.1:8990          0.0.0.0:*               LISTEN      16222/python        
tcp        0      0 127.0.0.1:8990          127.0.0.1:33237         TIME_WAIT   -

**Comment by zoufou** [comment]
Please send me the not working jasmin.cfg

**Comment by wakibi** [comment]
[jcli]
# If you want you can bind a single interface, you can specify its IP here
#bind                           = 127.0.0.1

# Accept connections on the specified port, default is 8990
port                            = 8990

# If authentication is True, access will require entering a username and password 
# as defined in admin_username and admin_password, you can disable this security 
# layer by setting authentication to False, in this case admin_* values are ignored.
authentication          = True
admin_username          = jcliadmin
# This is a MD5 password digest hex encoded
admin_password          = 79e9b0aa3f3e7c53e916f7ac47439bcb

# Specify the server verbosity level.
# This can be one of:
# NOTSET (disable logging)
# DEBUG (a lot of information, useful for development/testing)
# INFO (moderately verbose, what you want in production probably)
# WARNING (only very important / critical messages and errors are logged)
# ERROR (only errors / critical messages are logged)
# CRITICAL (only critical messages are logged)
log_level                       = DEBUG

# Specify the log file path
log_file                        = /var/log/jasmin/jcli.log

# The following directives define logging patterns including:
# - log_format: using python logging's attributes
#               refer to https://docs.python.org/2/library/logging.html#logrecord-attributes
# -log_date_format: using python strftime formating directives
#                   refer to https://docs.python.org/2/library/time.html#time.strftime
log_format                      = %(asctime)s %(levelname)-8s %(process)d %(message)s
log_date_format = %Y-%m-%d %H:%M:%S


The rest is the default for the config. That's the only part I changed.

**Comment by wakibi** [comment]
Please find the file attached. I have attached both the working, and the
one that's failing.

Cheers

On Fri, Jun 12, 2015 at 8:36 PM, zoufou <notifications@github.com> wrote:

> Please send me the not working jasmin.cfg
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jookies/jasmin/issues/186#issuecomment-111569771>.
>



-- 

Kind Regards
Wakibi Christopher

+256773861504 / +256700185883

I love what I do, and I know my worth...

**Comment by zoufou** [comment]
please upgrade to 0.6b23 at least and tell if the problem persists

**Comment by wakibi** [comment]
Working fine... Apologies for taking you back. I had it installed from source, so I think I got an older version from GitHub. I will test the other bug I had reported and get back as well.
