### ISSUE TITLE
Routes (MO & MT) must be updateable

### ISSUE THREAD

**Issue by zoufou** [jookies/jasmin#203]
Actually, the unique way to do so is to remove and add the route again.

**Comment by xamaxmacko** [comment]
Hello!

Please advise how to remove the route. They don't have any ID's so what is the way of removing them?

**Comment by zoufou** [comment]
a route have a unique order:

    mtrouter -l
    #Order Type          Rate     Connector ID(s)    Filter(s)                                                       
    #2000  StaticMTRoute 0.00000  smppc(CONNECT01)   <EvalPyFilter (pyCode=if routabl ..)>

To remove it:

    mtrouter -r 2000

**Comment by zoufou** [comment]
This feature is removed from the roadmap due to the following reasons:

* Jasmin's cli must be kept as simple as possible,
* Any extra logics must be based on jcli, so this type of features will be implemented on high level apis such as a web app, c.f. https://github.com/jookies/jasmin-web
