### ISSUE TITLE
Filters are dissappearing

### ISSUE THREAD

**Issue by xamaxmacko** [jookies/jasmin#204]
Hello community!

I've faced a strange issue.

Everytime I create any filter...in approximately 30-40 minutes they just dissapear.

filter -l gives me the result: Total Filters: 0

Has anybody faced this issue before?

**Comment by zoufou** [comment]
@xamaxmacko strange issue !

What Jasmin version are you using ? and can you tell some details so i can try to reproduce the issue ?

**Comment by xamaxmacko** [comment]
I've found that this issue is not about certain amount of time.
Here is scenario:
1. Telnet to jcli.
2. Creating a filter.
3. Quitting jcli.
4. Telnet again to jcli.
5. There is no filter!!!

So this issue is about using different telnet sessions.

Please tell me how to check Jasmin version?

**Comment by zoufou** [comment]
How much time from step 3 to 4 ?
And do you have activity on the gateway ? (connected users ? messages ? ...)

Here's how to get jasmin's version:

    python -c "import jasmin;print jasmin.get_release();"

**Comment by xamaxmacko** [comment]
How much time from step 3 to 4 ?

Just about couple of seconds. Made the filter, finished the session and started new one at once.

The version is 0.6b18

**Comment by zoufou** [comment]
Please update to 0.6b26 and test again.

**Comment by xamaxmacko** [comment]
We've just done update and tried again. The result is still the same. I can't find filter after finishing session and starting the new one

**Comment by zoufou** [comment]
@xamaxmacko please send me an email to fourat@gmail.com so we can launch a live session to check what's happening.

**Comment by zoufou** [comment]
Bug confirmed, filters are lost when jasmin is started with non default username **jcliadmin**.

**Comment by zoufou** [comment]
After testing, it seems to not to be a bug: **filters** and **httpccs** are helpers for creating routes and connectors, they only live in the current session, if you need them to live more, persist them to disk with **persist**.
