### ISSUE TITLE
No DLR From Jasmin

### ISSUE THREAD

**Issue by xamaxmacko** [jookies/jasmin#205]
Hello community.

I've noticed that while using the scheme ESME - Jasmin- SMSC, Jasmin doesn't give back delivery reports to the ESME. I mean Jasmin got the report from SMSC but he doesn't throw it back to ESME.

Are there any specific settings to make it work?

**Comment by zoufou** [comment]
Please follow these instructions:

* Activate SMPP Server debug level in logs
* Activate SMPP Client debug level in logs
* Redo your test
* Send you **smpp client log**, **default-smpps_01.log** and **messages.log**

**Comment by xamaxmacko** [comment]
Hello!

I've tried to set the  log level to DEBUG like this:
 log_level                       = DEBUG, removed the # sign. But I'm still geting only INFO level.

What am I doing wrong?

**Comment by zoufou** [comment]
Can you send me your jasmin.cfg file ?

**Comment by xamaxmacko** [comment]
Hello. This is full list of settings for smpp-server

[smpp-server]

# SMPP Server identifier
#id                                     = "smpps_01"

# If you want you can bind a single interface, you can specify its IP here
#bind                           = 0.0.0.0

# Accept connections on the specified port, default is 2775
#port                           = 2775

# Timeout for response to bind request
#sessionInitTimerSecs   = 30

# Enquire link interval
#enquireLinkTimerSecs   = 30

# Maximum time lapse allowed between transactions, after which,
# the connection is considered as inactive
#inactivityTimerSecs    = 300

# Timeout for responses to any request PDU
#responseTimerSecs              = 60

# Timeout for reading a single PDU, this is the maximum lapse of time between
# receiving PDU's header and its complete read, if the PDU reading timed out,
# the connection is considered as 'corrupt' and will reconnect
#pduReadTimerSecs               = 10

# Specify the server verbosity level.
# This can be one of:
# NOTSET (disable logging)
# DEBUG (a lot of information, useful for development/testing)
# INFO (moderately verbose, what you want in production probably)
# WARNING (only very important / critical messages and errors are logged)
# ERROR (only errors / critical messages are logged)
# CRITICAL (only critical messages are logged)
log_level                       = DEBUG

# Specify the log file path
#log_file                       = /var/log/jasmin/default-smpps_01.log

# The following directives define logging patterns including:
# - log_format: using python logging's attributes
#               refer to https://docs.python.org/2/library/logging.html#logrecord-attributes
# -log_date_format: using python strftime formating directives
#                   refer to https://docs.python.org/2/library/time.html#time.strftime
#log_format                     = %(asctime)s %(levelname)-8s %(process)d %(message)s
#log_date_format        = %Y-%m-%d %H:%M:%S

**Comment by zoufou** [comment]
seems okay since you have it uncommented.

did you restart jasmin ?

**Comment by xamaxmacko** [comment]
Yes, sure. I've restarted it at as soon as I made changes.

**Comment by zoufou** [comment]
Issue related to #210 

Will close this one
