### ISSUE TITLE
 ERROR  31008 Connection lost. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.

### ISSUE THREAD

**Issue by pguillem** [jookies/jasmin#212]
Any comments on this error message?
It happens after i send each message via SMPP.

It seems jasmin restarts the connection afterwards... but it shows up after every message.

**Comment by zoufou** [comment]
weird issue ! do you observe this with a specific connector ?

Please procede as below:

* Activate debug log and share the log after sending some messages
* Send a pcap file containing the smpp traffic

**Comment by zoufou** [comment]
UP

**Comment by techniclite** [comment]
Hi, I get too this message on a fresh ubuntu 15.04 when try to run the  consume_MT_messages.py
then I do a pip install --upgrade txamqp and disappear the error message.
