### ISSUE TITLE
Charset

### ISSUE THREAD

**Issue by pguillem** [jookies/jasmin#213]
Is there a specific place to configure wether to encode the messages as UNICODE or ASCII in jasmin ?
I'm sending the "@" character but it gets translated to a "?" symbol backwards.

**Comment by zoufou** [comment]
Using http or smpp ? a pcap file with input and output stream would be helpful

**Comment by pguillem** [comment]
Thanks zofou

Its happening in smpp.
Smpp. I'll dump a pcap today.

Best
Pedro

PEDRO M. GUILLEM
CTO
ETHERVOICE SAS ESP
Mobile: +57 3138534598
E-mail: pedro.guillem@ethervoice.net
www.ethervoice.net
Bogotá - Colombia

**Comment by zoufou** [comment]
UP

**Comment by sah-anshu** [comment]
please suggest how we can handle this issue. I am also getting @ as ?
