### ISSUE TITLE
COctetstring is longer than allowed Maximum size

### ISSUE THREAD

**Issue by pguillem** [jookies/jasmin#214]
When sending via SMPP, this message kept poping in the default outgoing log:

PDUParseError: Message ID is invalid: COctetString is longer than allowed maximum size (9)    

I had to manually modify pdu_encoding.py and set the self.maxSize variable to 160.

I believe the error was accounting for the lenght of my username to the remote SMPP server. But after setting this variable to something like 25 (way over the lenght of the username), the error kept showing.

I figured the sms size was also affecting the function... So i set a fixed size of 160 and everything worked like a charm.

I could not trace back the line invoking the _encode_ function, which should be casting the size as a parameter in the constructor _init_ in pdu_encode.py

Any ideas?

**Comment by zoufou** [comment]
Can you provide pcap ?

**Comment by zoufou** [comment]
UP

**Comment by zoufou** [comment]
Closed due to missing feedback
