### ISSUE TITLE
After an update installation, I can not send sms any more

### ISSUE THREAD

**Issue by weiqiwang** [jookies/jasmin#223]
I try to use apt-get to update python-jasmin.  and load the exists configration. then I can not send any sms. My provider told to me "numbers are not in international E.164 format"  Because I never change any configration, so there may be an issue in the new version. Report it here.

this is my configration:
==========================================
jcli : smppccm -s voxbone
ripf 0
con_fail_delay 10
dlr_expiry 86400
coding 0
submit_throughput 110
elink_interval 30
bind_to 30
port 2777
con_fail_retry yes
password mysmsgwpwd
src_addr None
bind_npi 1
addr_range None
dst_ton 1
res_to 60
def_msg_id 0
priority 0
con_loss_retry yes
username mysmsgwuser
dst_npi 1
validity None
requeue_delay 120
host 81.201.82.10
src_npi 1
trx_to 300
logfile /var/log/jasmin/default-voxbone.log
systype 
cid voxbone
loglevel 20
bind transceiver
proto_id None
dlr_msgid Unknown (object is from an old Jasmin release !)
con_loss_delay 10
bind_ton 1
pdu_red_to 10
src_ton 1

**Comment by tarikogut** [comment]
not possible

2015-07-01 3:04 GMT+03:00 Weiqi Wang <notifications@github.com>:

**Comment by zoufou** [comment]
@weiqiwang What's the problem ? do you get your messages rejected ? or just undelivered ? any log to show ? please provide more info.

**Comment by zoufou** [comment]
UP !

**Comment by weiqiwang** [comment]
Messages are not rejected at my end. It looks like normal. and I can get a success information. but in my provider end (Voxbone.com) the system log said "numbers are not in international E.164 format"
So the messages is not delivered to my customer. I have another server which is not upgrade, it works well.

I can not find the error from jasminsms logs. and I do not have other log. I will try reinstall the jasmin server later for futher testing.

**Comment by weiqiwang** [comment]
new problem, when I tried to reinstall jasmind, I can not be success.
I got this error messages:

Preparing to unpack .../python-jasmin_0.6.37-1_all.deb ...
invoke-rc.d: initscript jasmind, action "stop" failed.
dpkg: error processing archive /var/cache/apt/archives/python-jasmin_0.6.37-1_all.deb (--unpack):
 subprocess new pre-installation script returned error exit status 11
Errors were encountered while processing:
 /var/cache/apt/archives/python-jasmin_0.6.37-1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)


my system is "Ubuntu 14.04.2 LTS (GNU/Linux 3.16.0-41-generic x86_64)"

**Comment by zoufou** [comment]
It's an issue with the deb packager, fixed for next 0.6b38 release.

For the moment, you can follow this workaround:

* Start actual Jasmin version
* apt-get upgrade python-jasmin

If there still an issue, then:

* Backup your /etc/jasmin/store folder if you have any persisted data
* Uninstall Jasmin: apt-get --purge remove python-jasmin
* Install it again: apt-get install python-jasmin

**Comment by weiqiwang** [comment]
The fresh new installation works well. Thank you for your excellent work.
