### ISSUE TITLE
Autosplit messages

### ISSUE THREAD

**Issue by pguillem** [jookies/jasmin#225]
Hello all

is jasmin splitting the SMS when exceeding 140 bytes of text? or at least is there a trace of such actions? 

I noticed this particular 139 char message attempt was sent in UCS2 encoding and the status returned by the ESME was not updated in the rabbit queue. However the ESME did split the message in 3 and billed me 3 messages,as if it was a 140 char unicode message. The status in jasmin was not updated.

I came up with this log this morning. Can anybody explain what this log means?

2015-07-01 20:09:31 ERROR    11320 Request timed out after 60 secs: PDU [command: submit_sm, sequence_number: 1100, command_status: ESME_ROK
service_type: ''
source_addr_ton: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f6edc928d50>, 5, 'ALPHANUMERIC')
source_addr_npi: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f6edc928150>, 4, 'UNKNOWN')
source_addr: '57300XXXXXXX'
dest_addr_ton: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f6edc928d50>, 6, 'INTERNATIONAL')
dest_addr_npi: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f6edc928150>, 9, 'ISDN')
destination_addr: '573156632189'
esm_class: EsmClass[mode: DEFAULT, type: DEFAULT, gsmFeatures: set([EnumValue(<jasmin.vendor.enum.Enum object at 0x7f6edc8013d0>, 0, 'UDHI_INDICATOR_SET')])]
protocol_id: 0
priority_flag: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f6edc9289d0>, 0, 'LEVEL_0')
schedule_delivery_time: None
validity_period: datetime.datetime(2015, 7, 4, 23, 8, 27)
registered_delivery: RegisteredDelivery[receipt: NO_SMSC_DELIVERY_RECEIPT_REQUESTED, smeOriginatedAcks: set([]), intermediateNotification: False]
replace_if_present_flag: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f6edc928590>, 0, 'DO_NOT_REPLACE')
data_coding: DataCoding[scheme: DEFAULT, schemeData: UCS2]
sm_default_msg_id: 0
short_message: '\x05\x00\x03e\x02\x01\x00M\x00O\x00N\x00I\x00C\x00A\x00 \x00C\x00I\x00R\x00O\x00 \x00t\x00e\x00 \x00h\x00a\x00 \x00i\x00n\x00v\x00i\x00t\x00a\x00d\x00o\x00 \x00a\x00 \x00u\x00n\x00i\x00r\x00t\x00e\x00 \x00a\x00 \x00W\x00a\x00z\x00e\x00,\x00 \x00u\x00n\x00a\x00 \x00a\x00p\x00p\x00 \x00g\x00r\x00a\x00t\x00u\x00i\x00t\x00a\x00 \x00d\x00e\x00 \x00t\x00r\x00\xe1'

**Comment by zoufou** [comment]
ERROR 11320 Request timed out after 60 secs

That means you upstream connector didnt reply back with **submit_sm_resp** so the initial request (which is **submit_sm**) has timed out.
