### ISSUE TITLE
Statistics on SMS

### ISSUE THREAD

**Issue by xamaxmacko** [jookies/jasmin#228]
Hello.

Please advise will be any statistics on sent/received/delivered SMS implemented in future?

Or is there any possibility to check this statistics via telnet?

**Comment by zoufou** [comment]
There's a stats module in jcli: http://docs.jasminsms.com/en/latest/management/jcli/modules.html#stats-manager

**Comment by xamaxmacko** [comment]
I've checked this module, but there is no such information there. No SMS counting

**Comment by zoufou** [comment]
Here's an example:

    jcli : stats --user fourat
    #Item                     Type         Value
    #last_activity_at         SMPP Server  2015-07-03 22:47:08
    #bind_count               SMPP Server  1
    #bound_connections_count  SMPP Server  {'bind_transmitter': 0, 'bind_receiver': 0, 'bind_transceiver': 0}
    #submit_sm_request_count  SMPP Server  3
    #qos_last_submit_sm_at    SMPP Server  2015-07-03 22:46:32
    #unbind_count             SMPP Server  1
    #qos_last_submit_sm_at    HTTP Api     ND
    #connects_count           HTTP Api     0
    #last_activity_at         HTTP Api     ND
    #submit_sm_request_count  HTTP Api     0

You have **submit_sm_request_count** for HTTP and SMPP apis, it depends on what you're looking for ...

**Comment by xamaxmacko** [comment]
Is there any possibility to see how many messages were delivered?

**Comment by zoufou** [comment]
There's actually no stat for that, gonna create an issue for it so it can be in next release (b34).

By the way, if you need to build an advanced dashboarding on top of Jasmin, the jcli's stats are not intended for that, they are for operational monitoring and not business reporting.

Jasmin is not providing business reporting as users tend to desire differently, Jasmin will provide you raw data through rabbitmq and you'll setup your dashboard as you like.

I know people using kibana & logstash, logentries.com ...

**Comment by pguillem** [comment]
Zoufou contributed a rabbit listener to dump event driven delivery results 2 months ago. I modified his script to dump each message to mysql and further update the final delivery status on a table.

Check issue 142 (or 144, i can't remember). Works good for accounting traffic.

**Comment by zoufou** [comment]
@xamaxmacko in v0.6b37 you'll get more stats about sent/received messages in SMPP server api, http api and user profile.
