### ISSUE TITLE
SMS Transction timeout

### ISSUE THREAD

**Issue by xamaxmacko** [jookies/jasmin#229]
Hello!

Please advise what is timeout for one SMS transaction(submit_sm + submit_sm_resp).

Is there any possibility to tune it up manually?

**Comment by zoufou** [comment]
Check the smppc connector parameters here: http://docs.jasminsms.com/en/latest/management/jcli/modules.html#smpp-client-connector-manager

And especially:

    res_to	Timeout for responses to any request PDU
    trx_to	Maximum time lapse allowed between transactions, after which, the connection is considered as inactive and will reconnect
    pdu_red_to	Timeout for reading a single PDU, this is the maximum lapse of time between receiving PDU’s header and its complete read, if the PDU reading timed out, the connection is considered as ‘corrupt’ and will reconnect

**Comment by xamaxmacko** [comment]
How the Jasmin behaves in the next scenario:

Jasmin sends submit_sm to the SMSC, but get no submit_sm_resp in timeout that set in settings?

**Comment by zoufou** [comment]
It will end any outbound transaction and stop the connector, considering the connection is down.

**Comment by xamaxmacko** [comment]
What will be sent to ESME for example, the message was received from?

**Comment by zoufou** [comment]
Sorry but i dont get you

**Comment by zoufou** [comment]
Issue is continued in #247
