### ISSUE TITLE
can we pick messages directly from any database table

### ISSUE THREAD

**Issue by sah-anshu** [jookies/jasmin#235]
Hi
if it is possible to enqueue sms to jasmin directly from any database mysql /pgsql.

please advise.

**Comment by zoufou** [comment]
Please clarify, you want to send messages from db ?

**Comment by sah-anshu** [comment]
yes , say we have 10K record to send sms, then giving 10k request via curl can be time consuming. it shall be easy if jasmin could pick directly from db

**Comment by zoufou** [comment]
@sah-anshu it can be done as a wrapper to httpapi, or even at a lower level: perspective broker api (which httpapi and smpps are wrappers of it), anyway, this is a feature to be voted to be set in roadmap or provided as a contrib to the project.

**Comment by akrus** [comment]
+1 here :)

**Comment by sah-anshu** [comment]
+1 Yes, Then it will be easy to migrate from kannel to Jasmin

**Comment by perl-coder** [comment]
+1

**Comment by bodomic** [comment]
+1
