### ISSUE TITLE
Encoding troubles with GSM328

### ISSUE THREAD

**Issue by pguillem** [jookies/jasmin#246]
Is jasmin able to forward latin encoding or shift tables for the gsm 3.28 standard? 

How does jasmin handles the charset of an individual message? Is it up to the originator? Or will it accomodate the charset upon the contents of the message itself? 

I've noticed it handles UCS2 well but the message is splitted in 3 smaller 70 char messages when it reaches the ESME. As expected.

My questions:

1) is jasmin able to split messages upon encoding/lenght, dividing the length in 140 byte chunks?

2) when forwarding a 145 char UCS2 message, jasmin forwards one single message but can't handle the DLR for the 3 chunks (one message each) returned by the ESME. What is the jasmin behavior in this scenario? has anybody taught about this?

3) which files in the code control the encoding of the message? 

4) is jasmin translating encodings? Or just forwarding whatever it receives?

Is anybody else having trouble forwarding mesaages in gsm 3,28 with a shift table for a lanuage different than english?

**Comment by zoufou** [comment]
Hi! did you resolve the issue by your own ? i see no one gave a help for you.

**Comment by iKlotho** [comment]
I have a similar problem. I want to use shift tables for Turkish characters such as ç,Ç,Ö,ö,Ü,ü without Unicode. I did some research and found that I should place the UDH at the beginning of message payload like 0x03 0x25 0x01 0x01. 

0x03 -> UDH length (in this case 3 octet)
0x25 -> IEI indicates that header is National Language Locking Shift    
0x01 0x01 -> is for the Turkish Language

Can someone help me to implement custom UDH  in Jasmin?

**Comment by hzcodertr** [comment]
use hex encode with utf-16 BE  its working data coding 8

**Comment by iKlotho** [comment]
The UTF-16 is not what I want. It has 65 char limit. Also, I monkey patched the Natural Language Shift table for Turkish language and it's working. But still waiting for Jasmin SMS to implement this feature.

**Comment by zarakisan** [comment]
I faced with same problem and not found a solution yet. Anyone help?

> I have a similar problem. I want to use shift tables for Turkish characters such as ç,Ç,Ö,ö,Ü,ü without Unicode. I did some research and found that I should place the UDH at the beginning of message payload like 0x03 0x25 0x01 0x01.
> 
> 0x03 -> UDH length (in this case 3 octet)
> 0x25 -> IEI indicates that header is National Language Locking Shift
> 0x01 0x01 -> is for the Turkish Language
> 
> Can someone help me to implement custom UDH in Jasmin?
> 
> UPDATE:
> I managed to implement UDH but now stuck with shift table encoding problem. Still trying to figure out how to encode Turkish chars as shift table hex values.
