### ISSUE TITLE
No package python-jasmin available

### ISSUE THREAD

**Issue by lilslimxdg** [jookies/jasmin#254]
curl -s https://packagecloud.io/install/repositories/jookies/python-jasmin/script.rpm.sh | sudo bash
sudo yum install python-jasmin

The curl was fine and when I do this, it said that "No package python-jasmin available", how to fix this?
thanks for responding

**Comment by zoufou** [comment]
What's your OS and version ?

**Comment by lilslimxdg** [comment]
I'm using centos 6.5

**Comment by zoufou** [comment]
There's no packaging for CentOS 6.x, it's only for CentOS 7.x: http://docs.jasminsms.com/en/latest/installation/index.html#rhel-centos

**Comment by lilslimxdg** [comment]
wow thank you :(

**Comment by zoufou** [comment]
You can still install through the pypi process: http://docs.jasminsms.com/en/latest/installation/index.html#pypi
