### ISSUE TITLE
Error in starting service jasmind

### ISSUE THREAD

**Issue by lilslimxdg** [jookies/jasmin#257]
I'm using centos 7, I've installed all the needed prequisite packages
to the step which using "invoke-rc.d jasmind start" on centos 7 give me command not found so I'm using:
[root@localhost ~]# systemctl start jasmind
Give me status below, seems like the service haven't started properly, I still don't know why
[root@localhost ~]# systemctl status jasmind
jasmind.service - LSB: Jasmin SMS Gateway
   Loaded: loaded (/etc/rc.d/init.d/jasmind)
   Active: active (exited) since Tue 2015-07-14 11:24:27 ICT; 9min ago
  Process: 3920 ExecStart=/etc/rc.d/init.d/jasmind start (code=exited, status=0/SUCCESS)

Jul 14 11:24:29 localhost.localdomain jasmind[3920]: from jasmin.protocols.cli.jcli import JCliProtocol
Jul 14 11:24:29 localhost.localdomain jasmind[3920]: File "/usr/lib/python2.7/site-packages/jasmin/protocols/cli/jcli.py", line 5, in <module>
Jul 14 11:24:29 localhost.localdomain jasmind[3920]: from jasmin.protocols.cli.protocol import CmdProtocol
Jul 14 11:24:29 localhost.localdomain jasmind[3920]: File "/usr/lib/python2.7/site-packages/jasmin/protocols/cli/protocol.py", line 3, in <module>
Jul 14 11:24:29 localhost.localdomain jasmind[3920]: from twisted.conch import recvline
Jul 14 11:24:29 localhost.localdomain jasmind[3920]: ImportError: No module named conch
Jul 14 11:32:07 localhost.localdomain systemd[1]: Started LSB: Jasmin SMS Gateway.
Jul 14 11:33:28 localhost.localdomain systemd[1]: Started LSB: Jasmin SMS Gateway.
Jul 14 11:45:42 localhost.localdomain systemd[1]: Started LSB: Jasmin SMS Gateway.
Jul 14 13:46:23 localhost.localdomain systemd[1]: Started LSB: Jasmin SMS Gateway.

**Comment by raamtg** [comment]
From the looks of the errors, it seems you are using the Ubuntu start up scripts for your CentOS installation e.g. invoke-rc.d is ubuntu only as far as i know.

For CentOS, try service jasmind start.  I will get the documentation fixed accordingly.

This is how it looks in my environment (running RHEL 7).

[ec2-user@ip-172-31-43-24 ~]$ service jasmind start
Starting jasmind system service jasmind[  OK  ]
[ec2-user@ip-172-31-43-24 ~]$ 

[ec2-user@ip-172-31-43-24 ~]$ service jasmind status
30271
jasmind system service Status[  OK  ]
[ec2-user@ip-172-31-43-24 ~]$ 
[ec2-user@ip-172-31-43-24 ~]$ ps -ef | grep jasmin
ec2-user 17758 17678  0 09:15 pts/1    00:00:00 grep --color=auto jasmin
root     30271     1  0 Jul08 ?        00:00:00 su -s /bin/bash jasmin -c /usr/bin/python /usr/bin/jasmind --username jcliadmin --password jclipwd
jasmin   30276 30271  0 Jul08 ?        00:02:30 /usr/bin/python /usr/bin/jasmind --username jcliadmin --password jclipwd
[ec2-user@ip-172-31-43-24 ~]$

**Comment by zoufou** [comment]
Yes Raam that was the issue, @lilslimxdg is using Ubuntu's script inside CentOS, please consider using the CentOS one from the installation docs.

@raamtg, and in same time, this is also something to be enhanced in the packager so Jasmin will be **invoke** -able in CentOS.

**Comment by fareedawan** [comment]
same issue with me like "lilslimxdg".and also [root@localhost ~]# systemctl start jasmind
Job for jasmind.service failed because the control process exited with error code. See "systemctl status jasmind.service" and "journalctl -xe" for details.                                                                                            
plz guide me how to resolve this issue on centos 7
