### ISSUE TITLE
Dlr-level problem

### ISSUE THREAD

**Issue by sotoz** [jookies/jasmin#266]
Hello,
I'm setting the dlr-level=3 on the http request while I'm sending an SMS but jasmin is considering the request as a level 1 and is sending the sms-c level 1 dlr parameters only to my dlr-url.

My http request is like:
```
http://127.0.0.1:1401/send?username=(removed)&password=(removed)&from=SOTOS&to=(removed)&dlr=yes&dlr-level=3&dlr-method=get&dlr-url=http://127.0.0.1/sms/dlr.php&content=TEST&coding=0
```

The message is delivered on the mobile device and I'm getting a DLR that the message is received at messages.log 
```
WARNING  23686 Got a DLR for an unknown message id: 1000000402564282 (coded:38d7ebcc524ba)
INFO     23686 DLR [cid:cbf] [smpp-msgid:38d7ebcc524ba] [status:DELIVRD] [submit date:1507221414] [done date:1507221414] [sub/dlvrd messages:001/001] [err:000] [content:]
```

An example dlr in the dlr-thrower.log is the following
```
2015-07-22 14:58:40 INFO     23686 Throwed DLR [msgid:7973ebea-c67b-4f12-b428-06b9c5a20eb7] to http://127.0.0.1/sms/dlr.php?message_status=ESME_ROK&id=7973ebea-c67b-4f12-b428-06b9c5a20eb7&level=1.
```
And therefore I can't get the DLR status at my dlr-url if the message is delivered or not the mobile device. I have also tried with dlr-level=2.
Thanks

**Comment by zoufou** [comment]
Trying to reproduce this case, i'll get back to you.

**Comment by zoufou** [comment]
This is not an issue, everything is clear in this line:

    WARNING  23686 Got a DLR for an unknown message id: 1000000402564282 (coded:38d7ebcc524ba)

Here's a F.A.Q. entry on this subject: http://docs.jasminsms.com/en/latest/faq/users.html#when-receiving-a-dlr-got-a-dlr-for-an-unknown-message-id

You have to set **dlr_msgid** to the right value in the SMPP client connector configuration.

**Comment by sotoz** [comment]
I have seen that the problem got resolved by its own when I added another smpp connector with adifferent smpp server. 
The dlr thrower shouldn't report the level as 3 and not as 1 (as you can seen in the log line that I gave)?

**Comment by zoufou** [comment]
The thrower reported level1 for receiving the submit_sm_resp, then didnt report level3 since deliver_sm was not handled correctly.

Did i misunderstood something .?

**Comment by sotoz** [comment]
Nope, you understood correctly. I just made a false assumption that the dlr-thrower should show the dlr-level that was submitted through the http api request.
