### ISSUE TITLE
jasmin smpp-server post to http

### ISSUE THREAD

**Issue by chavezmx** [jookies/jasmin#270]
Hello I have been doing some testing with jasmin as a smpp server, and kannel as client, so I want to get a MO from the kannel and delivered to jasmin so it can post it to an http server. (I know that with kannel I can post it directly to an http server). I'm looking to use jasmin as an smpp server.
But for some reason I can't get jasmin to do the routing, my setup is the following:

#Filter id        Type                   Routes Description                     
#TF               TransparentFilter      MO MT  <TransparentFilter>             
Total Filters: 1

jcli : morouter -l
#Order Type                    Connector ID(s)                                  Filter(s)                                                       
#10    StaticMORoute           http(http-01)                                    <TransparentFilter>                                             
#0     DefaultRoute            http(http-01)                                                                                                    
Total MO Routes: 2

jcli : httpccm -l
#Httpcc id        Type                   Method URL                                                             
#http-01          HttpConnector          POST   http://172.30.7.158/endpoint.php                                
Total Httpccs: 1

jcli : smppccm -l
Total connectors: 0

And the log shows:

2015-07-24 16:11:39 WARNING  9191 SMPP connection established from 172.30.7.229 to port 2777
2015-07-24 16:11:39 INFO     9191 Added bind_transmitter bind for 'wapbooster'. Active binds: bind_receiver: 0, bind_transceiver: 0, bind_transmitter: 1.
2015-07-24 16:11:39 INFO     9191 Bind request succeeded for wapbooster in session [2d6197ae-713e-44ee-9391-d63b249b05b4]. 1 active binds
2015-07-24 16:11:51 ERROR    9191 No route matched from user wapbooster for SubmitSmPDU: PDU [command: submit_sm, sequence_number: 105, command_status: ESME_ROK

**Comment by zoufou** [comment]
Hello !

MO (which stands to Mobile Originated) is a DeliverSmPDU, in your case, Kannel is sending a SubmitSmPDU to Jasmin's server, it must be handled using a mtroute.

**Comment by chavezmx** [comment]
So I can't get it to send to http server ? Only smpp or there is any configuration to get it working ?

**Comment by zoufou** [comment]
Please tell what you're looking to achieve ? what's the scenario ?

**Comment by chavezmx** [comment]
I want to act as a proxy beteween some smpp/http messages platforms, but we have an internal platform that is the one that act as the decision maker about how to send them. 

so basically, I have already multiple kannel servers that send the messages to the final users, we have a webservice that has the api to send message, but one partner want to use smpp instead http so I want to accomplish this with jasmine, I know that kannel has a smppbox but it's not in active development anymore, the last time I used it, only about 1msg/second could be achieved.

Sorry for my bad English, hope I could make myself clear.

**Comment by zoufou** [comment]
let me draw you a simple schema:

Actually you have:

    your partner -----[http]----> Kannel -----[smpp]-----> some where in the world

And you need to:

    your partner -----[smpp]----> Jasmin -----[smpp]-----> some where in the world

If this is the case, then use **mtrouter** instead of **morouter**, you'll be able to route traffic from user "partner" (left) to the smpp connector on the right.

**Comment by chavezmx** [comment]
Ok right now:

your partner -----[http(our api)]------>[smpp(kannel)/webservice] -----> some where in the world

and I want if possible:

your partner -----[smpp(jasmin)]------>[http(our api*)]----->[smpp(kannel/jasmin)/webservice] -----> some where in the world

*have many business rules that could take many time to migrate to a class in jasmine, incluiding monitoring, services...

**Comment by zoufou** [comment]
This is definitely not supported, this can be a custom dev if needed, you can contact support@jasminsms.com for that.
