### ISSUE TITLE
How to take backup Of Configurations

### ISSUE THREAD

**Issue by sah-anshu** [jookies/jasmin#277]
Hi
I updated the git and previous Configuration got lost after rebuild of the app. Is there can way we shall retain the previous config Or any Configuration backup .

Thanks in advance

**Comment by zoufou** [comment]
This is related to #264:

* If you install/update Jasmin using **pip** then your */etc/jasmin* will be reset everytime you update, pip is for dev. and not for prod.
* Install Jasmin using deb or rpm packages, upgrades will never touch your config and persisted data
* If you need to stay with **pip**, then back your */etc/jasmin/jasmin.cfg* and */etc/jasmin/store* before updating, then restore them after, you'll keep going without config loss
