### ISSUE TITLE
Limit password length to 8 when creating/updating a smppc

### ISSUE THREAD

**Issue by zoufou** [jookies/jasmin#286]

**Comment by zoufou** [comment]
**system_id** must be limited to 16 chars as well.

**Comment by twoSeats** [comment]
@farirat sorry to comment on a closed issue, but can I just ask why is this actually a thing?
In my case I'm working with a local MNO and they have given me a password longer than 8 characters to use to access their smpp server. This restriction has me now quibbling with them over their password generation policy.
but why limit it in the first place?

**Comment by farirat** [comment]
The SMPP Specification restricts the length of the password. If you look at the definition of the password field in bind requests (eg. Section 4.1.1.1) it is defined as a variable length "C-Octet-String" with a maximum length of 9 octets.

The strings are null terminated so this gives you 8 usable characters for the password (see section 3.1.2).

Jasmin is sticking to the protocol specs, some vendors permit more flexibilities ...

**Comment by twoSeats** [comment]
oh right, thanks for the clarification. helps a lot.
