### ISSUE TITLE
Need to know about message id length 

### ISSUE THREAD

**Issue by sumeetb** [jookies/jasmin#290]
SMPP version supported by client  = 3.4

Issue: Not accepting long message id returned by jasmin gateway. Eg: 9f56r828-rghu-7g18-9f10-135t4m8eh8q0.
can jasmin gateway be configured to return short message id?

**Comment by zoufou** [comment]
Hi @sumeetb, as of smpp v3.4 the **receipted_message_id** length is 65 octets, so Jasmin's msg id format is compliant, i think you're running into a compliance issue with your smpp client.

Anyway, Jasmin msg id is a RFC 4122 UUID object, here you can find more information on it: https://docs.python.org/2/library/uuid.html , Jasmin's using **uuid4** by the way.

If you're looking to a quick workaround, you can easily change the way the msgid is generated, here's your file: https://github.com/jookies/jasmin/blob/master/jasmin/managers/content.py , look at the **randomUniqueId** function and you'll find your way, that'll be a fix for you case.

**Comment by sumeetb** [comment]
Thanks for quick response @zoufou  :)

**Comment by zoufou** [comment]
You're most welcome !
