### ISSUE TITLE
Debian OVF Template

### ISSUE THREAD

**Issue by tarikogut** [jookies/jasmin#291]
https://mega.nz/#!7klHkIhA!laTOJpiLIGHazGAD_oJDN23IkjRvFseMTwJCayH03IM 

it is debian 8.1 ovf template 

user jasmin
password jasmin

root pass jasmin

enter jasmin user and type jcli

good luck!

**Comment by zoufou** [comment]
Hi Tarik, thank you for the effort !

Jasmin is now packaged in docker as well: https://hub.docker.com/r/jookies/jasmin/
