### ISSUE TITLE
Allow for a clustered deployment

### ISSUE THREAD

**Issue by farirat** [jookies/jasmin#292]
Design and make Jasmin deployable in a clustered environment with unique host controller serving configurations to other cluster nodes.

**Comment by snellingio** [comment]
+1

**Comment by sotoz** [comment]
So far, how can Jasmin run in a clustered environment? Is it possible by having different jasmin instances on different servers to submit to the same (remote) message broker / redis?

**Comment by zoufou** [comment]
@sotoz it is actually possible through some painful configuration, that's why this issue is created, to provide a simple way to deploy jasmin in a cluster.

**Comment by sah-anshu** [comment]
@zoufou I think it is achievable if we break connectors and core services in different processes.

**Comment by zoufou** [comment]
The target design is to have jasmin deployed on n nodes, with one configurable instance that sync to others, a controller node.

This is similar to JBoss AS clustered deployment, or more light & simple: the zato.io esb.

**Comment by LeeVidor** [comment]
I'm looking to deploy Jasmin and provide HA for SMPP clients connecting to LB. Has there been any progress on this shared config? What is normally common to achieve this scenario?

**Comment by harbari** [comment]
@LeeVidor Hi
Did you find, how resolving the problem with a cluster? 
Did you build like HA architecture?
