### ISSUE TITLE
configuration lost after restart of jasmin

### ISSUE THREAD

**Issue by sah-anshu** [jookies/jasmin#298]
Hi
I connected to the  telnet 127.0.0.1 8990. Did the configuration of smppccm, group and user and then i restarted jasmin using service jasmind restart.

Again i telnet to telnet 127.0.0.1 8990 The configurations were lost.
python -c "import jasmin;print jasmin.get_release();"
0.6rc41

the permission to /etc//jasmin folders are below:

root@voice-server1:/etc/jasmin# ls -l
total 32
-rw-r--r-- 1 jasmin jasmin 20668 Aug 20 14:14 jasmin.cfg
drwxr-xr-x 2 jasmin jasmin  4096 Jul 10 16:04 resource
drwxr-xr-x 2 jasmin jasmin  4096 Jul 10 16:04 store

**Comment by edo-xcplat** [comment]
Hi,

From your comment it's not clear whether you've executed **persist** command after completing jasmin configuration in order to have it stored, i.e. reloaded upon service restart.

**Comment by sah-anshu** [comment]
Hi Thanks for your reply. 
kindly help me with persist command .

**Comment by ed-irwane** [comment]
While still connected via telnet console, after you're done with the configuration type "persist" to store your configuration.

Also, you can type "help" to get a complete list of commands. Or "help command" to get more detailed explanation for a particular one.

**Comment by sah-anshu** [comment]
thanks it was helpful.
