### ISSUE TITLE
custom esm_class for specific smsc

### ISSUE THREAD

**Issue by sah-anshu** [jookies/jasmin#299]
Hi

One Of my SMSC Uplink advised me to submit sms in esm_class=0 while jasmin is submitting in esm_class=3

Thanks in advance.

**Comment by zoufou** [comment]
The esm_class is set to Store and forward per default and is not exposed in jcli for modification, you can always play with the default value in jasmin/protocols/smpp/configs.py

**Comment by sah-anshu** [comment]
by changing value of esm_class in jasmin/protocols/smpp/configs.py shall change the value for all the uplink smsc. is it possibly configurable for specific smsc.

**Comment by zoufou** [comment]
In this case, you have to do some conditionals when jasmin is creating the connector in perspective_connector_add method, in jasmin/managers/clients.py.
