### ISSUE TITLE
Creation of groups in jcli including spaces in name

### ISSUE THREAD

**Issue by sotoz** [jookies/jasmin#300]
While testing the jasmin-web api I came across this problem. I tried to add/remove a group that has includes the space character. I added it correctly but I couldn't remove it afterwards. I tried the same on jcli and this is what I did:
````
jcli : group -a
Adding a new Group: (ok: save, ko: exit)
> gid test odiki
> ok
Successfully added Group [test odiki]
jcli : group -l
#Group id        
#test odiki      
Total Groups: 1
jcli : group -r test odiki
Unknown Group: test
jcli : group -remove=test odiki
Unknown Group: emove=test
````

The router.log correctly reported the addition with:
````
2015-08-25 21:57:19 INFO     4854 Adding a Group (id:test odiki)
````
but It didn't have any removals as expected. Now I have a group that I cannot remove with jcli.

Documentation on jcli group module isn't reporting any more info on that matter.

**Comment by zoufou** [comment]
you're using a prior version to 0.6rc41, please update jasmin to 0.6rc41, gid will be restricted to a given syntax.
