### ISSUE TITLE
Multiple Jasmin on single machine

### ISSUE THREAD

**Issue by sumeetb** [jookies/jasmin#303]
Is it possible to run multiple instance of jasmin gateway on single machine? I have multiple instance of rabbitmq and redis server running. 

Please let me know changes required in order to run multiple instance.

**Comment by zoufou** [comment]
You can adjust jasmin.cfg port bindings and log files folder to avoid any conflict, you have no need for multiple instances of rabbitmq & redis, only put different auth. credentials for each jasmin instance.

**Comment by sumeetb** [comment]
I tried above it started,but when trying to connect to cli, i am not getting username/password screen. Below is the output

$ ps -ef | grep jasmin
root     31237     1  2 10:11 ?        00:00:01 /usr/bin/python /usr/local/bin/jasmind.py --username jcliadmin --password jclipwd
root     31522     1 24 10:12 ?        00:00:01 /usr/bin/python /usr/local/bin/jasmind.py --username jcliadmin --password jclipwd

$ telnet 127.0.0.1 8991
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
▒▒pb▒none

**Comment by zoufou** [comment]
I see you're pointing both instances to the same jasmin.cfg, you need to use the **-c**  switch for a different config file

**Comment by sumeetb** [comment]
Can you please let me know the command? where i need to provide -c switch option?

**Comment by zoufou** [comment]
/usr/bin/python /usr/local/bin/jasmind.py --help

**Comment by sumeetb** [comment]
Hi,
I tried changing config file but not able to connect to cli for second instance. getting connection refused. Please see below output:

root     24086     1  0 12:31 ?        00:00:11 /usr/bin/python /usr/local/bin/jasmind.py -c /etc/jasmin/jasmin1.cfg --username jcliadmin --password jclipwd
root     24135     1  0 12:31 ?        00:00:01 /usr/bin/python /usr/local/bin/jasmind.py -c /etc/jasmin/jasmin.cfg --username jcliadmin --password jclipwd

$ telnet 127.0.0.1 8990
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused

$ telnet 127.0.0.1 8992
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Authentication required.

Username:

Also tried with different username and password for cli but that also didn't work :(

root     15647     1  1 13:33 ?        00:00:01 /usr/bin/python /usr/local/bin/jasmind.py -c /etc/jasmin/jasmin.cfg --username jcliadmin --password jclipwd
root     15685     1  0 13:33 ?        00:00:01 /usr/bin/python /usr/local/bin/jasmind.py -c /etc/jasmin/jasmin1.cfg --username jcliadmin1 --password jclipwd1

**Comment by zoufou** [comment]
checkout jcli.log, redis-client.log and amqp-client.log

**Comment by tarikogut** [comment]
use proxmox add virtual machine use multiple jasmin sms server

2015-08-27 14:39 GMT+03:00 zoufou <notifications@github.com>:

**Comment by sumeetb** [comment]
@zoufou : Please see log. For second instance  it should look into /etc/jasmin1/store/ not /etc/jasmin/store/. 

Please note,  i deleted stored files to start fresh.

Instance 1
========
2015-08-27 13:40:33 INFO     15647 [sref:3] New session started for 127.0.0.1:55512
2015-08-27 13:40:33 ERROR    15647 Config loading error: Cannot load from /etc/jasmin/store/jcli-prod.filters: [Errno 2] No such file or directory: '/etc/jasmin/store/jcli-prod.filters'
2015-08-27 13:40:33 ERROR    15647 Config loading error: Cannot load from /etc/jasmin/store/jcli-prod.httpccs: [Errno 2] No such file or directory: '/etc/jasmin/store/jcli-prod.httpccs'
2015-08-27 13:40:40 INFO     15647 [sref:3] Session stopped (Connection was closed cleanly.).

Instance 2
==========
2015-08-27 13:43:58 INFO     18599 [sref:2] New session started for 127.0.0.1:51142
2015-08-27 13:43:58 ERROR    18599 Config loading error: Cannot load from /etc/jasmin/store/jcli-prod.filters: [Errno 2] No such file or directory: '/etc/jasmin/store/jcli-prod.filters'
2015-08-27 13:43:58 ERROR    18599 Config loading error: Cannot load from /etc/jasmin/store/jcli-prod.httpccs: [Errno 2] No such file or directory: '/etc/jasmin/store/jcli-prod.httpccs'

@tarikogut I understand, we can use VMs for multiple instance, but the requirement is to run on single machine.

**Comment by sumeetb** [comment]
There is no error in other files apart from jcli.log mentioned above.

**Comment by zoufou** [comment]
@sumeetb those are not critical errors, it's normal, jcli is claiming there's no persisted data in store, nothing bad.

Did you think about managing multiple docker containers on one node ? that will avoid all the pain you're doing right now, you'll install clean and default jasmin configuration inside each container then nat different ports.

**Comment by tarikogut** [comment]
it is not possible because jasmin stored all data /etc  if you mean run
another port its not possible now


2015-08-27 15:20 GMT+03:00 zoufou <notifications@github.com>:

**Comment by zoufou** [comment]
You still can switch store place.

What about docker approach ?

**Comment by tarikogut** [comment]
https://www.docker.com/
if you need ovf file
https://mega.nz/#!7klHkIhA!laTOJpiLIGHazGAD_oJDN23IkjRvFseMTwJCayH03IM you
can download this link

2015-08-28 17:38 GMT+03:00 zoufou <notifications@github.com>:

**Comment by sumeetb** [comment]
The issue is resolved now. The issues were with ports. I have changed the all the ports to different series for second instance of gateway and it starts working. Thanks all for your help and support!

**Comment by llibarios12** [comment]
Hi @sumeetb can you share how this became possible? how the jasmin.cfg looks for handling multple jasmin in 1 instance. Thanks
