### ISSUE TITLE
Throughput Per From Number

### ISSUE THREAD

**Issue by mfreedman** [jookies/jasmin#304]
It would be nice to be able to set a max throughput at both the SMPP level, and the From Number level.

For instance, the SMPP might be able to handle 50 msgs/sec, but each longcode might need to be limited to 1 msg/sec.

**Comment by zoufou** [comment]
Please explain better, are you talking about smppc ? smpps ? a usage example maybe good for better understanding ..

**Comment by mfreedman** [comment]
Let's say our provider limits us to 10 SMS / second.  We connect to that provider via SMPP using Jasmin.  We send SMS to Jasmin via the HTTP API.

We must also not go over a per second threshold of 1 SMS per second per longcode.

It would be nice if we could send in 10 messages at once to Jasmin with a From number of 0001112222 (example number) and also 10 messages with a From number of 0001113333 and Jasmin could automatically throttle 10 on EACH number at 1 per second.

Hopefully that makes a little more sense.

**Comment by zoufou** [comment]
Does your provider accept multiple bindings ? if yes, then create as many connectors as you have longcodes, and stick each connector to a longcode using mtroute.

With this approach you can throttle messaging the way you want.

If your provide doesnt accept multiple bindings, then you still can do it through a cascaded deployment, this way:

    You---[http]--->Jasmin 1--->[many smpp binds]--->Jasmin 2--->[one smpp bind]--->Your provider

**Comment by mfreedman** [comment]
Thanks for the replies.  The provider does not allow multiple bindings.  I see what you're saying about the Jasmin 1 with the multiple bindings to the Jasmin 2 instance.

Do you see any issues if this were over for example 10,000+ bindings?

**Comment by zoufou** [comment]
10k bindings ? that's huge ! and can't be done on one server since 1 binding = 1 tcp connection, i guess it would take a bunch of buckets to reach 10k bindings ...

**Comment by mfreedman** [comment]
:)  I think that's why I was hoping for the possibility of a throughput limit on a filter or something.

**Comment by zoufou** [comment]
it's not a jasmin feature out of the box, but with some knowledge you can achieve such throttling, if you know how to drive the you'll start here: https://github.com/jookies/jasmin/blob/master/jasmin/managers/listeners.py#L177

**Comment by mfreedman** [comment]
I'll see what we can do.  Thanks!

**Comment by zoufou** [comment]
you're most welcome

dont hesitate to ping me if you're still struggling
