### ISSUE TITLE
Does Jasmin persist its configuration to disk ?

### ISSUE THREAD

**Issue by ixt1** [jookies/jasmin#309]
Jasmin installed on Ubuntu-15.04-server-amd64.
When restart server, Jasmin configuration not loading.
I'm looking for config file in folder /etc/jasmin/store , but nothing there.

**Comment by zoufou** [comment]
did you type **persist** in jcli before leaving out ?

Once you do, Jasmin will keep persisting your data automatically.

**Comment by ixt1** [comment]
Thanks a lot
:)

**Comment by zoufou** [comment]
you're welcome !
