### ISSUE TITLE
Postfix to Jasmin (Email to SMS)

### ISSUE THREAD

**Issue by ixt1** [jookies/jasmin#310]
How to setup Postfix to send incoming email to Jamin

For example when Postfix received email: un-pwd-phone@domain.com  pipe to Jasmin HTTP 
http://127.0.0.1:1401/send?username=un&password=pwd&to=phone&from=05555555&content=email_body

Thanks in advance.

**Comment by zoufou** [comment]
When asked for such integrations, i always refer to this simple one and adapt it to call Jasmin's api: http://tools.rebel-it.com.au/sms-transport/
