### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by sumeetb** [jookies/jasmin#311]
Does jasmin support unicode message? If yes, does it also convert it to unicode message before sending back to ESME?

**Comment by zoufou** [comment]
Are you talking about sending through http or smpp ?

**Comment by sumeetb** [comment]
Through SMPP

**Comment by zoufou** [comment]
no converting at all, as a router, jasmin will never update the message content, it will only read properties to decide on routing destination.

If you have unicode issues, then get assured, jasmin is not changing anything, you can verify it by dumping inbound and outbound smpp traffic and comparing the PDUs.

**Comment by sumeetb** [comment]
ok. Thanks!

**Comment by zoufou** [comment]
most welcome !
