### ISSUE TITLE
jasmin stop working after sending sms with invalid sender

### ISSUE THREAD

**Issue by majidkabir** [jookies/jasmin#321]
When I send sms with invalid sender number with http api jasmin gave a valid id to me, after this in all of my sending calls jasmin returns this message
Success "[Failure instance: Traceback: <class 'txamqp.client.Closed'>: Method(name=close, id=40) (406, 'PRECONDITION_FAILED - unknown delivery tag 24', 60, 90) content = None
/usr/local/lib/python2.7/site-packages/jasmin/managers/clients.py:566:perspective_submit_sm
/usr/local/lib/python2.7/site-packages/jasmin/queues/factory.py:215:publish
<string>:3:basic_publish
/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py:1274:unwindGenerator
--- <exception caught here> ---
/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py:1128:_inlineCallbacks
/usr/local/lib/python2.7/site-packages/txamqp/protocol.py:68:invoke
]"
and i must restart jasmind process!!!

**Comment by zoufou** [comment]
Your provider seems to use some vendor-specific tags, do you have information on that ?

**Comment by majidkabir** [comment]
I don't have any information about this tags, but the problem is when I send an sms that my vendor don't alow me to send by it this error occurs in next sending sms!!!

**Comment by zoufou** [comment]
Since your logs are not in debug i cannot know which type of pdu does this (is it deliver ? submit ? data ?)

Anyway, as of #322 resolution, Jasmin will just ignore vendor specific optional tags and will not raise any error anymore.

Please retest once #322 is closed and provide feedback here.

**Comment by zoufou** [comment]
Dear @majidkabir did you test with 0.6.post43 ?

**Comment by majidkabir** [comment]
Thanks 
Today after upgrading to 0.6.post43 the problem solved.
When user send a message with api, and SMSC return error, jasmin don't send any feedback to this user for sent message!

**Comment by zoufou** [comment]
You mean the SMSC is returning an error through a deliver_sm that does not get forwarded to user ?
if yes, please provide smppc & smpps debug logs, and messages.log
a tcpdump is helpful as well

**Comment by zoufou** [comment]
UP

**Comment by zoufou** [comment]
Issue closed since no feedback given.
