### ISSUE TITLE
New Feature: Expose STATS module over HTTP API - would be great for remote monitoring

### ISSUE THREAD

**Issue by deniskami** [jookies/jasmin#327]
Hi,

I would like to suggest a new feature. That is access STATS over HTTP. This can be used for remote jasmin service monitoring.

Thanks for your considerations and GREAT tool!!!

**Comment by zoufou** [comment]
Hey @deniskami thanks !

What do you mean by access stats ?

**Comment by deniskami** [comment]
Right now in order to check if Jasmin server has any issues I need to access it via Telnet and run 
jcli : stats --smppcs

It would be great if I can just access the same output by using HTTP GET to 
http://JASMINIP:1401/stats-smppcs
and get JSON back

**Comment by zoufou** [comment]
Actually you can check this project: https://github.com/jookies/jasmin-monitoring

It's a pack of scripts and templates to enable advanced Jasmin monitoring (including rabbitmq and auto discovery of users, connectors etc ...) through Zabbix, where you can also activate alerts to detect if a connector goes down, user have too much errors etc ...
