### ISSUE TITLE
'JCliSMPPClientConfig' object has no attribute 'dlr_msg_id_bases'

### ISSUE THREAD

**Issue by stdin** [jookies/jasmin#330]
Keep getting this error.

2015-11-04 21:09:43 CRITICAL 1075 Got an unknown exception: 'JCliSMPPClientConfig' object has no attribute 'dlr_msg_id_bases'

root@production-jasmin-1:~# dpkg -l | grep jasmin
ii  python-jasmin                    0.7.0-1                          all          SMS Gateway

root@production-jasmin-1:~# python -V
Python 2.7.6

root@production-jasmin-1:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

**Comment by zoufou** [comment]
What's the root cause ? what are you doing on jcli to get this error ?

**Comment by stdin** [comment]
I'm sending an SMS through HTTP API with dlr-url set.

**Comment by stdin** [comment]
Here is a full URL:

GET /send?username=[snip]&from=[snip]&dlr-url=[snip]&dlr-level=2&content=[snip]&to=[snip]&password=[snip]

**Comment by zoufou** [comment]
Is sms sent or not ?

**Comment by stdin** [comment]
SMS is sent, however delivery report is not.

**Comment by zoufou** [comment]
@stdin, am not able to reproduce the issue, did you upgrade jasmin while keeping old  persisted config ? if yes, what was your last version ?

**Comment by stdin** [comment]
No, it's a clean install. I can provide access to the machine if you're interested.

**Comment by zoufou** [comment]
i do, thx

share to my email please: fourat@gmail.com

**Comment by zoufou** [comment]
if you cant, then even a tcp dump of smpp session (bind, submit, deliver, unbind) would help me.

**Comment by zoufou** [comment]
Related to #265 

Running Jasmin instance many times may fuck-up with persisted configuration.
