### ISSUE TITLE
message parameter

### ISSUE THREAD

**Issue by ticanalse** [jookies/jasmin#356]
Hello! I installed jasmine. I tried to connect it to a platform that requires the following HTTP API:
http: //domain_name/send.php?from={{from}}&text ={{text}}&to={{to}}?
the problem is that Jasmine has as parameter message: content, while the platform as required message text parameter.
how can I fix it?
how to change the name of the parameter text message content?
thank you in advance!

**Comment by zoufou** [comment]
Duplicated to https://groups.google.com/forum/#!topic/jasmin-sms-gateway/7f114JODhXk
