### ISSUE TITLE
problem with "+" in the phone number 

### ISSUE THREAD

**Issue by supportticanalyse** [jookies/jasmin#357]
I installed Jasmin. it don't accept the "+" of phone number. 
I would like to know how to fix this? 
thank you in advance!

**Comment by zoufou** [comment]
In http or smpp ?

What's the error ?

**Comment by ticanalse** [comment]
http. if i send message i have :"Error "Argument [to] has an invalid value: [ 22675200209]." like error

**Comment by tarikogut** [comment]
it is not e164 format try this format and send again

2015-12-04 15:27 GMT+02:00 support <notifications@github.com>:

**Comment by ticanalse** [comment]
hi @tarikogut! i'm in Africa (Burkina Faso). my number is +22675200209. how can write it in e164 format?

**Comment by ticanalse** [comment]
i connect jasmin and my platform. my platform send HTTP API with the "+". I would like to know how to fix this?
thank you in advance!

**Comment by zoufou** [comment]
You're maybe mis-encoding the plus sign ...

**Comment by ticanalse** [comment]
my platform encoding "+" in "%2B" but it doesn't work!

**Comment by ticanalse** [comment]
Hi! would I know how to recognize the "+" sign to Jasmine? or how should I encode the sign "+"?

**Comment by zoufou** [comment]
Here's an example of http encoded + sign:

    %2B

So if you need to send to +332222:

    %2B332222

And here's a reference for more reading: http://www.w3schools.com/tags/ref_urlencode.asp

**Comment by ticanalse** [comment]
hi!
Yes that's right! but if I use "%2B" in the URL (http://127.0.0.1:1401/send?username=xxxx&password=xxxx&from=xxxx&to=%2B22673211539&content=test) and I test it in the URL of a browser, I receive a success message but the sms fails in my cell phone.
how do I do to fix this?

**Comment by zoufou** [comment]
You already fixed it :) just remove the encoded + sign and everything goes well.

Why do you need to add the plus ? since the message were delivered when not using it, it maybe your provider which not using that ...

**Comment by ticanalse** [comment]
of course! but my platform save the contacts with "+" and when sending it encode the "+" with "%2B". which is a problem because the sms fail. So when you configure a flow with a keyword in the platform return messages probably not arrive.
I hope you UNDERSTAND my anxiety?

**Comment by akrus** [comment]
Hi there!

Wanted to ask if it is possible to strip leading + sign in Jasmin (and e.g. replace it with 00)? Kannel has unified-prefix for this.

**Comment by farirat** [comment]
And Jasmin has the interceptor for that ;)
