### ISSUE TITLE
MO configuration

### ISSUE THREAD

**Issue by supportticanalyse** [jookies/jasmin#358]
Hi! I would like to know how to configure the MO? I read the documentation but I can not. My platform gave me the API: https://IP_address/api/v1/external/received/4ab12bfa-620e-4228-9137-1f51badef1ba/ 
how can configure the MO with it?
thanks!

**Comment by zoufou** [comment]
I understand you need to send MO traffic to some http endpoint ?

What's the endpoint address ?

**Comment by ticanalse** [comment]
Hi!
yes I need to send MO traffic to some http endpoint. I put the URL of my gateway jasmine in the plateform (http://127.0.0.1:1401/send?username=xxxx&password=xxxx&from=xxx&to=0022673211539&content=test) and the platform has generated another URL (https://IP_address/api/v1/external/received/4ab12bfa-620th-4228-9137-1f51badef1ba/) should I use in my gateway.
Now how to set up for the reception of messages from the phones work?
My endpoint address is: https://IP_address/api/v1/external/received/4ab12bfa-620th-4228-9137-1f51badef1ba/.
thank you in advance for your assistance?

**Comment by zoufou** [comment]
Go to jcli:

1. Add a http connector:

```
    jcli : httpccm -a
    Adding a new Httpcc: (ok: save, ko: exit)
    > url https://IP_address/api/v1/external/received/4ab12bfa-620th-4228-9137-1f51badef1ba/
    > method GET
    > cid HTTP-01
    > ok
    Successfully added Httpcc [HttpConnector] with cid:HTTP-01
```

2. Add a mo route pointing on it:

```
    jcli : morouter -a
    Adding a new MO Route: (ok: save, ko: exit)
    > type DefaultRoute
    jasmin.routing.Routes.DefaultRoute arguments:
    connector
    > connector http(HTTP-01)
    > ok
    Successfully added MORoute [DefaultRoute] with order:0
```

**Comment by ticanalse** [comment]
thanks! i tried to configure following your example but it's not work. if i send a sms with keyword my platform doesn't receive. i don't know where is the problem. can you tell me where could i see the log because i don't find it in /var/log/jasmin/?

**Comment by zoufou** [comment]
check your deliversm-thrower.log

**Comment by ticanalse** [comment]
in deliversm-thrower.log file i have this:
2015-12-07 10:05:14 INFO     5326 Thrower configured and ready.
2015-12-07 10:05:14 INFO     5326 Added amqpBroker
2015-12-07 10:05:14 INFO     5326 Consuming from routing key: deliver_sm_thrower.*
2015-12-07 10:49:40 INFO     14603 Thrower configured and ready.
2015-12-07 10:49:40 INFO     14603 Added amqpBroker
2015-12-07 10:49:40 INFO     14603 Consuming from routing key: deliver_sm_thrower.*

**Comment by chihau** [comment]
I have create the HTTP connector and MO route. How I can send SMS-MO to test my server?

**Comment by mrsanvicente** [comment]
Hello Farirat,

Do you the code of?

https://IP_address/api/v1/external/received/4ab12bfa-620th-4228-9137-1f51badef1ba/

I need understand how it works, in order to set one for me

Thanks

**Comment by mrsanvicente** [comment]
using the httpcc,   implies global variables? 

which are they?    sample .$contacts , $senderid , $msg 


Thanks
