### ISSUE TITLE
Web UI 

### ISSUE THREAD

**Issue by shuklaabhi** [jookies/jasmin#364]
How can I use web backend to monitor and configure which is based on Django, as per documentation. I can't see any Django dependency in requirements.txt.

**Comment by zoufou** [comment]
Hi !

There's no web console right now, everything is manageable through telnet console (jcli): http://docs.jasminsms.com/en/latest/management/jcli/index.html

**Comment by greenx** [comment]
Then need remove it from the documentation.

**Comment by twoSeats** [comment]
Anyone (like me) arriving at this issue should maybe have a look at [jasmin-web](https://github.com/jookies/jasmin-web) & [jasmin-api](https://github.com/jookies/jasmin-api)
