### ISSUE TITLE
Error in starting JCLI

### ISSUE THREAD

**Issue by majidkabir** [jookies/jasmin#365]
Hi @zoufou 

Recently I upgrade my jasmin to latest version (0.8.10) with pip, on one of my server there was no problem when starting jasmin, but in another server there is an error when jasmin want to start jcli listener. 
```
Traceback (most recent call last):
  File "/usr/bin/jasmind.py", line 234, in startJCliService
    self.components['jcli-server'] = reactor.listenTCP(JCliConfigInstance.port, JCli_f, interface=JCliConfigInstance.bind)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 478, in listenTCP
    p.startListening()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 1002, in startListening
    self.factory.doStart()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/site-packages/jasmin/protocols/cli/factory.py", line 80, in doStart
    if (self.config.authentication and self.loadConfigProfileWithCreds['username'] is not None
exceptions.TypeError: 'set' object has no attribute '__getitem__'
```

**Comment by majidkabir** [comment]
After that error jasmin started and work properly, I connect to jcli and add a smppc and persist it, but when I restart the jasmin gateway, there is not any smppc in my configs!!!

**Comment by zoufou** [comment]
what was your version before upgrading ?

check the first line of any persisted config file in /etc/jasmin/store, it indicates the version of jasmin used for that config.

**Comment by majidkabir** [comment]
After upgrading with pip my previous configs replaced with new config files! 
and now the version is 0.8.10

**Comment by zoufou** [comment]
Don't use pip for production, am not sure if it keeps your configs in place.

best way for production is deb & rpm packages, starting from 0.8, all upgrades will be backward compatible for your configs, it was not the case for 0.6.

**Comment by majidkabir** [comment]
Thank's zoufou but my problem is not this, I can't understand why on one of my server jasmin started without any error but on another server the error in first message occured!

**Comment by zoufou** [comment]
Sorry for misunderstanding, do you have same configs and same persisted store between both servers ?

**Comment by majidkabir** [comment]
In this server even when for the first time jasmin started this error occured, I copying all jasmin dircetory from the correct server but dont anything change!

**Comment by zoufou** [comment]
are you sure about right jasmin version ? 0.8.10 ?
please remove everything from /etc/jasmin/store and start jasmin

Ensure you dont have an old instance of jasmin already running: ps ax|grep jasmin
Rabbit & redis are started ?

**Comment by majidkabir** [comment]
This is the output:
![untitled](https://cloud.githubusercontent.com/assets/13327580/11913275/f775580c-a673-11e5-9e14-2a77a40ad2ec.png)

**Comment by zoufou** [comment]
tail -n 20 /var/log/syslog (or /var/log/messages)

**Comment by majidkabir** [comment]
![untitled](https://cloud.githubusercontent.com/assets/13327580/11913311/be218052-a674-11e5-9ce5-2f463a75b762.png)

**Comment by zoufou** [comment]
is it a virgin jasmin.cfg ? or did you update anything ?

**Comment by majidkabir** [comment]
It is virgin

**Comment by zoufou** [comment]
Then get me remote access so i can check it.

**Comment by majidkabir** [comment]
An ID for chat :)

**Comment by zoufou** [comment]
fourat@gmail.com

**Comment by majidkabir** [comment]
I solved the problem by changing jcli/factory.py line 48
from 
```
loadConfigProfileWithCreds = {'username', 'password'}
```
to
```
loadConfigProfileWithCreds = {'username':'jcliadmin', 'password':'jclipwd'}

```

**Comment by zoufou** [comment]
it will be closed by a PR
