### ISSUE TITLE
help: setting up 1st sms

### ISSUE THREAD

**Issue by illuminate3** [jookies/jasmin#372]
```
type DefaultRoute jasmin.routing.Routes.DefaultRoute arguments: connector
```

is giving me the error.

```
Unknown MT Route type:DefaultRoute jasmin.routing.Routes.DefaultRoute arguments: connector, available types: DefaultRoute, StaticMTRoute, RandomRoundrobinMTRoute
```

This is all supposed to be typed in on 1 line right?

Any ideas?

**Comment by farirat** [comment]
No, you type:

    type DefaultRoute
    connector smppc(someconnector)

**Comment by illuminate3** [comment]
I'm on step 3 of the Sending your first SMS instructions.

```
> type defaultroute
jasmin.routing.Routes.DefaultRoute arguments:
connector
> connector smppc(DEMO_CONNECTOR)
```

How do you get the commands on separate lines?

**Comment by farirat** [comment]
type 'enter' :)

**Comment by illuminate3** [comment]
```
jcli : type DefaultRoute
```
hit "enter / return" key

Get error:
```
Incorrect command: type DefaultRoute, type help for a list of commands
```

This is why I asked.

**Comment by farirat** [comment]
ok i see, you need to understand the prompt, if you have **jcli :** then you only have access to toplevel modules (double type tabulation to see those modules).

for your case, you need to be already inside a module setup:

    mtrouter -a
    type DefaultRoute

**Comment by illuminate3** [comment]
that's what I got:

```
jcli : mtrouter -a
Adding a new MT Route: (ok: save, ko: exit)
> type DefaultRoute
<class 'jasmin.routing.Routes.DefaultRoute'> arguments:
connector, rate
>
```

All on 1 line:

```
> type DefaultRoute jasmin.routing.Routes.DefaultRoute arguments: connector
Unknown MT Route type:DefaultRoute jasmin.routing.Routes.DefaultRoute arguments: connector, available types: DefaultRoute, StaticMTRoute, RandomRoundrobinMTRoute
>
```

Thanks for hanging in here with me!

**Comment by farirat** [comment]
No worries, type the followings line by line:

    mtrouter -a
    type defaultroute
    connector smppc(your_connector)
    rate 0
    ok

**Comment by illuminate3** [comment]
AH! got it!

I thought

```
<class 'jasmin.routing.Routes.DefaultRoute'> arguments:
connector, rate

```

was an error when it was just information.

Thanks!

**Comment by farirat** [comment]
you're welcome !
