### ISSUE TITLE
what is a Perspective broker?

### ISSUE THREAD

**Issue by illuminate3** [jookies/jasmin#373]
Does jasmin need special hardware to run outside of a server?

**Comment by farirat** [comment]
What's running "outside of a server"  ? :)

**Comment by illuminate3** [comment]
sorry, besides a server.

Does the server need a modem card?

**Comment by tarikogut** [comment]
where is terminate your smpp server ? GSM Modem ?

2016-01-07 22:20 GMT+02:00 illuminate3 <notifications@github.com>:

**Comment by illuminate3** [comment]
Are you saying that I need hardware to use with jasmin?
