### ISSUE TITLE
Param NOTSET not workin properly

### ISSUE THREAD

**Issue by neowisard** [jookies/jasmin#374]
Can't disable logging with NOTSET param. Level CRITICAL workin normally.

jasmin.cfg 

// Specify the server verbosity level.
// This can be one of:
// NOTSET (disable logging)
log_level            = NOTSET
log_file            = /var/log/jasmin/main-smpp.log

after restart , in main-smpp.log

>2016-01-12 09:25:20 WARNING  1 SMPP zzzzzzzz disconnected from port 2775: [Failure instance: Traceback (failure with no frames): <type 'exceptions.ValueError'>: Field is not nullable
]
2016-01-12 09:26:05 WARNING  1 SMPP connection established from zzzzzzzzz to port 2775
2016-01-12 09:26:06 ERROR    1 No route matched from user neo for SubmitSmPDU: PDU [command: submit_sm, sequence_number: 13, command_status: ESME_ROK

**Comment by farirat** [comment]
It seems you are trying to disable logging for a *smpp client connector*, this is DONE through jcli by updating connector params.
