### ISSUE TITLE
All DLRs are ignored for some unknown reason

### ISSUE THREAD

**Issue by farirat** [jookies/jasmin#375]
In v0.8 when pushing through smpp server at 50 MPS, it happens that dlrs are not matched when deliver_sm is received although the key in redis db already exist, but log is showing:

    INFO     31430 SMS-MT [cid:smpptest] [queue-msgid:a06440c7-c13f-4a72-9309-41576ea6ad42] [smpp-msgid:24] [status:ESME_ROK] [prio:0] [dlr:SMSC_DELIVERY_RECEIPT_REQUESTED] [validity:none] [from:john] [to:...] [content:...]
    WARNING  31430 Got a DLR for an unknown message id: 24 (coded:24)

The key seems to exist in db:

    127.0.0.1:6379> get queue-msgid:27
    "\x80\x02}q\x00(U\x05msgidq\x01U$d5aca148-0791-4c19-98e7-b329480c6870q\x02U\x0econnector_typeq\x03U\x05smppsq\x04u."

The monitoring is showing a key db not decreasing, proving that all dlrs were ignored:

<img width="1174" alt="screen shot 2016-01-17 at 11 43 07 pm" src="https://cloud.githubusercontent.com/assets/1020111/12380839/29a1b2d2-bd74-11e5-82ee-54df78cb9bd9.png">

**Comment by bagherfathi** [comment]
hi fourat,
i found whats the problem.(ofcourse for one part sms)
you set dlr in redis as string, but get as numeric
for example you set 000024 as dlr msgid but you get 24 for dlr msgid then redis return null
 
for multi part message problem is more complicated!

**Comment by farirat** [comment]
Hi @bagherfathi ! thank you for your help.

What version of Jasmin are you considering ? this issue is for 0.8.10

**Comment by bagherfathi** [comment]
yes, my jasmin 
version is 0.8.10

**Comment by farirat** [comment]
Then your line numbers seems to mismatch here: https://github.com/jookies/jasmin/blob/master/jasmin/managers/listeners.py

**Comment by bagherfathi** [comment]
excuse me , i added some break point to line, and line numbers changed

**Comment by bagherfathi** [comment]
you can find 
"hashKey = "queue-msgid:%s" % r.response.params['message_id']" 
in listeners.py

**Comment by bagherfathi** [comment]
correct line numbers is : 441 and 488

**Comment by farirat** [comment]
Yes, this issue were fixed in 0.9, checkout this: #366

I'll port this fix back to 0.8, thank you @bagherfathi for pointing it !

**Comment by farirat** [comment]
Issue still exists even in v0.8.11

**Comment by farirat** [comment]
After some tests, it seems it happens that redis get a bit slow and when a dlr come in, it's key is not found in redis since it's being saved.

Redis may be tuned up for better performance, or maybe redis should be replaced by some better db.
