### ISSUE TITLE
Using external AMQP Broker and Redis

### ISSUE THREAD

**Issue by xamaxmacko** [jookies/jasmin#379]
Hello!

We need to implement connection of Jasmin with remote AMQP and REDIS instead of ones installed locally on the same machine as Jasmin.

Is there any way to do that?

Thanks in advance.

**Comment by pyghassen** [comment]
Hi there,

I thing you change that on the main config file and override Redis client
and set to your remote Redis server, the same for RabbitMQ.

**Comment by pyghassen** [comment]
@xamaxmacko check this file and you will understand what I mean.
https://github.com/jookies/jasmin/blob/master/misc/config/jasmin.cfg

**Comment by farirat** [comment]
And to append on @pyghassen:

For redis: https://github.com/jookies/jasmin/blob/master/misc/config/jasmin.cfg#L460
For rabbit: https://github.com/jookies/jasmin/blob/master/misc/config/jasmin.cfg#L223
