### ISSUE TITLE
HTTP Stats do not include some of the same things as SMPP Stats

### ISSUE THREAD

**Issue by raamtg** [jookies/jasmin#388]
Hello, I noticed that the following features are in the  SMPP stats for a user, but not for the HTTP stats. Is this for a specific reason?

throttling_error_count

other_submit_error_count

submit_sm_count

deliver_sm_count

For example,  "other_submit_error_count" is there in SMPP. With HTTP, I can only see how many HTTP requests (submit_sm_request_count - HTTP API) were made, but not how many were succesfull and how many failed.

**Comment by farirat** [comment]
Dropped feature for low priority.
