### ISSUE TITLE
Forced routing

### ISSUE THREAD

**Issue by zspine** [jookies/jasmin#393]
We are using a custom java application as our SMS gateway and we are testing Jasmin with hopes to replace our custom SMS gateway. I would like to know if there is any way to force a connection to be used from application side instead of jasmin's routing system. 

Example:

```
<?php
$baseurl = 'http://127.0.0.1:1401/send'

$params = '?username=nathalie';
$params.= '&password=secret';
$params.= '&to='.urlencode('+24206155423');
$params.= '&content='.urlencode('Hello world !');

//e.g. skip jasmin routing and force a connection to be used
$params.= '&cid=DEMO_CONNECTOR;

$response = file_get_contents($baseurl.$params);
```

Thanks

**Comment by farirat** [comment]
You can inject message directly to rabbitmq and bypass http api.

**Comment by zspine** [comment]
@farirat Hi
Thank you very much for response and solution. Is there any documentation or any helpful resources to implement this with php (or any other language just for reference)?

**Comment by mrluciusfox** [comment]
Hi @zspine ,
[Here](https://gist.github.com/farirat/efc604070f34ef699c8b) you'll find an example written in python to inject a deliver_sm directly to rabbitmq.
It was shared by @farirat some time ago.

**Comment by zspine** [comment]
Hi @mrluciusfox 
Thank you very much! very helpful!

**Comment by zspine** [comment]
@farirat @mrluciusfox we are still not sure how to do the same thing with php, we tried several methods non of them seems to be working properly. I mean inject a deliver_sm directly to rabbitmq. any php examples?

Thank you, any help greatly appreciated!

**Comment by farirat** [comment]
How are you injecting the deliver_sm object from php ?

**Comment by zspine** [comment]
Hi @farirat ,

Sorry for the delayed response. Problem is we couldn't find any document or example which explains the content parameters to be used with the rabbitmq and the queue to be used. So we tried our best to understand the queue by consuming the queue through a php consumer but it's not revealing much information. 

Also I have traced through the python example to understand the content to be used with rabbitmq but it's not that simple to understand without some extensive python knowledge.

Is there any documentation which explains this process?

Thank you

P.S. We are also interested in commercial support, but couldn't find any pricing information on the website.

```
<?php

require_once __DIR__ . '/vendor/autoload.php';
use PhpAmqpLib\Connection\AMQPStreamConnection;
use PhpAmqpLib\Message\AMQPMessage;

$connection = new AMQPStreamConnection('localhost', 5672, 'guest', 'guest');
$channel = $connection->channel();
$channel->queue_declare('submit.sm.PROVIDER_2', false, false, false, false);

echo ' [*] Waiting for messages. To exit press CTRL+C', "\n";

$callback = function(AMQPMessage $msg) {
    echo " [x] Received ", "\n";
    file_put_contents(__DIR__ . '/dump/message.txt', $msg->body);
};

$channel->basic_consume('submit.sm.PROVIDER_2', '', false, true, false, false, $callback);

while(count($channel->callbacks)) {
    $channel->wait();
}
```

![rabbit-queue](https://cloud.githubusercontent.com/assets/1169685/15952935/e9fdaab0-2ee2-11e6-80f3-92430f8475ec.png)

**Comment by farirat** [comment]
The objects must be python class instances, you said, it requires some python knowledge, i don't know if there's any reliable way to instanciate same objects in php and keep interoperability between php and python, since the latter is simple to lear ;)
For commercial support, please push an email to support@jasminsms.com

**Comment by zspine** [comment]
Thank you very much for clarifying this. Definitely things would become more complex and less reliable if we try instantiate a python object from php. It's better to learn python than trying to solve it with php. :)

Thanks a lot for the commercial support email!
