### ISSUE TITLE
Hardcode in /store/ path 

### ISSUE THREAD

**Issue by neowisard** [jookies/jasmin#394]
"Hardlink" in code , if i correcting path for save\load profiles to /etc/jasmin, (jasmin.cfg)
i got error
>>Cannot load [jcli-prod] profile configuration from //etc/jasmin/store/jcli-prod.httpccs
>>Cannot load [jcli-prod] profile configuration from //etc/jasmin/store/jcli-prod.filters

to reproduce:
change path to /etc/jasmin/store to /etc/jasmin
restart
connect to cli and load\save profiles  (load\persist)

**Comment by farirat** [comment]
I dont really get you :)

**Comment by neowisard** [comment]
This error in a docker with core 3.14,
Solution : update docker ).
