### ISSUE TITLE
Black hole smpp server

### ISSUE THREAD

**Issue by mrluciusfox** [jookies/jasmin#396]
Hi,
Is there some way in Jasmin to simulate a SMSC with some configuration that send all MT to a black hole for testing? Like the fakesmsc module from Kannel.

**Comment by farirat** [comment]
I usually put SMPPSim from logica as fake smsc on front of Jasmin.

Attached to this message already.

[SMPPSim.tgz](https://files.zenhub.io/56bf7c70f7471cd9688f3b7d)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by mrluciusfox** [comment]
Thanks a lot!
