### ISSUE TITLE
PDUParseError: Unknown Error: Field must be null

### ISSUE THREAD

**Issue by graemeglass** [jookies/jasmin#397]
I am not sure if our providers SMSC is sending through the incorrect command id, or there is an issue here. 

If I change the TimeEncoder for validity_period to requireNull=False, all works fine. 
This bind works fine with kannel.

**Comment by farirat** [comment]
Hi Graeme,

Please check the attached specs (page 80/table 4-18), where it says very clearly deliver_sm must not use validity_period and it must be set to null, Jasmin sticks to that specs, only if you help me decode the specs and find a standard way to do it.

Maybe your client ESME is using a specific smpp version ?

[SMPP_v3_4_Issue1_2.pdf](https://files.zenhub.io/56d3630dbbad9f607dd41c10)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by graemeglass** [comment]
Thanks for this. 
I am going to chat to our provider to find out what version of smpp they are using and why they are sending us a validity_period on deliver_sm.

**Comment by farirat** [comment]
Issue reported again.

The PR will be studied again.
