### ISSUE TITLE
telnet session for jcliadmin crashes

### ISSUE THREAD

**Issue by astutesoftware** [jookies/jasmin#404]
Once the perspective broker api python script runs it does something to the user configuration
subsequently the telnet session when issued "user -l" or "user --list" terminates the telnet session.
this is happening only after the python script sample that creates the user ran.
and this is only happening with the user. other commands related to routes run well and the telnet session is maintained.

jcli : user --list
Connection closed by foreign host.

**Comment by astutesoftware** [comment]
Here is what the jcli.log shows when the telnet session terminates

2016-03-13 14:38:15 INFO     16481 [sref:5] New session started for 27.106.103.119:62089
2016-03-13 14:38:15 INFO     16481 filter configuration loaded (default profile)
2016-03-13 14:38:15 INFO     16481 httpcc configuration loaded (default profile)
2016-03-13 14:38:25 INFO     16481 [sref:5] Session stopped (cannot concatenate 'str' and 'int' objects).

**Comment by farirat** [comment]
Please tell what you did in the pb script before that error showed.

**Comment by astutesoftware** [comment]
i just ran it from the command line.

**Comment by astutesoftware** [comment]
ok. let me try replicating this issue. how can i reset all jasmin configuration to default and start all over ?

**Comment by farirat** [comment]
remove everything from /etc/jasmin/store/

**Comment by astutesoftware** [comment]
umm.. that fixed the problem.
do you want me to run the python script again and see if it breaks it again?

**Comment by farirat** [comment]
yes, and especially describe what your script is doing, and how ?

**Comment by astutesoftware** [comment]
The script that corrupted the user object is the example given in the doc for perspective broker.

http://jasmin.readthedocs.org/en/latest/faq/developers.html#how-to-directly-access-the-perspective-broker-api
# Gist from https://gist.github.com/zoufou/922e1cb2c4782660c257
"""
An example of scenario with the following actions:
 1. Add and start a SMPP Client connector
 2. Provision a DefaultRoute to that connector
 3. Provision a User

**Comment by farirat** [comment]
Please update the following in (https://gist.github.com/farirat/922e1cb2c4782660c257):

- Ligne 18, remove SmppClientConnector
- Line 21, add: from jasmin.protocols.cli.smppccm import JCliSMPPClientConfig as SmppClientConnector

Please test and feedback
