### ISSUE TITLE
RandomRoundrobin routing selects even an inactive SMPP connection

### ISSUE THREAD

**Issue by shani01** [jookies/jasmin#409]
Observed that RandomRoundrobinMTRoute selects an SMPP client connection that is not connected. I think it should check the connections that are available and select one of those. Tested in jasmin-0.9.2.

**Comment by farirat** [comment]
The RR mt route behaves just like static mt route when it comes to routing when connector is offline.

**Comment by shani01** [comment]
Thanks for the info. I think it will be good to have this feature for load balancing+redundancy towards SMSCs.

**Comment by farirat** [comment]
In this case, what will be the decision if all of the sub routes are offline ?

**Comment by shani01** [comment]
Two options; either reject with an error or store & retry after the configured interval in jasmin.cfg (error code to be defined as well). I am not sure about how to achieve the 2nd option since it looks like we store the message with the DC that has been decided in the routing.

**Comment by farirat** [comment]
This feature is addressed in #467.
