### ISSUE TITLE
Billing in case of long msgs from smpp

### ISSUE THREAD

**Issue by KumarDedhia** [jookies/jasmin#410]
Hey,
when I send long msg from my smpp client, Jasmin is charging for one msg instead for multiple msgs.
http works fine.
I went through the code but didnt find any logic for determining long msgs.
Is it smpp client that shld split and send, or is yet to implement?
I'm using v0.9b2
Thanks

**Comment by farirat** [comment]
Do you mean long message content within one unique pdu ? if yes, then that's logic, jasmin is charging on pdu count basis, if you send 2 pdus you get charged for 2 pdus, even if they are multipart (linked to each other), but if you send more than 160 chars in one pdu, jasmin will let you go with charging once only.
