### ISSUE TITLE
UTF-16 Encoding for special characters such as € and also Return line

### ISSUE THREAD

**Issue by joaquin386** [jookies/jasmin#415]
Hi Guys

Can not figure it out how to send and SMS with the HTTP API with special characters as the table of UNIcode show. Can not send € cause it outputs ???

Any idea how to encode \n or €?

BR

Joaquin

**Comment by farirat** [comment]
Hi @joaquin386, did you close the issue after finding the solution ? if yes please share for everyone

**Comment by joaquin386** [comment]
Hi farirat

I didn't find this forum suitable as I think it is more of a bug related forum (developers).
My question is at admin level but most likely will be a bug cause I get <<COntent not supported>> on my mobile terminal.

**Comment by farirat** [comment]
Continued in https://groups.google.com/forum/#!topic/jasmin-sms-gateway/9Ax6Okg5KUE

**Comment by davidcsi** [comment]
That group is closed, no solution can be found for this issue.
