### ISSUE TITLE
pause in receiving msgs

### ISSUE THREAD

**Issue by KumarDedhia** [jookies/jasmin#417]
I have about 1 million users and and their corresponding routes and connectors.
Persistence timer is set to 60s.
While system is on load, it stops receiving msgs for a moment until data is persisted.
This creates a huge loss and further reducing my input throughput.
Persistence Timer can be changed, but some how I cannot avoid persistence.
Regards 
Kumar

**Comment by KumarDedhia** [comment]
?

**Comment by farirat** [comment]
This happens because of the mono-process design, this will change under v0.9 and there will be dedicated processes for such tasks.
