### ISSUE TITLE
src_addr not being used

### ISSUE THREAD

**Issue by gibsonc** [jookies/jasmin#419]
While testing Jasmin 0.8.10, I followed the installation guide. I constantly got ERROR/ESME_RINVSRCADR even though I had src_addr set up in the config. I can however successfully send when I append &from=xxxx in the URL. Either the documentation needs to be updated (point 5), or there is a bug where the default is not being used when the from parameter is not passed since according to the HTTP API from is optional.

**Comment by farirat** [comment]
Can you please express what's the config you're setting ? and where ?

**Comment by gibsonc** [comment]
Once I got into jcli, I created a connector as per the install document. I then needed to set the source address as our SMPP gateways require it. I set the parameter src_addr (which is blank by default) via jcli to that that which was given to me.

**Comment by farirat** [comment]
Issue to be investigated, will concern v0.9 as v0.8 is closed.

**Comment by farirat** [comment]
Issue reproduced and fixed, will be released in 0.9b3
