### ISSUE TITLE
Process for ERROR/ESME_RTHROTTLED

### ISSUE THREAD

**Issue by neowisard** [jookies/jasmin#425]
Now we are have in jasmin.cfg  for ERROR/ESME_RTHROTTLED - 60 sec and have a process 
Our operator checked us , and for smsc

Submit_sm «1»
Submit_sm resp Ok
Submit_sm «2»
Submit_sm resp Ok
Submit_sm «3»
Submit_sm resp Throttling error <<Timeout 60 sec>>
Submit_sm «4»
Submit_sm resp Ok
Submit_sm «5»
Submit_sm resp Throttling error  <<Timeout 60 sec>>
Submit_sm «3»
Submit_sm resp Ok
Submit_sm «5»
Submit_sm resp Ok
**we got 1,2,4,3,5**

I think , what correct process is:

Submit_sm «1»
Submit_sm resp Ok
Submit_sm «2»
Submit_sm resp Ok
Submit_sm «3»
Submit_sm resp Throttling error
**<<Timeout 60 sec>>**  -- for the whole queue for smsc needs to be a delay
Submit_sm «3»
Submit_sm resp Ok
Submit_sm «4»
Submit_sm resp Ok
Submit_sm «5»
Submit_sm resp Throttling error  -- -- for the whole queue for smsc needs to be a delay
<<Timeout 60 sec>>
Submit_sm «5»
Submit_sm resp Ok
**we got 1,2,3,4,5**

**How can you support such a process ?**

**Comment by neowisard** [comment]
Maybe you can use for setting the delayed messages into the queue with its delay as here ?
http://yuserinterface.com/dev/2013/01/08/how-to-schedule-delay-messages-with-rabbitmq-using-a-dead-letter-exchange/

**Comment by farirat** [comment]
Hi @neowisard 

Delayed messages (for throttling error) must not delay the queue delivery, and since multipart messages are linked to each other by reference, the order of delivery is not important since the terminal will link them together based on those references.

**Comment by neowisard** [comment]
My operator says (and requires) that throtling error should suspend sending the entire queue on a timeout.My colleague modified the code 
https://github.com/dmtmalin/jasmin/commit/97d28868e44b74d1b47b15ddba451568fd45d26b 
it works via reactor, implemented via rabbitMQ(DLX) - failed .

And when the handler gets an error:
yield self.rejectAndRequeueMessage(amqpMessage, delay=retrial['delay'])

clients(no smsc) get timeout(>20s) on submitting too:
13:39:35: INFO : 24: (SmppClientDemo) Transfer Timeout. TotalSent 2, TotalReceived 2, Duration: 00:00:20.0035646
