### ISSUE TITLE
Jasmin installation on CentOs 7

### ISSUE THREAD

**Issue by john-joh** [jookies/jasmin#426]
Hi! I would like to know how to installation? I read the jasmin installation documention but I can not. on CentOs7 
[jasmin.txt](https://github.com/jookies/jasmin/files/264443/jasmin.txt)

how can i?
thanks!

**Comment by tarikogut** [comment]
sudo systemctl enable jasmind to systemctl enable jasmind change command

2016-05-14 12:14 GMT+03:00 john-joh <notifications@github.com>:

**Comment by john-joh** [comment]
before the sytemctl enable jasmind, Error so the jasmin installation not complete.

**Comment by farirat** [comment]
Fixed issue since 0.9.27
