### ISSUE TITLE
Installing Jasmin on Mac OS x

### ISSUE THREAD

**Issue by mzeeshanid** [jookies/jasmin#431]
It would be great if you add some tutorial or guidance for beginners in docs for installing it on Mac OS x. I just installed it using python package manager using the command `sudo pip install jasmin`. Now i am wondering how can i start the jasmin service and setup the directories with user permissions etc and use its HTTP api in my Django application.

**Comment by farirat** [comment]
I use docker on Mac, but also pip can do the trick.

**Comment by mzeeshanid** [comment]
Thank you. I am trying it. Mean while can you provide some links of easy and good tutorials for getting started?

**Comment by farirat** [comment]
Please check the jcli.log, amqp-client.log and redis.log to ensure that jasmin has connected to these.

Did you map the ports as documented ?
