### ISSUE TITLE
Syntax Error: while running "python setup.py install" on ubuntu 14.04LTS

### ISSUE THREAD

**Issue by prem-narain** [jookies/jasmin#432]
File "setup.py", line 29
    for sysdte a Lua script.ir in sysdirs:
               ^
SyntaxError: invalid syntax

**Comment by farirat** [comment]
What the hell is that ? :)
Please describe the env, with an extra screenshot as well

**Comment by prem-narain** [comment]
while i am trying to install  required modules using setup.py  for running jasmin properly on my system  than it is throwing error like as in setup.py file :

File "setup.py", line 29
for sysdte a Lua script.ir in sysdirs:
^
SyntaxError: invalid syntax

Can you tell me how i can solve it ...

**Comment by farirat** [comment]
I dont see where tht Lua thing come from really ..

**Comment by prem-narain** [comment]
In setup.py file see line number 29 which is written as

for sysdte a Lua script.ir in sysdirs:
        if not os.path.exists(sysdir):
            print 'WARNING: %s does not exist !' % sysdir

**Comment by farirat** [comment]
Here's what i have in my setup.py at that location: https://www.dropbox.com/s/qs8lirwfitgz4ls/Screenshot%202016-06-10%2018.34.02.png?dl=0

**Comment by prem-narain** [comment]
Thanks a lot Farirat ... its working fine now

**Comment by farirat** [comment]
And what was that **Lua** thing ? :)
