### ISSUE TITLE
sms not delivered

### ISSUE THREAD

**Issue by lidennis88** [jookies/jasmin#434]
Dear All,

I followed the installation guide to run jasmin with docker on Macbook, add then start a connector. Then run a test via the HTTP interface to send a test SMS and got a success response but the message was not delivered to the phone. I tried to check the log but couldn't find **/var/log/jasmin**. I even set the logfile with jcli still it's still not generated. Can anybody tell me how to debug it and where to find the log file?

$ curl "http://192.168.99.100:1401/send?username=foo&password=bar&to=<SKIPPED>&content=hello"
Success "a60baf06-26d0-4d23-8b07-9be040c7c1af"

Thanks.

Dennis

**Comment by lidennis88** [comment]
I actually log into the wrong container. After logging into the right container, I found the jasmin logs. The logs indicated that binding to the SMSC was successful but I found the following error in the messages.log that indicates "invalid dest address". I don't understand why I got this error. When I sent the message to the SMSC directly, it's delivered without problem.

2016-06-19 02:27:52 INFO     1 SMS-MT [cid:SPRINT_CONNECTOR] [queue-msgid:a60baf06-26d0-4d23-8b07-9be040c7c1af] [status:ERROR/ESME_RINVSRCADR] [retry:False] [prio:0] [dlr:NO_SMSC_DELIVERY_RECEIPT_REQUESTED] [validity:none] [from:None] [to:<SKIPPED>] [content:'hello']

**Comment by farirat** [comment]
That's an error returned from your provider, check the destination address format, and you ton/npi setting, these are usually the reason of your problem.

**Comment by tarikogut** [comment]
did you add source and destination  ???

**Comment by zouhirmahjoubi** [comment]
hello , any help plz 
jasmin sms delivered but not received.
