### ISSUE TITLE
telnet :Unable to connect to remote host: Connection refused

### ISSUE THREAD

**Issue by prem-narain** [jookies/jasmin#435]
while i am running :
`telnet 127.0.0.1 8990` 
`Trying 127.0.0.1`
**telnet: Unable to connect to remote host: Connection refused**

while port is free ,i checked it by 
**sudo netstat -tulpn | grep :2775**

what may be error ....?

**Comment by prem-narain** [comment]
Solved..

**Comment by Simon55** [comment]
@prem-narain how you solved have the same problem.
