### ISSUE TITLE
Partial encoding sent SMS

### ISSUE THREAD

**Issue by flyfantom** [jookies/jasmin#437]
Hello developers.

I have a problem with delivery messages more than 70 characters in Cyrillic and more than 160 characters in GSM Latin Alphabet. Messages sent and delivered, but correct encoding message content only in first part of message. In second and other parts encoding incorrect. I send messages through http-api with the parameter "coding = 8" (for coding to UCS2). Content message - is encompressed text in utf16, for example: "\xff\xfe"\x045\x04A\x04B\x04>\x042\x040\x04O\x04 \x00D\x04@\x040\x047\x040\x04". If i try send message up to 70 characters Cyrillic (ot 260 characters in Latin Alphabet) - all parts of message delivered in correct encoding.
Further messages going over configured smpp-connector to other operator. His support confirms this problem (1 part of message correct encoding, other parts - incorrect encoding). Please tell me, how that may be? Thank you.

**Comment by farirat** [comment]
In order to confirm the issue, pleaseprovide the following:

1. A dump of what you are sending to http api,
2. A dump of what Jasmin is sending out through smpp

**Comment by flyfantom** [comment]
In attach with message, dumps that you asked:
1. sms_coding.pcap.gz - dump of what i sending to http-api
2. sms_coding_out.pcap.gz - dump of what Jasmin is sending to our partners through smpp

[sms_coding.pcap.gz](https://github.com/jookies/jasmin/files/347655/sms_coding.pcap.gz)
[sms_coding_out.pcap.gz](https://github.com/jookies/jasmin/files/347656/sms_coding_out.pcap.gz)

**Comment by farirat** [comment]
Ok i see in outcome (_out) 3 parts using the same coding (8), 140 bytes for 1st and 2nd, and 68 bytes for the last one, where's the issue ?

**Comment by flyfantom** [comment]
Our partners claim but outgoing from our jasmin-smsc messages (which size more than 1 part), come to them with incorrect coding (with the exception of first part of message). I need help for confirmation correct coding for all parts outgoing messages. I also request dump for analyze from the our partners side. If all parts of test message (i.e. 3 of 3 parts in my example message) outgoing from our jasmine-smsc in correct coding (i.e. coding = 8) - problem on our partners side.

**Comment by farirat** [comment]
In this case, try to fill a long 3 part message content with the same character, then in the outgoing traces check if the character coding has changed from one part to another.

**Comment by flyfantom** [comment]
Hello.
Thank you for you advice. I try change message content. Our partners answered yesterday. Their engineer sent message from their SMSC to our Jasmin, message content the same text in the same coding. This message coming from their SMSC, and next our Jasmin sent this message to smpp-connector to our partners back, and nex - send it to my mobile phone. In this case message was delivered in correct coding (all parts of message). Log file in attach.
[TEST UCS2.txt](https://github.com/jookies/jasmin/files/358759/TEST.UCS2.txt)

**Comment by flyfantom** [comment]
I have update on our problem. I install other jasmin-smsc on other server, and make a connect over smpp from one to other. If i send the same message, i have a same problem. But in log`s on jasmin-server i see, that i send ONE message (one message = 2 parts), and in log`s on old jasmin-server i see TWO messages with different msgid. Perhaps is it problem?

**Comment by flyfantom** [comment]
Hello.
I still trying solve the problem. Can you tell me, why in case sending one message, in log file i see two messages with different msgid?
Thank you.
