### ISSUE TITLE
Debian/Ubuntu repository is insufficiently signed by key (weak digest)

### ISSUE THREAD

**Issue by prem-narain** [jookies/jasmin#438]
```
jasmind is working fine but while i am running **sudo apt-get update** showing as below in ubuntu 16.04

sudo apt-get update
Hit:1 http://ppa.launchpad.net/mystic-mirage/pycharm/ubuntu xenial InRelease
Hit:2 http://in.archive.ubuntu.com/ubuntu xenial InRelease
Hit:3 http://ppa.launchpad.net/webupd8team/atom/ubuntu xenial InRelease                        
Hit:4 http://in.archive.ubuntu.com/ubuntu xenial-updates InRelease                             
Hit:5 http://in.archive.ubuntu.com/ubuntu xenial-backports InRelease     
Get:6 http://security.ubuntu.com/ubuntu xenial-security InRelease [94.5 kB]
Hit:7 https://packagecloud.io/jookies/python-jasmin/ubuntu xenial InRelease
Fetched 94.5 kB in 4s (21.4 kB/s)
Reading package lists... Done
W: https://packagecloud.io/jookies/python-jasmin/ubuntu/dists/xenial/InRelease: Signature by key F86AA916A2195E121AEDB11437BBEE3F7AD95B3F uses weak digest algorithm (SHA1)
```

**Comment by pyghassen** [comment]
This issue related to gpg keys, you have to add it so you can update the jasmin repo, but I am not sure if it's supported on ubuntu 16.04

**Comment by farirat** [comment]
There's only Jasmin 0.8.12 packaged for Ubuntu 16.04, then newer releases (0.9.x) are packaged wily and vivid (15.04 and 15.10), you may ask why there's regression ? here's the reasons:

- Packaging each release for a Linux distro requires a lot of testing to make packages work without hassle, so decided to stay on 15.04 and 15.10 till the end of this year, then switch to LTS and drop previous Ubuntu versions,
- Any contrib is welcome, the packaging is made through this [project](https://github.com/jookies/jasmin-packager), so if you want, you can add packaging for more distros and maintain the packages,
- It's simple and easy to use jasmin through any other sort of installation type (pip, docker, ...)

**Comment by prem-narain** [comment]
I am trying to solve it using 
```
sudo apt-key adv --recv-keys --keyserver packagecloud.io F86AA916A2195E121AEDB11437BBEE3F7AD95B3F 
Executing: /tmp/tmp.xlE68HrnxK/gpg.1.sh --recv-keys
--keyserver
packagecloud.io
F86AA916A2195E121AEDB11437BBEE3F7AD95B3F
gpg: requesting key 7AD95B3F from hkp server packagecloud.io
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error

```

Can anyone tell me ,how i can solve this ...

**Comment by prem-narain** [comment]
Finally  I got the solution and its working fine for me ... I followed steps to over come on it which are as following 

**Step-1**   sudo apt-key list
**Step-2**   sudo apt-key remove key_of_packagecloud.io
**Step-3**   ls /etc/apt/sources.list.d
**Step-4**   sudo rm -i /etc/apt/sources.list.d/jookies_python-jasmin.list 

after that restart  jasmind service again and wow its working fine for me.
thanks @pyghassen and @farirat  for your great suggestions.:)

**Comment by farirat** [comment]
You are using an old release though: 0.8.12

**Comment by prem-narain** [comment]
Yes i am ... How can i update it to V0.9 
@farirat

**Comment by prem-narain** [comment]
I upgraded  as you tell in one issue **pip install --pre --upgrade jasmin**  to the latest version but know ... in my /etc/jasmin jasmin.cfg file is missing

**Comment by nzuwera** [comment]
@prem-narain,  Thanks for sharing i followed you steps and it worked for me
