### ISSUE TITLE
MT custom logic question

### ISSUE THREAD

**Issue by bilby91** [jookies/jasmin#439]
Hello guys,

I'm planning to use jasmin for the communication with another `SMPP` server that handles different message types through the `service_type` field.

For example, if I want to send a charged sms I need to prepend the letter `C` to the service identifier in order to perform the operation. I think jasmin can handle all this custom logic through the router or interceptors.

So, my question is. Should I use a custom router or an interceptor for this. What benefits do I have if I choose one or another ?

How can I test my script ?

Any help is more than welcome, I'm really new to SMPP.

**Comment by farirat** [comment]
If you need to update pdus on the fly then use the interceptor.

**Comment by bilby91** [comment]
@farirat Thanks. Another question, would it be easy to use the `jasmin` factories to unit test make scripts ? I think I would need to create a just a routable for the test right ?

**Comment by farirat** [comment]
Yes you can, take "jasmin.interceptor.test.test_interceptor" as an example, you can run the test using:

    trial jasmin.interceptor.test.test_interceptor

Check a complete build log here: https://travis-ci.org/jookies/jasmin/builds/125312131

**Comment by bilby91** [comment]
@farirat Great!! Will take a look.

Another question, how would you approach this scenario ? How can I link my scripts to the Jasmin code ? 

I just did a little python for a small project some months ago.

I can only use:

```
from jasmin.routing.Routables import SimpleRoutablePDU, RoutableSubmitSm, RoutableDeliverSm, Routable
from jasmin.vendor.smpp.pdu.operations import SubmitSM, DeliverSM
```
in my scripts ?

**Comment by farirat** [comment]
Yes, must be fine .. you just need to have the right classes from jasmin codebase, just like you did.

**Comment by bilby91** [comment]
@farirat I've been working with the example test_interceptor.py and have pretty good results. I have defined a module that handles the "interception". So, my interception script look like this.

```python
from middleman.middleware import Middleware

middleware = Middleware(routable)
```

And my Middleware Class is really dummy now.

```python
class Middleware:
    def __init__(self, routable):
        self.routable = routable
```

I'm trying to test that when the `run_script` function is called with my interception script, the Middleware __init__ method is called with the correct parameters.

```python
    # Build de InterceptorScript with the content of the runner.py file with 
    open(RUNNER_FILE_PATH, 'r') as runner_file:
        self.runner_script = InterceptorScript(runner_file.read())
    ...
    ...
    ...
    @defer.inlineCallbacks
    @patch('middleman.middleware.Middleware', '__init__')
    def test_middleman_is_called(self):
        yield self.connect('127.0.0.1', self.ipbPort)
        yield self.run_script(self.runner_script, self.routable_simple)
        
        # This doesn't work obviously because Middleware is not an instance of Mock.
        # Middleware.__init__.assert_called_once_with(self.routable_simple)

        # The ruby (rspec) version would look something like this :)
        # expect(Middleware).to receive(__init__).with(routable_simple)
```

**Comment by farirat** [comment]
From a night-read of your message, after a hard work day, i can be wrong at understanding, but i think your Middleware's __init__ is not called because it's from a separate module, is **middleman** in your **pythonpath** ?

The **self.run_script()** will simply **eval()** your script, and i dont see why it doesnt instantiate your middleware when you type

    middleware = Middleware(routable)

**Comment by bilby91** [comment]
@farirat from a night-read, hard work day you got it right I think lol. 

The issue was with how I was importing the Middleware class in my script.

I was doing

```python
from middleman.middleware import Middleware
```
instead of 

```python
from middleman.middleware.Middleware import Middleware
```
So my initializer was never called.

Now my test looks like this and works :)

```python
class RunnerScriptTestsCases(IntercentorPBProxyTestCase):
    @defer.inlineCallbacks
    def setUp(self):
        yield InterceptorPBTestCase.setUp(self)

    @defer.inlineCallbacks
    def test_middleman_is_called(self):
        yield self.connect('127.0.0.1', self.ipbPort)

        with patch.object(Middleware, '__init__') as mock:
            # We need to set a return value to the initializer always
            mock.return_value = None

            # Run the script
            yield self.run_script(self.runner_script, self.routable_simple)

        self.assertEqual(mock.called, True)
        self.assertIsInstance(mock.call_args[0][0], SimpleRoutablePDU)
```

I definitely need a good read on how python modules/classes import works.
