### ISSUE TITLE
How much sms/second jasmin can send and receive report ?

### ISSUE THREAD

**Issue by prem-narain** [jookies/jasmin#441]
Hello Everyone ,
                       Actually this is not an issue i want to discuss about jasmin throughput per second ,i am working on this since last few days and i want minimum throughput 3000 sms/second. So i want to ask you all ,is it capable of sending this much sms/second because i did test it on 100000 sms load and its throughput did vary between 20 to 25 sms/second.So anyone can suggest ... what i have to do to get this much throughput from jasmin.

Thanks

**Comment by prem-narain** [comment]
@farirat 
I am able to send 50 MPS from producer end but consumer is very slow its consuming speed is 15-20 MPS  using SMPP...Could you tell me how i can increase it...

**Comment by farirat** [comment]
Consumer is cpu bound, it scales only one cpu core, you need to think about parallelizing through multiple consumers.

**Comment by prem-narain** [comment]
I tried to solve it by using setting configuration of rabbitmq using **Prefetch_coun**t and **Prefetch_size** and it is also giving error in dlr-thrower like as 
**2016-07-15 11:31:11 ERROR    8314 Throwing SMPP/DLR [msgid:3750fcc6-1d51-4f55-92c6-7fa2753206b5] to (foo): SystemIdNotBound('foo',).
**

**Comment by prem-narain** [comment]
Still this problem is existing 

any suggestions pls  ...........

**Comment by prem-narain** [comment]
https://groups.google.com/forum/#!topic/jasmin-sms-gateway/OscMYeBZ0fg

Thanks

**Comment by connectarena** [comment]
unable to read above link. can you comment the how to achieve load. i am able to 20MPS only.

**Comment by manojr2k** [comment]
> https://groups.google.com/forum/#!topic/jasmin-sms-gateway/OscMYeBZ0fg
> 
> Thanks

https://groups.google.com/forum/#!topic/jasmin-sms-gateway/OscMYeBZ0fg  is not showing anything , can you please explain what exactly you have done ?

**Comment by rodolfoaRAVEN** [comment]
Hi. How can I access the Google group? It does not allow me to enter and it appears as restricted content ...

**Comment by ascii-mango** [comment]
Hi, i am also looking for a solution or reply struggling with jasmin throughput its very low.
@farirat any help please.

**Comment by rodolfoaRAVEN** [comment]
I imagine that the solution should be on the side of adjusting the Rabbitmq parameters to give more capacity to the queues, buffers queues or to have simultaneous processes, but I cannot find how to do it. I tried working with Rabbit, but the default credentials don't work for me. I guess all Jasmin users who have large volumes have had this problem .......    HELP !

**Comment by ascii-mango** [comment]
Are you using interceptors, I don’t think rabbit mq is a bottleneck here. Using an interceptor having a static route just drastically reduces the throughput.

**Comment by rodolfoaRAVEN** [comment]
Yes, I have an interceptor that acts as an HLR lookup, to determine the destination operator and route in message ...... if so, I will see how to get the Interceptor out and do that process before Jasmin .... .. are you sure about that? Have you read it in another Issue?
Too bad that friends with more experience in Jasmin do not give any help with this .....  (:-(

**Comment by ascii-mango** [comment]
@rodolfoaRAVEN see this https://github.com/jookies/jasmin/issues/875
