### ISSUE TITLE
Message id timing generation question

### ISSUE THREAD

**Issue by bilby91** [jookies/jasmin#442]
Hello,

I'm implementing an interceptor where I add some custom logic to modify the PDU in order to be compliant with my provider. Depending of the "type" of message I'm sending I need to add some stuff to the service type field. My problem is that I can not send any custom metadata when I use the http api so, in the interceptor, I have no way to identify the "type" of message I'm dealing with. What I think I can do is to query my API to get more information on the message. 

So, my question are:

- Is the uuid returned in the `send` api call available in the interceptor ? This is the only way I think I can get more information on the message.
- You think this is a good idea ?
- There is a better approach to deal with this kind of situations ?

Thanks!! Your project is really awesome!

**Comment by farirat** [comment]
What do you mean by "type" of message ?

**Comment by bilby91** [comment]
@farirat Thanks for answering!

My provider adds some business rules on top of the service type field. Basically, depending on the "type" of message I need to fill the service type field.

Some examples of messages types are:

- Content (Represents an sms content for the user)
- Authorization (Represents an authorization message to "authenticate" the user)
- Subscription (Represents the user confirmation to a subscription)

 Thanks again for the help!

**Comment by bilby91** [comment]
@farirat Do you think that it is a good idea to use the `content` parameter to transport the message metadata plus the real content and transform the pdu in the interceptor with the correct content ?

Thanks for the help @farirat!
