### ISSUE TITLE
Split interceptor in multiple files

### ISSUE THREAD

**Issue by bilby91** [jookies/jasmin#443]
Hello guys!

Is it possible to split an interceptor in multiple files and import them ? They should be stored in a particular location ? I did some investigation and I saw that the interceptor code is serialized into a file with the configurations and when execution is needed an eval happens.

Thanks!

**Comment by farirat** [comment]
Interceptor script can call python modules visible on system's PYTHONPATH (in case Jasmin is installed through deb or rpm), otherwise, it maybe virtualenv's PYTHONPATH ... depends on your config in this situation.

**Comment by bilby91** [comment]
@farirat, thanks for the tip. Worked.
