### ISSUE TITLE
More performance

### ISSUE THREAD

**Issue by KumarDedhia** [jookies/jasmin#444]
Would not like to call this as an Issue, 
Has anyone tried running this project with pypy or adding JIT compilation or even cythonizing it, what difficulties were faced, any major performance achieved, share our experience if anyone tried, that would make the project more interesting.

**Comment by prem-narain** [comment]
Yes i tried to run it using pypi but it did not affect on its performance,time complexcity is same as before.

**Comment by farirat** [comment]
did you make a new performance measure after getting the 0.9b15 release ?

**Comment by prem-narain** [comment]
No, Actually my company target is to achieve 10k sms/seconds so we decided to make new SMSC using python and C++.
