### ISSUE TITLE
service_type is not modified when changed in an interceptor

### ISSUE THREAD

**Issue by andres99x** [jookies/jasmin#445]
I’m trying to modify the service_type in `mtinterceptor`.

My script looks like this:

```
routable.pdu.params['service_type']  = 'CRECE'
routable.pdu.params['short_message'] = 'Chau'

# Set logger
logger = logging.getLogger('logging-example')

if len(logger.handlers) != 1:
    hdlr = logging.FileHandler('/var/log/jasmin/runner.log')
    formatter = logging.Formatter('%(asctime)s %(levelname)s %(message)s')
    hdlr.setFormatter(formatter)
    logger.addHandler(hdlr)
    logger.setLevel(logging.DEBUG)

logger.info('Got pdu: %s' % routable.pdu)
```

After the interceptor run, the log shows the correct `service_type` and `short_message` but only the `short_message` is correctly received on the other end (SMSC).

I have done a tcpdump of the tcp package to double check that it is not an issue in the SMSC.

Any special consideration for updating the `service_type` ?

Thanks

**Comment by farirat** [comment]
Wich version are you using ? am unable to reproduce your issue with 0.9b3

**Comment by andres99x** [comment]
Hey @farirat I am using a docker image: https://hub.docker.com/r/jookies/jasmin/
```
jookies/jasmin        latest              9519670fac70        3 months ago        476.6 MB
```

Given the Dockerfile it seams it's using the 0.9b3 version 
```
ENV JASMIN_VERSION 0.9b3
```

**Comment by farirat** [comment]
hi @andres99x, still not able to reproduce the issue (check the last commit related to this issue).

Can you please provide access to system (send email to support@jasminsms.com with issue id) so i can check it on live.

**Comment by farirat** [comment]
Issue confirmed, service_type is forced in https://github.com/farirat/jasmin/blob/0.9b4/jasmin/managers/listeners.py#L33
