### ISSUE TITLE
DLR not being pushed for Failed, EXPIRED etc., cases

### ISSUE THREAD

**Issue by jasminUser** [jookies/jasmin#454]
Hi Guys, 

My team was able to modify a few lines of code in operations.py to capture all the failed DLRs, Expired dlrs with different sub cases etc.,, however, we are unable to push those DLRs to our respective clients. Can you guys please guide on where exactly we need to change code and what needs to be changed too?

Thanks in Advance!
Regards

**Comment by farirat** [comment]
Can you please explain why arent you able to push those DLRs ?

**Comment by jasminUser** [comment]
Hi,

I have no clue about why our expired and failed DLRs are not being pushed, but delivered cases are being pushed. I can give you webex or do a hangout call sharing the screen if you are willing to have a look at it.

Regards

**Comment by farirat** [comment]
There's **success_states = ['ACCEPTD', 'DELIVRD']**, if you set **registered_delivery_receipt=SMSC_DELIVERY_RECEIPT_REQUESTED** then any DLR in **success_states** !only! will be delivered back to ESME; if you set **registered_delivery_receipt=SMSC_DELIVERY_RECEIPT_REQUESTED_FOR_FAILURE** then any DLR will be delivered back to ESME (including **success_states** and **failure_states**).
