### ISSUE TITLE
Tag messages when using http api

### ISSUE THREAD

**Issue by farirat** [jookies/jasmin#455]
Add a new http api optional parameter (**tags**) to provide ability to tag a **routable** object.

This will be helpful to recognize the routable inside interceptor or even to help the router using the TagFilter to match on given tags and force some desired routing rule.

> Sponsored feature

**Comment by bilby91** [comment]
@farirat We realised that we will also need the tag in the `deliverSmHttpThrower`. Can we add this too ?

**Comment by farirat** [comment]
deliverSmHttpThrower takes incoming deliver_sm pdus from upstream and "throw" them to an http endpoint, how are you willing to use tags in there ? the upstream have no way to tag pdus like you do from downstream (http api).

**Comment by bilby91** [comment]
@farirat Didn't realise that. We might need the service_type in the application layer (thrower listener). I thought about using the inverse solution. Tag the routable based on the service_type and receive the request from the thrower with the tags.

**Comment by farirat** [comment]
I dont really get you, can you put more details ? maybe a graphic callflow would be better explaining ?

**Comment by bilby91** [comment]
@farirat Will create a flow diagram to illustrate my idea for next week. Either way, as I said before, this not priority at the moment. Tagging with the http api is.

**Comment by bilby91** [comment]
@farirat Any ETA for this feature ?
