### ISSUE TITLE
HTTP Client?

### ISSUE THREAD

**Issue by codecowboy** [jookies/jasmin#457]
I saw mention of an HTTP client which sounded like it might be a web interface to jasmin functionality (i.e a browser-based GUI). Am I mistaken? If not, what port would that be running on in the docker image?

**Comment by DanielOneM** [comment]
Check [the docs](http://jasmin.readthedocs.io/en/latest/apis/ja-http/index.html) for more details about using the Jasmin HTTP API. The usual port is 1401, but you can configure this.

**Comment by farirat** [comment]
And you may also have a look at those satellite projects around jasmin: https://github.com/jookies
