### ISSUE TITLE
Tuning messaging performance by storing DLR tracking in runtime memory

### ISSUE THREAD

**Issue by farirat** [jookies/jasmin#463]
This will be an option to switch from redis to runtime memory for better performance, the runtime memory must have a way to expire keys to avoid overflows.

This may turn into default behaviour (and redis will turn optional) in future.

**Comment by DanielOneM** [comment]
If I might give a suggestion: maybe abstract away the whole "caching" mechanism. So instead of Redis, it could be based on any other system (whether it's Aerospike, Memcached or memory).

**Comment by farirat** [comment]
Hi !

I dont know about aerospike, but anyway, i'm looking to remove any extra cost when looking for a dlr map (or to remap parts of a long message), redis were used for its performance, now it's the bottleneck for jasmin, there's tcp connection and http marshalling overheads that add some milliseconds to each call.

Am looking for a way to store data while having **direct** access to it, **and** data must expire and automatically removed after some time to avoid getting overwhelmed with unused/trash data.

**Comment by farirat** [comment]
Same as #464, feature dropped.
