### ISSUE TITLE
Exporting and importing configs

### ISSUE THREAD

**Issue by balsagoth** [jookies/jasmin#465]
I'm trying to upgrade jasmin from version 0.9b3 to the latest 0.9b7, but if i start 0.9b7 all the configs are erased. 
Is there any simple way to do this, instead of manually recreating all configs again?

**Comment by farirat** [comment]
can you send your configs ? or create some anonymized configs in 0.9b3 and send the files to me to reproduce the issue ?

**Comment by farirat** [comment]
Issue not reproduced till now.
