### ISSUE TITLE
Jasmin is reported to consume too much memory when pushing continuously in a high throughput

### ISSUE THREAD

**Issue by farirat** [jookies/jasmin#466]

**Comment by farirat** [comment]
Described scenario is:

- 60 MPS (MT with DLR request)
- 2 hours, memory get full

**Comment by farirat** [comment]
Tried to reproduce the issue:

- Using v0.9b7
- Ran a campaign ~2h with 60MPS
- SMS are pushed through http api with dlr-level=3
- dlr-url is timeouting to stress up jasmin
- jasmin is run with memory_profiler

**Result:**
Memory consumption never passed 500mb, closing the issue.

If the issue is reproducing, please profile jasmin's memory with memory_profiler and provide the memory graph.

**Comment by balsagoth** [comment]
As we talked on slack, i'm reopening the issue for further investigation.

Here two graphs, one running on my local machine and the other on production.
Development server is connected do smppsim, and those spikes are when i changed the submit_throughput to 0 on jcli. 
![development_server](https://cloud.githubusercontent.com/assets/183991/18691520/08975fe4-7f8c-11e6-9c14-8c8895c5be64.png)

Production server is a centos virtualmachine with 8GB of RAM. Two connectors with submit_throughput set to 100, on a `RandomRoundrobinMTRoute` configuration.
I process every entry on the `messages.log` to a elk server, so i put on the second image the graphic of last 50h (180000 seconds), to match with the memory profiler graph. 
You can spot that when I sent those 80k sms the memory increase and never decrease. It's not much memory, but the number of sent sms is low.

![production_server](https://cloud.githubusercontent.com/assets/183991/18691567/58d8694e-7f8c-11e6-9bd3-26e1f1333838.png)

![screen shot 2016-09-20 at 23 52 59](https://cloud.githubusercontent.com/assets/183991/18691984/f35b4976-7f8e-11e6-912f-668b1eeda338.png)

**Comment by farirat** [comment]
Hi @balsagoth,

From those graphs i see no over-consuming, Jasmin is using no more than 800Mb of ram, memory is not decreasing and that's pretty normal, memory is taken from system is not returned back to system if the latter does not ask for it, it's reserved.

**Comment by tuilaga85** [comment]
Hi, we are now faced with memory consume, with 400k messages it keep 3G of RAM and status queue change to Flow, so many unacked messages. We followed that when unacked messages are gone, jasmin will continue to send messages. Please check the image in the attachments.
![2019-01-04_19-49-30 jasmin](https://user-images.githubusercontent.com/3398550/50688934-48715a00-105a-11e9-86ca-c93808ad786e.png)
