### ISSUE TITLE
Implement new type of route: FailoverMTRoute and FailoverMORoute

### ISSUE THREAD

**Issue by farirat** [jookies/jasmin#467]
These new routes will transfer message to the first available connector in the order they were introduced to the route, example:

    jcli : mtrouter -a
    Adding a new MT Route: (ok: save, ko: exit)
    > type failovermtroute
    ....
    > connector smppc(c1);smppc(c2);smppc(c3)
    ....

In this example, first connector "c1" will always be the first destination, "c2" is its failover and "c3" is c2's failover.

Failover occurs only when connector is not bound (can be connected ...).

A special note for **FailoverMORoute**: MO routes can point to **smpps** or **http** connectors, the latter is a stateless protocol and have retrial mechanism, a solution must cover this type of protocol where failover will occur after all retrials were done.

> Sponsored feature

**Comment by balsagoth** [comment]
Great news. This would support load balancing when all are available?

**Comment by farirat** [comment]
@balsagoth what do you mean by supporting LB ?

**Comment by balsagoth** [comment]
It's the same functionality requested on #409

**Comment by farirat** [comment]
It's somewhat different from Failover implementation, the Roundrobin algorithm will pick a random connector from the pool without caring about it's status (whether it's up or down), the Failover will pick the first connector from the pool and if it's down will fallback to second, then third etc .. till it find the first connector up or will finish the round and log an error on the route (no connectors are available to handle the message).

The big difference is randomness, Failover is sequential and not random.

**Comment by balsagoth** [comment]
Got it @farirat. Thanks

**Comment by cristianpetresimion** [comment]
Good morning Fourat,

Could you please provide a status for this implementation ?

Thank you

**Comment by cristianpetresimion** [comment]
Kind reminder

**Comment by ominds** [comment]
I was looking at the code for this router

I noticed it just returns the next connector in sequence. From its name, I thought it would skip stopped/disconnected connectors? Could someone explain this to me? What's the purpose of the Failover routers?

**Comment by farirat** [comment]
It's behaving just like you expect ;) dont struggle at the code, go make a trial.
