### ISSUE TITLE
Consider 'message_payload' when 'short_message' is empty or not provided

### ISSUE THREAD

**Issue by oluwatosinoni** [jookies/jasmin#470]
Hello,

I recently started using JASMIN and I have been experiecing an issue with the MOs coming in. The content parameter is blank even though messages sent from the device has content.

Find logs below:

> 2016-09-20 19:27:11 DEBUG    4729 Got one message (msgid:ca27fc56-d122-4cc6-94b9-3efcabbb25f8) to throw: PDU [command: deliver_sm, sequence_number: 2, command_status: ESME_ROK
> service_type: ''
> source_addr_ton: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f2d90b4e1d0>, 6, 'INTERNATIONAL')
> source_addr_npi: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f2d90bc0f50>, 9, 'ISDN')
> source_addr: '234xxxxxxxxxx'
> dest_addr_ton: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f2d90b4e1d0>, 2, 'SUBSCRIBER_NUMBER')
> dest_addr_npi: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f2d90bc0f50>, 2, 'PRIVATE')
> destination_addr: '3000'
> esm_class: EsmClass[mode: DEFAULT, type: DEFAULT, gsmFeatures: set([])]
> protocol_id: 0
> priority_flag: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f2d90b4e890>, 0, 'LEVEL_0')
> schedule_delivery_time: None
> validity_period: None
> registered_delivery: RegisteredDelivery[receipt: NO_SMSC_DELIVERY_RECEIPT_REQUESTED, smeOriginatedAcks: set([]), intermediateNotification: False]
> replace_if_present_flag: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f2d90b4e2d0>, 0, 'DO_NOT_REPLACE')
> data_coding: DataCoding[scheme: DEFAULT, schemeData: SMSC_DEFAULT_ALPHABET]
> sm_default_msg_id: 0
> short_message: ''
> source_network_type: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f2d90b4e750>, 7, 'GSM')
>  **message_payload: 'KANYA BABA'**
> dest_network_type: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f2d90b4e750>, 7, 'GSM')
> ]
> 2016-09-20 19:27:11 DEBUG    4729 Calling http://52.x.x.xx/jasmin/mo.php with args {'priority': 0, 'from': '234xxxxxxxxxx', 'origin-connector': 'Nxxxxxxx', 'coding': 0, 'content': '', 'to': '3000', 'id': 'ca27fc56-d122-4cc6-94b9-3efcabbb25f8'} using GET method.
> 2016-09-20 19:27:11 INFO     4729 Throwed message [msgid:ca27fc56-d122-4cc6-94b9-3efcabbb25f8] to connector [cid:HTTP-KANNEL] using http to http://52.x.x.xx/jasmin/mo.php.
> 2016-09-20 19:27:11 DEBUG    4729 Destination end replied to message [msgid:ca27fc56-d122-4cc6-94b9-3efcabbb25f8]: 'ACK/Jasmin'
> 
> 2016-09-20 19:27:11 INFO     4729 SMS-MO [cid:Nxxxxxx] [queue-msgid:ca27fc56-d122-4cc6-94b9-3efcabbb25f8] [status:ESME_ROK] [prio:LEVEL_0] [validity:None] [from:234xxxxxxxxxx] [to:3000]  **[content:]**

How do I resolve this?

Any help would be greatly appreciated.

Thanks.

**Comment by farirat** [comment]
Will be released in 0.9b11
