### ISSUE TITLE
HTTP client connector management

### ISSUE THREAD

**Issue by mhasaneen** [jookies/jasmin#473]
I have created an http connector to use it with MO router but after a while this connector have been removed and I do not know why??

**Comment by balsagoth** [comment]
Do you persisted the configuration?

**Comment by mhasaneen** [comment]
Thank you for the replay.
No, I did not persist the configuration.
The problem is this is the only configuration what is removed, I have created smppcucm, morouter, httpccm and mtrouter and this is the only this is the missing one.
thanks in advance.

**Comment by farirat** [comment]
Httpc and filters are helpers for the current jcli session, if you need to reuse them in future sessions then persist your config.
