### ISSUE TITLE
I have importe jasmin images in docker,after that i created user,connector.Can anyone tell me how we can use the http url to send the message from our local browser or is their any other way to send the message?

### ISSUE THREAD

**Issue by Rupesh9742** [jookies/jasmin#484]

**Comment by farirat** [comment]
Did you map the port 1401 ?

**Comment by Rupesh9742** [comment]
yes. Do I need to write some code or directly I can access the url from my local browser?

**Comment by farirat** [comment]
You just need to take the example from documentation for sending your first sms through http and just replace host and port from your docker container config.

**Comment by Rupesh9742** [comment]
I am trying to run the url directly but I am getting page can't be displayed.

**Comment by farirat** [comment]
What's the url you're calling ?

**Comment by Rupesh9742** [comment]
http://127.0.0.1:1401/send?username=foo&password=bar&to=06222172&content=hello

**Comment by farirat** [comment]
This is more a docker usage issue, you may misused docker's port mapping.

**Comment by Rupesh9742** [comment]
How I can configure or I can use the url in docker for running in local browser?

**Comment by farirat** [comment]
run **docker ps** and provide outcome here plz

**Comment by Rupesh9742** [comment]
![docker image](https://cloud.githubusercontent.com/assets/22683484/19222517/fde806ac-8e77-11e6-85a4-b48eaadd4df7.JPG)

**Comment by farirat** [comment]
and:

  curl "http://127.0.0.1:1401/send"

?

**Comment by Rupesh9742** [comment]
![curl](https://cloud.githubusercontent.com/assets/22683484/19222572/334b5b2c-8e79-11e6-85e1-040196bb3058.JPG)

**Comment by farirat** [comment]
So you have a responding jasmin instance ...

do it again:

    curl "http://127.0.0.1:1401/send?username=foo&password=bar&to=06222172&content=hello"

**Comment by Rupesh9742** [comment]
when I am running  the url and I am giving my number it's coming success but I am not getting any message on my number.

**Comment by farirat** [comment]
Then you might check your routing config ...

closing this issue, for support you may participate here: https://groups.google.com/forum/#!forum/jasmin-sms-gateway

**Comment by Rupesh9742** [comment]
currently I am using the router configuration which is mentioned in in pdf. please tell me other routing configuration.
