### ISSUE TITLE
Can i use the default smppccm which is mentioned in jasmine doc for sending the message to any mobile number in india.host 172.16.10.67

### ISSUE THREAD

**Issue by Rupesh9742** [jookies/jasmin#488]

**Comment by sah-anshu** [comment]
Dear Rupesh
IP 172.16.10.67 is used Internally to use SMPP Simulation purpose. You can't use it to connect this IP unless this IP is internally active for you and the SMPP Server is running on specific port.


anshus-MacBook-Pro:~ anshu$ ping 172.16.10.67
PING 172.16.10.67 (172.16.10.67): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
^C
--- 172.16.10.67 ping statistics ---
6 packets transmitted, 0 packets received, 100.0% packet loss
anshus-MacBook-Pro:~ anshu$ telnet 172.16.10.67 2775
Trying 172.16.10.67...
^C
anshus-MacBook-Pro:~ anshu$ telnet 172.16.10.67 2777
Trying 172.16.10.67...
^C
anshus-MacBook-Pro:~ anshu$

**Comment by farirat** [comment]
Dear @Rupesh9742, as said by @sah-anshu, that ip from the docs is for demonstration purpose, jasmin is a piece of software to help you connect to your smpp provider, it does not provide you the provider credentials.

You can go contact brokers like infobip,messagebird,twilio,plivo ... there's hundreds and they provide you the smpp creds.
