### ISSUE TITLE
How to update dlr reports to particular messageId in new jasmin0.9.b11

### ISSUE THREAD

**Issue by anushakl** [jookies/jasmin#492]
HI i am using jasmin 0.9.b3 version but unfortunately new version 0.9.b11 is updated in repository due to new version we are unable to update dlr reports to particular messageId. so, plz help us ,Thanks in Advance .

**Comment by farirat** [comment]
Hi, please express clearly the issue:

- You cannot update to b11 from b3 ?
- You updated then you've got new issues with dlrs ? describe the issues.
- What api are you using to push mt ? http ? smpp ? both ?

**Comment by anushakl** [comment]
Hi Thanks for your response. Actually my issues are:
       I need jasmin 0.9.b3 version but i didn't find it in rpm. Prevously we used it and we worked on it now we are unable to catch dlr's from log file and update status in our database using smslogger (python script) in new version jasmin 0.9.b11. We are using both smpp and html. So, plz help us to resolve this problem.

**Comment by farirat** [comment]
Please provide details on your problem, any logged exception ? error ? ...

**Comment by farirat** [comment]
Seems same as #493, continuing discussion there.
