### ISSUE TITLE
Change deliver_sm template

### ISSUE THREAD

**Issue by anotherdevs** [jookies/jasmin#500]
Hi

The format in the SMPP 3.4 specification are:

id:IIIIIIIIII sub:SSS dlvrd:DDD submit date:YYMMDDhhmm done date:YYMMDDhhmm stat:DDDDDDD err:E Text:...

However some providers can add more info like: mcc, mnc, price.

How can I change this "template", so it listens for this information and as well can send it to the DLR receiver?

**Comment by farirat** [comment]
You can do magic inside interceptors ...

**Comment by anotherdevs** [comment]
Hi farirat

Thank you for returning to me.

Can you provide with an example?

**Comment by farirat** [comment]
Examples from doc:

http://docs.jasminsms.com/en/latest/interception/index.html#scripting-examples

**Comment by anotherdevs** [comment]
Hi farirat

I might have been expressing myself wrongly.

When a message has been submitted, a deliver_sm will be sent back containing the status of the message (DLR). I would like to also get the mcc, mnc and price, that my provider can inject into DLR.

This informations is also supposed to be sent the DLR of my customer.

Is that possible with interceptors?

**Comment by farirat** [comment]
- This is where dlr parsing is done (as it come from upstream): https://github.com/jookies/jasmin/blob/master/jasmin/protocols/smpp/operations.py#L54
- This is where dlr construction is done (before pushing back to downstream): https://github.com/jookies/jasmin/blob/master/jasmin/protocols/smpp/operations.py#L221
