### ISSUE TITLE
HTTP API not understanding special characters fx.: æ ø å

### ISSUE THREAD

**Issue by anotherdevs** [jookies/jasmin#502]
Hi

The HTTP API does not understand special characters fx.: æ ø å.
It's getting malformed when coding = 1.

It works with coding set to 3, but if the message exceeds 140 characters, it's again getting malformed.

What is the correct setting?

**Comment by farirat** [comment]
Are you "urlencoding" your content ?

**Comment by anotherdevs** [comment]
Yes, it is encoded as URL.

æøå = %C3%A6%C3%B8%C3%A5
