### ISSUE TITLE
Nested routing?

### ISSUE THREAD

**Issue by ominds** [jookies/jasmin#512]
Have been contemplating weather having nested routers would be a good idea. For example, let's say we have a round-robin route, the inner items could be fail-over routes. So if one fails, it will switch to the next, etc.

It could also work the other way around, a fail-over route would have round-robin routes inside it. So each one of the round-robin routes would be iterated over until one doesn't fail.

Does that make sense? Or is there some other/preferred way to implement this?

**Comment by farirat** [comment]
It makes sense ! and it can be done with an interceptor tagging the routable, and make routes based on tagfilters.
