### ISSUE TITLE
Getting no route when I have a route

### ISSUE THREAD

**Issue by ominds** [jookies/jasmin#516]
I'm getting "no route found" despite having routes with tag filters, and correct tags

#3     StaticMTRoute           0 (!)      smppc(A)                                       <TG (tag=2)>                                                    
#2     StaticMTRoute           0 (!)      smppc(B)                                 <TG (tag=3)>                                                    
#1     StaticMTRoute           0 (!)      smppc(C)                                    <TG (tag=4)>                                                    

Here are my filters

#default          TransparentFilter      MO MT  <T>                             
#A        TagFilter              MO MT  <TG (tag=3)>                    
#B           TagFilter              MO MT  <TG (tag=4)>                    
#C              TagFilter              MO MT  <TG (tag=2)>                    

And here's the HTTP request I'm making

http://smpp.dev:1401/send?username=admin&password=whatever&from=Ashraf&to=12345678&content=TESTING%201234&priority=1&dlr=yes&dlr-url=http%3A%2F%2Fsmpp.ash%2Fapi%2Fdlr&dlr-level=2&dlr-method=GET&tags=4

And finally, here's the response I'm getting

Error "No route found"

Is there anything wrong I'm doing here?

**Comment by farirat** [comment]
Can you provide ssh access to your environment ? this will let me reproduce the issue quickly and plan a potential fix, if yes then send your information to support@jasminsms.com, do not share your production environment, please prepare a staging one if possible.

**Comment by ominds** [comment]
Wish I had setup port forwarding before I left the office. Will send you the access tomorrow (Tue)

**Comment by ominds** [comment]
Sent

**Comment by farirat** [comment]
Tracking on Jasmin support desk: JSD-28

**Comment by ominds** [comment]
Glad we helped catch an important bug!

**Comment by ominds** [comment]
You have any expectations on when a new dpkg will be rolled out with fix?

**Comment by farirat** [comment]
0.9rc16 is planned for next monday.

**Comment by ominds** [comment]
Ah, so long! Any other way I can get early access? I can help QA until Monday. We have today, tomorrow and Sunday as work days here.

**Comment by farirat** [comment]
This will be fixed today, you can take the patch ;)
one moment ..

**Comment by ominds** [comment]
How's the dpkg version mapped to git branches/tags? For example, I have package 0.9.15-2, that would be what in terms of branches/tags?

**Comment by farirat** [comment]
0.9.15-x is 0.9b15, the x is package-dependent: first package of a branch would take ..-1, second will be ..-2.

For that 0.9b15 there were two package generations, some users reported an issue in systemd service handling in 0.9.15-1.

**Comment by ominds** [comment]
Right. Good to know. Let me know when that commit lands on branch .16 and I'll take it from there :)

**Comment by farirat** [comment]
@ominds you can now consider the branch 0.9rc16

**Comment by jackbit** [comment]
the same error in docker `Error "No route found"` when sending message

```
http://127.0.0.1:1401/send?username=foo&password=bar&to=%2B1234567890&content=hello+bro
```

**Comment by farirat** [comment]
@jackbit i dont think we're talking about the same issue, @ominds's issue is related to routing based on tags and i don't see that you're setting some tags within your url request, so please check your routing.
