### ISSUE TITLE
systemd not avlibel on centos 6

### ISSUE THREAD

**Issue by AmmarAbuQoura** [jookies/jasmin#522]
Hello, 
i'm installing your nice system and now i don't know where to but this files since i'm using centos 6 and there is on systemd 
systemd scripts must be downloaded from here <https://github.com/jookies/jasmin/tree/master/misc/config/systemd> and manually installed into your 
system, once placed in /lib/systemd/system jasmind shall be enabled and started:

**Comment by farirat** [comment]
As said [here](http://docs.jasminsms.com/en/latest/installation/index.html#rhel-centos), only Centos/RHEL 7 packages are provided.

You'll need to install using pypi if you have lower version.
