### ISSUE TITLE
Can't access jasmin ID in interceptors

### ISSUE THREAD

**Issue by ominds** [jookies/jasmin#524]
I need to save the messages to a DB, I figured I could do that via interceptors. The problem is 

1. MT interceptor doesn't know the jasmin ID
2. MO interceptors for the DLR doesn't have the jasmin ID too, so I can't map it to the sent message

Am I going about this the wrong way? Or is there something I'm missing?

**Comment by farirat** [comment]
Interceptors are run in a blocking way, the message will pass only after your script getting successfully executed, so imagine your DB is getting slow or unreachable or having some SQL errors = messages are lost.

Intereceptors are better for routing and inline message update.

For your db logging, i see you did not take a look [here](http://docs.jasminsms.com/en/latest/faq/developers.html#how-to-log-messages-in-a-third-party-database), this way you'll log your messages to DB asynchronously, even if your DB has vanished for some time, you'll never loose a message.

**Comment by ominds** [comment]
Right. So I created a amqp listener, and I'm getting the messages. The body of the message is unreadable, it seems to be encoded in some way (I think this is the PDU?). Is it a serialized object? My amqp queue listener is written in PHP, would be great if there was a way I can parse the body into an array or object.

**Comment by ominds** [comment]
Any updates on this? I just need to parse the message body in PHP. But can't figure out how it's stored in the amqp message.
