### ISSUE TITLE
Adding custom TLV parameter in MT interceptor.

### ISSUE THREAD

**Issue by egidijusz** [jookies/jasmin#528]
Hello,

is there a way to add custom TLV parameter when sending MT message (trough smsc, using smpp)? I'm thinking - mtinterceptor? But can't find anything about it in documentation.

If there is a way - could you point me to the right direction in documentation/code?

Thank you!

**Comment by egidijusz** [comment]
Found this issue #429 
I suppose it's still the case - no possibility to add custom TLV parameters, yes?

**Comment by 2naive** [comment]
Same question for receiving TLV params in interceptor and proxy them forward
