### ISSUE TITLE
Delivery response is not accepting by jasmin

### ISSUE THREAD

**Issue by ferozewaris** [jookies/jasmin#529]
Hi 

I have been sending sms from jasmin to smsc over SMPP by making smppccm connector (transceiver) smsc is sending back the delivery response in deliver_sm packet jasmin is unable to receive this delivery response.  my message flow is as follows 

Kannel ----> Jasmin ----> smsc  
protocol: SMPP

**Comment by farirat** [comment]
What do you get in messages.log when DLR is expected from smsc ?

**Comment by ferozewaris** [comment]
i get nothing when DLR is expected from smsc.

**Comment by farirat** [comment]
So how are you sure your smsc is sending a DLR ?

**Comment by ferozewaris** [comment]
Because i am using smsc simulator i.e SMPPSim and it is sending delivery response in deliver_sm

**Comment by ferozewaris** [comment]
waiting for your reply

**Comment by sah-anshu** [comment]
pl check in kannel dlr_index value ? are you really requesting DLR in kannel .
If you are using kannel SQLBOX pl share sample record of that send_sms table.

**Comment by ferozewaris** [comment]
Yes i am really requesting delivery request. I am using dlr-mask = 31. Let me share some jasmin logs in which delivery response is requested. 
427 SMS-MT [cid:DEMO_CONNECTOR] [queue-msgid:7c747657-260d-4540-8548-819cf1d20ed2] [smpp-msgid:1] [status:ESME_ROK] [prio:0] [dlr:SMSC_DELIVERY_RECEIPT_REQUESTED] [validity:none] [from:1234564811] [to:453214164196] [content:'check']
