### ISSUE TITLE
TLV SMPP

### ISSUE THREAD

**Issue by muriloventuroso** [jookies/jasmin#536]
A provider sends me some information in TLV fields. Since Jasmin does not have support for this yet how could I just capture this information?

**Comment by farirat** [comment]
MO or MT traffic ?

**Comment by muriloventuroso** [comment]
DLR of MT

Em dom, 26 de fev de 2017 19:26, The Z <notifications@github.com> escreveu:

**Comment by farirat** [comment]
Can you provide a tcp trace ?

**Comment by muriloventuroso** [comment]
These were the data my provider gave me. I could not make a trace, the connection has to be in SSL.

TLV:

0x0427 - (1063) - message_state - byte

ENROUTE - 1 - The message is in enroute state.
DELIVERED - 2 - Message is delivered to destination
EXPIRED - 3 - Message validity period has expired.
DELETED - 4 - Message has been deleted.
UNDELIVERABLE - 5 - Message is undeliverable
ACCEPTED - 6 - Message is in accepted state (i.e. has been manually read on behalf of the subscriber by customer service)
UNKNOWN - 7 - Message is in invalid state
REJECTED - 8 - Message is in a rejected state

TLV - extraopt:
0x1401 - (5121) - carrier_id - short
0x1402 - (5122) - carrier_name - string
0x1403 - (5123) - sent_status_code - short
0x1404 - (5124) - sent_status - string
0x1405 - (5125) - delivered_status_code - short
0x1406 - (5126) - delivered_status - string

Example of PDU:
DR Request sent: (deliver: (pdu: 258 5 0 2) (addr: 1 1 5519991145117) (addr: 1 1 27127) (sm: enc: ISO-8859-1 msg: id:e807ff00-8f07-11e6-88f1-0242c05eba42 sub:001 dlvrd:001 submit date:1610101338 done date:1610101338 stat:DELIVRD err:000 text:Message Text) (opt: (byte: (tlv: 1063) 2) ) (extraopt: (short: (tlv: 5121) 1) (str: (tlv: 5122) VIVO) (short: (tlv: 5123) 2) (str: (tlv: 5124) SENT_SUCCESS) (short: (tlv: 5125) 104) (str: (tlv: 5126) NOT_DELIVERED) ) ) . ESM_CLASS: 4

**Comment by terrycain** [comment]
I too could do with support for custom TLVs, my provider sends MCC and MNC data in an optional tag (0x1403) in deliver_sm's

Have uploaded a pcap with the TLV, its a bit hacked up as i dropped out a lot of packets, can get another pcap if its helpful.
[smpp_dump.pcap.zip](https://github.com/jookies/jasmin/files/1122427/smpp_dump.pcap.zip)

I'm more than happy to try and piece together a PR for this but am 1. not too sure where I should start an d 2. don't know how you guys would want the data to reach the user/program getting hit by the dlr

**Comment by terrycain** [comment]
Can we get anymore info on this?

**Comment by farirat** [comment]
Hey @terrycain,
Jasmin would actually bypass any TLV parameter, still there's cases where vendors are using standard tags to embed non-standard parameters (eg: putting MCC/MNC inside a DST TON parameter ...), these cases are hard to investigate and can be time consuming.

You can request a commercial time allocation from support@jasminsms.com to dig in this issue.
