### ISSUE TITLE
Example using_pb.py from FAQ will crash the server when adding new user

### ISSUE THREAD

**Issue by aivisol** [jookies/jasmin#538]
The code sample here:  http://docs.jasminsms.com/en/latest/faq/developers.html#how-to-directly-access-the-perspective-broker-api  will crash the server if you use it as is. The problem appears to be that gid and uid should be passed as strings not integers. This will not work:

```
# Provisiong router with users
g1 = Group(1)
u1 = User(uid = 1, group = g1, username = 'foo', password = 'bar')
```

Instead use this:
```
g1 = Group('group1')
u1 = User(uid = '1', group = g1, username = 'foo', password = 'bar')
```

maybe better is to add some type checking and protection inside the code itself?

**Comment by farirat** [comment]
Will be fixed in next release !
thank you
