### ISSUE TITLE
Multiple SMPP Sessions

### ISSUE THREAD

**Issue by sah-anshu** [jookies/jasmin#542]
Hi Z!

To Connect Multiple Sessions of any Uplink SMPP, DO we need to create the separate Uplinks like uplink1, uplink2, uplink3 with same credentials and route SMPP via roundrobin method 

Or 

We have any other alternative. 

Kindly advice.

**Comment by farirat** [comment]
roundrobin is a standard routing feature, you can do your own thing to group your connectors through your interceptor script.
