### ISSUE TITLE
MO Re-routing 

### ISSUE THREAD

**Issue by sah-anshu** [jookies/jasmin#543]
Hi Z!,

I have a situation, If we get any specific ERR code from any Uplink, We want to re-route it to another uplink based on Tag filter but the message ID shall remain same.  This situation is imp for our SMPP Users.

SMPP CLIENT 1 ------->>SUBMIT_SM>>--------<JASMIN>>>>>>-->>>>UPLINK 1
SMPPCLIENT 1 <-------MESSAGE_ID <-------JASMIN  (While submission)

While We got DLR from uplink 1 with specific error code 
We resent it to Uplink 2 with some other re-routing. But message ID shall remain same and again if we got status then we send to SMPP Client final report after that retry.

Please advice. how can we handle this situation.

-Anshu

**Comment by farirat** [comment]
I think this is a bit difficult, msgid are autogenerated on message request, if you want to resend then this is considered as a new request, then new msgid.

I never tried to update the msgid inside the interceptor, seems weird but you still can do it :)

**Comment by sah-anshu** [comment]
This senario is useful when we received some specific error code from one uplink and then we want to route to other uplink for delivery. 

Can you suggest me if we have something built-up similar in jasmin.
