### ISSUE TITLE
Persistent config not loading on startup

### ISSUE THREAD

**Issue by SteveAyre** [jookies/jasmin#546]
Do you know why the files in /etc/jasmin/store/  might not be loaded when jasmin first starts?

I can log into jcli and use 'load' and the files load correctly.

I see the following in jcli.log, which might be related

> 2017-03-15 16:34:15 INFO     16848 OnStart loading configuration default profile with username: 'jcliadmin'
> 2017-03-15 16:34:15 ERROR    16848 Authentication error, cannot load configuration profile with provided username: 'jcliadmin'

**Comment by SteveAyre** [comment]
Using 0.9.b15

**Comment by SteveAyre** [comment]
The config is loaded correctly if I set `authentication = False` in `[jcli]`

**Comment by SteveAyre** [comment]
I found that it is using these default options which do not match the password I've set in `[jcli]`
> loadConfigProfileWithCreds = {'username': 'jcliadmin', 'password': 'jclipwd'}

The reason was our init script was not passing --username and --password options.

**Comment by Newcss** [comment]
/lib/systemd/system/jasmind.service
Init String:
ExecStart=/usr/bin/jasmind.py --username jcliadmin --password XXXXX

Change XXXXX to your password.
