### ISSUE TITLE
deliver_sm_thrower cluster routing

### ISSUE THREAD

**Issue by SteveAyre** [jookies/jasmin#548]
Hi,

We're trying to configure a jasmin cluster. They use the same shared /etc/jasmin/store/ settings and a rabbitmq cluster.

We are able to connect to node A as user 'Client-01'. We send a MT message which is published on the submit.sm.Server-01 queue, and consumed on node B which is connected to the test server. The server echoes the message back. Node B publishes to the deliver_sm_thrower queue.

However we are seeing in deliver_sm_thrower.log that the message is consumed on node B, which has no connection from Client-01. After a few seconds the message is then consumed on node A and delivered to the client.

Is there a way to get this working without the timeout delay?

It seems to me that it might be better for the deliver_sm_thrower queue to use the UID in the queue name or routing key, so that any node the client has connected to would consume the messages and not the nodes which do not have the user connected.

**Comment by balsagoth** [comment]
Hi @SteveAyre,

Did you have Redis cluster?

**Comment by SteveAyre** [comment]
rabbitmq
