### ISSUE TITLE
MtRouter via jasmin connector httpc

### ISSUE THREAD

**Issue by kamalaithammou** [jookies/jasmin#550]
I used smpp server to receive the SMS I want to send them via http smsc but there is no http connector for MT?????

**Comment by cvmathur** [comment]
I'm facing same issue. Any word on this guys ?

**Comment by farirat** [comment]
Jasmin has no http upstream connector, this is provided through a commercial plugin, please contact the support for further details.

**Comment by mexicarne** [comment]
Hello @farirat . Apologies for writing here. I interested in this plugin and tried to contact support at jasminsms, but got no reply in two days. Does this plugin still supported/provided?

**Comment by farirat** [comment]
@mexicarne What's your support ticket id ?

**Comment by mexicarne** [comment]
its JSD-366
