### ISSUE TITLE
Cannot start RedisClient: NOAUTH Authentication required.

### ISSUE THREAD

**Issue by muriloventuroso** [jookies/jasmin#551]
I am having the following error when using password in the redis configuration:

`Cannot start RedisClient: NOAUTH Authentication required.`

I set the password in /etc/jasmin/jasmin.cfg

**Comment by balsagoth** [comment]
Hi,

It worked here. Could you provide more details about your installation?

**Comment by magojr** [comment]
This is the last issue i miss to solve on our installation. If I set a password in redis server and I insert the same in the config files of Jasmin, something doesn't work as expected: the redis-cli log show a correct auth but the syslog (Eg "systemctl status jasmind") give the error in the Title. I debugged a bit this issue and I verified that the password is correctly set up in redis client object, both for  dlrlookupd instance and for jasmind instance so it seems to be some factory initialization issue or some other component of Jasmin trying to use Redis without authentication (but I have NOT found anything like that).
Is there someone that can try to authenticate Redis on his development box to check about this issue?
It should be great to know if it's a system dependent issue or a bug or even a dependencies issue.
Thanks!

**Comment by redbaron-gt** [comment]
@magojr Same problem here, any solution?

**Comment by magojr** [comment]
Hello, @redbaron-gt not at the moment, we're actually using redis on the same host of Jasmin and blocked queryes from outside.

**Comment by lauer** [comment]
I have just written a solution for my installation in #991
