### ISSUE TITLE
How to send Lao and Thai langauge

### ISSUE THREAD

**Issue by kommaly** [jookies/jasmin#556]
Hi
I have problem when try to send Unicode character (I follow jasmin's document # Sending UCS2) but i the message that i receive is incorrect, this is my code in python:

import urllib2
import urllib

baseParams = {'username':'foo', 'password':'bar', 'to':'856205xxxxxxx'}

content = \u0eaa\u0eb0\u0e9a\u0eb2\u0e8d\u0e94\u0eb5'
baseParams['from'] = 'MService'
baseParams['content'] = content
baseParams['coding'] = 8
urllib2.urlopen("http://xx.xx.xx.xx:1401/send?%s" % urllib.urlencode(baseParams)).read()

For the result should be ສະບາຍດີ
But my phone receive Japaneses and chines language
(for UTF-16 encoding refer: http://asecuritysite.com/coding/asc2?val=3584%2C4096)
 
and here for my Smpp connector

jcli : smppccm -s MConn
ripf 0
con_fail_delay 10
dlr_expiry 86400
coding 0
logrotate midnight
submit_throughput 1000
elink_interval 30
bind_to 30
port 5019
con_fail_retry yes
password bar
src_addr None
bind_npi 0
addr_range None
dst_ton 0
res_to 120
def_msg_id 0
priority 1
con_loss_retry yes
username foo
dst_npi 0
validity None
requeue_delay 120
host x.x.x.x
src_npi 0
trx_to 300
logfile //var/log/jasmin/default-MConn.log
systype
ssl no
cid MConn
loglevel 20
bind transceiver
proto_id None
dlr_msgid 0
con_loss_delay 10
bind_ton 5
pdu_red_to 10
src_ton 5

Please help me.

**Comment by farirat** [comment]
You should not send unicode data (\u), you have to encode your unicode to UTF16BE, as a result this char 'ສ' would be '\x0E\xAA' (according to the utf16 table you provided).

**Comment by kommaly** [comment]
Wow! Thank you, it work now
