### ISSUE TITLE
Cant send using REST API

### ISSUE THREAD

**Issue by TBorgert** [jookies/jasmin#557]
Nothing is shown in the logs. Other options seem to work, I get http codes in the logs.

**Comment by farirat** [comment]
please provide more info, how are you testing ? what are you getting ? version ? ...

**Comment by TBorgert** [comment]
Sorry. 

I am new to this, I thought that because it is a release candidate, this send function would not be complete.

Version: Jasmin 0.9.rc16 on Ubuntu 16.04

restapi.log
2017-04-13 11:51:35 INFO     1921 API Started.
2017-04-13 11:51:36 INFO     1923 Starting Jasmin Rest API ...
2017-04-13 11:51:36 INFO     1923       [OK] /ping
2017-04-13 11:51:36 INFO     1923       [OK] /secure/balance
2017-04-13 11:51:36 INFO     1923       [OK] /secure/rate
2017-04-13 11:51:36 INFO     1923       [OK] /secure/send
2017-04-13 11:51:36 INFO     1923       [OK] /secure/sendbatch
2017-04-13 11:51:36 INFO     1923 API Started.

Im testing using curl:

curl -X POST -H 'Authorization: Basic *********' -d '{
  "to": 554199980****,
  "from": "thiago",
  "content": "Hello",
  "dlr": "yes",
  "dlr-url": "http://192.168.202.54/dlr_receiver.php",
  "dlr-level": 3
}' http://127.0.0.1:8080/secure/send

I get nothing after send this command.

If i send something to /security/balance or /security/ping , i receive information on jasmin http log. When i send a sms using /security/send , i get nothing on logs.

Ping - terminal
# curl -X GET http://127.0.0.1:8080/ping

==> http-accesslog.log <==
127.0.0.1 - - [13/Apr/2017:13:41:23 +0000] "GET /ping HTTP/1.1" 200 11 "-" "python-requests/2.9.1"

Balance - terminal
# curl -X GET -H 'Authorization: Basic *****************' http://127.0.0.1:8080/secure/balance

==> http-accesslog.log <==
127.0.0.1 - - [13/Apr/2017:14:00:06 +0000] "GET /balance?username=thiago&password=******* HTTP/1.1" 200 36 "-" "python-requests/2.9.1"

Send - terminal - (I tested with DLR = yes, but the result was the same, with no news in the logs or return.)
# curl -X POST -H 'Authorization: Basic *****************' -d '{
>   "to": 5541999804666,
>   "from": "thiago",
>   "content": "Hello",
>   "dlr": "no",
> }' http://127.0.0.1:8080/secure/send

==> http-accesslog.log <==
Nothing new =(

Sending with old http api is OK

http://ec2-54-233-190-150.sa-east-1.compute.amazonaws.com:1401/send?username=thiago&password=*******&to=5541999******&content=hello

Return on browser:
Success "5d9219b5-b20e-4836-af12-fce0131501be"

If you need any more specific details please let me know.

Kind Regards.

**Comment by farirat** [comment]
Add the **-v** switch to curl and check if you a response, curl may be silent ..

**Comment by tarikogut** [comment]
you forgetten UTF-8 POST

2017-04-13 17:42 GMT+03:00 The Z <notifications@github.com>:

**Comment by TBorgert** [comment]
curl -X GET http://127.0.0.1:8080/ping -v
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /ping HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Transfer-Encoding: chunked
< Date: Thu, 13 Apr 2017 15:00:20 GMT
< Server: TwistedWeb/16.0.0
<
* Connection #0 to host 127.0.0.1 left intact

**Comment by farirat** [comment]
Okay you have HTTP500 Error.

check your restapi.log ? and check your service statuses:

- systemctl status jasmin-restapi
- systemctl status jasmin-celery

**Comment by TBorgert** [comment]
root@ip-172-31-17-140:/var/log/jasmin# cat restapi.log
2017-04-12 20:21:42 INFO     23952 Starting Jasmin Rest API ...
2017-04-12 20:21:42 INFO     23952      [OK] /ping
2017-04-12 20:21:42 INFO     23952      [OK] /secure/balance
2017-04-12 20:21:42 INFO     23952      [OK] /secure/rate
2017-04-12 20:21:42 INFO     23952      [OK] /secure/send
2017-04-12 20:21:42 INFO     23952      [OK] /secure/sendbatch

root@ip-172-31-17-140:/var/log/jasmin# systemctl status jasmin-restapi
● jasmin-restapi.service - Jasmin SMS Restful API server
   Loaded: loaded (/lib/systemd/system/jasmin-restapi.service; disabled; vendor preset: enabled)
   Active: active (running) since Thu 2017-04-13 11:51:35 UTC; 5h 27min ago
 Main PID: 1920 (sh)
    Tasks: 7
   Memory: 89.3M
      CPU: 4.039s
   CGroup: /system.slice/jasmin-restapi.service
           ├─1920 /bin/sh -c twistd -n --pidfile=/tmp/twistd-web-restapi.pid web --wsgi=jasmin.protocols.rest.api
           └─1923 /usr/bin/python /usr/bin/twistd -n --pidfile=/tmp/twistd-web-restapi.pid web --wsgi=jasmin.protocols.rest.api

Apr 13 15:06:25 ip-172-31-17-140 jasmin-restapi[1920]:             appIterator = self.application(self.environ, self.startResponse)
Apr 13 15:06:25 ip-172-31-17-140 jasmin-restapi[1920]:           File "falcon/api.py", line 212, in falcon.api.API.__call__ (falcon/api.c:2565)
Apr 13 15:06:25 ip-172-31-17-140 jasmin-restapi[1920]:             self._call_resp_mw(middleware_stack, req, resp, resource)
Apr 13 15:06:25 ip-172-31-17-140 jasmin-restapi[1920]:           File "falcon/api.py", line 555, in falcon.api.API._call_resp_mw (falcon/api.c:6466)
Apr 13 15:06:25 ip-172-31-17-140 jasmin-restapi[1920]:             process_response(req, resp, resource)
Apr 13 15:06:25 ip-172-31-17-140 jasmin-restapi[1920]:           File "/usr/lib/python2.7/dist-packages/jasmin/protocols/rest/__init__.py", line 46, in process_resp
Apr 13 15:06:25 ip-172-31-17-140 jasmin-restapi[1920]:             response.status[:3], request.context.get('username', '*'), request.remote_addr,
Apr 13 15:06:25 ip-172-31-17-140 jasmin-restapi[1920]:         exceptions.AttributeError: 'Request' object has no attribute 'remote_addr'
Apr 13 15:06:25 ip-172-31-17-140 jasmin-restapi[1920]:
Apr 13 15:06:25 ip-172-31-17-140 jasmin-restapi[1920]: 2017-04-13 15:06:25+0000 [-] 127.0.0.1 - - [13/Apr/2017:15:06:25 +0000] "POST /secure/send HTTP/1.1" 500 - "-
lines 1-21/21 (END)
root@ip-172-31-17-140:/var/log/jasmin# systemctl status jasmin-celery
● jasmin-celery.service - Jasmin Celery server
   Loaded: loaded (/lib/systemd/system/jasmin-celery.service; disabled; vendor preset: enabled)
   Active: active (running) since Thu 2017-04-13 11:51:35 UTC; 5h 28min ago
 Main PID: 1919 (sh)
    Tasks: 5
   Memory: 86.0M
      CPU: 356ms
   CGroup: /system.slice/jasmin-celery.service
           ├─1919 /bin/sh -c celery -A jasmin.protocols.rest.tasks worker -l info -c 4 --autoscale=10,3
           ├─1921 python2.7 /usr/bin/celery -A jasmin.protocols.rest.tasks worker -l info -c 4 --autoscale=10,3
           ├─1935 python2.7 /usr/bin/celery -A jasmin.protocols.rest.tasks worker -l info -c 4 --autoscale=10,3
           ├─1936 python2.7 /usr/bin/celery -A jasmin.protocols.rest.tasks worker -l info -c 4 --autoscale=10,3
           └─1937 python2.7 /usr/bin/celery -A jasmin.protocols.rest.tasks worker -l info -c 4 --autoscale=10,3

Apr 13 11:51:35 ip-172-31-17-140 jasmin-celery[1919]: If you depend on pickle then you should set a setting to disable this
Apr 13 11:51:35 ip-172-31-17-140 jasmin-celery[1919]: warning and to be sure that everything will continue working
Apr 13 11:51:35 ip-172-31-17-140 jasmin-celery[1919]: when you upgrade to Celery 3.2::
Apr 13 11:51:35 ip-172-31-17-140 jasmin-celery[1919]:     CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']
Apr 13 11:51:35 ip-172-31-17-140 jasmin-celery[1919]: You must only enable the serializers that you will actually use.
Apr 13 11:51:35 ip-172-31-17-140 jasmin-celery[1919]:   warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
Apr 13 11:51:35 ip-172-31-17-140 jasmin-celery[1919]: [2017-04-13 11:51:35,912: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
Apr 13 11:51:35 ip-172-31-17-140 jasmin-celery[1919]: [2017-04-13 11:51:35,928: INFO/MainProcess] mingle: searching for neighbors
Apr 13 11:51:36 ip-172-31-17-140 jasmin-celery[1919]: [2017-04-13 11:51:36,940: INFO/MainProcess] mingle: all alone
Apr 13 11:51:36 ip-172-31-17-140 jasmin-celery[1919]: [2017-04-13 11:51:36,950: WARNING/MainProcess] celery@ip-172-31-17-140 ready.

**Comment by farirat** [comment]
Ok, it seems some requirements were not installed for some reason.

I see it's an AWS instance, can you please share an access ? please email it to support@jasminsms.com

**Comment by TBorgert** [comment]
Access shared. Thank you farirat.

**Comment by farirat** [comment]
Issue details below:

**1. Environment:**
- Ubuntu 16.04.2
- Jasmin 0.9.16 installed using apt

**2. Issue:**
A _HTTP/1.1 500 Internal Server Error_ is returned when invoking any rest api service, no errors are logged in restapi.log

**3. Resolution:**
Upgrade python falcon library to v1.1.0:

`# pip install --upgrade falcon`

**4. Root Cause:**
Ubuntu 16.04.2 seems to package an old falcon version (0.3.0-5) which is not compatible with Jasmin's restapi (falcon>=1.1.0).

**5. Diagnostic Steps:**
Showing the **jasmin-restapi** service status reveals the following error:
```
# systemctl status jasmin-restapi
jasmin-restapi.service - Jasmin SMS Restful API server
   Loaded: loaded (/lib/systemd/system/jasmin-restapi.service; disabled; vendor preset: enabled)
   Active: active (running) since Mon 2017-04-17 18:10:08 UTC; 3h 20min ago
...
...
... exceptions.AttributeError: 'Request' object has no attribute 'remote_addr'
...
```

and checking falcon's version reveals the following:
```
# dpkg -l|grep falcon
ii  python-falcon                    0.3.0-5
```
