### ISSUE TITLE
Rejecting SubmitSmPDU - While Submit from HTTP  API

### ISSUE THREAD

**Issue by sah-anshu** [jookies/jasmin#559]
2017-04-18 01:15:41 CRITICAL 15264 Rejecting SubmitSmPDU[1106dd29-7c67-400e-91c3-d9d3c8cc56ea] through [cid:p_trans] for an unknown error (<type 'exceptions.TypeError'>): %d format: a number is required, not str

jcli : smppccm -s p_trans
ripf 0
con_fail_delay 10
dlr_expiry 86400
coding 0
logrotate midnight
submit_throughput 20
elink_interval 30
bind_to 30
port XXXX
con_fail_retry yes
password XXXXXXXX
src_addr XXXXXX
bind_npi 0
addr_range None
dst_ton 1
res_to 120
def_msg_id 0
priority 0
con_loss_retry yes
username LSmultiple
dst_npi 0
validity None
requeue_delay 120
host XXXXXXXX
src_npi 0
trx_to 300
logfile //var/log/jasmin/default-p_trans.log
systype SMPP
ssl no
cid p_trans
loglevel 10
bind transceiver
proto_id None
dlr_msgid 0
con_loss_delay 10
bind_ton 1
pdu_red_to 10
src_ton 1

Please help.

**Comment by sah-anshu** [comment]
While i added manually from telnet it works. 
Just curious what went wrong for that exception.  Earlier i had used jasmin-api to add this.

**Comment by farirat** [comment]
jasmin-api may be pushing some values in string format while jasmin does not accept it, the display cannot reveal the value type, but i guess it's more about the binding port or some timeout values ...

There's type casting even when you type the config through jcli, [check this out](https://github.com/jookies/jasmin/blob/master/jasmin/protocols/cli/smppccm.py#L51), jasmin-api may not do the same type casting and it needs some contrib to be fixed ;)

**Comment by sah-anshu** [comment]
Ok thanks.
