### ISSUE TITLE
Custom src_ton

### ISSUE THREAD

**Issue by jancss** [jookies/jasmin#562]
Hello.

This might be a very simple issue, but one provider asks for a very specific destination address format. Its a 15 digit code thats basically 3 digits for the national id of the source provider, 3 digits for the destination provider, followed by the number in a national 9 digit format. All the while they're asking to set dst_ton to international. I dont know if its jasmin thats throwing the ESME_RINVDSTADR error or the provider, in any case its not working. Is there a simple way to get around the validation or a way of setting a custom format for the destination number?

Thanks.

**Comment by farirat** [comment]
It must be your provider returning back a ESME_RINVDSTADR  error, you can check your messages.log or better, taking a tcpdump trace.

**Comment by jancss** [comment]
Ok so if it shows up in messages.log its definitely the provider throwing the error?

2017-04-21 23:53:54 INFO     1 SMS-MT [cid:{provider}] [queue-msgid:cf605120-ae04-4d91-85a3-06c6c71652f6] [status:ERROR/ESME_RINVDSTADR] [retry:False] [prio:0] [dlr:NO_SMSC_DELIVERY_RECEIPT_REQUESTED] [validity:none] [from:{origina}] [to:{15 digit number}] [content:'test']

So, conceptually, jasmin doesnt filter/invalidate any messages with a 15 digit destination number with dst_ton set to 1?

Thanks!

**Comment by farirat** [comment]
No, Jasmin does not care about your message headers or content, it's a router.

Closing this issue.
