### ISSUE TITLE
Is there any method to remove specific message_id from store

### ISSUE THREAD

**Issue by sah-anshu** [jookies/jasmin#565]
Hi

Is there any method to remove specific message_id from store. or specific mobile_number. 

Kindly help
Anshu

**Comment by sah-anshu** [comment]
![screen shot 2017-04-28 at 10 35 18 am](https://cloud.githubusercontent.com/assets/9985291/25514941/7eb51f1c-2bfe-11e7-8f70-4e9fc73e5bce.png)
![screen shot 2017-04-28 at 10 35 08 am](https://cloud.githubusercontent.com/assets/9985291/25514944/84217b76-2bfe-11e7-8317-6fb479e61013.png)

If we delete specific key will that cause to remove the specific message from Q

**Comment by farirat** [comment]
Messages are enqueued in rabbitmq, you can do it with the right rabbitmq client.
