### ISSUE TITLE
Symbols not displaying correctly in Phone

### ISSUE THREAD

**Issue by sah-anshu** [jookies/jasmin#566]
Hi

 "content": "Same content goes to 3 numbers- 20-10 ~!@#$%^&*()",

- I have tested coding  0, 2, 8  in http api request, restapi request.  As well as i setup coding value in smppccm but there is no success.

- While i tested the same using kannel downlink It worked correctly. ie. We need to set some value in HTTP and restful API

Pl help
Anshu

**Comment by sah-anshu** [comment]
duplicate issue #213

**Comment by sah-anshu** [comment]
2017-04-28 21:36:51 DEBUG    6103 Outbound transaction finished with message id 2
2017-04-28 21:37:16 DEBUG    6103 Sending PDU: PDU [command: submit_sm, sequence_number: 3, command_status: ESME_ROK
service_type: None
source_addr_ton: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f3a2f16ccd0>, 4, 'NATIONAL')
source_addr_npi: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f3a2f16ced0>, 9, 'ISDN')
source_addr: 'WEBSMS'
dest_addr_ton: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f3a2f16ccd0>, 6, 'INTERNATIONAL')
dest_addr_npi: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f3a2f16ced0>, 9, 'ISDN')
destination_addr: '919790197346'
esm_class: EsmClass[mode: STORE_AND_FORWARD, type: DEFAULT, gsmFeatures: set([])]
protocol_id: 1
priority_flag: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f3a2f16c990>, 0, 'LEVEL_0')
schedule_delivery_time: None
validity_period: None
registered_delivery: RegisteredDelivery[receipt: NO_SMSC_DELIVERY_RECEIPT_REQUESTED, smeOriginatedAcks: set([]), intermediateNotification: False]
replace_if_present_flag: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f3a2f16cb10>, 0, 'DO_NOT_REPLACE')
data_coding: DataCoding[scheme: DEFAULT, schemeData: SMSC_DEFAULT_ALPHABET]
sm_default_msg_id: 0
short_message: 'Testing SMS anshu@test.com'
]
2017-04-28 21:37:16 DEBUG    6103 Sending data [0000004d000000040000000000000003000201574542534d53000101393139373930313937333436000301000000000000001a54657374696e6720534d5320616e73687540746573742e636f6d]
2017-04-28 21:37:16 DEBUG    6103 Outbound transaction started with message id 3

**Comment by farirat** [comment]
@sah-anshu i dont really get your point, what are your trying to do ? what's expected ? and what do you get ?
Are you using latest release ?

**Comment by sah-anshu** [comment]
Hi @farirat while we send symbols like "@" from HTTP API / Rest API it automatically get converted into unknown symbols in phone. 

I can see coding as parameter in http API, I kept it 0, 2, or 8 but no effect. While i saw additional parameter in smppccm "coding" - I also changed it to 0,2 

If i am missing something. Please advise. 

Anshu

**Comment by sah-anshu** [comment]
@farirat resolved now i can getting correctly.
