### ISSUE TITLE
Seems Interceptor not working  / Updating routing flag

### ISSUE THREAD

**Issue by sah-anshu** [jookies/jasmin#567]
![screen shot 2017-04-29 at 4 45 15 am](https://cloud.githubusercontent.com/assets/9985291/25550562/bfe94ed8-2c97-11e7-83e8-3e908d335b87.png)
![screen shot 2017-04-29 at 4 45 58 am](https://cloud.githubusercontent.com/assets/9985291/25550566/c213cf30-2c97-11e7-8846-d28c6a086fbd.png)
![screen shot 2017-04-29 at 4 46 44 am](https://cloud.githubusercontent.com/assets/9985291/25550567/c683a158-2c97-11e7-9f18-9be11b1c58d3.png)
![screen shot 2017-04-29 at 4 47 11 am](https://cloud.githubusercontent.com/assets/9985291/25550578/cde66f02-2c97-11e7-8799-9373d1fcf452.png)

Kindly take a Look and advice. 
-
Anshu

**Comment by farirat** [comment]
When using http api the "registered_delivery" param is set in the pdu according to what your request has (in dlr, dlr-level and dlr-url parameters), interception does not force these values.

**Comment by sah-anshu** [comment]
Incase of http request i am not putting these values dlr, dlr-level and dlr-url parameters. I wish to enable these values thro' interceptors.

**Comment by sah-anshu** [comment]
I even tried to set source_addr using interceptor using your sample code .
This script will override sender-id"

routable.pdu.params['source_addr'] = 'WEBSMS'
But it didn't happened.

**Comment by farirat** [comment]
please check your interceptor script, changing source_addr is working.

**Comment by sah-anshu** [comment]
:) I works thanks
