### ISSUE TITLE
Jasmin Interceptor does not start

### ISSUE THREAD

**Issue by basarolgun** [jookies/jasmin#569]
Hello,
I want to start interceptor but it gave "interceptord.py[11476]:   Cannot start Interceptor: Non-hexadecimal digit found" How can i fix this?

**Comment by sah-anshu** [comment]
please share us /var/log/jasmin/interceptor.log

**Comment by basarolgun** [comment]
i do not have that file, i think it is not generated because the service is not started well

**Comment by sah-anshu** [comment]
- are you using latest build ?
- Have you created any MO/MT Interceptor yet.
- Are you starting jasmin with Interceptor.  --enable-interceptor-client

**Comment by basarolgun** [comment]
Im using 0.9.b15 build.

yes i created a MT interceptor (jcli : mtinterceptor -l
#Order Type                 Script                                          Filter(s)
#0     DefaultInterceptor   <MTIS (pyCode=from jasmin.vendor.smpp.pdu.pd ..)>
Total MT Interceptors: 1
jcli : mtinterceptor -s 0
DefaultInterceptor/<MTIS (pyCode=from jasmin.vendor.smpp.pdu.pd ..)>)

Yes im starting jasmind with --enable-interceptor-client (ExecStart=/usr/bin/jasmind.py --username jcliadmin --password jclipwd --enable-interceptor-client)

**Comment by farirat** [comment]
Are you getting this error on service startup or when intercepting a message ?

**Comment by basarolgun** [comment]
im getting this error on interceptor service startup.

**Comment by farirat** [comment]
Is it a clean install ? or did you update any Jasmin python files ? how did you install ? deb/rpm/pypi/docker ?

Can you retest the same with the latest 0.9rc16 ?

**Comment by basarolgun** [comment]
it is clean install, i used rpm packages. it is not possible to upgrade Jasmin now, because of security restrictions. The server do not have internet connection.

**Comment by basarolgun** [comment]
I upgraded Jasmin to 0.9.rc16 but nothing changed about interceptor, can you help please? Where should i check?

**Comment by basarolgun** [comment]
I found the problem, it is because admin password in interceptor.cfg file. it was a string. After chancing the password, interceptor service run smoothly. Thank you.
