### ISSUE TITLE
binary messages

### ISSUE THREAD

**Issue by georgerizescu** [jookies/jasmin#582]
Hi,
i need help sending configuration messages using jasmin.
I've found this blog (https://mobiforge.com/email-configuration-sms) and i'm doing like this:
1. convert the xml configuration file to wbxml
2. convert wbxml content to hexa using urlencode in php
3. send the result using content:
http://localhost:1401/send?username=u&password=p@&to=XXXXXXXXX&from=XXXX&coding=2&content=%22%.....

i'm receiving the message in my phone, but is not recognised as a configuration message, the message looks like wbxml file

**Comment by farirat** [comment]
Use the hex-content instead of content, more info here: http://docs.jasminsms.com/en/latest/apis/ja-http/index.html#sending-sms-mt

And did you consider the rest api instead of the http api ? there's also hex-content parameter there.

**Comment by georgerizescu** [comment]
As i'm only testing if jasmin can handle wap configuration messages i used only http-api.
What i tried so far (starting from xml->wbxml->hex using hexlify(content)):
1.send using hex_content
http://localhost:1401/send?username=u&password=p&to=xxxxxxx&from=xxx&coding=2&hex-content=030b6a00c54503312e...
2. send using different coding type
3. adding a MTinterceptor and changing service_type to WAP (from default None)
No solution worked so far.
What i understand from that blog is that u need to tell the phone that this is a configuration message (by using User Data Header).

Even if on jasmin website it says that "Supports easy creation and sending of specialized/binary SMS like mono Ringtones, WAP Push, Vcards" i didn't find any info about this in the documentation.

**Comment by farirat** [comment]
Binary content is sent through hex-content.

Do you have a desired pdu dump ? i'll tell you what params to use to get a similar pdu.

**Comment by georgerizescu** [comment]
i don't have one..but i will request one from our partner..hopefully they can provide one with their data

**Comment by georgerizescu** [comment]
I found this working pdu: (using kannel)
http://www.kannel.org/pipermail/users/2010-May/010799.html

DEBUG: boxc_receiver: sms received
DEBUG: send_msg: sending msg to box:<127.0.0.1>
DEBUG: SMPP[send_xxx]: Manually forced source addr ton = 1, source add npi = 1
DEBUG: SMPP[send_xxx]: Manually forced dest addr ton = 1, dest add npi = 1
DEBUG: SMPP[send_xxx]: Sending PDU:
DEBUG: SMPP PDU 0x16e29b0 dump:
DEBUG:   type_name: submit_sm
DEBUG:   command_id: 4 = 0x00000004
DEBUG:   command_status: 0 = 0x00000000
DEBUG:   sequence_number: 35 = 0x00000023
DEBUG:   service_type: NULL
DEBUG:   source_addr_ton: 1 = 0x00000001
DEBUG:   source_addr_npi: 1 = 0x00000001
DEBUG:   source_addr: "1072"
DEBUG:   dest_addr_ton: 1 = 0x00000001
DEBUG:   dest_addr_npi: 1 = 0x00000001
DEBUG:   destination_addr: "569xxx"
DEBUG:   esm_class: 67 = 0x00000043
DEBUG:   protocol_id: 0 = 0x00000000
DEBUG:   priority_flag: 0 = 0x00000000
DEBUG:   schedule_delivery_time: NULL
DEBUG:   validity_period: NULL
DEBUG:   registered_delivery: 0 =0x00000000
DEBUG:   replace_if_present_flag: 0 =0x00000000
DEBUG:   data_coding: 0 = 0x00000000
DEBUG:   sm_default_msg_id: 0 = 0x00000000
DEBUG:   sm_length: 39 = 0x00000027
DEBUG:   short_message:
DEBUG:    Octet string at 0x16dad80:
DEBUG:      len:  39
DEBUG:      size: 1024
DEBUG:      immutable: 0
DEBUG:      data: 06 05 04 0b 84 23 f0 3f 3f 3f 3f 3f 3f 6a 3f 45   .....#.??????j?E
DEBUG:      data: 3f 3f 67 6f 6f 67 6c 65 2e 6d 6f 62 69 3f 3f 3f   ??google.mobi???
DEBUG:      data: 67 6f 74 6f 3f 3f 3f                              goto???
DEBUG:    Octet string dump ends.
DEBUG: SMPP PDU dump ends.
DEBUG: SMPP[send_xxx]: Got PDU:
DEBUG: SMPP PDU 0x16e29b0 dump:
DEBUG:   type_name: submit_sm_resp
DEBUG:   command_id: 2147483652 =0x80000004
DEBUG:   command_status: 0 = 0x00000000
DEBUG:   sequence_number: 35 = 0x00000023
DEBUG:   message_id: "6f83f702"
DEBUG: SMPP PDU dump ends.

**Comment by lsadehaan** [comment]
The issue is probably that you don't have the UDHI set in the ESM_CLASS of the PDU sent by Jasmin.
You could create an interceptor that sets the ESM_CLASS for a specific user (or some other filter) - it seems there is no other way to set it through the HTTP interfaces. In the interceptor you would want to set it like this: 
routable.pdu.params['esm_class'] = EsmClass(EsmClassMode.DEFAULT, EsmClassType.DEFAULT, [EsmClassGsmFeatures.UDHI_INDICATOR_SET])
routable.lockPduParam('esm_class')
