### ISSUE TITLE
Issue sending SMS

### ISSUE THREAD

**Issue by JFnine** [jookies/jasmin#583]
Hi, 

I'm trying send a SMS by using SMPP client (jasminsms) and connecting it to a SMScenter, the theory is that I should bind my SMPPclient, which is situated in a server of mine, to the SMScenter, when I do that, then what I do is, by using a POST, to send a message, in theory the SMScenter should send the SMS to my device...

Am I understanding something in the wrong way here? 

Kind regards.

**Comment by farirat** [comment]
All is okay @JFnine ! :)

**Comment by JFnine** [comment]
Then there is something that is not letting me do that. @farirat :(

**Comment by sah-anshu** [comment]
Hi
There are following steps. if you can let me know i can probably help. ( you are using rest / http api )?

- check mtrouter / filter
- check with user balance
- check with smscenter logs or message.log placed in /var/log/jasmin
- finally at-last check the amqp log too.

-
Anshu

**Comment by JFnine** [comment]
Hi @sah-anshu , thank you very much, I'm actually using rest api. 

**mtrouter:**
#2     StaticMTRoute           0.20000    smppc(INX)                                       <T> 

**filter:**
#Filter id        Type                   Routes Description                     
#Filter           TransparentFilter      MO MT  <T> 

**user:**
username AireNet
mt_messaging_cred defaultvalue src_addr None
mt_messaging_cred quota http_throughput ND
mt_messaging_cred quota balance ND
mt_messaging_cred quota smpps_throughput 10.0
mt_messaging_cred quota sms_count ND
mt_messaging_cred quota early_percent ND
mt_messaging_cred valuefilter priority ^[0-3]$
mt_messaging_cred valuefilter content .*
mt_messaging_cred valuefilter src_addr XXXXXX (IP I use to my SMPP server)
mt_messaging_cred valuefilter dst_addr XXXXXX (IP that uses my SMScenter, public)
mt_messaging_cred valuefilter validity_period ^\d+$
mt_messaging_cred authorization http_send True
mt_messaging_cred authorization http_dlr_method True
mt_messaging_cred authorization http_balance True
mt_messaging_cred authorization smpps_send True
mt_messaging_cred authorization priority True
mt_messaging_cred authorization http_long_content True
mt_messaging_cred authorization src_addr True
mt_messaging_cred authorization dlr_level True
mt_messaging_cred authorization http_rate True
mt_messaging_cred authorization validity_period True
mt_messaging_cred authorization http_bulk False
uid AireNet
smpps_cred quota max_bindings ND
smpps_cred authorization bind True
gid GINX

**message.log jasmin**

2017-05-26 10:39:17 INFO     19916 SMS-MO [cid:DEMO_JSC_INX] [queue-msgid:9b5d0105-2c7b-45c0-9396-760c9cb248d5] [status:ESME_ROK] [prio:LEVEL_0] [validity:None] [from:346XXXXXX] [to:6XXXXXXX [content:'Hl']

**log amqp:**

2017-05-22 09:30:02 INFO     19916 A new queue has been successfully declared [submit.sm.DEMO_JSC_INX]
2017-05-26 15:34:12 INFO     19916 A new queue has been successfully declared [submit.sm.INX]

**Comment by sah-anshu** [comment]
Its Ok, I can help you on this. I am on skype "anshusah" ping me.

**Comment by preciousgeorge** [comment]
hello @sah-anshu i am trying to do something similar but can't seem to be making any head ways, i tried pushing directly to rabbitmq to see it jasmin would pick it up and send but to no avail, could i add you on skype so you could walk me through some things?
