### ISSUE TITLE
AQMP configuration for rest API

### ISSUE THREAD

**Issue by sah-anshu** [jookies/jasmin#584]
Hi,
 I can see the rest api amqp url is given fixed. i can't see any configuration parameter in jasmin.cfg
Am i doing any mistake or there is any other way to do this.

![screen shot 2017-05-29 at 2 48 01 am](https://cloud.githubusercontent.com/assets/9985291/26536061/2005500c-4451-11e7-8a58-e394839c0888.png)

Anshu

**Comment by sah-anshu** [comment]
can we configure broker_url using config jasmin.cfg ?

**Comment by farirat** [comment]
it's not fixed, you can set it through /etc/jasmin

**Comment by sah-anshu** [comment]
Whats paremeter in /etc/jasmin ?

**Comment by sah-anshu** [comment]
kindly advice />
