### ISSUE TITLE
Make it possible to bypass Jasmin router after interceptor returning back a success (ESME_ROK) for smpp connections

### ISSUE THREAD

**Issue by farirat** [jookies/jasmin#589]

**Comment by farirat** [comment]
This feature will make it possible to intercept a submit_sm, return a success (ESME_ROK) status with no further routing, a useful trick to convert submits to delivers for example ..

**Comment by farirat** [comment]
Interceptor is still not passing success return codes for smpp and http

**Comment by sah-anshu** [comment]
is this fixed ?

**Comment by farirat** [comment]
Fixed in branch 0.9rc25 and not release yet in master
