### ISSUE TITLE
Reqest Dlr using smpp client 

### ISSUE THREAD

**Issue by hadibm** [jookies/jasmin#592]
Hello,

I am using the example on your web site for accessing perspective-broker-api and send a msg 
http://jasmin.readthedocs.io/en/latest/faq/developers.html#how-to-directly-access-the-perspective-broker-api

my added code: 
# send msg
        config = SMPPClientConfig(id='DEMO_CONNECTOR')
        opFactory = SMPPOperationFactory(config)
        msg = opFactory.SubmitSM(
            source_addr='00000',
            destination_addr='0000',
            short_message='Dlr3'
                                )

        msg.params['registered_delivery'] = RegisteredDelivery(RegisteredDeliveryReceipt.SMSC_DELIVERY_RECEIPT_REQUESTED)
 
result=yield proxy_smpp.submit_sm(cid="DEMO_CONNECTOR", SubmitSmPDU=msg )

My question is how can I request DLR and specify the parameters  dlr-level , dlr-url , dlr-method similar to the http api???

Regards,

**Comment by farirat** [comment]
Here you go: https://github.com/jookies/jasmin/blob/master/jasmin/protocols/http/server.py#L328

**Comment by hadibm** [comment]
Thank you very much for your replay.
Previously I tried to use the SMPPClientManagerPBProxy ,  and I couldn't assign the parameters dlr-level , dlr-url , dlr-method 
. 
Now I am trying to use the SMPPClientManagerPB and I am getting the following error :
2017-06-17 10:47:32 DEBUG    8432 Adding a new connector DEMO_CONNECTOR
2017-06-17 10:47:32 DEBUG    8432 getConnector [DEMO_CONNECTOR] returned None
2017-06-17 10:47:32 ERROR    8432 AMQP Broker is not added
2017-06-17 10:47:32 DEBUG    8432 Starting connector [DEMO_CONNECTOR]
2017-06-17 10:47:32 DEBUG    8432 getConnector [DEMO_CONNECTOR] returned None
2017-06-17 10:47:32 ERROR    8432 Trying to start a connector with an unknown cid: DEMO_CONNECTOR
2017-06-17 10:47:32 DEBUG    8432 Enqueuing a SUBMIT_SM to connector [DEMO_CONNECTOR]
2017-06-17 10:47:32 DEBUG    8432 getConnector [DEMO_CONNECTOR] returned None
2017-06-17 10:47:32 ERROR    8432 Trying to enqueue a SUBMIT_SM to a connector with an unknown cid: DEMO_CONNECTOR

Regards,
Here is my code:
@defer.inlineCallbacks
def runScenario():
    try:
        LOG_CATEGORY = "jasmin-pb-client-mgmt"

        proxy_smpp = SMPPClientManagerPB()


        proxy_smpp.log=logging.getLogger(LOG_CATEGORY)

        log = logging.getLogger(LOG_CATEGORY)
        if len(log.handlers) != 1:
            log.setLevel(1)
            handler = TimedRotatingFileHandler(filename='/home/osboxes/hd/service-smppclients.log', when='W6')
            formatter = logging.Formatter('%(asctime)s %(levelname)-8s %(process)d %(message)s', '%Y-%m-%d %H:%M:%S')
            handler.setFormatter(formatter)
            log.addHandler(handler)
            log.propagate = False

        connector1 = {'id': 'DEMO_CONNECTOR','cid': 'DEMO_CONNECTOR', 'host': ' ', 'port': 9080, 'username': 'user',
                      'password': 'pass', 'reconnectOnConnectionFailure': True}
        #config1 = SMPPClientConfig(**connector1)
        SMPPClientConfigInstance = JCliSMPPClientConfig(**connector1)


        yield proxy_smpp.perspective_connector_add(pickle.dumps(SMPPClientConfigInstance, pickle.HIGHEST_PROTOCOL))
        yield proxy_smpp.perspective_connector_start("DEMO_CONNECTOR")
        
        # send msg
        config = SMPPClientConfig(id='DEMO_CONNECTOR')
        opFactory = SMPPOperationFactory(config)

        ss = opFactory.SubmitSM(
            source_addr='0000',
            destination_addr='0000',
            short_message='msg',
        )

        msg.params['registered_delivery'] = RegisteredDelivery(RegisteredDeliveryReceipt.SMSC_DELIVERY_RECEIPT_REQUESTED)


        result=yield proxy_smpp.perspective_submit_sm(cid="DEMO_CONNECTOR", SubmitSmPDU=msg,dlr_url='http://127.0.0.1/hd.php', dlr_level=3,  dlr_method='GET')
        print result

    except Exception, e:
        print "ERROR RUNNING SCENARIO: %s" % str(e)
    finally:
        reactor.stop()
runScenario()
reactor.run()
