### ISSUE TITLE
Documentation website not opening

### ISSUE THREAD

**Issue by sumeetb** [jookies/jasmin#597]
The below website it not opening. 

http://docs.jasminsms.com/en/latest/installation/index.html

Can you please check?

**Comment by farirat** [comment]
The documentation is hosted on readthedocs.org, they're service seems to be down ...

As tweeted: https://twitter.com/readthedocs/status/880372161554202625

You still can generate the docs:

```
  $ git clone https://github.com/jookies/jasmin
  $ cd misc/doc
  $ make html
  ...
  ...
  Build finished. The HTML pages are in build/html.
```

**Comment by sumeetb** [comment]
Ok. Thanks for steps to generate docs :)
