### ISSUE TITLE
SMPP over SSL on server side

### ISSUE THREAD

**Issue by KyuAlex** [jookies/jasmin#598]
Hi,

I think SSL is not supported so I make a feature request.

Thank you by advance!

**Comment by farirat** [comment]
Hey @KyuAlex 

SSL is implemented through smpp.twisted project (on which relies jasmin), it's not covered by any unit tests and from what i can know it's not used by user, long story short: make your testings :)

Usually we use smpp over vpn tunnels, so smpp stays clear and not encoded.

**Comment by KyuAlex** [comment]
Hi,

Is it the following part which need to change?

https://github.com/jookies/jasmin/blob/577a156ae42a684d038118df18edb2a8f298eb39/jasmin/bin/jasmind.py
# Add service
  | self.components['smpps-pb-server'] = reactor.listenTCP(
  | SMPPServerPBConfigInstance.port,
  | pb.PBServerFactory(jPBPortalRoot),
  | interface=SMPPServerPBConfigInstance.bind)


The following part need to be used to listen SSL instead of clear text right?
    factory = Factory()
    factory.protocol = Echo
    reactor.listenSSL(8000, factory,
                      ssl.DefaultOpenSSLContextFactory(
            'keys/server.key', 'keys/server.crt'))
    reactor.run()

**Comment by farirat** [comment]
Theoretically yes, needs to be tested in real world.

**Comment by laurieodgers** [comment]
Was this ever solved? I note it is still open. SMPPS server is something I'm looking for at the moment.

**Comment by farirat** [comment]
Do not put ssl into jasmin, keep your traffic in clear while on your premise, put ssl only on your network edge, use haproxy for example: https://serversforhackers.com/c/using-ssl-certificates-with-haproxy
