### ISSUE TITLE
Got a DLR for an unknown message id 

### ISSUE THREAD

**Issue by sah-anshu** [jookies/jasmin#599]
Hi,
I have found one problem. There are 2 similar SMPP with SAME Credentials to achieve better sending speed. I sent SMS from connection 1 but the uplink Sent me DLR thro' connection 2. 

In this senario jasmin gives the error.  Please advice.

Logs
===
root@instance-1:/var/log/jasmin# grep "3107071515352900930" ./ -r

./default-v_trans1.log:short_message: 'id:3107071515352900930 sub:001 dlvrd:001 submit date:1707151735 done date:1707151750 stat:EXPIRED err:0032 text:Test Message'

./default-v_trans2.log:message_id: '3107071515352900930'

./messages.log:2017-07-15 15:35:29 INFO     2428 SMS-MT [cid:v_trans2] [queue-msgid:f5867be3-cee0-4114-8505-2d6dcd38422a] [smpp-msgid:3107071515352900930] [status:ESME_ROK] [prio:0] [dlr:SMSC_DELIVERY_RECEIPT_REQUESTED] [validity:none] [from:XXXXXX] [to:91XXXXXXXXX] [content:'Test Message']

./messages.log:2017-07-15 15:50:32 ERROR    537 [msgid:3107071515352900930] (retrials: 1/2) DLRMapNotFound: Got a DLR for an unknown message id: 3107071515352900930 (coded:3107071515352900930)

./messages.log:2017-07-15 15:50:42 ERROR    537 [msgid:3107071515352900930] (final) DLRMapNotFound: Got a DLR for an unknown message id: 3107071515352900930 (coded:3107071515352900930)

**Comment by farirat** [comment]
Are you using 2 jasmin instances ? or 2 connector inside 1 jasmin instance ?

If case case #1, then give your connectors the same cid, if case #2 then you cant manage DLRs coming on another connector because the mapping takes the cid as a parameter.

**Comment by sah-anshu** [comment]
Ok. I understood this.  I am using 2 connectors inside 1 jasmin Instance. 

But like kannel, can we make multiple sessions of same smpp connector to achieve more sending speed to uplink.  ?

**Comment by fpalamour** [comment]
Would have loved to have an answer. I'm facing the same issue right now.

**Comment by farirat** [comment]
Unfortunately i dont have a complete understanding of the issue, please describe it with more details of your deployment and callflow.

tcp traces are of a great help as well

**Comment by fpalamour** [comment]
I'll answer on https://github.com/jookies/jasmin/issues/789
