### ISSUE TITLE
Billing when SMS-MT status is RINVDSTADR

### ISSUE THREAD

**Issue by TBorgert** [jookies/jasmin#603]
Hi!

I was doing a stress test on my Jasmin server sending SMS-MT to invalid numbers and verified that my user's balance is decremented. 

My endpoint (Infobip) does not charge me for the returned messages with error. Is there any way to prevent billing if delivery errors are returned?

Please, can you help me?

**Comment by farirat** [comment]
You may check if async billing is your way to do ..

**Comment by TBorgert** [comment]
I've tried different combinations of this setting without success, always being charged.

**Comment by TBorgert** [comment]
I checked before asking. The user is charged in any way, setting async billing with ND(None) or 1% ..100% ..

**Comment by farirat** [comment]
Can you provide a trace where i can see downstream and upstream submits with their respective resps ?

**Comment by TBorgert** [comment]
Please find file attached.

Thank you very much.

[Jasmin.zip](https://github.com/jookies/jasmin/files/1201539/Jasmin.zip)

**Comment by farirat** [comment]
Checking your traces and the documentation here: http://docs.jasminsms.com/en/latest/billing/index.html#billing-call-flow-async

It seems to be a "work as designed", the second portion gets charged on submit_sm_resp without caring about the status, it follows this simple logic: **if message were routed somewhere then charge the user** ...

You still can update the logic yourself by digging in Jasmin's codebase, you can also make a request for commercial change from support@jasminsms.com.
