### ISSUE TITLE
Async Mode Window Size

### ISSUE THREAD

**Issue by aneesio** [jookies/jasmin#611]
Hello,
Could someone please help me in configuring window size please? I want to change the default window size to 1. i.e changing Async mode to Sync mode.

Thanks in advance

**Comment by KamuiX** [comment]
An old threat but hopefully someone will find it helpfull even after more than 3 years. 
One operator also shared their configuration and they ask from our side to set the parameter
"Window size"

I do not see any parameter  with a name like this to smppcm. Is it available in Jasmin and what is the name of it?

**Comment by aneesio** [comment]
@KamuiX I somehow missed your comment. We never found any solution, and I've changed jobs since then.
