### ISSUE TITLE
size does not match expected

### ISSUE THREAD

**Issue by rrickardt** [jookies/jasmin#614]
When user send for example 3 segment SAR message over SMPP, delivery fails. Error is simmilar to all segments, this is segment no.3 In messages.log:

for last segment
CRITICAL 2639 Rejecting SubmitSmPDU[8f996302-637d-4e62-8f71-9467baa89793] through [cid:upstream-tx] for an unknown error (<type 'exceptions.ValueError'>): Value (123 012345678 012340123 012345678901 0123450123 012345678 0) size 59 does not match expected 1

I am not able to find error in PDU of last segment:

2017-08-28 07:56:00 DEBUG    2639 Complete PDU dump: PDU [command: submit_sm, sequence_number: 260370, command_status: ESME_ROK
service_type: ''
source_addr_ton: EnumValue(<jasmin.vendor.enum.Enum object at 0x13f4810>, 5, 'ALPHANUMERIC')
source_addr_npi: EnumValue(<jasmin.vendor.enum.Enum object at 0x13f4d10>, 4, 'UNKNOWN')
source_addr: 'Source'
dest_addr_ton: EnumValue(<jasmin.vendor.enum.Enum object at 0x13f4810>, 6, 'INTERNATIONAL')
dest_addr_npi: EnumValue(<jasmin.vendor.enum.Enum object at 0x13f4d10>, 9, 'ISDN')
destination_addr: '111222233316'
esm_class: EsmClass[mode: DEFAULT, type: DEFAULT, gsmFeatures: set([])]
protocol_id: 0
priority_flag: EnumValue(<jasmin.vendor.enum.Enum object at 0x13f4f10>, 0, 'LEVEL_0')
schedule_delivery_time: None
validity_period: datetime.datetime(2017, 8, 31, 7, 55, 7, tzinfo=<jasmin.vendor.smpp.pdu.smpp_time.FixedOffset object at 0x2df6050>)
registered_delivery: RegisteredDelivery[receipt: SMSC_DELIVERY_RECEIPT_REQUESTED, smeOriginatedAcks: set([]), intermediateNotification: False]
replace_if_present_flag: EnumValue(<jasmin.vendor.enum.Enum object at 0x1402210>, 0, 'DO_NOT_REPLACE')
data_coding: DataCoding[scheme: DEFAULT, schemeData: SMSC_DEFAULT_ALPHABET]
sm_default_msg_id: 0
short_message: ''
sar_total_segments: 3
sar_msg_ref_num: 2
sar_segment_seqnum: 3
message_payload: ''123 012345678 012340123 012345678901 0123450123 012345678 0
more_messages_to_send: EnumValue(<jasmin.vendor.enum.Enum object at 0x13f5990>, 1, 'MORE_MESSAGES')
]

**Comment by farirat** [comment]
Hey @rrickardt 

Is this on smppc or smpps side ? do you have a pcap trace ?

**Comment by rrickardt** [comment]
This debug is from jasmin smpps. I have debug from all 3 segments, presently no pcap trace, but i can attach it later today.

**Comment by rrickardt** [comment]
Please find attached zipped pcap.

[datasys.zip](https://github.com/jookies/jasmin/files/1260093/datasys.zip)

**Comment by rrickardt** [comment]
Closing it. This looks like upstream SMSC is not supporting message_payload TLV.
