### ISSUE TITLE
Unable to Send Special Charcters through Smpp Client

### ISSUE THREAD

**Issue by satyags** [jookies/jasmin#618]
Hello,
   Please suggest me in following problem. 

  we are sending an SMS through SMPP Client and unable to send '@' symbol. .ie ASCII characters.  we done the  [fix](
https://github.com/jookies/jasmin/pull/540/commits/a8b653275cd8a7c05db83e84bf9cfa2971d085f9) to jasmin server. still we are getting ? in place of @ and [].

Operator wants to send the message in ASCII encoding.

Please suggest us to solve the issue. 
Thanks in advance..

**Comment by farirat** [comment]
@satyags Jasmin does not alter your sms content nor sms headers when you push in smpp, you can check that by comparing tcp traces from input/output on jasmin node.

Your issue is outside of Jasmin, check your smpp client.

**Comment by satyags** [comment]
Hello,

  Is it possible to change the encoding in Jasmin to operator connection.
If possible please suggest me how to change .

Thanks in advance.

-------------------------------------------

Thanks & Regards,
SG Satyakishore Garapati,
Python Devloper


*Contact: *+91-9985111878

*Email*: satya.g@iton.com | *website*: www.iton.com
This e-mail and any attachments to it are confidential and intended for the
use of the addressee. If you are not the intended recipient you must not
use, disclose, read, forward, copy or retain any of the information. If you
received this e-mail in error, please delete it and notify the sender by
return e-mail or telephone.
