### ISSUE TITLE
submit.sm.resp.CONNECTOR is not consumed

### ISSUE THREAD

**Issue by ivanrvpereira** [jookies/jasmin#62]
Hi,

I'm a django developer and new to this promising project. And also new to smpp protocol world. 

I started using jasmin today for sms marketing purposes, and now i'm already able to send messages through clickatell smpp using jasmin. But i only got this message status `message_status=ESME_ROK`. I think this status tells me that message arrived clickatell smsc, but i want also the delivery status of messages. When a message is sent with wrong number, i get an unparsable PDU on default.CONNECTOR.log. Also i see that submit.sm.resp.CONNECTOR queue on Rabbitmq is not consumed.

Can you please help me to figure where i should look?

**Comment by fourat** [comment]
Hi,

I&#39;d like to add you to my professional network on LinkedIn.

- Fourat

Accept: https://www.linkedin.com/blink?simpleRedirect=0Rd3AMdPcScjAPejAOdzoOdzARfkh9rCZFt65QqnpKqipdhl1vc49zhzRVpkJApn9xq7cCt7dBtmtvpnhFtCVFfmJB9C5QoORBt6BSrCAJt7dBtmsJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9CcObj5WpmZQczlFbmFEpjlBr3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5962663023184211968_500&markAsRead=


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=oP8JcnFBrTgOdmAJqCxBdmlIfmhFpipdrm5yoSZ3m30MjBAPrS9kcBwThTFAnTcOj4F4e4FNuBcRuB1ygBxoh2RVoQlzgRlvcj9DsAwPp5sTrT5UtQEJhmlLdjhjglsQkRAVlTgUqztBlnlysSV7cAh1tSR7hApiqSgJcP98kTxLuzBMiPxHkn1vk6Rlh4tQpmxLmkoVs4NDt71GcDgVlSpejndBqiROlk51gl5IuBETkTxxslhFhB51fmhFrSMCt7dBtmtvpnhFtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9CcObj5WpmZQczlFbmFEpjlBr3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5962663023184211968_500&amp;markAsRead= Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ct7dBtmtvpnhFtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9CcObj5WpmZQczlFbmFEpjlBr3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5962663023184211968_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by tarikogut** [comment]
added


2015-01-18 21:34 GMT+02:00 Fourat ZOUARI <notifications@github.com>:
