### ISSUE TITLE
Mail to SMS

### ISSUE THREAD

**Issue by pizu** [jookies/jasmin#620]
Hi,

I would like to know if mail to sms is supported.

Example: mobilenumber@system.subdomain.domain.com

Thanks,
David

**Comment by farirat** [comment]
Hey @pizu,

This requires a custom integration with Jasmin, you can drop us a line to support@jasminsms.com for enterprise services.

**Comment by tarikogut** [comment]
you can do with postfix mail server


2017-10-06 14:16 GMT+03:00 The Z <notifications@github.com>:

**Comment by pizu** [comment]
how? :) I cannot find anything that connects with the smpp.

**Comment by tarikogut** [comment]
http://chopey.blogspot.com.tr/2006/12/e-mail-to-sms-email2sms.html

2017-10-06 15:46 GMT+03:00 pizu <notifications@github.com>:
