### ISSUE TITLE
messages.log - log rotation does not work as expected

### ISSUE THREAD

**Issue by raamtg** [jookies/jasmin#622]
Hi, I noticed after upgrading to v0.9.25 that the messages.log does not rotate properly. Exactly at midnight GMT, when the file is rotated, both the messages.log and the messages.log.yyyy-mm-dd are being written to at the same time. the one with the date back up only has SMS-MT being written to it, and messages.log contains everything except SMS-MT messages e.g. DLR's.

This only happens with messages.log. All other log files rotate properly.

Temporary solution is to restart docker every day at midnight GMT :-(

**Version**
[root@820671-web jasmincore]# docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
[root@820671-web jasmincore]# 

root@bd8e248cb4fc:/# python
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import jasmin;print jasmin.get_release();
0.9.25

**Logs**

-rw-r--r-- 1 root root   854922 Oct  9 18:59 default-1_TG_DGC1729.log.2017-10-09
-rw-r--r-- 1 root root    21415 Oct  9 19:01 smppclient-manager.log
-rw-r--r-- 1 root root  1067139 Oct  9 19:10 jcli.log
-rw-r--r-- 1 root root    30226 Oct  9 **19:10 messages.log**
-rw-r--r-- 1 root root    24832 Oct  9 19:10 default-1_TG_DGC1685.log
-rw-r--r-- 1 root root    24832 Oct  9 19:10 default-1_TG_DGC1729.log
-rw-r--r-- 1 root root  3097164 Oct  9 19:10 dlr-thrower.log
-rw-r--r-- 1 root root  2698253 Oct  9 19:10 router.log
-rw-r--r-- 1 root root   149381 Oct  9 19:10 default-TG_SMPPServer_01.log
-rw-r--r-- 1 root root    86412 Oct  9 **19:10 messages.log.2017-10-09**

**Comment by farirat** [comment]
Hey @raamtg this were reported even before 0.9.25 and with all rotated logs.

Can be an issue with the timerotator, have to confirm this.

**Comment by farirat** [comment]
Close in 0.9.26 through #629
