### ISSUE TITLE
Validity period parameter transmited only in first submit_sm when message is long.

### ISSUE THREAD

**Issue by demos98** [jookies/jasmin#623]
Hi, when i use http ip parameter "validity-period" for MT, and message is long, validity period parameter transmited only in first submit_sm. Is there any solution to fix it? Thx.

**Comment by farirat** [comment]
Hi @demos98, i'll try to reproduce the scenario to confirm if it's a bug.

**Comment by demos98** [comment]
Hi Thank you for infomation.
