### ISSUE TITLE
Include mysql libraries in Docker File please

### ISSUE THREAD

**Issue by raamtg** [jookies/jasmin#624]
Hi, in order to use sms_logger.py or any other AMQP consumer to log messages in DB, we need to run the following commands within docker

docker exec -it mycontainer /bin/bash
apt-get update
apt-get install libmysqlclient-dev
pip install MySQL-python

Can we include this as part of the DockerFile so we have the mysql connector available to us out of the box?

**Comment by tarikogut** [comment]
install mysql in docker and test it

**Comment by raamtg** [comment]
I have, and I know it works. I am just recommending that we include this in the DockerFile to make it more of an "out of the box" solution.

**Comment by tarikogut** [comment]
you use SQL Alcamy

**Comment by raamtg** [comment]
maybe there is a misunderstanding. I am just trying to run sms_logger.py within Docker. I got it to work, but had to install the mysql dependencies within docker myself. I figured it would be useful for others in the future if these dependencies were included as part of the standard Jasmin Docker distribution as users would need to be able to write data to mysql anyway.

**Comment by tarikogut** [comment]
sudo apt-get install python-pip python-dev libmysqlclient-dev



2017-10-15 18:03 GMT+03:00 Raam <notifications@github.com>:

**Comment by farirat** [comment]
Sms logger can run anywhere and not only in the same container with jasmin, so there's no reason to add extra nonused libs out of the box.

You still can customize dockerfile for your custom project, just extend the one coming from jookies/jasmin.

**Comment by raamtg** [comment]
ok fair enough. I have just scripted it such that at the start of the container, i execute this command:

`apt-get update;apt-get -y install python-mysqldb`

and i'm good to go. Thanks for the help guys.

This issue can be closed.

Raam
