### ISSUE TITLE
Make the message id generation customizable through pluggable code

### ISSUE THREAD

**Issue by farirat** [jookies/jasmin#627]
Through this plugin, Jasmin will return different msgid format than the usual uuid4.

**Comment by farirat** [comment]
it is now possible to make custom message ids through installing/overloading this simple plugin:

https://github.com/jookies/jasmin-plugins/tree/master/msgidPlugin

Message id is generated here: https://github.com/jookies/jasmin-plugins/blob/master/msgidPlugin/msgid_plugin/__init__.py

**Comment by sah-anshu** [comment]
How to Implement plugins. pl advice

**Comment by farirat** [comment]
This is a simple plugin: https://github.com/jookies/jasmin-plugins/tree/master/msgidPlugin

**Fork** it, **clone** it and **python setup.py install** it

Jasmin will discover the new plugin on the system and will call it's **msgid_plugin. get_random_unique_msgid_plugin()** method to get a message id.
