### ISSUE TITLE
NameError JasminTask jasmin-restapi

### ISSUE THREAD

**Issue by jjtovarl** [jookies/jasmin#633]
(venv) root@ubuntu:~/jasmin# systemctl status jasmin-restapi
● jasmin-restapi.service - Jasmin SMS Restful API server
   Loaded: loaded (/lib/systemd/system/jasmin-restapi.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since jue 2017-11-02 02:06:43 CST; 8h ago
  Process: 3809 ExecStart=/bin/sh -c twistd -n --pidfile=/tmp/twistd-web-restapi.pid web --wsgi=jasmin.protocols.rest.api (code=exited, status=1/FAILURE)
 Main PID: 3809 (code=exited, status=1/FAILURE)

nov 02 02:06:43 ubuntu jasmin-restapi[3809]:   File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 199, in __new__
nov 02 02:06:43 ubuntu jasmin-restapi[3809]:     tasks.register(new(cls, name, bases, attrs))
nov 02 02:06:43 ubuntu jasmin-restapi[3809]:   File "/usr/lib/python2.7/dist-packages/celery/app/registry.py", line 35, in register
nov 02 02:06:43 ubuntu jasmin-restapi[3809]:     self[task.name] = inspect.isclass(task) and task() or task
nov 02 02:06:43 ubuntu jasmin-restapi[3809]:   File "/usr/lib/python2.7/dist-packages/jasmin/protocols/rest/tasks.py", line 24, in __init__
nov 02 02:06:43 ubuntu jasmin-restapi[3809]:     super(JasminTask, self).__init__()
nov 02 02:06:43 ubuntu jasmin-restapi[3809]: NameError: global name 'JasminTask' is not defined
nov 02 02:06:43 ubuntu systemd[1]: jasmin-restapi.service: Main process exited, code=exited, status=1/FAILURE
nov 02 02:06:43 ubuntu systemd[1]: jasmin-restapi.service: Unit entered failed state.
nov 02 02:06:43 ubuntu systemd[1]: jasmin-restapi.service: Failed with result 'exit-code'.
(venv) root@ubuntu:~/jasmin# 

(venv) root@ubuntu:~/jasmin# systemctl status jasmin-celery
● jasmin-celery.service - Jasmin Celery server
   Loaded: loaded (/lib/systemd/system/jasmin-celery.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since jue 2017-11-02 02:06:43 CST; 8h ago
  Process: 3808 ExecStart=/bin/sh -c celery -A jasmin.protocols.rest.tasks worker -l info -c 4 --autoscale=10,3 (code=exited, status=1/FAILURE)
 Main PID: 3808 (code=exited, status=1/FAILURE)

nov 02 02:06:43 ubuntu jasmin-celery[3808]:   File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 199, in __new__
nov 02 02:06:43 ubuntu jasmin-celery[3808]:     tasks.register(new(cls, name, bases, attrs))
nov 02 02:06:43 ubuntu jasmin-celery[3808]:   File "/usr/lib/python2.7/dist-packages/celery/app/registry.py", line 35, in register
nov 02 02:06:43 ubuntu jasmin-celery[3808]:     self[task.name] = inspect.isclass(task) and task() or task
nov 02 02:06:43 ubuntu jasmin-celery[3808]:   File "/usr/lib/python2.7/dist-packages/jasmin/protocols/rest/tasks.py", line 24, in __init__
nov 02 02:06:43 ubuntu jasmin-celery[3808]:     super(JasminTask, self).__init__()
nov 02 02:06:43 ubuntu jasmin-celery[3808]: NameError: global name 'JasminTask' is not defined
nov 02 02:06:43 ubuntu systemd[1]: jasmin-celery.service: Main process exited, code=exited, status=1/FAILURE
nov 02 02:06:43 ubuntu systemd[1]: jasmin-celery.service: Unit entered failed state.
nov 02 02:06:43 ubuntu systemd[1]: jasmin-celery.service: Failed with result 'exit-code'.
(venv) root@ubuntu:~/jasmin# 

(venv) root@ubuntu:~/jasmin# pip install celery --upgrade
Requirement already up-to-date: celery in ./venv/lib/python2.7/site-packages
Requirement already up-to-date: billiard<3.6.0,>=3.5.0.2 in ./venv/lib/python2.7/site-packages (from celery)
Requirement already up-to-date: pytz>dev in ./venv/lib/python2.7/site-packages (from celery)
Requirement already up-to-date: kombu<5.0,>=4.0.2 in ./venv/lib/python2.7/site-packages (from celery)
Requirement already up-to-date: amqp<3.0,>=2.1.4 in ./venv/lib/python2.7/site-packages (from kombu<5.0,>=4.0.2->celery)
Requirement already up-to-date: vine>=1.1.3 in ./venv/lib/python2.7/site-packages (from amqp<3.0,>=2.1.4->kombu<5.0,>=4.0.2->celery)
(venv) root@ubuntu:~/jasmin#

**Comment by farirat** [comment]
Duplicate to #628 

Fix coming in next release.

**Comment by jjtovarl** [comment]
Thanks @farirat

**Comment by kirosen** [comment]
Is there any solution for this problem?
