### ISSUE TITLE
Error "InterceptorPB not set !"

### ISSUE THREAD

**Issue by jjtovarl** [jookies/jasmin#634]
Help
Sending a SMS
http://xxx.xx.xxx.xxx:1401/send?username=pruebas&password=pruebas&to=123456789&content=hello
Error "InterceptorPB not set !"

**Comment by farirat** [comment]
You have to enable Interceptor as described in the documentation

**Comment by jjtovarl** [comment]
Thank @farirat 
Jasmin's interceptor is running.
![runinterceptor](https://user-images.githubusercontent.com/8610590/32704983-2096763e-c7d4-11e7-9777-4c3d1508cca2.png)

and nothing

**Comment by jjtovarl** [comment]
Error enable communication between jasmind and interceptord services by editing jasmind.service file not locate in (/etc/systemd) file locate in (/lib/systemd/system)
Help

**Comment by jjtovarl** [comment]
I found the problem, 
File: jasmin.service
[Unit]
Description=Jasmin SMS Gateway
Requires=network.target jasmin-interceptord.service jasmin-dlrd.service jasmin-dlrlookupd.service
After=network.target

[Service]
SyslogIdentifier=jasmind
PIDFile=/var/run/jasmind.pid
ExecStart=/usr/bin/jasmind.py --username jcliadmin --password jclipwd --enable-interceptor-client

deleted user and group.
