### ISSUE TITLE
Using 0.9.26 - I found execption in messages.log

### ISSUE THREAD

**Issue by sah-anshu** [jookies/jasmin#635]
Hi

2017-11-18 07:20:28 CRITICAL 7526 Got an unknown exception (<type 'exceptions.TypeError'>): <lambda>() takes exactly 2 arguments (0 given)

-
Anshu

**Comment by farirat** [comment]
Version ? any data to reproduce it ?

**Comment by sah-anshu** [comment]
Yes - I was using v 0.9.25 and installed 0.9.26 and restarted jasmin & it crashed.

**Comment by farirat** [comment]
It can be a configuration migration problem, what kind of config do you have actually persisted ?
