### ISSUE TITLE
TLV Support doubt

### ISSUE THREAD

**Issue by umesh936** [jookies/jasmin#642]
Hi I have to add some tlv parameter in sending MT. Does Jasmin have TLV support? if so then ho can i add those parameter. If not, is there any work around of it ?

**Comment by farirat** [comment]
hey @umesh936 

You cant inject TLV through the standard API, this is not support by Jasmin.

**Comment by umesh936** [comment]
hi Farirat, Thanks for this information, Is there any way around to inject TLV parameters.
