### ISSUE TITLE
Rest API sendbatch does not support hex_content

### ISSUE THREAD

**Issue by Eudorajab1** [jookies/jasmin#644]
Hi there,

I have issues using secure/sendbatch part of the rest api. Arabic characters go through fine on the secure/ send but not on the /sendbatch. I have tested using same message contenet on both and checked that the right hex_content is being passed to both. Send works fine but sendbatch does not

**Comment by farirat** [comment]
Hey @Eudorajab1 

Please attach both json contents to reproduce the issue.
