### ISSUE TITLE
How to set TON and NPI using the interceptor?

### ISSUE THREAD

**Issue by mrsanvicente** [jookies/jasmin#647]
Hello
 i am looking  how to set the TON and NPI  while updating PDU values within interceptor?
SIMILar as updating the destination address:

 routable.pdu.params['destination_addr'] = number 

Can you please help me?

Thank you very much.

Can you please help me?

Thank you very much.

**Comment by farirat** [comment]
Check this: https://github.com/jookies/jasmin/blob/master/jasmin/protocols/smpp/test/test_pdu_encoding.py#L293

That's a way of setting ton/npi inside a pdu, same can be used inside an interceptor

**Comment by mrsanvicente** [comment]
Thank you farirat.
