### ISSUE TITLE
docker build failed for jasmin 0.9.27 @ Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64

### ISSUE THREAD

**Issue by sah-anshu** [jookies/jasmin#649]
fyi:

Setting up supervisor (3.0r1-1+deb8u1) ...
invoke-rc.d: policy-rc.d denied execution of start.
Processing triggers for systemd (215-17+deb8u7) ...
Processing triggers for libc-bin (2.19-18+deb8u10) ...
Processing triggers for ca-certificates (20141019+deb8u3) ...
Updating certificates in /etc/ssl/certs... 0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....done.
Processing triggers for python-support (1.0.15) ...
Removing intermediate container ea7170545c5a
 ---> 76d2989dcf9e
Step 6/12 : RUN mkdir -p /etc/jasmin/resource     /etc/jasmin/store     /var/log/jasmin   && chown jasmin:jasmin /etc/jasmin/store     /var/log/jasmin   && pip install --pre jasmin=="$JASMIN_VERSION"
 ---> Running in 67d923f76981
Downloading/unpacking jasmin==0.9.27
  Could not find a version that satisfies the requirement jasmin==0.9.27 (from versions: 0.6b35, 0.6b27, 0.9b13, 0.9b9, 0.6b26, 0.6b8, 0.9.25, 0.9b15, 0.6b15, 0.8b1, 0.8b2, 0.9rc22, 0.9rc24, 0.9rc16, 0.8b6, 0.6b9, 0.6b1, 0.6b25, 0.6b28, 0.8rc9, 0.6rc41, 0.6b33, 0.6, 0.6b16, 0.9b2, 0.8b4, 0.8.post11, 0.9b0, 0.9b11, 0.8b3, 0.6b32, 0.6b7, 0.9b10, 0.9rc23, 0.9b7, 0.6b14, 0.8b7, 0.6rc40, 0.6b6, 0.9b5, 0.9b3, 0.8.post14, 0.8b8, 0.9rc18, 0.8.10, 0.6b5, 0.8.dev0, 0.8.post12, 0.6b38, 0.9b12, 0.9rc21, 0.6b12, 0.6b11, 0.9b8, 0.6b2, 0.6b34, 0.6b18, 0.9b14, 0.9b1, 0.6b3, 0.9rc20, 0.9rc19, 0.6b36, 0.8.post13, 0.6b19, 0.6b4, 0.9.26, 0.9rc17, 0.8b5, 0.6b24, 0.6b13, 0.6b17, 0.6b37, 0.7b0, 0.9b4, 0.6b10, 0.6.post43, 0.6b39)
Cleaning up...
No distributions matching the version for jasmin==0.9.27
Storing debug log for failure in /root/.pip/pip.log
The command '/bin/sh -c mkdir -p /etc/jasmin/resource     /etc/jasmin/store     /var/log/jasmin   && chown jasmin:jasmin /etc/jasmin/store     /var/log/jasmin   && pip install --pre jasmin=="$JASMIN_VERSION"' returned a non-zero code: 1

Anshu S.

**Comment by farirat** [comment]
The master branch is still pointed on 0.9.26.

0.9.27 is still not released

**Comment by sah-anshu** [comment]
when you are planning to release 0.9.27

**Comment by farirat** [comment]
I'm waiting for txamqp to move to 0.8.2, ref: https://github.com/txamqp/txamqp/pull/7

**Comment by sah-anshu** [comment]
""Done https://pypi.python.org/pypi/txAMQP/0.8.2 ""
