### ISSUE TITLE
Asterisk connector

### ISSUE THREAD

**Issue by support4net** [jookies/jasmin#652]
I would like to know if there's a way to interact Jasmin with asterisk acting as SMS gateway used in this projects: 
http://www.raspberry-asterisk.org
https://github.com/tangaza/Tangaza/wiki/Connecting-a-GoIP-GSM-VoIP-gateway-to-an-Asterisk-AGI

**Comment by sah-anshu** [comment]
@support4net Use PHP AGI and HTTP Api of Jasmin to send sms.
