### ISSUE TITLE
Expose setQuota in HTTP API

### ISSUE THREAD

**Issue by mexicarne** [jookies/jasmin#653]
Hello, 

I need the possibility to reset quota value via HTTP API and as far I understand it cannot be done in current version of code. There is `user_update_quota `method in `RouterPBProxy` object, but it increments supplied value instead of resetting it. 

I'm going to implement that behavior and wanna ask how to do that better?
a) expose PB's `setQuota` method via HTTP API
b) pass an extra parameter (replace=False by default) to `updateQuota` to allow completely replace the old value

I personally prefer the second solution.
Thanks

**Comment by farirat** [comment]
You can expose PB method on http api, or just use a telnet jcli wrapper like this one: https://github.com/jookies/jasmin-api (unmaintained)

**Comment by mexicarne** [comment]
May I close that?

**Comment by farirat** [comment]
Will be exposed in 0.9.28, issue closed, thx @mexicarne !
