### ISSUE TITLE
Getting UnicodeDecodeError error smpp-server-pb.log file

### ISSUE THREAD

**Issue by sumeetb** [jookies/jasmin#655]
I have deployed latest version of Jasmin gateway but i am getting below error. I was not getting this error in old version. Error is from smpp-server-pb.log log file. I am using [smpp-server]. Coding is set to 0 in smppccm

ERROR    1181 Caught an error while trying to push pdu through deliverer (system_id:test-1): (UnicodeDecodeError) 'ascii' codec can't decode byte 0xcd in position 3: ordinal not in range(128)

**Comment by farirat** [comment]
@sumeetb which version please ?

**Comment by sumeetb** [comment]
@farirat I think its 0.9.26. I followed the instruction from here -> http://docs.jasminsms.com/en/latest/installation/index.html. I have deployed on Ubuntu.

**Comment by farirat** [comment]
Can you provide steps-to-reproduce procedure ?

**Comment by sumeetb** [comment]
@farirat Please see below steps.
Steps:
1. Deploy latest version 0.9.26
2. Enable [smpp-server] in jasmin.cfg and start jasmin gateway, it will start jasmin, dlrd , dlrlookupd
3. Create user, group, user filter, SMPPC connector (This will be used to connect to SMPP simulator acting as SMSC) and MTRouter
4. Send SMS from client over smpp-server ip and port
5. Message is getting forwarded to SMPP Simulator.
6. When simulator is sending back DLR, error is thrown in smpp-server-pb.log
7. DLR is not getting back to client.

**Comment by sumeetb** [comment]
@farirat Please let me know if you need more details. This issue is blocking me to use Jasmin gateway and i have no clue how to resolve this.

**Comment by farirat** [comment]
This is mostly caused by a regression in txamqp library, you must be using txamqp v0.8+

You have two options: degrade txamqp back to v0.7 or catch the new release of 0.9.27 in a couple of days.

**Comment by sumeetb** [comment]
Thanks @farirat. Degrading txamqp back to v0.7 worked :)

**Comment by farirat** [comment]
0.9.27 is released anyway :)

**Comment by sumeetb** [comment]
I will update with 0.9.27 @farirat :) . Thanks for your help!
