### ISSUE TITLE
Decoding of Short Message Reassembled

### ISSUE THREAD

**Issue by mexicarne** [jookies/jasmin#664]
Hello, 

from time to time we are getting SMS-MO with `coding=8`, that cannot be decoded from utf-16-be. The resulting text looks like:

![image](https://user-images.githubusercontent.com/1031992/38133098-675371cc-3416-11e8-8ecb-6ac4ea5d0bc3.png)

These incorrect messages are always going by pairs (two separate messages) and mostly have the same receive timestamp. 

Here is how they are recognized in wireshark:
![image](https://user-images.githubusercontent.com/1031992/38133155-b367aa6a-3416-11e8-9e91-02203f275f2d.png)

Normal `Deliver_sm` decoding works just well, but with `Deliver_sm (Short Message Reassembled)`  there are some decoding issues. 

For example, here is the error I getting from python when trying to decode such a message (content is a value of `content` field from Jasmin http request)

```python
>>> import urllib
>>> content = '%06%08%04%F1F%02%02%04%3D%040%041%04%40%040%042%00+%04%3D%04%3E%04%3C%045%04%40%00+%00%2B%007%009%008%007%001%000%009%008%009%009%002%00.%00+%04%21%00+%047%040%041%04%3E%04B%04%3E%049%00+%04%3E%00+%04%12%040%04A%00%2C%00+%04%1C%04%22%04%21%00.%00%0A'
>>> urllib.unquote_plus(content).decode('utf-16-be')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/encodings/utf_16_be.py", line 16, in decode
    return codecs.utf_16_be_decode(input, errors, True)
UnicodeDecodeError: 'utf16' codec can't decode byte 0x0a in position 104: truncated data
```

Using decode() with 'ignore' argument works, but gives me a gibberish. Is this a Jasmin issue, or upstream smsc issue? I can provide you with pcap dump privately, if you are willing to see it.
Thank you!

**Comment by farirat** [comment]
Hello

Jasmin is transmitting the content **as is**, you may check it by comparing the message content going to jasmin (smpp) and getting out of it (http), you must find the same bytes.

Going to your script, you are decoding the content from utf16 and the error is clear: this content is not utf16 so you cant decode it as utf16, unfortunately smpp does not have anything to indicate the content coding, you need to guess it.

**Comment by mexicarne** [comment]
```python
>>> chardet.detect(urllib.unquote_plus(content))
{'confidence': 0.0, 'language': None, 'encoding': None}
```
So the message has incorrect encoding at all. May you clarify what this reassembled messages are? Is there a way they can be assembled back to something meaningful? Since they are going as pairs at the same time, it's pretty clear that they are parts of single message and I'm trying to understand what should be done to handle them. Thank you!

**Comment by mexicarne** [comment]
```python
>>> chardet.detect(urllib.unquote_plus(content))
{'confidence': 0.0, 'language': None, 'encoding': None}
```
So the message has incorrect encoding at all. May you clarify what this reassembled messages are? Is there a way they can be assembled back to something meaningful? Since they are going as pairs at the same time, it's pretty clear that they are parts of single message and I'm trying to understand what should be done to handle them. Thank you!

**Comment by farirat** [comment]
i dont know the context behind your messaging scenario, but coding is just a way to make raw bytes readable by human beings, if the content is not meant to be humanized then it may be just a raw binary for some application ...

**Comment by mexicarne** [comment]
it's a bug in jasmin related to concatenation of multi-part messages. fixed ourself.
