### ISSUE TITLE
[question] Weighted round robin MT/MO routes

### ISSUE THREAD

**Issue by terrycain** [jookies/jasmin#666]
Was looking at implementing this, thought I'd ask before I go about doing so, is this currently being worked on or am I free to have a crack at it?

**Comment by farirat** [comment]
Hey there,

Currently am working on a smarter routing rule:
- Send to connector A (set as primary)
- If sending failed (no resp or no DLR) then resend to B (secondary)
- If sending failed ... then resend to C (secondary)
- And looping till reaching the last secondary or message sent

This is being a commercial plugin that can be made public if final customer agree on it :)

Still to reply on your question: no active workouts are on the simple/static roundrobin algorithm

**Comment by Swabuu** [comment]
Hello, 

This would indeed be a nifty feature! 

Is still already a commercial plugin? Otherwise I would gladly discuss this specific plugin as well as other available plugins further with you.

**Comment by danielferrer** [comment]
Hi @farirat ,
Any update on this ? Will be made public ?
What about a "weighted connector route " ? I'm willing to implement this, I'll give a try, but maybe someone has done so...

regards

> Hey there,
> 
> Currently am working on a smarter routing rule:
> 
>     * Send to connector A (set as primary)
> 
>     * If sending failed (no resp or no DLR) then resend to B (secondary)
> 
>     * If sending failed ... then resend to C (secondary)
> 
>     * And looping till reaching the last secondary or message sent
> 
> 
> This is being a commercial plugin that can be made public if final customer agree on it :)
> 
> Still to reply on your question: no active workouts are on the simple/static roundrobin algorithm
