### ISSUE TITLE
Bind failed on  smpp-1-ire.smscarrier.com:8011 !

### ISSUE THREAD

**Issue by arkxdns** [jookies/jasmin#667]
Hello,

I have to connect to a server: **smpp-1-ire.smscarrier.com at port 8011,**  I following your instructions but I can not connect, all other configurations and test works :

"  Establishing TCP connection to smpp-1-ire.smscarrier.com:8011
2018-04-10 15:24:06 INFO     11188 Connecting to IPv4Address(TCP, 'smpp-1-ire.smscarrier.com', 8011) ...
2018-04-10 15:24:07 WARNING  11188 SMPP connection established from 52.31.169.62 to port 51982
2018-04-10 15:24:07 INFO     11188 Connection made to smpp-1-ire.smscarrier.com:8011
2018-04-10 15:24:07 WARNING  11188 Requesting bind as transceiver
2018-04-10 15:24:07 ERROR    11188 Bind failed [[Failure instance: Traceback (failure with no frames): <class 'jasmin.vendor.smpp.pdu.error.SMPPTransactionError'>: ESME_RBINDFA$
]]. Disconnecting..."

I tried to change the 2275 listening port in 8011 on jasmin.cfg , nothing...

But this works : 

_ID du système: ****
Mot de passe: ****
Hôte: smsc-sim.smscarrier.com
Port: 2775_

Thanks for any help !

F.B.

**Comment by farirat** [comment]
Username/password anonymized ...

**Comment by farirat** [comment]
I guess you have a ESME_RBINDFAIL error, that's a pdu returned from your provider, this is an issue to investigate with it.

**Comment by sah-anshu** [comment]
Hi

Please check following points with uplink:
 - Whether any IP restriction is there for your account. 
 - Are you allowed to bind as Transmitter/receiver / transreceiver  ( I can see jasmin is binding uplink as transreceiver TRX)

rdgs,
Anshu

**Comment by arkxdns** [comment]
Hi

I tested the connection with NowSMS and it was the same thing until I added these parameters:  

 - System Type: SMPP 
 - SMSC Character Set: IA5 (GSM).

The success was total. Now I have to find these settings on JasminSMS to work, and that's where I need your help again.

Thanks you.

Regards.
Fred.

**Comment by amechax** [comment]
Hi,

Try below settings
- systype smpp -> default value Null
- coding 0 -> default value 0

**Comment by arkxdns** [comment]
Hi,

I put your settings successfully, but the session service does not start, so no connection, I really thought it would succeed.

Thanks.

**Comment by arkxdns** [comment]
I am still convinced that Jasmin can be configured with my service provider, but I do not know all JasminSMS settings, as with [NowSMS](https://www.nowsms.com/) it worked, and that I used for tests, I took a [screenshot of the configuration](http://www.exonet3i.com/img/nowsms-config1.jpg), if someone one can help me find the 2 parameters that are missing, **systype smpp** which is accepted but also maybe **SMSC Character Set** whose value should be: IA5 (GSM).

JasminSMS Gateway is perhaps not compatible with this provider, it would still be extraordinary, given the notoriety of Jasmin.

Anyway, thank you for your help.

**Comment by amechax** [comment]
Hi, I have a connection to smscarrier with below config. Ignore values for [username, port, host, password]

ripf 0
con_fail_delay 10
dlr_expiry 86400
coding 0
logrotate midnight
submit_throughput 1
elink_interval 30
bind_to 30
port 2775
con_fail_retry yes
password visit12
src_addr None
bind_npi 0
addr_range None
dst_ton 1
res_to 120
def_msg_id 0
priority 0
con_loss_retry yes
username smscarrier
dst_npi 1
validity None
requeue_delay 120
host 127.0.0.1
src_npi 1
trx_to 300
logfile //var/log/jasmin/default-smscarrier.log
systype
ssl no
cid smscarrier
loglevel 20
bind transceiver
proto_id None
dlr_msgid 0
con_loss_delay 10
bind_ton 0
pdu_red_to 10
src_ton 2

If the configure is ok, consider previous comment on IP restrictions. Confirm that you can ping and  telnet to IP/port.

**Comment by arkxdns** [comment]
Hello amechax !

It works perfectly, with Docker, I added to the systype parameter: SMPP.

Thanks !
