### ISSUE TITLE
Random UnicodeDecodeError using HTTP API

### ISSUE THREAD

**Issue by maximecaze** [jookies/jasmin#669]
Using HTTP API, I have a 400 http error while sending french accents encoded in UTF-16 through jasmin 0.9.25.

Example : 
String : test with é
Request : `GET /send?username=USER&password=PWD&to=NUMBER&from=FROM&hex-content=007400650073007400200077006900740068002000E9&coding=8 HTTP/1.1`
HTTP return code : 400

In interceptor.log, I can see 
_Executing script on routable (from:FROM, to:NUMBER) returned: <type 'exceptions.UnicodeDecodeError'>: 'utf8' codec can't decode byte 0xe9 in position 21: unexpected end of data_

And it works fine with other strings containing some accentued characters, so I am getting nuts.

Working example :
String : Plus d'infos au + 33 0 00 00 00. No d'urgence 112 gratuit depuis l'étranger, quelle que soit la zone d'émission de l'appel.
Request : `GET /send?username=USER&password=PWD&to=NUMBER&from=FROM&hex-content=0050006C007500730020006400270069006E0066006F00730020006100750020002B00200033003300200030002000300030002000300030002000300030002E0020004E006F0020006400270075007200670065006E0063006500200031003100320020006700720061007400750069007400200064006500700075006900730020006C002700E9007400720061006E006700650072002C0020007100750065006C006C0065002000710075006500200073006F006900740020006C00610020007A006F006E006500200064002700E9006D0069007300730069006F006E0020006400650020006C00270061007000700065006C002E&coding=8 HTTP/1.1`
HTTP return code : 200

Or am I totally wrong wanting to encode my string to utf-16 ?

Thank you

**Comment by amechax** [comment]
Hello, try with this on hex-content, 74657374207769746820E9

Below test on 0.9.27 

with 74657374207769746820E9
`2018-04-18 16:44:04 INFO     937 SMS-MT [cid:tele-tz] [queue-msgid:41044342-b133-4926-ac19-48b2fed55431] [smpp-msgid:1] [status:ESME_ROK] [prio:0] [dlr:SMSC_DELIVERY_RECEIPT_REQUESTED] [validity:none] [from:INFO] [to:255NNNXXXXXX] [content:'test with \xe9']`

With 007400650073007400200077006900740068002000E9
`2018-04-18 16:46:30 INFO     937 SMS-MT [cid:tele-tz] [queue-msgid:8fdeecac-f0c8-4ea1-a432-6a8d5a89ddad] [smpp-msgid:2] [status:ESME_ROK] [prio:0] [dlr:SMSC_DELIVERY_RECEIPT_REQUESTED] [validity:none] [from:INFO] [to:255NNNXXXXXX] [content:'\x00t\x00e\x00s\x00t\x00 \x00w\x00i\x00t\x00h\x00 \x00\xe9']`

**Comment by maximecaze** [comment]
Thank you for your help @amechax 

I noticed that in http-api, I had :
`2018-04-19 13:37:20 ERROR    24557 Failed running interception script, got the following return: False`
`2018-04-19 13:37:20 ERROR    24557 Error: 400: InterceptorRunError (Failed running interception script, check log for details)`

And in interceptor.log :
`2018-04-19 13:37:20 ERROR    24556 Executing script on routable (from:2xxxx, to:07xxxxxxxx) returned: <type 'exceptions.UnicodeDecodeError'>: 'utf8' codec can't decode byte 0xe9 in position 21: unexpected end of data`

Interceptor was configured to catch any incoming messages, so I dropped the interception configuration and it works now. So it seems that interception failed with some encoded messages, is that normal ?
