### ISSUE TITLE
Installing jasmin through "pip install" , ImportError: No module named pip.req

### ISSUE THREAD

**Issue by crazydavidoff** [jookies/jasmin#670]
Hi , due to new version of pip (10) Installing jasmin fails with error "ImportError: No module named pip.req".
to solve this problem: 
1) download jasmin
`pip download jasmin`

2) edit setup.py 
replace string "from pip.req import parse_requirements"  with

```
try: # for pip >= 10
    from pip._internal.req import parse_requirements
except ImportError: # for pip <= 9.0.3
    from pip.req import parse_requirements
```
3) run install
`python setup.py install`

**Comment by farirat** [comment]
Thank you @crazydavidoff !

Will be pushed in next release.
