### ISSUE TITLE
SMPP secondary connection not working on JasminSMS

### ISSUE THREAD

**Issue by pizu** [jookies/jasmin#673]
Connection lost. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.

Bind failed [[Failure instance: Traceback (failure with no frames): <class 'jasmin.vendor.smpp.pdu.error.SMPPTransactionError'>: ESME_RINVSYSID ({'name': 'ESME_RINVSYSID', 'description': 'Invalid System ID'})

> jcli : smppccm --show xxxxxx
> ripf 0
> con_fail_delay 10
> dlr_expiry 86400
> coding 0
> logrotate midnight
> submit_throughput 110
> elink_interval 30
> bind_to 30
> port 17600
> con_fail_retry yes
> password xxxxxx
> src_addr
> bind_npi 1
> addr_range None
> dst_ton 1
> res_to 120
> def_msg_id 0
> priority 0
> con_loss_retry yes
> username xxxxxx
> dst_npi 1
> validity None
> requeue_delay 120
> host xxxxxx
> src_npi 1
> trx_to 300
> logfile //var/log/jasmin/default-xxxxxx.log
> systype SMPP
> ssl no
> cid smpp-corporate-any
> loglevel 20
> bind transmitter
> proto_id None
> dlr_msgid 0
> con_loss_delay 10
> bind_ton 1
> pdu_red_to 10
> src_ton 5

The only difference between the 1st and second connection are the ton/npi

**Comment by pizu** [comment]
If I stop the 1st SMPP Connect it works.. is it possible to use 2 smpp connections?

**Comment by farirat** [comment]
ESME_RINVSYSID is returned by your upstream provider, it seems it doesnt accept multi-session binding.
