### ISSUE TITLE
How to Convert String to hex-content

### ISSUE THREAD

**Issue by sah-anshu** [jookies/jasmin#674]
Hi
I can see this example  to send Unicode SMS in hex content. Can you please advise how to convert any Unicode String to their hex-content. 

# Sending UCS2 (UTF-16) arabic binary content
baseParams['hex-content'] = '0623063106460628'
baseParams['coding'] = 8
urllib2.urlopen("http://127.0.0.1:1401/send?%s" % urllib.urlencode(baseParams)).read()

Thanks in advance. 
Anshu

**Comment by farirat** [comment]
https://docs.python.org/2/library/binascii.html#binascii.hexlify

**Comment by sah-anshu** [comment]
1st Attempt

```
textmessage = u"ਤੁਹਾਡੀ ਸ਼ਿਕਾਇਤ ਨੰਬਰ 565/18 FDK ਨਾਲ ਦਰਜ ਹੋ ਗਈ"
print textmessage.encode("utf-16").encode('string-escape')
baseParams['hex-content'] = binascii.hexlify(textmessage.encode("utf-16").encode('string-escape'))
print baseParams['hex-content']
baseParams['coding'] = 8
```
`\xff\xfe$\nA\n9\n>\n!\n@\n \x006\n?\n\x15\n>\n\x07\n$\n \x00(\np\n,\n0\n \x005\x006\x005\x00/\x001\x008\x00 \x00F\x00D\x00K\x00 \x00(\n>\n2\n \x00&\n0\n\x1c\n \x009\nK\n \x00\x17\n\x08\n
5c7866665c786665245c6e415c6e395c6e3e5c6e215c6e405c6e205c783030365c6e3f5c6e5c7831355c6e3e5c6e5c7830375c6e245c6e205c783030285c6e705c6e2c5c6e305c6e205c783030355c783030365c783030355c7830302f5c783030315c783030385c783030205c783030465c783030445c7830304b5c783030205c783030285c6e3e5c6e325c6e205c783030265c6e305c6e5c7831635c6e205c783030395c6e4b5c6e205c7830305c7831375c6e5c7830385c6e`
Result Garbage Character on phone.

**Comment by sah-anshu** [comment]
2nd Attempt. 

`textmessage = r"ਤੁਹਾਡੀ ਸ਼ਿਕਾਇਤ ਨੰਬਰ 565/18 FDK ਨਾਲ ਦਰਜ ਹੋ ਗਈ"
print textmessage.encode('string-escape')
baseParams['hex-content'] = binascii.hexlify(textmessage.encode('string-escape'))
print baseParams['hex-content']
baseParams['coding'] = 8
`


`\xe0\xa8\xa4\xe0\xa9\x81\xe0\xa8\xb9\xe0\xa8\xbe\xe0\xa8\xa1\xe0\xa9\x80 \xe0\xa8\xb6\xe0\xa8\xbf\xe0\xa8\x95\xe0\xa8\xbe\xe0\xa8\x87\xe0\xa8\xa4 \xe0\xa8\xa8\xe0\xa9\xb0\xe0\xa8\xac\xe0\xa8\xb0 565/18 FDK \xe0\xa8\xa8\xe0\xa8\xbe\xe0\xa8\xb2 \xe0\xa8\xa6\xe0\xa8\xb0\xe0\xa8\x9c \xe0\xa8\xb9\xe0\xa9\x8b \xe0\xa8\x97\xe0\xa8\x88
5c7865305c7861385c7861345c7865305c7861395c7838315c7865305c7861385c7862395c7865305c7861385c7862655c7865305c7861385c7861315c7865305c7861395c783830205c7865305c7861385c7862365c7865305c7861385c7862665c7865305c7861385c7839355c7865305c7861385c7862655c7865305c7861385c7838375c7865305c7861385c786134205c7865305c7861385c7861385c7865305c7861395c7862305c7865305c7861385c7861635c7865305c7861385c786230203536352f31382046444b205c7865305c7861385c7861385c7865305c7861385c7862655c7865305c7861385c786232205c7865305c7861385c7861365c7865305c7861385c7862305c7865305c7861385c783963205c7865305c7861385c7862395c7865305c7861395c783862205c7865305c7861385c7839375c7865305c7861385c783838`

Result Again Garbage Character.

**Comment by sah-anshu** [comment]
pl advise where i am making mistake.

**Comment by sah-anshu** [comment]
@farirat 
I have found the similar answer in Javascript 
https://github.com/r12a/app-conversion

But I need help in python too.
