### ISSUE TITLE
jasmin smpp to http

### ISSUE THREAD

**Issue by kuziakhmedov** [jookies/jasmin#677]
Hello
I am guided by the article http://jasmin.readthedocs.io/en/latest/apis/ja-http/index.html#receiving-sms-mo
<<SMS-MO incoming messages (Mobile Originated) are forwarded by Jasmin to defined URLs using simple HTTP GET/POST, the forwarding is made by deliverSmHttpThrower service, and the URL of the receiving endpoint is selected through a route checking process>>
And trying to route message received from SMPP client to an HTTP listener
Here is my current configuration 

jcli : httpccm -l
#Httpcc id        Type                   Method URL
#http_01          HttpConnector          GET    http://10.2.18.140:8010/api/terminationNotif
#HTTP-01          HttpConnector          GET    http://10.2.18.140:8010/api/terminationNotif

jcli : morouter -l
#Order Type                    Connector ID(s)                                  Filter(s)
#0     DefaultRoute            http(http_01)

No http request is made and here is what I am getting in the log

2018-05-29 14:57:10 WARNING  24632 SMPP connection established from 10.7.129.48 to port 2775
2018-05-29 14:57:10 INFO     24632 Added bind_transmitter bind for 'test'. Active binds: bind_receiver: 1, bind_transceiver: 0, bind_transmitter: 1.
2018-05-29 14:57:10 ERROR    24632 No route matched from user test for SubmitSmPDU: PDU [command: submit_sm, sequence_number: 2, command_status: ESME_ROK

I even tried to transmit a message to an SMPP client, but it seems like that Jamin gateway acts like ESME.

Here is configuration

jcli : smppccm -l
#Connector id                        Service Session          Starts Stops
#BillingToCamel                      started None             1      0
Total connectors: 1
jcli : smppccm -s BillingToCamel
ripf 0
con_fail_delay 10
dlr_expiry 86400
coding 0
logrotate midnight
submit_throughput 1
elink_interval 30
bind_to 30
port 2775
con_fail_retry yes
password password
src_addr None
bind_npi 0
addr_range None
dst_ton 1
res_to 120
def_msg_id 0
priority 0
con_loss_retry yes
username smppclient
dst_npi 1
validity None
requeue_delay 120
host 10.2.18.140
src_npi 1
trx_to 300
logfile //var/log/jasmin/default-BillingToCamel.log
systype
ssl no
cid BillingToCamel
loglevel 20
bind transmitter
proto_id None
dlr_msgid 0
con_loss_delay 10
bind_ton 0
pdu_red_to 10
src_ton 2

I have two questions?
Does SMPP to HTTP really works (Is there a way to implement it using Jasmin)?
Can Jasmin act as SMSC to ESME clients(send messages to ESME clients)?

Thank you

**Comment by farirat** [comment]
You are receiving submit_sm (MT) instead of deliver_sm (MO), you may have your MNO inversing the pdus ...
