### ISSUE TITLE
typo in documentation for Jasmin

### ISSUE THREAD

**Issue by s-tobe** [jookies/jasmin#678]
Hi ,
while reading the docs I might have found a typo 
http://jasmin.readthedocs.io/en/latest/interception/index.html#enabling-interceptor

it states:
Intercepting a message

As stated earlier, interceptor is behaving similarly to The message router, here’s an example of setting up a **# MO message (deliver_sm)** interception rule through jcli management console:
...
  and further down it is stated

...
Same thing apply to setting up a  **# MT message (submit_sm)** interception rule, here’s another example using a filtered rule instead of a default one:

BUT should it not be MO message (submit_SM) and MT message (submit_deliver)???

thanks 
Stefan

**Comment by farirat** [comment]
From what i know, there's no submit_deliver pdu in smpp protocol, MO is deliver_sm, MT is submit_sm, and both can be represented by data_sm as well, but the latter is not implemented in jasmin.

**Comment by s-tobe** [comment]
Sorry I made a typo myself in the issue; I ment saying
BUT should it not be MO message (submit_sm) and MT message (deliver_sm)???

**Comment by farirat** [comment]
Are you from somewhere in LATAM ? i see a lot of users reporting MO in submit_sm instead of deliver_sm in that region.

**Comment by s-tobe** [comment]
Hi I work for a mobile telco in the Netherlands
I think the confusion comes from the following:
in your Jasmin docs you define the following:

    MO Messages (deliver_sm) hitting MOROUTER table (spec says deliver_sm only to be originated from SMSC TO ESME)
    MT Messages (submit_sm) hitting MTROUTER table (spec says submit_sm only to be originated from ESME TO SMSC) 

However in Telcoworld usually the following terminology is used:

handset --called MO submit--> smsc --called MT deliver leg--> other smsc/handset

so as you can see the combination of MO (deliver_sm) in your docs seem to conflict with telco MO submit
and well MT (submit_sm) conflicts with telco MT Deliver)

I have no opinion on what is correct however my goal is to understand the required config of your amazing open source tool, because we like the setup and the professional approach you show in your design.

regards
Stefan

**Comment by farirat** [comment]
Hello Stef, thanks for this clarification.

I dont think MO will turn to MT just after the SMSC, but some implementations may differ anyway, Jasmin is considering a MO the message from where it **first** originated: the mobile station.
Same goes for MT, it's pointing the mobile station as a termination.

So now that you understood the differences, it's not a typo :)

**Comment by s-tobe** [comment]
Most important is to realize that in jasmin 
deliver_sm operation hits MOROUTER table
and
submit_sm hits MTROUTER table
