### ISSUE TITLE
update of .py filters is not reflected in jasmin cli

### ISSUE THREAD

**Issue by s-tobe** [jookies/jasmin#679]
When i'd like to update the python filter in the file that is referenced by filter type EvalPyFilter, the updated content is not reflected/uploaded into jasmin  when I do: filter -l or filter -s <filter name>

question:
do I need to delete the filter and add again with same name?
will it break the dependencies between the existing filter in jasmin and the reference to it in mtrouter for example?
what is the best current practice to update python filter file contents?

**Comment by farirat** [comment]
You need to delete/add the filter to reload, you are right, there must be a better way to reload the filter
