### ISSUE TITLE
Reassembled short message header removed after submit_sm with interceptor

### ISSUE THREAD

**Issue by mrsanvicente** [jookies/jasmin#683]
Hello,

When a long sms (concatenated sms) is sent with submit_sm through  JASMIN, the content is transmitted as is.
BUT when i am using interceptor for modifying some parameters like, origination number and ton. i noticed that sms is not arriving to the terminal.
I capture a trace before interceptor and before.  I can see that a header is removed, the one that says "Reassembled short message length" on the  UDH part.    This header is needed in order to be read the sms and the terminal.  Can you please let me know your comments.

Thank you.

Here are the traces before and after passing the interceptor.       
![concatenated-after-interceptor](https://user-images.githubusercontent.com/5883115/40868703-25217e7a-65d5-11e8-8a71-f3394b4f6639.jpg)
![concatenated-before-interceptor](https://user-images.githubusercontent.com/5883115/40868704-25a49eae-65d5-11e8-8dfd-e75b11152fd1.jpg)

**Comment by mrsanvicente** [comment]
Hello Farirat.

Any chance to apply a workaround in the meantime?

**Comment by mrsanvicente** [comment]
Hello Farirat,

It is a critical bug for me.  I noticed that there are old issues still waiting for the v0.9 milestone.

Can you help me to patch this bug?  Any clue which file need to be patched, so can take a look?

Thank you in advance.

**Comment by farirat** [comment]
Please show/describe your interceptor script

**Comment by mrsanvicente** [comment]
Hello farirat,

Basically:  
"Search Portablity DB and add TAG, change ani,SET ton/npi, "

Here you go..
[porta.py.txt](https://github.com/jookies/jasmin/files/2078777/porta.py.txt)

Thanks



"Search Portablity DB and add TAG, change ani,SET ton/npi, "
import redis, requests, json
import csv, random
from random import randint
##Logging ## ----------------------------------------------------------------------------
import logging
logger = logging.getLogger('logging-example')
if len(logger.handlers) != 1:
    hdlr = logging.FileHandler('/var/log/jasmin/sms.log')
    formatter = logging.Formatter('%(asctime)s %(levelname)s %(message)s')
    hdlr.setFormatter(formatter)
    logger.addHandler(hdlr)
    logger.setLevel(logging.DEBUG)
#logger.info('Got pdu: %s' % routable.pdu)

##SET TON##-----------------------------------------------------------------------------
routable.pdu.params['dest_addr_ton'] = 'NATIONAL'
routable.pdu.params['dest_addr_npi'] = 'ISDN'
routable.pdu.params['source_addr_ton'] = 'NATIONAL'
routable.pdu.params['source_addr_npi'] = 'ISDN'

##Change ANI with a random number from a block ##------------------------------------------------------------------------
client = routable.pdu.params['source_addr']

if client == "A":

        prim  = str(2260002)
        sec = randint(0, 400)
        sec = str(sec).zfill(3)
        anumb = "%s%s" %(prim,sec)
        routable.pdu.params['source_addr'] = anumb

else:
        prim  = ['1194300','1144660']
        sec = randint(0, 200)
      sec = str(sec).zfill(3)
        aprim = random.choice(prim)
        anumb = "%s%s" %(aprim,sec)
        routable.pdu.params['source_addr'] = anumb

newani = routable.pdu.params['source_addr']

### Check porbability ROUTING  10 number digit -  Others smpp_status =254   or http status = 520--------

number = routable.pdu.params['destination_addr']
data = number [2:]
r = redis.StrictRedis(host='x.x.x.x', port=6379, db=0)
data = str(data)
resp = r.get(data)
data7 = data[0:7]
data6 = data[0:6]
data5 = data[0:5]
data4 = data[0:4]

if not resp:
     # print "Not ported, search series"
      resp7 = str(r.get(data7))
      resp6 = str(r.get(data6))
      resp5 = str(r.get(data5))
      resp4 = str(r.get(data4))
      if resp7.find("010") != -1 or resp6.find("010") != -1 or resp5.find("010") != -1 or resp4.find("010") != -1:
            logger.info('SerieT,%s,%s,%s' %(client,newani,number) )
            routable.pdu.params['destination_addr'] = number [2:]
            routable.addTag(100)
      elif resp7.find("011") != -1 or resp6.find("011") != -1 or resp5.find("011") != -1 or resp4.find("011") != -1:
            logger.info('SerieF,%s,%s,%s' %(client,newani,number) )
            routable.pdu.params['destination_addr'] = number [2:]
            routable.addTag(100)
     .
     .
     .

      else:
            print "Serie others"
            logger.info('Serieother2V,%s,%s,%s' %(client,newani,number) )
            routable.pdu.params['destination_addr'] = number [2:]
            routable.pdu.params['service_type'] = 'other'
            routable.addTag(101)

else:
      if resp[0:3] == "010":
            logger.info('PT,%s,%s,%s' %(client,newani,number) )
            routable.pdu.params['destination_addr'] = number [2:]
            routable.addTag(100)
      elif resp[0:3] == "011":
        .
        .
        .
      else:
            logger.info('Pother2V,%s,%s,%s' %(client,newani,number) )
            routable.pdu.params['service_type'] = 'other'
            routable.pdu.params['destination_addr'] = number [2:]
            routable.addTag(101)

**Comment by mrsanvicente** [comment]
How is it low priority this issue when ANY concatenated message going through jasmin is not working?

**Comment by sah-anshu** [comment]
True, Its serious bug.

**Comment by sah-anshu** [comment]
hi, @farirat 
please update on this, there is no point of using interceptor if it make another part of sms unusable.

**Comment by farirat** [comment]
Hello @mrsanvicente 

Tried to reproduce your issue with this simple interceptor:

> routable.pdu.params['service_type'] = 'other'
> routable.pdu.params['destination_addr'] = '222222222'
> routable.addTag(101)`

And were unable to get your scenario, all long messages are routed correctly from downstream to upstream passing through the interceptor, i've tested both httpapi and smppc with long messages.

Recalling your traces, i can see there are message identifier, part number and part count in message headers, that's okay and you must be receiving correct long messages.

Please clarify your case if still to date.

**Comment by mrsanvicente** [comment]
Hello @farirat ,

The issue is with concatenated sms.  This long messages are splitted into many sms,  but the SMSUD header keeps track of all the text and its parts.  That header is the being removed, and that is the issue on this ticket.  Please find attached a image of a good concatenated sms and its pcap. ( It worked because we disable any interceptor).


![image](https://user-images.githubusercontent.com/5883115/47941418-b4491200-deb3-11e8-90b5-a63a241ee9d6.png)
![concatenated_c_ok](https://user-images.githubusercontent.com/5883115/47941472-e5c1dd80-deb3-11e8-9b8f-aa1dd4f61c7d.jpg)



Thank you
Mario

**Comment by farirat** [comment]
Please show the udh header content of an intercepted multipart message.

**Comment by mrsanvicente** [comment]
Here you go,

Please find attached, and UDH header of a intercepted message, a non intercepted, and a pcap of a intercepted sms.
[Multipart-NotOK.zip](https://github.com/jookies/jasmin/files/2554982/Multipart-NotOK.zip)



![image](https://user-images.githubusercontent.com/5883115/48091997-04d0b000-e1d1-11e8-8f03-47840f88353a.png)
![image](https://user-images.githubusercontent.com/5883115/48092042-2c277d00-e1d1-11e8-8336-2f797bdf1930.png)


Thank you

**Comment by farirat** [comment]
In the provided pcap trace file i can see 3 pdus with correct UDH:
- First one has identifier (3) parts (3) part number (1)
- First one has identifier (3) parts (3) part number (2)
- First one has identifier (3) parts (3) part number (3)

All seems okay except wireshark showing the "Unreassembled" issue.

**Comment by mrsanvicente** [comment]
Hello @farirat 
It looks normal,  until you make a comparison with a Multipart sms not intercepted.  You will notice that each sms  contains the whole sms fragments on the UDH header, under short message body  ( As if you only need a fragment of the sms to get the whole text).   That header is being removed while passing through the interceptor.  Please compare with this Pcap file.
 -
[Multipart-OK.zip](https://github.com/jookies/jasmin/files/2555895/Multipart-OK.zip)

![image](https://user-images.githubusercontent.com/5883115/48108200-cefaee00-e207-11e8-9640-6e5c7111bb1e.png)

**Comment by cholthi** [comment]
Hi @farirat , this issue is still present. Interceptors are not correctly sending long messages. concatenated messages are not routed to handset after passing through an interceptor. Normal short message works okay whether through interceptor or not.
