### ISSUE TITLE
[question] Have the MT connector returned in DLR

### ISSUE THREAD

**Issue by terrycain** [jookies/jasmin#685]
Would it make sense to return what connector/&route an MT message uses in the DLR?

I was thinking getting the name of the connector from [here](https://github.com/jookies/jasmin/blob/master/jasmin/protocols/http/server.py#L206) and passing it in [here](https://github.com/jookies/jasmin/blob/master/jasmin/protocols/http/server.py#L369), adding it into the hmset [here](https://github.com/jookies/jasmin/blob/01325ae89ed1e7f43cac8ede3ae89087608cfbd3/jasmin/managers/clients.py#L604).

Then extracting the value [here](https://github.com/jookies/jasmin/blob/01325ae89ed1e7f43cac8ede3ae89087608cfbd3/jasmin/managers/dlr.py#L177) defaulting to an empty string if missing, then passing it into `DLRContentForHttpapi` and adding it to the properties dict [here](https://github.com/jookies/jasmin/blob/01325ae89ed1e7f43cac8ede3ae89087608cfbd3/jasmin/managers/content.py#L103)

I can make a PR if needed

**Comment by farirat** [comment]
Dont know if this is useful but if you're willing to add it then it's most welcome.
 :)

**Comment by terrycain** [comment]
Ha Its useful to me at least :). I'll work on a PR this week
