### ISSUE TITLE
Missing RESTful API

### ISSUE THREAD

**Issue by pyghassen** [jookies/jasmin#69]
I just checked the documentation for the HTTP API, and I found out that is more RPC style than Resource oriented.

**Comment by tarikogut** [comment]
im adding json api thanks :)

**Comment by fourat** [comment]
Where are you doing it ? any design you're using ?

**Comment by tarikogut** [comment]
im programing sorry i little speak eng


2015-01-02 22:54 GMT+02:00 Fourat ZOUARI <notifications@github.com>:

**Comment by tarikogut** [comment]
i f you accept i can join your team :)

**Comment by fourat** [comment]
everyone is welcome, let's discuss your contrib scope

**Comment by zoufou** [comment]
Will be provided in #281
