### ISSUE TITLE
Is there a mechanism to check the validity of the number?

### ISSUE THREAD

**Issue by MAPIIIAJI** [jookies/jasmin#695]
Hi dear support Jasmin SMS Gateway! First sorry for my English! And I have next situation: I use SMS gateway Gammu and Gammu has serious minus side. It is have not feature for checks receiver phone number correction. And I have question: Does Jasmine have a mechanism to check the validity of the number?

Gammu issue link: https://github.com/gammu/gammu/issues/409 

Thank in advance!

**Comment by farirat** [comment]
There's two ways to take:

(1) Applying correct filters (using regex) in routing configuration will ensure you only send correct phone numbers.
(2) On top of the filters (way n°1) you can add interception mechanism, it will take care of wrong numbers and **correct** them by removing spaces, dots, adding suffix, etc ...

**Comment by MAPIIIAJI** [comment]
farirat, thank you for reply. Just gorgeous. And the first and second point is implemented with Jasmin?

**Comment by farirat** [comment]
Yes

**Comment by MAPIIIAJI** [comment]
Thanks, topic is closed
