### ISSUE TITLE
Jasmin SMS Gateway and USB-modem

### ISSUE THREAD

**Issue by wijde** [jookies/jasmin#697]
Expensive professionals, there is another question) Deal in is, that mean the next alignment:
OS: CentOS
Installed Jasmin SMS Gateway
USB modem (the modem is defined as a serial device: ttyUSB*)
Actually there is a question: is it Possible to make friends with a modem that works as a serial device with Jasmin SMS Gateway. In advance my thanks for the answer.

**Comment by MAPIIIAJI** [comment]
Are there any ideas? Thank you!

**Comment by farirat** [comment]
Jasmin only accept smpp as upstream (http+smpp as downstream), there's a commercial plugin that can add multi-protocol upstreams including serial modem, http, etc ...

**Comment by MAPIIIAJI** [comment]
farirat thanks for your reply! If it's not difficult for you, you could point to the source of this plugin. Thank you for your help earlier

**Comment by farirat** [comment]
please file a request to support@jasminsms.com

**Comment by grumpyman57** [comment]
@farirat and where does one obtain this plugin for Jasmin that add GSM modem support? I can find no reference to one using Google. If someone knows if such a thing actually exists, and where to obtain it, that would be most helpful.
