### ISSUE TITLE
Performance numbers of Jasmin SMS Gateway

### ISSUE THREAD

**Issue by techwizardg** [jookies/jasmin#698]
This is not an issue but not sure where to post and get the information. We are evaluating Jasmin SMS Gateway for use in one of our products and in the process of it, we are looking for benchmarks for the same via both HTTP API and SMPP

Would appreciate if we could get the following information

a) HTTP API - through put per second with detailed information of how many ESME accounts were created and was delivery receipt enabled
with Del receipt on and off
b) SMPP API - through put per second with detailed information of how many ESME accounts were created and with or with out del receipt. Was the account in TRX/RX/TX mode

Also do we support the following

a) Rate limiting per ESME Connection
b) DND check

Your reply to the same is highly appreciated

**Comment by Eudorajab1** [comment]
Hi there,

I have been using Jasmin for a number of years now and might be able to answer quite a few of your questions but it depends very much on your setup. If you can provide a bit more information on what you are trying to achieve there is probably a solution.

**Comment by techwizardg** [comment]
we are looking at using this for our ESMEs to connect over HTTP and SMPP and submit the message to SMSC. We are planning to run the gateway on a box with 8 core and 32 GB RAM and looking at a TPS of around 3000 TPS with delivery receipt on

**Comment by Eudorajab1** [comment]
Okay for that I think you are going to need a few instances of Jasmin as in my experience a single hosted instance can handle around 300 TPS. There are however a number of ways to overcome this mainly by using docker containers but that is a slightly more complex setup. If you need any specific information you can email me at eudorajab1@gmail.com

**Comment by ShivanDana** [comment]
@techwizardg, did you find any answers? As I have the same inquiry

**Comment by asanka-x** [comment]
@techwizardg, I am also looking for answers for the same questions. Mainly I need to know how much throughput can be handled by the smpp module and http module (for inbound message we are using urls)

**Comment by magojr** [comment]
@techwizardg I'm also interested to know the throughput reached with that box, anyone have an idea of that? (or about any other box, posting also the box specs)

**Comment by majidshirazy** [comment]
There isn't any update about this platform benchmark? how many TPS it can handle for how many esme account with 32 core 2.0Ghz cpu and 32GB RAM?
