### ISSUE TITLE
HTTP-API Error "Unknown error: expected string or buffer"

### ISSUE THREAD

**Issue by TW20-MH** [jookies/jasmin#699]
When I used the HTTP-API on Port 1401 then I will get an HTTP 500 ERROR:

Error "Unknown error: expected string or buffer"

on Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-124-generic x86_64)
Python 2.7.12
Jasmin 0.9.27

**Comment by farirat** [comment]
What are you pushing to the http api ?

**Comment by ihsanz2** [comment]
@farirat, i've same issue, but in my case i follow all document instruction and already bind to my provider and call http://127.0.0.1:6600/send?username=oky12345&password=asda2123&to=62852740892&content=hello

the response is "Unknown error: expected string or buffer".

here my setting

jcli: smppccm -l 
#DEMO_CONNECTOR                      started BOUND_TRX        1      0

jcli : user -l
#oky12345         foogroup         oky12345         ND (!)  ND (!) ND/ND

jcli : group -l
#foogroup

mtrouter 
#0     DefaultRoute            0 (!)      smppc(DEMO_CONNECTOR)

did i do some mistake in my setting?

**Comment by juanantoniotv** [comment]
Check the http-api.log,  connector logs in /var/log/jasmin looking for errors, did you change default http api port?, default port is 1401.

**Comment by ihsanz2** [comment]
@juanantoniotv thank you for your kindly respond, 

when i try to curl from my terminal, i got "Mandatory argument [to] is not found."

but when i try to calling from my browser i got Error "Unknown error: expected string or buffer"


here my log from http-api
========================

ihsan@RP-SN2:~ $ cat /var/log/jasmin/http-api.log
20181114 021324 ERROR    5822 Error: 400: UrlArgsValidationError (Mandatory argument [to] is not found.)
20181114 021447 ERROR    5822 Error: 400: UrlArgsValidationError (Mandatory argument [to] is not found.)
20181114 021628 ERROR    5822 Error: expected string or buffer
20181114 021714 ERROR    5822 Error: 400: UrlArgsValidationError (Mandatory argument [to] is not found.)



and yes, i change my port to 6600. this is my setting 
===================================

# If you want you can bind a single interface, you can specify its IP here
#bind                           = 0.0.0.0

# Accept connections on the specified port, default is 1401
port                            = 6600

i do exactly step by step like document examples and i call with 

http://127.0.0.1:6600/send?username=oky12345&password=asda2123&to=62852740892&content=hello

**Comment by ihsanz2** [comment]
@juanantoniotv thank you for your kindly respond,

when i try to curl from my terminal, i got "Mandatory argument [to] is not found."

but when i try to calling from my browser i got Error "Unknown error: expected string or buffer"

here my log from http-api
ihsan@RP-SN2:~ $ cat /var/log/jasmin/http-api.log
20181114 021324 ERROR 5822 Error: 400: UrlArgsValidationError (Mandatory argument [to] is not found.)
20181114 021447 ERROR 5822 Error: 400: UrlArgsValidationError (Mandatory argument [to] is not found.)
20181114 021628 ERROR 5822 Error: expected string or buffer
20181114 021714 ERROR 5822 Error: 400: UrlArgsValidationError (Mandatory argument [to] is not found.)

and yes, i change my port to 6600. this is my setting
If you want you can bind a single interface, you can specify its IP here
#bind = 0.0.0.0

Accept connections on the specified port, default is 1401
port = 6600

i do exactly step by step like document examples and i call with

http://127.0.0.1:6600/send?username=oky12345&password=asda2123&to=62852740892&content=hello

**Comment by juanantoniotv** [comment]
Maybe is an install error, no configuration, I have this response when don't set "to" param, - Error "Mandatory argument [to] is not found.", check if you have a correctly python version. I installed Jasmin around 12 times and did't have this error.
