### ISSUE TITLE
RESTful-API logging in http-api.log too

### ISSUE THREAD

**Issue by TW20-MH** [jookies/jasmin#700]
When I using the RESTful-API then I see log-entries in http-api.log too. 
Is it possible to separate the log-entries from RESTful-API and HTTP API?

Maybe:
restapi.log for RESTful-API 
http-api for HTTP API
default-smpps_01.log for SMPP
..and so on.

I would like to use it for an itemized billing.

**Comment by farirat** [comment]
How did you make the install ?

You should normally get a /etc/jasmin/restapi.conf if you did a rpm or deb install.
