### ISSUE TITLE
How can I enable REST API on docker

### ISSUE THREAD

**Issue by itsursujit** [jookies/jasmin#704]
Hi,

Thank you for such awesome library. I tried to install jasmin using docker. I was able to access HTTP API after installation. Please let me know how should I follow to activate REST API on docker.

Also, 
Is there any web interface to manage Jasmine and integrate it with PHP?

**Comment by Eudorajab1** [comment]
Hello @itsursujit,

With regards to your first question are you using the standard official standard docker container?
Regarding web interface I have developed one which I am using to manage multiple docker containers written in python using web2py scaffolding and if you need details please contact me via email: eudorajab1@gmail.com. Alternatively I think there have been a lot of attempts for the last number of years to get a good jasmin GUI up and running but I dont know how good they are.

**Comment by JerrelS** [comment]
Hi itsursujit 

I have the same issue.

did you resolve it ?

**Comment by appcoreopc** [comment]
for dev / one time off thing, you can 

// stop your container
sudo service docker stop 

// make sure you get empty string - no docker process running 

cat /var/run/docker.pid

sudo dockerd -H tcp://0.0.0.0:2375

**Comment by Sevyls** [comment]
> for dev / one time off thing, you can
> 
> // stop your container
> sudo service docker stop
> 
> // make sure you get empty string - no docker process running
> 
> cat /var/run/docker.pid
> 
> sudo dockerd -H tcp://0.0.0.0:2375
> 
> For a more permanent solution (please change to port 2375 if required) :-
> 
> https://success.docker.com/article/how-do-i-enable-the-remote-api-for-dockerd
> 
> once you have your changes, then restart your docker service.
> 
> sudo service docker start

Hi @appcoreopc , I think this is not related to the original question. We don't need to access the dockerd rest services.

We would like to run Jasmin's REST API, like described here: http://docs.jasminsms.com/en/latest/apis/rest/index.html

I get a python syntax error running the proposed celery command:

```
$ docker exec -it jasmin /bin/bash
root@96fa4becea03:/# celery -A jasmin.protocols.rest.tasks worker -l info -c 4 --autoscale=10,3
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 7, in <module>
    from celery.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/celery/__init__.py", line 153, in <module>
    from . import local  # noqa
  File "/usr/local/lib/python2.7/dist-packages/celery/local.py", line 17, in <module>
    from .five import PY3, bytes_if_py2, items, string, string_t
  File "/usr/local/lib/python2.7/dist-packages/celery/five.py", line 7, in <module>
    import vine.five
  File "/usr/local/lib/python2.7/dist-packages/vine/__init__.py", line 6, in <module>
    from .abstract import Thenable
  File "/usr/local/lib/python2.7/dist-packages/vine/abstract.py", line 8
    class Thenable(Callable, metaclass=abc.ABCMeta):  # pragma: no cover
                                      ^
SyntaxError: invalid syntax
```

**Comment by LemuelPuglisi** [comment]
Any updates on this issue?

**Comment by itsursujit** [comment]
They do not seem support any bugs

**Comment by LemuelPuglisi** [comment]
It's open source, they are not supposed to fix any bug.. Instead, we can try to contribute. 
I'm actually trying to set it up and make it works, feel free to contact me to collaborate!

**Comment by kissonde** [comment]
> It's open source, they are not supposed to fix any bug.. Instead, we can try to contribute.
> I'm actually trying to set it up and make it works, feel free to contact me to collaborate!
@LemuelPuglisi any advances with this?

**Comment by LemuelPuglisi** [comment]
> @LemuelPuglisi any advances with this?

Yes! You can start the process inside an entrypoint file like this: 

`twistd --pidfile=/tmp/twistd-web-restapi.pid web --wsgi=jasmin.protocols.rest.api`

Also make sure your container has python-mimeparse lib.

**Comment by ankur928** [comment]
@LemuelPuglisi 

I tried to run
`twistd --pidfile=/tmp/twistd-web-restapi.pid web --wsgi=jasmin.protocols.rest.api`

I get the below-mentioned error. Please help if you have been able to setup Jasmin Restful API in Docker correctly. Thanks.
```
:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named x509'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
Traceback (most recent call last):
  File "/usr/local/bin/twistd", line 9, in <module>
    load_entry_point('Twisted==19.2.0rc2', 'console_scripts', 'twistd')()
  File "/usr/local/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 31, in run
    app.run(runApp, ServerOptions)
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 669, in run
    config.parseOptions()
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 636, in parseOptions
    usage.Options.parseOptions(self, options)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/usage.py", line 267, in parseOptions
    self.subOptions.parseOptions(rest)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/usage.py", line 255, in parseOptions
    self._dispatch[optMangled](optMangled, arg)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/usage.py", line 411, in <lambda>
    fn = lambda name, value, m=method: m(value)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/tap.py", line 170, in opt_wsgi
    application = reflect.namedAny(name)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/reflect.py", line 308, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/reflect.py", line 247, in _importAndCheckStack
    return __import__(importName)
  File "/usr/local/lib/python2.7/dist-packages/jasmin/protocols/rest/__init__.py", line 7, in <module>
    from .api import PingResource, BalanceResource, RateResource, SendResource, SendBatchResource
  File "/usr/local/lib/python2.7/dist-packages/jasmin/protocols/rest/api.py", line 10, in <module>
    from .tasks import httpapi_send
  File "/usr/local/lib/python2.7/dist-packages/jasmin/protocols/rest/tasks.py", line 4, in <module>
    from celery import Celery, Task
  File "/usr/local/lib/python2.7/dist-packages/celery/__init__.py", line 153, in <module>
    from . import local  # noqa
  File "/usr/local/lib/python2.7/dist-packages/celery/local.py", line 17, in <module>
    from .five import PY3, bytes_if_py2, items, string, string_t
  File "/usr/local/lib/python2.7/dist-packages/celery/five.py", line 7, in <module>
    import vine.five
  File "/usr/local/lib/python2.7/dist-packages/vine/__init__.py", line 6, in <module>
    from .abstract import Thenable
  File "/usr/local/lib/python2.7/dist-packages/vine/abstract.py", line 8
    class Thenable(Callable, metaclass=abc.ABCMeta):  # pragma: no cover
```

**Comment by farirat** [comment]
Which jasmin version is this ?

**Comment by ankur928** [comment]
@farirat 
I do not know how to check the Jasmin version. Please advise. I pulled a Docker container that has Jasmin using the below-mentioned command. I am able to get the HTTP API to work. However, there has not been any success with RESTful API.

`docker pull jookies/jasmin`

**Comment by farirat** [comment]
Restapi is not enabled by default as indicated here: https://github.com/jookies/jasmin/blob/master/docker/Dockerfile#L45

The dockerfile is given as a sample, you may edit it and add more components into it.

**Comment by ankur928** [comment]
@farirat 
I know that REST API is not enabled by default. I am not able to enable it.

**Comment by sebin** [comment]
In case anybody is still looking for this, I was able to get it working by building a new image on top of jasmin image.

config.py
```
"""This is the jasmin-celery and jasmin-restapi configurations"""

import logging
import os

# RESTAPI
old_api_uri = os.environ.get('JASMIN_OLD_API_URI', 'http://127.0.0.1:1401')
show_jasmin_version = True
auth_cache_seconds = 10
auth_cache_max_keys = 500

log_level = logging.getLevelName('INFO')
log_file = '/var/log/jasmin/restapi.log'
log_rotate = 'W6'
log_format = '%(asctime)s %(levelname)-8s %(process)d %(message)s'
log_date_format = '%Y-%m-%d %H:%M:%S'
```

Dockerfile.rest
```
FROM jookies/jasmin:0.10 as base

WORKDIR /build
COPY config.py /build/jasmin/protocols/rest/

RUN pip install .

FROM base

WORKDIR /usr/jasmin
ENV PATH=$PATH:/usr/local/bin

ENTRYPOINT ["python", "twistd", "-n", "--pidfile=/tmp/twistd-web-restapi.pid", "web", "--wsgi=jasmin.protocols.rest.api"]

```

And you might want to run another container with celery worker running on it. You can use `jasmin` image with entrypoint modified to `["/usr/local/bin/celery", "-A", "jasmin.protocols.rest.tasks", "worker", "-l", "INFO", "-c", "4"]`

-------------------------

Docker compose file with all of them combined:

```
version: "3"

services:
  redis:
    image: redis:alpine
    restart: unless-stopped

  rabbit-mq:
    image: rabbitmq:alpine
    restart: unless-stopped

  jasmin:
    image: jookies/jasmin:0.10
    restart: unless-stopped
    container_name: jasmin
    volumes:
      - /var/log/jasmin:/var/log/jasmin
    ports:
      - 2775:2775
      - 8990:8990
      - 1401:1401
    depends_on:
      - redis
      - rabbit-mq
    environment:
      REDIS_CLIENT_HOST: redis
      AMQP_BROKER_HOST: rabbit-mq
  
jasmin_celery:
    image: jookies/jasmin:0.10
    restart: unless-stopped
    container_name: jasmin_celery
    depends_on:
      - rabbit-mq
      - redis
    entrypoint: ["/usr/local/bin/celery", "-A", "jasmin.protocols.rest.tasks", "worker", "-l", "INFO", "-c", "4"]
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbit-mq:5672//
      CELERY_RESULT_BACKEND: redis://:@redis:6379/1
  
jasmin_rest:
    build:
      context: .
      dockerfile: Dockerfile.rest
    restart: unless-stopped
    container_name: jasmin_rest
    ports:
      - 8080:8080
    depends_on:
      - jasmin
      - jasmin_celery
    entrypoint: ["/usr/local/bin/python", "/usr/local/bin/twistd", "-n", "--pidfile=/tmp/twistd-web-restapi.pid", "web", "--wsgi=jasmin.protocols.rest.api"]
    environment:
      JASMIN_OLD_API_URI: http://jasmin:1401
```

**Comment by farirat** [comment]
@sebin it's better you file a pr for that and include your contrib into jasmin :)

**Comment by MajdiRajeb** [comment]
> In case anybody is still looking for this, I was able to get it working by building a new image on top of jasmin image.
> 
> config.py
> 
> ```
> """This is the jasmin-celery and jasmin-restapi configurations"""
> 
> import logging
> import os
> 
> # RESTAPI
> old_api_uri = os.environ.get('JASMIN_OLD_API_URI', 'http://127.0.0.1:1401')
> show_jasmin_version = True
> auth_cache_seconds = 10
> auth_cache_max_keys = 500
> 
> log_level = logging.getLevelName('INFO')
> log_file = '/var/log/jasmin/restapi.log'
> log_rotate = 'W6'
> log_format = '%(asctime)s %(levelname)-8s %(process)d %(message)s'
> log_date_format = '%Y-%m-%d %H:%M:%S'
> ```
> 
> Dockerfile.rest
> 
> ```
> FROM jookies/jasmin:0.10 as base
> 
> WORKDIR /build
> COPY config.py /build/jasmin/protocols/rest/
> 
> RUN pip install .
> 
> FROM base
> 
> WORKDIR /usr/jasmin
> ENV PATH=$PATH:/usr/local/bin
> 
> ENTRYPOINT ["python", "twistd", "-n", "--pidfile=/tmp/twistd-web-restapi.pid", "web", "--wsgi=jasmin.protocols.rest.api"]
> ```
> 
> And you might want to run another container with celery worker running on it. You can use `jasmin` image with entrypoint modified to `["/usr/local/bin/celery", "-A", "jasmin.protocols.rest.tasks", "worker", "-l", "INFO", "-c", "4"]`
> 
> Docker compose file with all of them combined:
> 
> ```
> version: "3"
> 
> services:
>   redis:
>     image: redis:alpine
>     restart: unless-stopped
> 
>   rabbit-mq:
>     image: rabbitmq:alpine
>     restart: unless-stopped
> 
>   jasmin:
>     image: jookies/jasmin:0.10
>     restart: unless-stopped
>     container_name: jasmin
>     volumes:
>       - /var/log/jasmin:/var/log/jasmin
>     ports:
>       - 2775:2775
>       - 8990:8990
>       - 1401:1401
>     depends_on:
>       - redis
>       - rabbit-mq
>     environment:
>       REDIS_CLIENT_HOST: redis
>       AMQP_BROKER_HOST: rabbit-mq
>   
> jasmin_celery:
>     image: jookies/jasmin:0.10
>     restart: unless-stopped
>     container_name: jasmin_celery
>     depends_on:
>       - rabbit-mq
>       - redis
>     entrypoint: ["/usr/local/bin/celery", "-A", "jasmin.protocols.rest.tasks", "worker", "-l", "INFO", "-c", "4"]
>     environment:
>       CELERY_BROKER_URL: amqp://guest:guest@rabbit-mq:5672//
>       CELERY_RESULT_BACKEND: redis://:@redis:6379/1
>   
> jasmin_rest:
>     build:
>       context: .
>       dockerfile: Dockerfile.rest
>     restart: unless-stopped
>     container_name: jasmin_rest
>     ports:
>       - 8080:8080
>     depends_on:
>       - jasmin
>       - jasmin_celery
>     entrypoint: ["/usr/local/bin/python", "/usr/local/bin/twistd", "-n", "--pidfile=/tmp/twistd-web-restapi.pid", "web", "--wsgi=jasmin.protocols.rest.api"]
>     environment:
>       JASMIN_OLD_API_URI: http://jasmin:1401
> ```

i tried to do that but still got no rest-api working i only have now two containers having jasmin on it . i still can't run jasmin rest api 
![Capture](https://user-images.githubusercontent.com/92594686/167250239-93324f08-e062-4538-ada0-d9e6b084c95d.PNG)
