### ISSUE TITLE
About Jasmin SMS Gateway

### ISSUE THREAD

**Issue by coinhosting** [jookies/jasmin#705]
Hi,

currently we are using kannel with ksmppd for sms sending our daily traffic is approx 10M sms but we are facing few issue with our current system please help me if jasmin resolve my issue.

1. kannel only ask 1 part DLR from provider incase of long SMS (more then 160 character).
2. TPS Issue for ESME clients. (esme not getting enough TPS)
3. we want to be able to repush DLR to ESME clients.
4. we want retry undelivered (ex if we send an sms from smsc1 and retry with smsc2 incase of  
    undelivered ) without send dlr to esme
5. we want to filter DND / blacklist (from mysql) before proceed to provider

if anybode tested jasmin for high traffic please suggest if this manage our traffic better then kannel

Thanks

**Comment by wordboxltd** [comment]
We can support beyond your expectation on Jasmin or ksmppd

**Comment by wladimiravila** [comment]
@coinhosting I'm trying to handle the same traffic, could I know your server specifications?
