### ISSUE TITLE
DLRs do not get back to smpp client

### ISSUE THREAD

**Issue by sharkovios** [jookies/jasmin#706]
Dear All, 
We are facing a problem with Jasmin and DLRs:
We have a connection with Kannel to Jasmin smpps called foo.
If the Kannel disconnects from jasmin there is some DLRs that are lost (there are nowhere to be found), Kannel didn't received it and jasmin has marked them as unacked in rabbitmq queue.
After we restart the connection (kannel) even these unacked messages are never sent back to the client.
I'm guessing it is a bug?
We are using jasmin (0.9.27) on a Debian 9 (stretch)

Any help would be greatly appreciated

**Comment by farirat** [comment]
What do you get in jasmin's logs (dlr thrower logs) ?

**Comment by sharkovios** [comment]
2018-10-29 14:50:42 DEBUG    5256 DCS Iteration 1/1 taking [cid:foo] (smpps Connector)
2018-10-29 14:50:42 ERROR    5256 Throwing SMPP/DELIVER_SM [msgid:1] to (simple 1/1)[cid:foo], <class 'jasmin.routing.throwers.SystemIdNotBound'>: foo.
2018-10-29 14:50:42 DEBUG    5256 Message try-count is 939 [msgid:1]: requeuing
2018-10-29 14:50:42 DEBUG    5256 Requeuing Content[1] with delay: 30 seconds
2018-10-29 14:50:42 DEBUG    5256 Got one message (msgid:1) to throw: PDU [command: deliver_sm, sequence_number: None, command_status: ESME_ROK
service_type: None
source_addr_ton: None
source_addr_npi: None
source_addr: '3069xxxxxxxxxxxx'
dest_addr_ton: None
dest_addr_npi: None
destination_addr: 'ANT1NEXT'
esm_class: EsmClass[mode: DEFAULT, type: SMSC_DELIVERY_RECEIPT, gsmFeatures: set([])]
protocol_id: None
priority_flag: None
schedule_delivery_time: None
validity_period: None
registered_delivery: None
replace_if_present_flag: None
data_coding: None
sm_default_msg_id: None
short_message: 'id:c8b4d0c3-a585-4903-8de7-64e17345b4d6 sub:001 dlvrd:001 submit date:201810291448 done date:201810291448 stat:REJECTD err:020 text:ok'
message_state: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f93b95ceb10>, 7, 'REJECTED')
receipted_message_id: 'c8b4d0c3-a585-4903-8de7-64e17345b4d6'

I forgot to mention that the DLRs are injected into rabbitmq with a python program

**Comment by farirat** [comment]
Hello, that's clear the DLR were not forwarded because the ESME were not bound at that moment, Jasmin does not retry forwarding the DLR.

**Comment by sharkovios** [comment]
Thats Bad. If a client disconnect, he will not receive his DLR?

**Comment by rio14** [comment]
whta will be the solution for that

**Comment by primeKal** [comment]
i am facing the same problem i set the morouter as the same connector i used to send the mtrouter it to my smsc sim and still my user is bound but says its not

**Comment by primeKal** [comment]
I think  the connector id needs to be the same name as the user id, in morouting instead of asking to get connector id it should take user name
