### ISSUE TITLE
submit_throughput is applied to "logical" message, not to message parts for multipart message

### ISSUE THREAD

**Issue by sputtene** [jookies/jasmin#708]
Hi,

My setup is this:
* **Client**: Jasmin, smppc connection to server, `submit_throughput` is **1**
* **Server**: Jasmin, TRX connection with client, `mt_messaging_cred quota smpps_throughput` set to **10.0** for the client

Sending single-part messages from the client to the server works fine.

When sending multipart messages on the other hand, the server refuses with a **ERROR/ESME_RTHROTTLED** status.

In the server log, this looks like:
> QoS: submit_sm_event is faster (0:00:00.004376) than fixed throughput (0:00:00.100000) for user (smpp-handset), rejecting message.

In the jasmin source code, I see that on the sending side the rate limiting is applied to complete messages, not per part of a multipart message.

See https://github.com/jookies/jasmin/blob/master/jasmin/managers/listeners.py lines 147-167 (calculation of the slowdown according to the configured rate limiting) and lines 230-235 (submitting the message as one unit).

**Proposed fix:** Either the sending side should take rate limiting into account per message part, not per complete message or the receiving part should not apply rate limiting to message parts belonging to a multipart message, but consider the multipart message as one unit to count against the threshold.

Kind regards,
Sven

**Comment by farirat** [comment]
Confirmed behaviour, Jasmin is counting the whole multipart message instead of each part, the rate limiting must be aware of multiparts and make the control based on it.

**Comment by sputtene** [comment]
Hi @farirat,

I'd like to fix this (by making the sending code aware of rate limiting and applying the delay between sending not only messages, but also between each part of multipart messages.

I haven't been able to set up a decent environment where I can run the current unit tests successfully, so I'm hesitant to modify the existing code.

Can you assist me (possibly through direct message/email) to get things set up or point me to instructions on how to get a functioning development environment?
I prefer to use a virtualenv, so there is no cross contamination between my OS Python deployment and the jasmin codebase.

If not, I'll just test my modifications by just running them.

**Comment by farirat** [comment]
You can follow the build log here: https://travis-ci.org/jookies/jasmin/builds/450057390
In order to get a running instance.

**Comment by sputtene** [comment]
Super, thanks!

I'll see if I can fix the bug and I'll send you a PR.

Because of time constraints, I'll probably not be able to do that before the weekend though.

**Comment by fpalamour** [comment]
Any news about this ? Setting the throughput on application that can randomly either send multi-part or not, is rather difficult, because you can't guess the message size.
