### ISSUE TITLE
Fine-grained log format?

### ISSUE THREAD

**Issue by sputtene** [jookies/jasmin#709]
Hi,

Is it possible to configure a `log_format` with fine-grained control over what is logged an what isn't?

I only see `%(message)s` in the `log_format` in the config file, but `message` contains everything (sender, receiver, status, but also content).

I'd like to remove the message content from the log entries, because that's very privacy sensitive.

I have looked to the documentation, but I can't find the answer to this question there.

**Comment by farirat** [comment]
This is duplicate to #691 and will be delivered in 0.9.28 mid December.

**Comment by sputtene** [comment]
Thanks! I'll hold out until then :)
