### ISSUE TITLE
Website damaged

### ISSUE THREAD

**Issue by Falke-Design** [jookies/jasmin#714]
Hello,
I wanted to inform me about the project, and then I saw that the website ([https://www.jasminsms.com/](https://www.jasminsms.com/)) is damaged.
If you go on About, Download or Support a 404 Error is showing.

These Erros make the project a bit dubious and cause new users to doubt. 
Best fix it quickly.

**Comment by farirat** [comment]
Fixed, thank you @Falke-Design !
