### ISSUE TITLE
Jasmin stop sending message when RabbitMQ consume more than 3G of RAM

### ISSUE THREAD

**Issue by tuilaga85** [jookies/jasmin#715]
Hi, we are now faced with problems with Jasmind system. We deploy 5 jasmin instances, each instance have 4 cores and 8G Ram, 1 RabbitMQ instance with 8 cores / 16G Ram. 
TPS is now 2-30/each. But when pushing message into queue more than 300k , it cost more than 3G RAM in RabbitMQ instance, half of number is unacked message and jasmind system stop sending message. 
After 2-3 hours, when unacked messages are gone, system will resume. Please help us to find the problems here
![2019-01-04_19-49-30 jasmin](https://user-images.githubusercontent.com/3398550/50689134-f977f480-105a-11e9-9f44-10699033b5a8.png)

**Comment by farirat** [comment]
Hello there,

Is every Jasmin instance stressed with 30 MPS ? what kind of messages are going unacked ? (in which queue) ?

Did you tune-up rabbitmq to make use of the 8c/16g ram config ?
