### ISSUE TITLE
dst_ton connector setting not working @0.9b27

### ISSUE THREAD

**Issue by 2naive** [jookies/jasmin#717]
@farirat hi! I got version 0.9b27 from http://bit.ly/jasmin-deb-repo  and still have the same problem:

```
jcli : smppccm -s tele2
dst_ton 1
dst_npi 1
src_npi 0
src_ton 5
```

```
2019-01-14 16:20:37 DEBUG    1208 Sending PDU: PDU [command: submit_sm, sequence_number: 38, command_status: ESME_ROK
service_type: ''
source_addr_ton: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f4874ed9990>, 5, 'ALPHANUMERIC')
source_addr_npi: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f4874ed9c50>, 4, 'UNKNOWN')
dest_addr_ton: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f4874ed9990>, 4, 'NATIONAL')
dest_addr_npi: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f4874ed9c50>, 9, 'ISDN')
esm_class: EsmClass[mode: STORE_AND_FORWARD, type: DEFAULT, gsmFeatures: set([])]
protocol_id: 0
priority_flag: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f4874f94f90>, 0, 'LEVEL_0')
schedule_delivery_time: None
validity_period: None
registered_delivery: RegisteredDelivery[receipt: NO_SMSC_DELIVERY_RECEIPT_REQUESTED, smeOriginatedAcks: set([]), intermediateNotification: False]
replace_if_present_flag: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f4874ed9450>, 0, 'DO_NOT_REPLACE')
data_coding: DataCoding[scheme: DEFAULT, schemeData: UCS2]
sm_default_msg_id: 0
short_message: '\x00T\x00e\x00s\x00t\x001'
]
```

```
2019-01-14 03:00:12 DEBUG    1208 Sending PDU: PDU [command: bind_transceiver, sequence_number: 1, command_status: ESME_ROK
system_type: ''
interface_version: 52
addr_ton: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f48766d02d0>, 3, 'UNKNOWN')
addr_npi: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f48766d0990>, 4, 'UNKNOWN')
address_range: None
]

```

So my provider says I use wrong dest_addr_ton. How may I fix it?

Thanks in advance!

_Originally posted by @2naive in https://github.com/jookies/jasmin/issues/104#issuecomment-454009168_

**Comment by 2naive** [comment]
So finally it saved and worked:
```
source_addr_ton: 'ALPHANUMERIC'
source_addr_npi: 'UNKNOWN'
dest_addr_ton: 'INTERNATIONAL'
dest_addr_npi: 'ISDN'
```
-- I didn`t get how resetting and restarts helped.

Closed.

**Comment by 2naive** [comment]
> jcli : smppccm -s tele2
> dst_ton 1
> 

> dest_addr_ton: EnumValue(<jasmin.vendor.enum.Enum object at 0x7faad2081a50>, 4, 'NATIONAL')


-- again the same

**Comment by 2naive** [comment]
So I do able to change it via interceptor:

> from jasmin.vendor.smpp.pdu.pdu_types import AddrTon
> routable.pdu.params['dest_addr_ton'] = AddrTon.INTERNATIONAL

but still cannot manage it through 
> smppccm -u

**Comment by farirat** [comment]
Hello

Setting the value through smppccm is like indicating to Jasmin which value to consider if the smpp client did not set the value, you are setting a -default- value that can be overwrited by smpp client, i guess this is what's happening in your case.

Intercepting is a better approach if you want to -force- and take control of what's getting routed through Jasmin.

Hope this is making things clear

**Comment by 2naive** [comment]
@farirat thanks for your reply and clarification!

Let my make it mor clear:
I've got X smpp clients _(let's assume they have the same ton/npi settings)_, and I do have several SMSC connections via SMPP clients are routed to based on mcc/mnc logic.

SMSC has different settings for npi/ton. So in that case and based on your answer -- is it possible to restrict clients to rewrite SMSC connectors settings?

The other way I see is to rewrite it by myself in interceptor, but it seems strange to me, because each connector already have this information.

If it's not possible to forbid for clients to overwrite it, may I still easy get the connector settings in interceptor to replace?

Thanks for your help!

**Comment by sgupta0498** [comment]
@2naive  
I did change the interceptor values with
`routable.pdu.params['source_addr_npi'] = AddrNpi.ISDN
routable.pdu.params['dest_addr_npi'] = AddrNpi.ISDN`

but still i got the pdu 

`source_addr_npi: EnumValue(<jasmin.vendor.enum.Enum object at 0x7fb0a67fc6d0>, 9, 'ISDN')`
`dest_addr_npi: EnumValue(<jasmin.vendor.enum.Enum object at 0x7fb0a67fc6d0>, 9, 'ISDN')`

there is an error in mapping the key and values 

my `jasmin scppccm -s connector` setting is
`src_ton 5
dst_ton 1
src_npi 1
dst_npi 1`


Please help

Thanks in advance

**Comment by Divyesh22598** [comment]
jasmind service not available error occur. How can i fix it?
