### ISSUE TITLE
GSM 7 bit default alphabet problems

### ISSUE THREAD

**Issue by bdelosrios** [jookies/jasmin#725]
Hi

I’m forcing both side of the smpp channel with gsm7, however special characters (like áéíóú) keep having troubles in the destination cellphone.

Here I have 2 examples:

Sent message 1: @
Received message 1: ¿

Sent message 2: @£$¥èéùìòÇ\nØø\rÅåΔ_ΦΓΛΩΠΨΣΘΞ\x1bÆæßÉ !\"#¤%&'()*+,-./0123456789:;<=>?¡ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÑÜ`¿abcdefghijklmnopqrstuvwxyzäöñüà

Received message 2: ¿¿¿¿¿e¿¿¿¿\n¿
\r¿¿¿¿¿¿¿¿¿¿¿¿¿\x1b¿¿¿E !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\NU¿'abcdefghijklmnopqrstuvwxyz{|nu¿

Thank you in advance, 
Boris

**Comment by Arcusgi** [comment]
Hi boris, 

Did you use the same alphabet for displaying? 

GSM7 = ¡
ANSI = @ 
HEXA = 0x00

Some characters are not implemented in ANSI alphabet, ex: $, ¥, è, é, ù, etc. that maybe why you have got lot of ¿ 

Perhaps you should display the hex values of the message payload.
