### ISSUE TITLE
Sending sms with filters to specific connectors(tag filters)

### ISSUE THREAD

**Issue by atagdev** [jookies/jasmin#727]
We tried to send bulk text messages, using this link -> http://ip:port/secure/sendbatch and the json body is as provided below:- 
 {
    "messages": [
    {
        "to": [
        "1234567890"
        ],
        "content"test"
    }
  ],
}  
We were able to send the texts, but requirement is to add tag filters to route them to the specific connectors. So how can we add tags, so that we can send these tags along with the body. Something similar to the provided eg:-
{
    "messages": [
    {
        "to": [
        "1234567890"
        ],
        "content"test"
    }
  ],
    "tags": "tag"
}
Is this possible?

**Comment by farirat** [comment]
No ...

Tagging can only be done through interception mechanism.
