### ISSUE TITLE
long message rest api

### ISSUE THREAD

**Issue by sayanmohsin** [jookies/jasmin#728]
how do i send long message with RestApi?

**Comment by farirat** [comment]
You just send your long text, Jasmin will slice it and run it on the wire.

**Comment by Divyesh22598** [comment]
I'm trying to send multi sms with restapi. but not delivered on my mobile. so i/m check my log file i got error please fix this error.

**2019-03-29 23:09:27 ERROR    17948 [412] jasmin@127.0.0.1 POST /secure/sendbatch**
