### ISSUE TITLE
Missing DLR's issue

### ISSUE THREAD

**Issue by mexicarne** [jookies/jasmin#729]
Hello, we have an often reproducible problem of not getting DLR to dlr_url, while we have these DLRs in smpp dump.

**Here is example:**

- We sent 5 messages from the single A-number to single B-number.
- We sent them with dlr_level=3 and dlr_url=http://localhost/dlrhub (this service is at the same host where jasmin is)
- We seeing 5 DLR's from upstream smsc in smpp dump (the dump has been done at jasmin host)
- We seeing 8 http requests to our dlrhub from jasmin: 5/5 with dlr_level=1, and 3/5 with dlr_level=2

So the question is why two lvl2 DLRs were not sent to us by jasmin and what we can do with this?

**Attached files in archive**:
dlr_dump.pcap - dump containing 5 DLRs from upstream smsc
dlrhook.txt - http requests from jasmin we got at dlr_url
dlrlookupd-messages.txt - relevant records from dlrlookupd-messages.log
dlr-throver.txt - relevant records from dlr-throver.log

Here are our **jasmin queue id -> smsc_id** (from dlr dump) mapping:

**DLRs we got from jasmin:**

>                  jasmin queue_id                       smsc_id
> 643aabc5-b304-4743-862d-57997b6ba8ce | 6095762
> 2382170f-706d-4821-b5dc-6f97184b771e | 6095714
> 42454613-1c4c-4f87-9bef-5d265f6cced2 | 6095666

**DLRs we haven't got from jasmin**

>                jasmin queue_id                          smsc_id
> ce6e21ce-dc39-4610-b1c6-7408a615b1ef | 6095554
> de73867e-77da-4b84-bf41-d395c6d39d85 | 6095762

At least for 6095554 I see this in dlrlookupd log, but it have nothing for 6095762:
`
[msgid:6095554] (final) DLRMapNotFound: Got a DLR for an unknown message id: 0006095554 (coded:6095554)`

Thank you!

**Comment by mexicarne** [comment]
@farirat I sent JSD-694 about this bug

**Comment by mexicarne** [comment]
Bug in jasmin. Fixed ourself. 

Can't recommend official paid support btw. We paid €80 for resolution of this issue, and got nothing except some general recommendations. After the funds were automatically transferred withing peopleperhour.com deal, they just stopped to respond.

**Comment by hadpro24** [comment]
> Bug in jasmin. Fixed ourself.
> 
> Can't recommend official paid support btw. We paid €80 for resolution of this issue, and got nothing except some general recommendations. After the funds were automatically transferred withing peopleperhour.com deal, they just stopped to respond.

maxicarne, how to do you fixed this probleme ?
