### ISSUE TITLE
HTTP API Error

### ISSUE THREAD

**Issue by ZeeshanSultan** [jookies/jasmin#740]
I tried to setup a basic installation. Everything worked smoothly.
SMPP Connectivity is established since i can also receive incoming messages from SMSC.
Outbound messages not working giving the following error

Here's my python code for sending the message
```
import urllib2
import urllib
baseParams = {"username": "switch", "password": "switch", "to": "92300xxxxxxx", "content": "Hello"}
urllib2.urlopen("http://127.0.0.1:1401/send?%s" % urllib.urlencode(baseParams)).read()


```

/var/log/jasmin/messages.log

> 2019-04-17 10:37:43 INFO     19078 SMS-MT [cid:TestConn] [queue-msgid:355dd405-0249-4556-a8b9-aabf50807e39] [status:ERROR/RESERVEDSTATUS_UNKNOWN_STATUS] [retry:False] [prio:0] [dlr:NO_SMSC_DELIVERY_RECEIPT_REQUESTED] [validity:none] [from:None] [to:92300xxxxxxx] [content:'Hello']

**Comment by farirat** [comment]
This is an error status returned from your upstream, did you check with it ?

**Comment by hzcodertr** [comment]
did you add from parameters ???
