### ISSUE TITLE
jasminsms.com marked as Phishing site in Chrome

### ISSUE THREAD

**Issue by Sevyls** [jookies/jasmin#743]
Jasminsms.com is marked as a phishing site in Chrome. Please fix.

**Comment by Swabuu** [comment]
I'm having the same issue once in a while. I'm getting re-directed a few times and then I finally land on (for now) on the below website.

Link: http://friendly-animals.com/current-business.asp

**Comment by farirat** [comment]
Issue fixed, thank you !

**Comment by AndrewGretton** [comment]
This is now reoccuring; have checked from a number of separate web browsers on different machines @farirat
