### ISSUE TITLE
using JasminSMS as router between two CPs

### ISSUE THREAD

**Issue by atari83** [jookies/jasmin#744]
Hello there,

I've a scenario that I wish I could use JasminSMS to implement it.
So, there is a Content provider (CP1) that wish to communicate with my system (the Router[JasminSMS]) and I need to transfer the messages to other content provider (CP2).

CP1 can deliver the messages through SMPP and REST API. please correct me if i'm mistaken here but i think Jasminsms supports both of these ways to receive the messages. (all good here)

However, CP2 can only accept the messages though REST API, there is no SMPP support at their end. 

Is the any feature / connector exist in Jasmin that I could use to deliver the messages to the second CP ?

Thanks.

**Comment by bagherfathi** [comment]
No

**Comment by farirat** [comment]
@atari83 you're in need of a http/rest upstream connector, this is a commercially licensed product, please file a request to support@jasminsms.com if interested.
