### ISSUE TITLE
providers that work best with jasmin

### ISSUE THREAD

**Issue by prontell** [jookies/jasmin#746]
My team and I are new to jasmin and we were wondering if you can recommend some providers that are affordable and that can work well with jasmin.
Can you use jasmin without a sms provider?
Thanks for your help!

**Comment by JohnGDalrymple** [comment]
If you are still interested I would recommend my company - Mobex.  We use Jasmin.  John@mobex.biz

**Comment by farirat** [comment]
Unfortunately you cannot use Jasmin without a telecom provider access to send/receive messages.

**Comment by JohnGDalrymple** [comment]
We are happy to provide access to send/receive messages via Jasmin
