### ISSUE TITLE
Can't get StaticMTRoute to work

### ISSUE THREAD

**Issue by mustaf4sh** [jookies/jasmin#749]
Hi all. I have several SMSC providers and based on the MT destination address I choose one of the connectors and forward the message through that SMSC. For this to work I have created below filters:

    jcli : filter -l
    #Filter id           Type                            Routes     Description
    #DESTFLTR1     DestinationAddrFilter  MO MT  <DA (dst_addr=^72[0-9]{7}$)>
    #DESTFLTR2     DestinationAddrFilter  MO MT  <DA (dst_addr=^79[0-9]{7}$)>
    Total Filters: 2

Then I have created below MT routers:

    jcli : mtrouter -l
    #Order Type             Connector ID(s)    Filter(s)
    #1     StaticMTRoute    smppc(VAS_CON_1)   <DA (dst_addr=^72[0-9]{7}$)>, <DA (dst_addr=^79[0-9]{7}$)>
    #0     DefaultRoute     smppc(VAS_CON_1)
    Total MT Routes: 2

Above you can see the default route and route with order 1 both use the same connector, so when I send a message through HTTP API it uses the default connector and sends message successfully. But when I change the DefaultRoute it doesn't work anymore. 

Example number: 790853487

I have used below regular expressions as well and none of them worked

^79|2\d{7}$
^79|2\\d{7}$
72|9\d{7}

It looks like the filters are invalid.

**Comment by farirat** [comment]
Try this: ^7(9|2)\d{7}$

**Comment by mustafashujaie** [comment]
It didn't work :(
