### ISSUE TITLE
CPU usage going high once sending SMS

### ISSUE THREAD

**Issue by sbirnd** [jookies/jasmin#755]
Hi there,
I am trying to send 50K SMS using jasmin. But during sending these SMS, jasmin process consuming complete available CPU (mostly above 70%) and due to this system started hangging and MPS reduce from 27 MPS to 2 MPS.

After my analysis I found below processes are taking too much CPU.
jasmind.py --> 75% CPU and 0.8% RAM
dlrlookupd.py --> 50.5% CPU and 0.9% RAM

Could some one please help me on this? Hope you expert can help me to overcome his issue.

**Comment by juanantoniotv** [comment]
Did you set submit_throughput (Messages per second) on the smppccm connector?

**Comment by sbirnd** [comment]
> Did you set submit_throughput (Messages per second) on the smppccm connector?

Yes, I did. "submit_throughput 50"

**Comment by sbirnd** [comment]
Any one can please help me on this?

**Comment by KyuAlex** [comment]
I also have the same problem
![image](https://user-images.githubusercontent.com/19887575/60393523-b56d3480-9b51-11e9-8299-211500647597.png)
Is there anyway to support multi thread?

**Comment by farirat** [comment]
For 50 MPS are you pushing through http or smpp api ? what's the rate of your pushing ?

**Comment by KyuAlex** [comment]
SMPP

**Comment by farirat** [comment]
> what's the rate of your pushing ?

**Comment by sbirnd** [comment]
30-45 MPS

**Comment by vinhduy11** [comment]
I also have the same problem. I use SMPP Client to connect to JASMIN to send SMS. SMS send unstable sometime because high CPU. How can I config JASMIN for multicore CPU??
