### ISSUE TITLE
"connector/cid" params  in the dlr response is missing

### ISSUE THREAD

**Issue by nikhilrivet** [jookies/jasmin#758]
hello Team
can anyone help me. I set the dlr level at 3 but "connector/cid" param in DLR respone is missing
This is my response

{"message_status"=>"DELIVRD", "donedate"=>"190710204927", "sub"=>"001", "err"=>"ND", "level"=>"2", "text"=>"", "id_smsc"=>"6F09BDC7-94A1-4B9D-BC96-EC66AABF10C2", "dlvrd"=>"001", "subdate"=>"190710204925", "id"=>"c57b6a08-40d5-4acb-9402-03632f54b2a4"}

Regards 
Nikhil thomas

**Comment by nikhilrivet** [comment]
Anyone please help me, i am new in jasmin.

**Comment by farirat** [comment]
Did you check if your upstream provider forwarded a terminal level dlr already ?
