### ISSUE TITLE
How can MO to a given mobile number be routed to Jasmin server?

### ISSUE THREAD

**Issue by piosystems** [jookies/jasmin#759]
I am trying to implement Jasmin server for sending MT messages as well as for receiving MO messages. From the documentation, I have not been able to figure out how an MO message from a mobile phone can be routed through the telecoms provider to my Jasmin server. Can mobile number(s) be associated with the Jasmin server? If yes, how?

**Comment by farirat** [comment]
Do your telecom provider send you MO traffic ? if yes, then you will see the inbound messages in messages.log, then you will need to make routings through the morouter jcli module.
