### ISSUE TITLE
Problem with DLR  err:002

### ISSUE THREAD

**Issue by rodolfoaRAVEN** [jookies/jasmin#760]
I need help. My Jasmin gateway sends sms correctly. It works basically by interconnecting with modems gateway with SMPP. My problem is that all the DLRs are reporting with error. I can visualize this in the log default-smpps_01.log always appears **stat: DELIVRD err:002**
How can I interpreat this error **err: 002**?
Should I understand that the message was not delivered then?
Can I somehow remove that error so that it does not appear?

Thanks since now.

**Comment by magojr** [comment]
Got the same error here getting back the DLR that can't be received:
DELIVER_SM [uid:testuser] [from:3912345678] [to:Testsender] [content:'id:fa9542be-3c16-44bb-9a8c-d277ea1851ef submit date:1911211739 done date:1911211741 stat:DELIVRD err:002']
Someone solved this issue?

**Comment by farirat** [comment]
Hello, did you check the originated DLR received from the upstream ? if not, take a tcp capture and check the content of the DLR.

**Comment by magojr** [comment]
Hello farirat, thank you very much for your suggestion.
I'm surely going to check about it but i can receive the correct DLR using the simple php-smpp library when i connect directly to the gateway.
Now that jasmin is between the php-smpp library and the gateway I got this error.

Anyway I need just "id", "stat", and "done date", so the 002 error is not an issue in my workflow.
But seems that it's preventing the DLR to get delivered back:

IN smpp-server-pb.log i see
Caught an error while trying to push pdu through deliverer (system_id:testuser]): (SMPPClientSessionStateError) Unbind received

IN dlr-thrower.log
Throwing SMPP/DLR [msgid:8a50cec6-f454-450b-8147-0e1b6f4166cf] to (testuser]): DeliveringFailed(u'Delivering failed, check testuser] smpps logs for more details',).

I'm not experienced on jasmin, maybe i'm missing some configs but I was figuring DLRs was keeped in some queues waiting to be read for a while, as I was doing before directly with the SMPP gateway.
Isn't it?

Any help is very apreciated, I will be back with tcpdump.
Thank you

**Comment by magojr** [comment]
UPDATE
dumping TCP, converting to HEX, searching for deliver_sm command, I found the DLR PDU **received by Jasmin from the gateway**:
"id:bec4271c-2d65-4352-aa67-4c01ba5c0f1f sub:001 dlvrd:001 submit date:1911220809 done date:1911222009 stat:DELIVRD err:000 text: "

Then I dumped the PDU **received by my app from Jasmin:**
"id:67b682d7-cb20-46ef-9b20-4f88ae3a92b0 submit date:1911221303 done date:1911221307 stat:DELIVRD err:002"

The format is wrong/uncomplete and err 002 seems to be linked to a wrong error length but the length of the original error code (000) is right (it should be 1-4 byte), also other fields are missing: _sub_, _dlvrd_ and _text_ (just a white char but usefull to correctly parse the DLR).

I need to send back the same DLR I receive from the Gateway, how should I configure jasmin to do so?
Thnak to anyone for helping.

**Comment by farirat** [comment]
Hello @magojr 

Issue identified and adressed in 0.9.32, will be delivered very soon.

Thx

**Comment by magojr** [comment]
Hello farirat,
thank you for your fix, I reply also here to keep track of it.
I take a look into the code and ther's something wrong into the "message" part of the pdu in the DLR, according with the SMPP protocol http://opensmpp.org/specs/SMPP_v3_4_Issue1_2.pdf (Appendix A, page 167)  they should contain fields like in this sample: “id:IIIIIIIIII sub:SSS dlvrd:DDD submit date:YYMMDDhhmm done
date:YYMMDDhhmm stat:DDDDDDD err:E Text: . . . . . . . . .”.
In the practical usage, text are quite always a blank space even if it may be 20 characters, the other fields needs to be present. 
Inside operations.py the content is based on r"id:%s submit date:%s done date:%s stat:%s err:%03d" so the format itself is not the correct one, 3 fields are missing and parser doesn't accept them.
I'm going to correct it but there aren't at all variables to insert data for the sub (Number of short messages originally submitted), dlvrd (Number of short messages delivered) so I'm going to insert them as fixed value waiting for a fix that bring the original DLR values here in this method. 
I see your comment that the DLR must be refactored and "@todo: get the real err from original dlr received in jasmin.managers.dlr.DLRLookup.deliver_sm_dlr_callback".
Mot sure, maybe you was already on the point....
Thank you

**Comment by magojr** [comment]
here the code i modified to switch to a correct DLR "format" starting on the 255 line of the protocols/smpp/operations.py file, data is not correctat all, it remain a workaround, real data need to be take from the original DLR but now my jasmin is generating DLR that can be read correctly from other apps and SMPPs without giving any error in parsing.
Added just the dlivrd variable... and update the format.
Hope it can help
`        sm_message_stat = message_status
        dlvrd = 0
        # Prepare message_state
        if message_status[:5] == 'ESME_':
            if message_status == 'ESME_ROK':
                message_state = MessageState.ACCEPTED
                sm_message_stat = 'ACCEPTD'
                err = 6
                dlvrd = 1
            else:
                message_state = MessageState.UNDELIVERABLE
                sm_message_stat = 'UNDELIV'
                err = 5
        elif message_status == 'UNDELIV':
            message_state = MessageState.UNDELIVERABLE
            err = 5
        elif message_status == 'REJECTD':
            message_state = MessageState.REJECTED
            err = 8
        elif message_status == 'DELIVRD':
            err = 0
            dlvrd = 1
            message_state = MessageState.DELIVERED
        elif message_status == 'EXPIRED':
            err = 3
            message_state = MessageState.EXPIRED
        elif message_status == 'DELETED':
            err = 4
            message_state = MessageState.DELETED
        elif message_status == 'ACCEPTD':
            err = 6
            dlvrd = 1
            message_state = MessageState.ACCEPTED
        elif message_status == 'ENROUTE':
            err = 1
            dlvrd = 1
            message_state = MessageState.ENROUTE
        elif message_status == 'UNKNOWN':
            err = 7
            dlvrd = 1
            message_state = MessageState.UNKNOWN
        else:
            raise UnknownMessageStatusError('Unknow message_status: %s' % message_status)

        # Build pdu
        if dlr_pdu == 'deliver_sm':
            short_message = r"id:%s sub:%03d dlvrd:%03d submit date:%s done date:%s stat:%s err:%03d text: " % (
                msgid,
                1,
                dlvrd,
                parser.parse(sub_date).strftime("%y%m%d%H%M"),
                datetime.datetime.now().strftime("%y%m%d%H%M"),
                sm_message_stat,
                err,
            )
`

**Comment by farirat** [comment]
> Hello farirat,
> thank you for your fix, I reply also here to keep track of it.
> I take a look into the code and ther's something wrong into the "message" part of the pdu in the DLR, according with the SMPP protocol http://opensmpp.org/specs/SMPP_v3_4_Issue1_2.pdf (Appendix B, page 167) they should contain fields like in this sample: “id:IIIIIIIIII sub:SSS dlvrd:DDD submit date:YYMMDDhhmm done
> date:YYMMDDhhmm stat:DDDDDDD err:E Text: . . . . . . . . .”.
> In the practical usage, text are quite always a blank space even if it may be 20 characters, the other fields needs to be present.
> Inside operations.py the content is based on r"id:%s submit date:%s done date:%s stat:%s err:%03d" so the format itself is not the correct one, 3 fields are missing and parser doesn't accept them.
> I'm going to correct it but there aren't at all variables to insert data for the sub (Number of short messages originally submitted), dlvrd (Number of short messages delivered) so I'm going to insert them as fixed value waiting for a fix that bring the original DLR values here in this method.
> I see your comment that the DLR must be refactored and "@todo: get the real err from original dlr received in jasmin.managers.dlr.DLRLookup.deliver_sm_dlr_callback".
> Mot sure, maybe you was already on the point....
> Thank you

@magojr the message content of a dlr is not **strictly** defined by the smpp specs, it says the following:

> The informational content of an SMSC Delivery Receipt may be inserted into the
> short_message parameter of the deliver_sm operation. The format for this Delivery Receipt
> message is SMSC **vendor specific** but following is a typical **example** of Delivery Receipt report.
> 
> “id:IIIIIIIIII sub:SSS dlvrd:DDD submit date:YYMMDDhhmm done
> date:YYMMDDhhmm stat:DDDDDDD err:E Text: . . . . . . . . .”

Thus said, Jasmin have it's own DLR text format as defined here: https://github.com/jookies/jasmin/blob/0.9.31/jasmin/protocols/smpp/operations.py#L294.

I'm going to fix the **err:** value transmission from original dlr to forwarded one through this ticket, target is 0.9.32.

**Comment by magojr** [comment]
Hello farirat,
thank you for addressing the full flow for the error 002.
You are right, it's not **strictly** defined but (IMHO) that scheme become a de-facto standard, used from most of the upstream gateway so that's what anyone is expecting to get back. Just a sample, the (widely used) php-smpp library use this regexp to parse the DLR content:
/^id:([^ ]+) sub:(\d{1,3}) dlvrd:(\d{3}) submit date:(\d{10,12}) done date:(\d{10,12}) stat:([A-Z ]{7}) err:(\d{1,3}) text:(.*)$/si

As aleady said, you are right, this regexp is clearly the wrong piece of code here... it should check for any single fields and give back only those present, but it's he most used library in php SMPP implementation for what i know so it may be a good target of software that can connect to jasmin as client.

It would be great in my opinion to have a way (maybe in the cfg file) to switch to this (widely used) format. I'm going to pass also the 2 missing fields from the original DLR (if present), following the changes made in the last commit, I can share that code if you are interested.

**Comment by farirat** [comment]
Hello @magojr 

Will address the extra items in a later opportunity, or maybe a PR is welcomed ;)

Although still not packaged, 0.9.32 branch is stable and you can make your tests.

I'm working actually on python 3 port and willing to merge into 0.9.32, if not possible then will be partial work for next releases, this is why 0.9.32 may get delayed a bit.

**Comment by magojr** [comment]
Hello @farirat,
thank you, actually I updated to the branch 0.9.32 as suggested and re-inserted inside the code my workaround in order to have the format I need for the DLR.

I recompiled the pyc using the commad " python -m py_compiler operations.py " but the pyc is smaller than the previous one and it shouldn't because I added a variable and some static bytes...
Am I missing something?

I will create a PR but consider I don't code in Python since 7/8 years (except these few lines)... so basically I forgot quite all... I'm surely going to refresh my python and also to better learn Jasmin but... it may take me a quite long time :-)

**Comment by magojr** [comment]
Hello @faritat, 
after update to 0.9.32, got issue in the exception management, 
``
Throwing SMPP/DLR [msgid:ed474394-05f8-4444-8a60-087b1065e6a7] to (testuser): TypeError('%d format: a number is required, not str',).
``
The log is at line 635  in routing/throwers.py but I don't found the place where it's raised. Checking the previous commit it seems the [4498056](https://github.com/jookies/jasmin/commit/44980565388b945c5368270e20302fd0fa94735e) but I'm not sure of that.

**Comment by farirat** [comment]
hey mag

**Comment by farirat** [comment]
Checking, thx !

**Comment by magojr** [comment]
> Checking, thx !

May I help you in some way?
