### ISSUE TITLE
Throwing SSL Handshake Error/Python 3

### ISSUE THREAD

**Issue by burgoyn1** [jookies/jasmin#761]
When I am running the thrower, I get the following error:

`2019-07-16 08:20:31 ERROR    1 Throwing message [msgid:7118a17b-54e3-4c6c-87bb-b5f86676a028] to (simple 1/1)[cid:webhook1] (https://url), <class 'OpenSSL.SSL.Error'>: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')].`

I have checked everything and all the code seems to be running the latest of python 2.7. Anyone have any ideas which could help?

Also, is there a point where this will be upgraded to python 3 as python 2.7 is going to be deprecated in 5 months.

**Comment by farirat** [comment]
hello @myfriend12 

Are you using a valid/non-expired ssl certificate on your https endpoint ?

We're working on a py3 port to Jasmin.

**Comment by myfriend12** [comment]
Yes. It is my production system. We are running it off of cloudflare and I found out they have disabled sslv3 and only support tls. Currently trying to work on a solution.

As a feature request for upcoming versions, connecting to amqps would also be awesome.

**Comment by Damilola0612** [comment]
@myfriend12 , I was about asking the same question you raised. my company is working on a pplication that would need to incorporate SMS gateway and while researching, we decided on jasmin. but this issue with jasmin using python 2.7 is really a disadvantage.
![image](https://user-images.githubusercontent.com/24529726/67276693-2481e680-f4bd-11e9-9cb6-1d8b83d8f7a8.png)

**Comment by hzcodertr** [comment]
install windows ubuntu subsystem :)

**Comment by myfriend12** [comment]
@Damilola0612 I had to rewrite some of the jasmin code regarding sending the request to get it to work properly.

**Comment by phil-lavin** [comment]
@burgoyn1 : can you advise what the fix is for this? HTTPS on endpoints that don't support SSLv3 is completely broken, it seems.

**Comment by burgoyn1** [comment]
@phil-lavin Honestly, there were many issues I came across regarding jasmin that I ended up ditching it and using a product called Diafaan instead.

Regarding this though, I believe I ended up replacing the http class they are using with the built in requests class, but I don't remember exactly. I only left this open because it is still an issue which needs fixing.

**Comment by farirat** [comment]
Jasmin is now ported to python 3.6+ in release 0.10
