### ISSUE TITLE
Unknown messsage id issue in dlrlookupd-messages.log

### ISSUE THREAD

**Issue by nikhilrivet** [jookies/jasmin#763]
Hello 
 i am getting this issue while sending messages
2019-07-18 13:41:38 ERROR    15233 [msgid:78634E33-F57D-478B-8562-6FDB3C9D767C] (retrials: 1/2) DLRMapNotFound: Got a DLR for an unknown message id: 78634e33-f57d-478b-8562-6fdb3c9d767c (coded:78634E33-F57D-478B-8562-6FDB3C9D767C)

Please help me in this

**Comment by farirat** [comment]
Are you experiencing latency issues ? which version of Jasmin are you using ?

**Comment by nikhilrivet** [comment]
Yes i am facing latency issue. Using jasmin V 0.09

**Comment by farirat** [comment]
Please provide more info about your use case.

**Comment by nikhilrivet** [comment]
Hi guys,
My issue is fixed.
The problem occurred with the dlrd.py process. when i start jasmin, 'dlrd.py' was not processing then i removed the file in /tmp/*.lock then it worked well.
