### ISSUE TITLE
send message

### ISSUE THREAD

**Issue by ezra-he** [jookies/jasmin#768]
Hi all，
There are some confused during starting jasmin to send sms, I download the source from git and run jasmind.py, and do some configuration following the install document, and request http://127.0.0.1:1401/send?username=foo&password=bar&to=06222172&content=hello. then the data has been published,the question as bellow:

1. How should I consume this message? the message status is ready

2. There is no log in message.log, default-DEMO_CONNECTOR.log, default-smpps_01.log.

ps:
-rw-r--r--. 1 root root 3165 8月  29 10:37 amqp-client.log
-rw-r--r--. 1 root root    0 8月  29 09:53 default-DEMO_CONNECTOR.log
-rw-r--r--. 1 root root    0 8月  29 09:42 default-smpps_01.log
-rw-r--r--. 1 root root  837 8月  29 10:32 deliversm-thrower.log
-rw-r--r--. 1 root root  122 8月  29 10:37 dlrlookupd-messages.log
-rw-r--r--. 1 root root 1540 8月  29 10:34 http-accesslog.log
-rw-r--r--. 1 root root  918 8月  29 10:34 http-api.log
-rw-r--r--. 1 root root 2171 8月  29 10:34 jcli.log
-rw-r--r--. 1 root root    0 8月  29 09:53 messages.log
-rw-r--r--. 1 root root 8000 8月  29 10:37 redis-client.log
-rw-r--r--. 1 root root 4308 8月  29 10:34 router.log
-rw-r--r--. 1 root root  156 8月  29 10:34 service-smppclient.log
-rw-r--r--. 1 root root 1536 8月  29 10:34 smppclient-manager.log
-rw-r--r--. 1 root root  399 8月  29 10:32 smpp-server-pb.log

Could you pls told me how i can send the sms to my phone, what should i do, thanks.

**Comment by juanantoniotv** [comment]
Did you set smppc Connector?, check if you have a Bound connection:
```
smppccm -l
#Connector id                        Service Session          Starts Stops
#con_75                              started None             1      0    
#con_77                              started None             1      0    
#con_78                              started None             1      0    
#con_81                              started BOUND_TRX        1      0    
#con_82                              started BOUND_TRX        1      0    
#con_83                              started BOUND_TRX        1      0   
```
In my case i have 3 Bound Connections ready to send messages, review if you have a valid StaticMTRoute or RandomRoundrobinMTRoute.

**Comment by ezra-he** [comment]
> smppccm -l



> Did you set smppc Connector?, check if you have a Bound connection:
> 
> ```
> smppccm -l
> #Connector id                        Service Session          Starts Stops
> #con_75                              started None             1      0    
> #con_77                              started None             1      0    
> #con_78                              started None             1      0    
> #con_81                              started BOUND_TRX        1      0    
> #con_82                              started BOUND_TRX        1      0    
> #con_83                              started BOUND_TRX        1      0   
> ```
> 
> In my case i have 3 Bound Connections ready to send messages, review if you have a valid StaticMTRoute or RandomRoundrobinMTRoute.

hi, i checked my smpcc connector, it is ready:

Type help or ? to list commands.

Session ref: 5
jcli : smppccm -l                 
#Connector id                        Service Session          Starts Stops
#DEMO_CONNECTOR                      started BOUND_TRX        1      0    
Total connectors: 1
jcli : 
the connector's configure as below:
jcli : smppccm -a
> cid DEMO_CONNECTOR
> host 127.0.0.1
> port 2775
> username smppclient1
> password password
> submit_throughput 110
> ok
Successfully added connector [DEMO_CONNECTOR]


could you pls give me some advice? thanks.

**Comment by hzcodertr** [comment]
add to DLR params. look http api documentation  you must set dlr and dlr-url.
