### ISSUE TITLE
Problem tagging with a custom Python script

### ISSUE THREAD

**Issue by Otaron** [jookies/jasmin#769]
Hi all, 

For local SMS we are connected to the two local providers via SMPP but their international prices are pretty bad so we connected to Nexmo via SMPP, I will probably change to use the HTTP API one day but for now it is the solution that requires less dev.

I made a python script that :
- connect to the Nexmo API to recognize the number and determine the country
- connect to the Nexmo API to determine the price
- Convert the price in Vatu (our local currency and we did 1credit = 1vatu) 

The Python script, while needing some improvement, is working but my goal is now to tag my messages with a tag that would match the price in credit/vatu I got in my script so I can use the right MTRoute with the right rate.

I created a MTinterceptor with the following script but it doesn't seem to be working, any hep would be greatly appreciated :)

```
`import nexmo
import json
import requests
import urllib
from jasmin.routing.Routables import RoutableSubmitSm

nexmo_key = '********'
nexmo_secret = '********'

destination_addr = routable.pdu.params['destination_addr']

#get country
params = {
    'api_key': nexmo_key,
    'api_secret': nexmo_secret,
    'number': destination_addr,
}

url = 'https://api.nexmo.com/ni/basic/json?' + urllib.urlencode(params)

response = requests.get(url)

json_data = json.loads(response.text)

#get price of country
params = {
    'api_key': '*******',
    'api_secret': '********',
    'country':json_data['country_code'],
}

url = 'https://rest.nexmo.com/account/get-pricing/outbound?' + urllib.urlencode(params)

response = requests.get(url)
json_data = json.loads(response.text)

vuprice = round(float(json_data['mt'])*130,0)

routable.addTag(int(vuprice))

result = True
`
```

**Comment by farirat** [comment]
Try to use more logging to debug your script, this is a blind interceptor noone can know why it's not working.

log every step and you'll find the mess

**Comment by Otaron** [comment]
Farirat, 

Indeed my code was quick and dirty and adding logging helped me quite a lot!
The issue was that I did not re-create the router after updating the script....

Thanks and sorry for the disturbance.
