### ISSUE TITLE
wanna add src_addr and dst_addr in the dlr result

### ISSUE THREAD

**Issue by NinjaKimOne** [jookies/jasmin#772]
i'm using restful api to send sms and found when sending bulk sms  , the result from callback_url msgid can't match with the msgid from dlr result, so i wanna add src_hp and dst_hp to the dlr, so i can use these props to match the origin msg i sent, for updating the sent result correctly, but i tried serveral times to modify the source file, all failed in the end, it's so hard for me to start , can anyone help me?

**Comment by davidcsi** [comment]
You should probably do that with an interceptor

**Comment by hzcodertr** [comment]
Jasmin Custom Edition :P
[image: image.png]

**Comment by NinjaKimOne** [comment]
> You should probably do that with an interceptor

is there any sample code?

**Comment by davidcsi** [comment]
search for INTERCEPTOR in the documentation
