### ISSUE TITLE
Underscore removed when using datacoding 0

### ISSUE THREAD

**Issue by KyuAlex** [jookies/jasmin#775]
Hello,

I got a claim from a customer and confirmed it myself.

If I send with datacoding 0 an underscore, it gets removed but if I send with datacoding 1, it works.

Does anyone have same problem?

Thanks

**Comment by farirat** [comment]
Check your bytecoding, is it gsm337 ?

**Comment by KyuAlex** [comment]
it is ascii

**Comment by farirat** [comment]
please show a byte vs. code screenshot, like wireshark outcome, i need to know the exact bytecode used for the _ character representation

**Comment by KyuAlex** [comment]
![image](https://user-images.githubusercontent.com/19887575/68591324-d6686d80-04d3-11ea-9d6e-a2c45a3cdb67.png)

**Comment by farirat** [comment]
I need the message content (in the bottom of the packet details)

**Comment by KyuAlex** [comment]
I sadly can't see anything below on the packet. Should I use specific option with tcpdump?

**Comment by farirat** [comment]
can you send me the pcap file ? if it's private you can send it to bruno.chaudhary@jookies.net
