### ISSUE TITLE
ModuleNotFoundError: No module named 'grp'

### ISSUE THREAD

**Issue by Damilola0612** [jookies/jasmin#779]
I'm running the 'pip install jasmin' command on the cli and I'm this error "ModuleNotFoundError: No module named 'grp'". pls help

**Comment by farirat** [comment]
What's your OS version ? python version ?

**Comment by ZhangYongZhe** [comment]
python3.7

**Comment by farirat** [comment]
py3 were not supported prior to v0.10 of jasmin, please check again now.
