### ISSUE TITLE
Failed to start jasmind service

### ISSUE THREAD

**Issue by najd1001** [jookies/jasmin#780]
Hi all,

I have installed jasmin successfully based on jasmin official docs http://docs.jasminsms.com/en/latest/installation/index.html#ubuntu
, but jasmin failed to start with the following trace:

Oct 24 22:25:27 work-station systemd[1]: Started Jasmin SMS Gateway interceptor.
Oct 24 22:25:27 work-station systemd[1]: Started Jasmin SMS Gateway.
Oct 24 22:25:27 work-station systemd[1]: Started Jasmin SMS Gateway DLR throwing standalone daemon.
Oct 24 22:25:27 work-station systemd[1]: Started Jasmin SMS Gateway DLR lookup standalone daemon.
Oct 24 22:25:27 work-station jasmind[8629]: Traceback (most recent call last):
Oct 24 22:25:27 work-station jasmind[8629]:   File "/usr/bin/jasmind.py", line 11, in <module>
Oct 24 22:25:27 work-station jasmind[8629]:     from twisted.internet import reactor, defer
Oct 24 22:25:27 work-station jasmind[8629]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/reactor.py", line 38, in <module>
Oct 24 22:25:27 work-station jasmind[8629]:     from twisted.internet import default
Oct 24 22:25:27 work-station jasmind[8629]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/default.py", line 56, in <module>
Oct 24 22:25:27 work-station jasmind[8629]:     install = _getInstallFunction(platform)
Oct 24 22:25:27 work-station jasmind[8629]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/default.py", line 44, in _getInstallFunction
Oct 24 22:25:27 work-station jasmind[8629]:     from twisted.internet.epollreactor import install
Oct 24 22:25:27 work-station jasmind[8629]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/epollreactor.py", line 24, in <module>
Oct 24 22:25:27 work-station jasmind[8629]:     from twisted.internet import posixbase
Oct 24 22:25:27 work-station jasmind[8629]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 18, in <module>
Oct 24 22:25:27 work-station jasmind[8629]:     from twisted.internet import error, udp, tcp
Oct 24 22:25:27 work-station jasmind[8629]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 29, in <module>
Oct 24 22:25:27 work-station jasmind[8629]:     from twisted.internet._newtls import (
Oct 24 22:25:27 work-station jasmind[8629]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/_newtls.py", line 21, in <module>
Oct 24 22:25:27 work-station jasmind[8629]:     from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
Oct 24 22:25:27 work-station jasmind[8629]:   File "/usr/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 41, in <module>
Oct 24 22:25:27 work-station jasmind[8629]:     from OpenSSL.SSL import Error, ZeroReturnError, WantReadError
Oct 24 22:25:27 work-station jasmind[8629]:   File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
Oct 24 22:25:27 work-station jasmind[8629]:     from OpenSSL import crypto, SSL
Oct 24 22:25:27 work-station jasmind[8629]:   File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 194, in <module>
Oct 24 22:25:27 work-station jasmind[8629]:     if _lib.Cryptography_HAS_SSL_ST:
Oct 24 22:25:27 work-station jasmind[8629]: AttributeError: 'module' object has no attribute 'Cryptography_HAS_SSL_ST'
Oct 24 22:25:27 work-station interceptord[8628]: Traceback (most recent call last):
Oct 24 22:25:27 work-station interceptord[8628]:   File "/usr/bin/interceptord.py", line 11, in <module>
Oct 24 22:25:27 work-station interceptord[8628]:     from twisted.internet import reactor, defer
Oct 24 22:25:27 work-station interceptord[8628]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/reactor.py", line 38, in <module>
Oct 24 22:25:27 work-station interceptord[8628]:     from twisted.internet import default
Oct 24 22:25:27 work-station interceptord[8628]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/default.py", line 56, in <module>
Oct 24 22:25:27 work-station interceptord[8628]:     install = _getInstallFunction(platform)
Oct 24 22:25:27 work-station interceptord[8628]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/default.py", line 44, in _getInstallFunction
Oct 24 22:25:27 work-station interceptord[8628]:     from twisted.internet.epollreactor import install
Oct 24 22:25:27 work-station interceptord[8628]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/epollreactor.py", line 24, in <module>
Oct 24 22:25:27 work-station interceptord[8628]:     from twisted.internet import posixbase
Oct 24 22:25:27 work-station interceptord[8628]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 18, in <module>
Oct 24 22:25:27 work-station interceptord[8628]:     from twisted.internet import error, udp, tcp
Oct 24 22:25:27 work-station interceptord[8628]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 29, in <module>
Oct 24 22:25:27 work-station interceptord[8628]:     from twisted.internet._newtls import (
Oct 24 22:25:27 work-station interceptord[8628]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/_newtls.py", line 21, in <module>
Oct 24 22:25:27 work-station interceptord[8628]:     from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
Oct 24 22:25:27 work-station interceptord[8628]:   File "/usr/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 41, in <module>
Oct 24 22:25:27 work-station interceptord[8628]:     from OpenSSL.SSL import Error, ZeroReturnError, WantReadError
Oct 24 22:25:27 work-station interceptord[8628]:   File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
Oct 24 22:25:27 work-station interceptord[8628]:     from OpenSSL import crypto, SSL
Oct 24 22:25:27 work-station interceptord[8628]:   File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 194, in <module>
Oct 24 22:25:27 work-station interceptord[8628]:     if _lib.Cryptography_HAS_SSL_ST:
Oct 24 22:25:27 work-station interceptord[8628]: AttributeError: 'module' object has no attribute 'Cryptography_HAS_SSL_ST'
Oct 24 22:25:27 work-station jasmin-dlrlookupd[8631]: Traceback (most recent call last):
Oct 24 22:25:27 work-station jasmin-dlrlookupd[8631]:   File "/usr/bin/dlrlookupd.py", line 10, in <module>
Oct 24 22:25:27 work-station jasmin-dlrlookupd[8631]:     from twisted.internet import reactor, defer
Oct 24 22:25:27 work-station jasmin-dlrlookupd[8631]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/reactor.py", line 38, in <module>
Oct 24 22:25:27 work-station jasmin-dlrlookupd[8631]:     from twisted.internet import default
Oct 24 22:25:27 work-station jasmin-dlrlookupd[8631]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/default.py", line 56, in <module>
Oct 24 22:25:27 work-station jasmin-dlrlookupd[8631]:     install = _getInstallFunction(platform)
Oct 24 22:25:27 work-station jasmin-dlrlookupd[8631]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/default.py", line 44, in _getInstallFunction
Oct 24 22:25:27 work-station jasmin-dlrlookupd[8631]:     from twisted.internet.epollreactor import install
Oct 24 22:25:27 work-station jasmin-dlrlookupd[8631]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/epollreactor.py", line 24, in <module>
Oct 24 22:25:27 work-station jasmin-dlrd[8630]: Traceback (most recent call last):
Oct 24 22:25:27 work-station jasmin-dlrd[8630]:   File "/usr/bin/dlrd.py", line 9, in <module>
Oct 24 22:25:27 work-station jasmin-dlrd[8630]:     from twisted.internet import reactor, defer
Oct 24 22:25:27 work-station jasmin-dlrd[8630]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/reactor.py", line 38, in <module>
Oct 24 22:25:27 work-station jasmin-dlrd[8630]:     from twisted.internet import default
Oct 24 22:25:27 work-station jasmin-dlrd[8630]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/default.py", line 56, in <module>
Oct 24 22:25:27 work-station jasmin-dlrd[8630]:     install = _getInstallFunction(platform)
Oct 24 22:25:27 work-station jasmin-dlrd[8630]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/default.py", line 44, in _getInstallFunction
Oct 24 22:25:27 work-station jasmin-dlrd[8630]:     from twisted.internet.epollreactor import install
Oct 24 22:25:27 work-station jasmin-dlrd[8630]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/epollreactor.py", line 24, in <module>
Oct 24 22:25:27 work-station jasmin-dlrd[8630]:     from twisted.internet import posixbase
Oct 24 22:25:27 work-station jasmin-dlrd[8630]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 18, in <module>
Oct 24 22:25:27 work-station jasmin-dlrd[8630]:     from twisted.internet import error, udp, tcp
Oct 24 22:25:27 work-station jasmin-dlrd[8630]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 29, in <module>
Oct 24 22:25:27 work-station jasmin-dlrd[8630]:     from twisted.internet._newtls import (
Oct 24 22:25:27 work-station jasmin-dlrd[8630]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/_newtls.py", line 21, in <module>
Oct 24 22:25:27 work-station jasmin-dlrd[8630]:     from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
Oct 24 22:25:27 work-station jasmin-dlrd[8630]:   File "/usr/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 41, in <module>
Oct 24 22:25:27 work-station jasmin-dlrd[8630]:     from OpenSSL.SSL import Error, ZeroReturnError, WantReadError
Oct 24 22:25:27 work-station jasmin-dlrd[8630]:   File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
Oct 24 22:25:27 work-station jasmin-dlrd[8630]:     from OpenSSL import crypto, SSL
Oct 24 22:25:27 work-station jasmin-dlrd[8630]:   File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 194, in <module>
Oct 24 22:25:27 work-station jasmin-dlrd[8630]:     if _lib.Cryptography_HAS_SSL_ST:
Oct 24 22:25:27 work-station jasmin-dlrd[8630]: AttributeError: 'module' object has no attribute 'Cryptography_HAS_SSL_ST'
Oct 24 22:25:27 work-station jasmin-dlrlookupd[8631]:     from twisted.internet import posixbase
Oct 24 22:25:27 work-station jasmin-dlrlookupd[8631]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 18, in <module>
Oct 24 22:25:27 work-station jasmin-dlrlookupd[8631]:     from twisted.internet import error, udp, tcp
Oct 24 22:25:27 work-station jasmin-dlrlookupd[8631]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 29, in <module>
Oct 24 22:25:27 work-station jasmin-dlrlookupd[8631]:     from twisted.internet._newtls import (
Oct 24 22:25:27 work-station jasmin-dlrlookupd[8631]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/_newtls.py", line 21, in <module>
Oct 24 22:25:27 work-station jasmin-dlrlookupd[8631]:     from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
Oct 24 22:25:27 work-station jasmin-dlrlookupd[8631]:   File "/usr/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 41, in <module>
Oct 24 22:25:27 work-station jasmin-dlrlookupd[8631]:     from OpenSSL.SSL import Error, ZeroReturnError, WantReadError
Oct 24 22:25:27 work-station jasmin-dlrlookupd[8631]:   File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
Oct 24 22:25:27 work-station jasmin-dlrlookupd[8631]:     from OpenSSL import crypto, SSL
Oct 24 22:25:27 work-station jasmin-dlrlookupd[8631]:   File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 194, in <module>
Oct 24 22:25:27 work-station jasmin-dlrlookupd[8631]:     if _lib.Cryptography_HAS_SSL_ST:
Oct 24 22:25:27 work-station jasmin-dlrlookupd[8631]: AttributeError: 'module' object has no attribute 'Cryptography_HAS_SSL_ST'
Oct 24 22:25:27 work-station systemd[1]: jasmind.service: Main process exited, code=exited, status=1/FAILURE
Oct 24 22:25:27 work-station systemd[1]: jasmind.service: Unit entered failed state.
Oct 24 22:25:27 work-station systemd[1]: jasmind.service: Failed with result 'exit-code'.
Oct 24 22:25:27 work-station systemd[1]: jasmin-interceptord.service: Main process exited, code=exited, status=1/FAILURE
Oct 24 22:25:27 work-station systemd[1]: jasmin-interceptord.service: Unit entered failed state.
Oct 24 22:25:27 work-station systemd[1]: jasmin-interceptord.service: Failed with result 'exit-code'.
Oct 24 22:25:27 work-station systemd[1]: jasmin-dlrd.service: Main process exited, code=exited, status=1/FAILURE
Oct 24 22:25:27 work-station systemd[1]: jasmin-dlrd.service: Unit entered failed state.
Oct 24 22:25:27 work-station systemd[1]: jasmin-dlrd.service: Failed with result 'exit-code'.
Oct 24 22:25:27 work-station systemd[1]: jasmin-dlrlookupd.service: Main process exited, code=exited, status=1/FAILURE
Oct 24 22:25:27 work-station systemd[1]: jasmin-dlrlookupd.service: Unit entered failed state.
Oct 24 22:25:27 work-station systemd[1]: jasmin-dlrlookupd.service: Failed with result 'exit-code'.

here are my working environment parameters:

ubuntu version 16.04 LTS
python version 2.7.12
jasmin version 0.9.29
rabbitmq-server version 3.5.7-1ubuntu0.16.04.2
redis-server version 2:3.0.6-1ubuntu0.4

Thank you in advance

**Comment by najd1001** [comment]
The problem was a broken pyOpenSSL python module, it is resolved by remove pyOpenSSL and reinstall it again and everything works fine.

**Comment by davidcsi** [comment]
you should close this ticket.

**Comment by najd1001** [comment]
Resolved.
