### ISSUE TITLE
httpccm

### ISSUE THREAD

**Issue by lordkkjmix** [jookies/jasmin#781]
Hi,
i'm new jasmin use and i whan to connect jasmin to other network operator by http.
The operator to receive traffic need other parameter like autorization bearer.
How to add other parameter in jasmin httpcc

**Comment by hzcodertr** [comment]
you must need smpp to http converter jasmin not supported that its commerical :)

**Comment by lordkkjmix** [comment]
Can you recommend me smpp to http converter.

**Comment by hzcodertr** [comment]
you can use nodejs-smpp for post to http
