### ISSUE TITLE
jasmin works like smsgateway.me?

### ISSUE THREAD

**Issue by oortega** [jookies/jasmin#782]
Hello,

can someone tell me if it works like smsgateway.me

with smsgateway.me you install an android app and through the smsgateway API you send the messages to the smartphone and it sends the sms with its own balance.

So Jasmin sends the sms?
Jasmin sends the sms through a smartphone with balance?
If Jasmin sends the SMS, through which operator (ATT, Verizon ...) sends it?

Thanks.

**Comment by juanantoniotv** [comment]
Jasmin works throug the SMPP protocol or http API, you can connect with another device does support SMPP protocol to send or recive SMS, directly Jasmin does't send SMS to cellphones, maybe if smsgateway.me does provide a SMPP protocol or and html API compatible with Jasmin  could connect with Jasmin and administrate the rates or manage the sms routes. But Jasmin does't works like smsgateway.me. See the diagram on https://www.jasminsms.com/.
