### ISSUE TITLE
wanted to know about  routable global variable

### ISSUE THREAD

**Issue by manojr2k** [jookies/jasmin#783]
Hi 

can somebody will provide me more details about  routable global variables, where and how i can take the reference for the available routable variables?is any document for the same ?

actually i want to develop evalpy filter , where i can set the Route as per the destination .
how i can achieve the same ?
and also , i wanted to log the submit_sm and deliver_sm in to mysql , how to achive the same?

Regards

**Comment by davidcsi** [comment]
Those variables are injected when an interceptor is run:
https://github.com/jookies/jasmin/blob/1708a9469d327291606dc0896480590392c0b9c0/jasmin/interceptor/interceptor.py#L51

You can use it right in your interceptor.
You need to add a mtinterceptor and mointerceptor to launch your script, check out http://docs.jasminsms.com/en/latest/interception/index.html#enabling-interceptor

**Comment by manojr2k** [comment]
Hi David
Thanks for the reply 
Just needed few clarification , below is the mtinterceptor example , 
in this  what is the meaning of  **order 100** and  **filters U-foo;DA-33**  

jcli : mtinterceptor -a
Adding a new MT Interceptor: (ok: save, ko: exit)
> type StaticMTInterceptor
<class 'jasmin.routing.Interceptors.DefaultInterceptor'> arguments:
filters, script
> script python2(/opt/jasmin-scripts/interception/mt-interceptor.py)
> filters U-foo;DA-33
> order 100
> ok
Successfully added MTInterceptor [StaticMTInterceptor] with order:100

**Comment by davidcsi** [comment]
Order is the order of execution if you more than one mtinterceptor
Filter is to only execute if those are present. If you want to execute for all, then don’t add a filter

**Comment by manojr2k** [comment]
Thanks david
