### ISSUE TITLE
how to map dlrs with batches?

### ISSUE THREAD

**Issue by connectarena** [jookies/jasmin#785]
How to map batch success response batchid with dlr  id. below are the requests and dlrs. how to know individual number delivery report with dlr.

**request**

curl -X POST -H 'Authorization: Basic xxxxx' -d '{
  "messages": [
    {
      "to": [
        "xxxxxx",
        "xxxxxx"
      ],
      "content": "Same content goes to 3 numbers",
      "dlr": "yes",
      "dlr-url": "http://182.72.244.85:9294/",
      "dlr-level": 3
    }
  ]
}' http://182.72.244.85:8080/secure/sendbatch

{"data": {"batchId": "4ba9627a-575b-4b2d-baca-4e6645789379", "messageCount": 2}}

**dlr**

POST / HTTP/1.0
Host: 182.72.244.85:9294
User-Agent: Jasmin gateway/1.0 DLRThrower
Content-Length: 96
Content-Type: application/x-www-form-urlencoded
connection: close
Accept: text/plain

message_status=ESME_ROK&connector=DEMO_CONNECTOR&id=6df8f68a-d526-4ceb-8319-031985b11912&level=1

**Comment by farirat** [comment]
Each message can have a unique dlr-url where you can inject message id or whatever can be used to identify the message on the dlr callback

**Comment by connectarena** [comment]
with callbackurl param in request. its working

**Comment by amestsantim** [comment]
> with callbackurl param in request. its working

Can you please explain how you achieved this?
Thanks!
