### ISSUE TITLE
what are the parameters need to change to achieve high throughput?

### ISSUE THREAD

**Issue by connectarena** [jookies/jasmin#787]
Can't send more than 30MPS. tried using gunicorn instead of twisted with multiple processes, rest-api throughput param, smppc connection submit_throughput value. Is there any other configs need to change(rabbitmq etc.) to achieve high throughput. Tested with multiple smppc connections with roundroubin.

In the below issue posted google group link. but the link is not opened.
https://github.com/jookies/jasmin/issues/441

**Comment by rodolfoaRAVEN** [comment]
I have an identical problem. It seems that they found a solution, but you cannot access the Google Group ......

**Comment by rodolfoaRAVEN** [comment]
Please,  give some information or tips to improve throughput.  My Jasmin installation gives a maximum of 20 sms/sec with SMPP , in conditions that the provider supports much more .....        Google Group is close.......
