### ISSUE TITLE
jasminsms issues on CentOs 7.7 / PIP installation

### ISSUE THREAD

**Issue by magojr** [jookies/jasmin#788]
Installed jasminsms 0.9.31 on a CentOs 7.7 (updated) box and found some issues.
To avoid conflict with other packages/libraries version, all libraries and modules have been installed using pip, avoiding yum.
After a week of testing, configuring I miss 3 point:
- DLR received by the gateway are wrongly forwarded to the origin, a 002 error is given [(002 error)](https://github.com/jookies/jasmin/issues/760#issuecomment-557521457) 
- Redis can only be used without any password, if configured with password it raise the error  "Cannot start RedisClient: NOAUTH Authentication required." at startup [redis password](https://github.com/jookies/jasmin/issues/551)
- Rabbit works good with guest/guest user/password but connecting with another autenticated user bring to an issue: dlr queue data get into queue but it doesn't get consumed.

I don't think these can be bugs, they can't be bug on a software like jasmin they probably are due to the actual centos specific system/library/configuration.
I would like to try with Ubuntu and yum because it seems to be the "official installation OS", isn't it?
May the ubuntu installation with yum repos can be a more stable option?
Anybody else experienced/solved these issue on a CentOs 7 box ?

Thanks!

**Comment by farirat** [comment]
Hello, dlr err:002 is adressed in #760 

For the rest (redis/rabbit), i guess you need to provide more details on your situations so i can help.

**Comment by magojr** [comment]
Hello farirat,
first of all, thank you very much for addressing that issue!

I can describe in detail the other 2 issue here, these 2 can be "workarounded" using local installation without "securing" Redis and Rabbit.

Redis
I added a password to Redis and I can connect to redis using that password from redis-cli, from php redis admin, and from another propretary app (Laravel based). Using that password in jasmin bring to an error logged even at startup as: "RedisClient: NOAUTH Authentication required".
Switching to a wrong password or to a "correct_password" (with double quotes) in jasmin.conf I got  an error like "wrong password" (I don't remember exactly but it say the password was wrong) so basically the correct one get recognized in some way. It seems that jasmin don't "understand" to be autenticated after using the correct password (this is jus an idea, not sure about it).
So actually we're using it locally binding only to 127.0.0.1 without any password but it may be a very limiting option in order to scale out over multiple box and/or Redis cluster.

RabbitMQ
As best practice, I should instal it and remove the guest/guest user switching to a username|strenght_password config. I did it and inserted them into the jasmin config file. Restarted Jasmin and it seems to works (no eror on startup) but DLR queue doesn't get consumed (not sure on other queues yet because I fastly recreate guest|guest user in order to get it back working). As soon as I reinserted the default Guest user, it come back to works correctly so, probably, somewhere in the code the default Guest/Guest user is takebn even if another user/password are configured in jasmin.conf

These are the versions i'm using (latest on epel repo for CentOs):
redis.x86_64                           3.2.12-2.el7                   @epel
rabbitmq-server.noarch                 3.3.5-34.el7                   @epel
   erlang-kernel.x86_64                   R16B-03.18.el7                 @epel

Hope it can helps and let me know if you need any specific data, I can reproduce them if needed and check about specific detail.

Thank you again!

**Comment by farirat** [comment]
If i needed to reproduce your env i'll have to set rabbit/redis authentication with passwords ? is this correct ?

**Comment by magojr** [comment]
Yes, of course.
In detail, for Redis in /etc/redis.conf
uncomment the line with "requirepass" and insert a password like
requirepass abcde1234fghi
then in /etc/jasmin/jasmin.cfg in the section [redis-client]
password                   = abcde1234fghi

systemctl restart redis
systemctl restart jasmind
systemctl status jasmind
==> show the error

**Comment by magojr** [comment]
For Rabbit it's a bit more tricky to be verified.
You need to:
-add to Rabbit a user like adminuser/strongpassword
-change username and password accordigly in /etc/jasmin/jasmin.cfg [amqp-broker] section
-restart Jasmin
-remove or disable the Guest user in Rabbit
-send one or more SMS activating the DLR for suxess too and wait for the receive
-come back to the Rabbit Admin and check that the Rabbit "dlr" queue elements doesn't get consumed


Then, adding or reactivating the Guest/Guest user, they get consumed (not sure if it's needed a foregn application that read them from Jasmin but I don't think so).

**Comment by hzcodertr** [comment]
edit jasmin.cfg

**Comment by farirat** [comment]
> elements

Do 

> For Rabbit it's a bit more tricky to be verified.
> You need to:
> -add to Rabbit a user like adminuser/strongpassword
> -change username and password accordigly in /etc/jasmin/jasmin.cfg [amqp-broker] section
> -restart Jasmin
> -remove or disable the Guest user in Rabbit
> -send one or more SMS activating the DLR for suxess too and wait for the receive
> -come back to the Rabbit Admin and check that the Rabbit "dlr" queue elements doesn't get consumed
> 
> Then, adding or reactivating the Guest/Guest user, they get consumed (not sure if it's needed a foregn application that read them from Jasmin but I don't think so).

I cannot reproduce your case, do you have an accessible environment ? if yes, then send me the creds to bruno.chaudhary@jookies.net

**Comment by magojr** [comment]
Hello hzcodertr,
thank you for your interest/help but I didn't understand your comment.
If you mean "open jasmin.cfg and insert the Redis password in the appropriate section", as explained it's what I've done without success, I've got anyway a "RedisClient: NOAUTH Authentication required".
That is why I asked support for it, I also tested with double quotes and wrong password that give me another error so it seems that Jasmin is autenticating correctly to Redis but the initial message get misunderstood and jasmin "match" that as not authorized. It may depend from the version of Redis, I don't know exactly...

Let me know if you have any other option to test.
Thank you

**Comment by magojr** [comment]
Thank you again farirat,
you have got my e-mail with ssh access key and my personal contact for any help needed.


> > elements
> 
> Do
> 
> > For Rabbit it's a bit more tricky to be verified.
> > You need to:
> > -add to Rabbit a user like adminuser/strongpassword
> > -change username and password accordigly in /etc/jasmin/jasmin.cfg [amqp-broker] section
> > -restart Jasmin
> > -remove or disable the Guest user in Rabbit
> > -send one or more SMS activating the DLR for suxess too and wait for the receive
> > -come back to the Rabbit Admin and check that the Rabbit "dlr" queue elements doesn't get consumed
> > Then, adding or reactivating the Guest/Guest user, they get consumed (not sure if it's needed a foregn application that read them from Jasmin but I don't think so).
> 
> I cannot reproduce your case, do you have an accessible environment ? if yes, then send me the creds to [bruno.chaudhary@jookies.net](mailto:bruno.chaudhary@jookies.net)

**Comment by magojr** [comment]
UPDATE
Redis: Tested password auth with Jasmin 0.9.32 version and got the same error ("RedisClient: NOAUTH Authentication required").

**Comment by magojr** [comment]
I'm closing this issue because it's due to a misreading of jasmin.cfg file described in [#798](https://github.com/jookies/jasmin/issues/798)
