### ISSUE TITLE
NO_SMSC_DELIVERY_RECEIPT_REQUESTED when multi-part SMS

### ISSUE THREAD

**Issue by fpalamour** [jookies/jasmin#789]
Hello,

I noticed that some of the multi-part SMS are sent with NO_SMSC_DELIVERY_RECEIPT_REQUESTED and I can't find why.

I'm using the rest API and always sending dlr-level and dlr-url. Also, my provider said I could use 5 binds with the same credentials. So what I did is create 5 connectors with different cid like so :

bind_1, bind_2, bind_3, bind_4 and bind_5. Settings are the same for all connectors, only the CID is different for each.
Then I have a RoundRobinMTRouter that picks any of the 5 connectors to send the multi-part message. Is that related to that fact that the SMS is sent with a no_dlr field ? I've seen on another issue that you mention using the same CID name when duplicating connectors in order to use all binds available.

Thank you.

**Comment by farirat** [comment]
Do you have the same issue with one bind one staticmtroute ?

**Comment by fpalamour** [comment]
I created a StaticMTRoute that sends towards smppc(bind_1) with a higher order. Long SMS was also sent with a [dlr:NO_SMSC_DELIVERY_RECEIPT_REQUESTED] (from jasmin/messages.log INFO level)

**Comment by farirat** [comment]
So the issue is not related to multibind / roundrobin route, it's related to multipart messages.

Jasmin is intentionally doing this, it only require dlr of the last part to say message were received, that's the actual design for http to smpp messaging.

On smpp to smpp, Jasmin does not alter the pdu, means you'll get dlr for each pdu if you asked for it.

**Comment by fpalamour** [comment]
My carrier noticed that Jasmin was requesting a DLR only for the last part of a long SMS. So I suppose Jasmin is then able to throw the DLR for the whole message through the dlr-thrower. I hear what you say, but I'm still confused about why when I send a long SMS through the rest API, the message sent to the carrier as seen in the log doesn't ask for a DLR. Surely I must be missing something here.

**Comment by fpalamour** [comment]
I just tested sending a long SMS to another carrier and it works as expected. Although the long SMS in the messages.log file still says 'NO_SMSC_DELIVERY_RECEIPT_REQUESTED', I did receive the DLR. So I suppose the NO_SMSC_DELIVERY_RECEIPT_REQUESTED we're seeing in the log is just the flag of the first part of the message, the second and last one being the one carrying the DLR_REQUESTED flag.

I'm gonna investigate some more and deal with the carrier then. Thank you for your time.

**Comment by maduonline** [comment]
@fpalamour did you find anything else on this matter? I'm facing the same issue.

**Comment by geethupendra** [comment]
> 
> 
> @fpalamour did you find anything else on this matter? I'm facing the same issue.

Did u disscuss with IPS, probably may be ISP...

**Comment by fpalamour** [comment]
I'm sorry I ended with another lib that fitted my needs more. I hope you'll find a solution.

**Comment by TW20-MH** [comment]
> I'm sorry I ended with another lib that fitted my needs more. I hope you'll find a solution.

@fpalamour   Hi i have the same problem. What do you mean with "lib" and what do you use now?

**Comment by fpalamour** [comment]
I forked https://github.com/python-smpplib/python-smpplib to develop my own solution. More time to code, in exchange for more control.
