### ISSUE TITLE
TCP Keep-Alive Interval option?

### ISSUE THREAD

**Issue by yigithancavusoglu** [jookies/jasmin#794]
Hey,

I could not find a way to set keep-alive interval, by default Jasmin sends keep-alive thing in **every second** to check whether connection is established or not. If there is a way to set keep-alive **interval** on the configuration please let me know.

Thank you.

**Comment by ezechinwa** [comment]
I am also interested in this, just curious, are you getting a large amount of traffic to your server and getting disconnected often?

**Comment by yigithancavusoglu** [comment]
> I am also interested in this, just curious, are you getting a large amount of traffic to your server and getting disconnected often?

Yeah, exactly.
