### ISSUE TITLE
SMPP DLR Flow

### ISSUE THREAD

**Issue by magojr** [jookies/jasmin#797]
I'm trying to understand the DLR Flow when the client and the server are both SMPP. The issue is that the documentation don't explain that (if we can call it an issue).
I found in the documentation a very extensive paragraph on the HTTP thrower but very few bits covering the smppsapi case.
I also activate the DEBUG log on every section but I don't get logged any information except for the DLR lookup row with the DLR data.

I think the DLR should be received from the upstream smpp provider and put into a "location" (queue/hash on Rabbit/Redis) where it should be kept until:
  1) The SMPP client connect and get it using a read
  2) A timeout is reached

What i don't understand is
-Is the explained behaviour the way Jasmin is managing DLR or I'm wrong?
-How long Jasmin keep in memory the DLR? Where can I customize that time?

(I think I lost some DLR because of a connection instability from the SMPP client to Jasmin but I'm not sure about the reason)

Any help is apreciated.
A nice week end to everyone ;-)

**Comment by fpalamour** [comment]
Hey @magojr,
I know you can increase the duration a DLR is kept on redis either on the smppc object via the cli with the option dlr_expiry or in the jasmin.cfg file (default is 24h I believe).

**Comment by magojr** [comment]
Hello @fpalamour,
for what I know, dlr_expiry means "How many time we should keep in Redis the mapping, waiting to receive a DLR from the upstream gateway?"

I'm serching for something that answer the question: "After I received the DLR from the upstream gateway. how many time should I keep it waiting for a Read from the SMPP client?"

In the documentation, under **HTTP API**, some parameters are documented like config/dlr-thrower/retry_delay  and config/dlr-thrower/max_retries.
I'm searching for the same params for an SMPP client scenario.

**Comment by fpalamour** [comment]
My bad, I replied too quickly, and now that I get your question, it is way beyond my knowledge, I'm sorry. Although I'm gonna try a guess. There's a retry mechanism with the http dlr-thrower cause HTTP can allow that thanks to the ACK string that is required along with the 200 HTTP code. But is it the same with SMPP ? Can't you just push the DLR to your SMPP client regardless of your client state ? I didn't know there was a READ mechanism to get a DLR. To me, it worked like a push pattern, not a pull one. I might very well be wrong.

**Comment by magojr** [comment]
Not at all, http seems to me a bit more like a "push" because on the other side ther's an http server answering (I mean, an http server should be always on) but even in this case, the server may be down, or the database may be overloaded so a specific answer is required to know that the DLR has been received.

If the DLR is sent back to an SMPP client, the connected entity is not a server but a client and it may be not connected at that time.
Anyway I probably found the answer: 
config/dlr-thrower/retry_delay
and
config/dlr-thrower/max_retries
parameters are both used [here](https://github.com/jookies/jasmin/blob/master/jasmin/routing/throwers.py#L640) in the smpp_dlr_callback   (max_retries indirectly inside the rejectAndRequeueMessage method) so they are used both in the HTTP and SMPP thrower even if they are documented only under the HTTP API section.

Checking my case in the logs and following the code, it seems that I get [here ](https://github.com/jookies/jasmin/blob/master/jasmin/routing/throwers.py#L626) then I go into the L628 logging "Throwing SMPP/DLR  ... Delivering failed, check testsmppuser smpps logs for more details"
But I don't go into  any of the "# Requeue message for later retry" cases (I don't have any log with "Message try-count is" or with "Message is no more processed").

I don't understand how it's possible because the only way to get out is to have SmppsNotSetError Excepion that is raised on the line 592 and if that is the case I shouldn't have "Delivering failed" Exception that is raised at line 626... if the client isn't connect for a while I'm looding somewhere DLR after a "quite low period" even if I setted up a retry schedule of 24 hours.

**Comment by magojr** [comment]
Found the issue!
(But I don't know how to fix it...)

In my jasmin.cfg file i've got these parameters:
_[dlr-thrower]
http_timeout        = 60
retry_delay         = 60
max_retries         = 1440_

I added 2 int value to the log [here in throwers.py](https://github.com/jookies/jasmin/blob/master/jasmin/routing/throwers.py#L628):
_self.getThrowingRetrials(message)_  and  _self.config.max_retries_

If my smpp client doesn't read anything, in the log I found 4 lines every 30 seconds 
_1 of 3
2 of 3
3 of 3
4 of 3
Message is no more processed after receiving "Delivering failed [...]" error_

Parameters are read from the cfg file in [routing/configs.py](https://github.com/jookies/jasmin/blob/master/jasmin/routing/configs.py#L72) but it seems all right here.

May some tab and/or whitespaces into the cfg file bring to this issue?

@farirat have you ever experienced something like that?
It may explain also other issue I'm experiencing...

**Comment by magojr** [comment]
I close this issue because the issue itself is on the configparameter read.
I'm going to create a correct one for that.
