### ISSUE TITLE
Error reading section from config

### ISSUE THREAD

**Issue by magojr** [jookies/jasmin#798]
I was experiencing some strange behaviours, at the end I understood that not all the sections in /etc/jasmin/jasmin.cfg was correctly parsed.
I added a very basic log in [config/tool.py](https://github.com/jookies/jasmin/blob/master/jasmin/config/tools.py#L50) to check about it and i've got this result logged:
_Section interceptor not found reading string bind
Section interceptor not found reading int port
Section interceptor not found reading bool authentication
Section interceptor not found reading string admin_username
Section interceptor not found reading string admin_password
Section interceptor not found reading string log_level
Section interceptor not found reading string log_rotate
Section interceptor not found reading string log_file
Section interceptor not found reading string log_format
Section interceptor not found reading string log_date_format
Section interceptor not found reading int log_slow_script
Section amqp-broker not found reading string host
Section amqp-broker not found reading int port
Section amqp-broker not found reading string username
Section amqp-broker not found reading string password
Section amqp-broker not found reading string vhost
Section amqp-broker not found reading string spec
Section amqp-broker not found reading int heartbeat
Section amqp-broker not found reading string log_level
Section amqp-broker not found reading string log_file
Section amqp-broker not found reading string log_rotate
Section amqp-broker not found reading string log_format
Section amqp-broker not found reading string log_date_format
Section amqp-broker not found reading bool connection_loss_retry
Section amqp-broker not found reading bool connection_failure_retry
Section amqp-broker not found reading int connection_loss_retry_delay
Section amqp-broker not found reading int connection_failure_retry_delay
Section redis-client not found reading string host
Section redis-client not found reading int port
Section redis-client not found reading int dbid
Section redis-client not found reading string password
Section redis-client not found reading int poolsize
Section redis-client not found reading string log_level
Section redis-client not found reading string log_file
Section redis-client not found reading string log_rotate
Section redis-client not found reading string log_format
Section redis-client not found reading string log_date_format
Section smpp-server-pb-client not found reading string host
Section smpp-server-pb-client not found reading int port
Section smpp-server-pb-client not found reading string username
Section smpp-server-pb-client not found reading string password
Section dlr-thrower not found reading int http_timeout
Section dlr-thrower not found reading int retry_delay
Section dlr-thrower not found reading int max_retries
Section dlr-thrower not found reading string dlr_pdu
Section dlr-thrower not found reading string log_level
Section dlr-thrower not found reading string log_file
Section dlr-thrower not found reading string log_rotate
Section dlr-thrower not found reading string log_format
Section dlr-thrower not found reading string log_date_format
Section amqp-broker not found reading string host
Section amqp-broker not found reading int port
Section amqp-broker not found reading string username
Section amqp-broker not found reading string password
Section amqp-broker not found reading string vhost
Section amqp-broker not found reading string spec
Section amqp-broker not found reading int heartbeat
Section amqp-broker not found reading string log_level
Section amqp-broker not found reading string log_file
Section amqp-broker not found reading string log_rotate
Section amqp-broker not found reading string log_format
Section amqp-broker not found reading string log_date_format
Section amqp-broker not found reading bool connection_loss_retry
Section amqp-broker not found reading bool connection_failure_retry
Section amqp-broker not found reading int connection_loss_retry_delay
Section amqp-broker not found reading int connection_failure_retry_delay
Section dlr not found reading string pid
Section dlr not found reading int dlr_lookup_retry_delay
Section dlr not found reading int dlr_lookup_max_retries
Section dlr not found reading bool smpp_receipt_on_success_submit_sm_resp
Section dlr not found reading string log_level
Section dlr not found reading string log_file
Section dlr not found reading string log_rotate
Section dlr not found reading string log_format
Section dlr not found reading string log_date_format
Section dlr not found reading bool log_privacy
String option redis-client -> password not found
Int option amqp-broker -> connection_failure_retry_delay not found
Int option sm-listener -> dlr_lookup_retry_delay not found
Int option sm-listener -> dlr_lookup_max_retries not found_

I don't think it's a general issue it may be based on my cfg file or library version...
I checked the configparser installed versione and it is the 4.0.2 one.
Anyone experienced a similar issue?
Thanks!

Edit, checking in the config file:
String option redis-client -> password not found **[True, it's commented]**
Int option amqp-broker -> connection_failure_retry_delay not found **[True, missing partams?]**
Int option sm-listener -> dlr_lookup_retry_delay not found **[True, missing partams?]**
Int option sm-listener -> dlr_lookup_max_retries not found **[True, missing partams?]**_

Sections are all present except for **smpp-server-pb-client** and **interceptor**

**Comment by farirat** [comment]
Hello @magojr 

This is weird ... is this a special case for centos 7.7 ? or are you experiencing same behaviour on other boxes ?

Using docker or bare ?

Thx

**Comment by magojr** [comment]
Hello @farirat,
thank you for your answer, yes, it's very very strange!

I installed jasmin on CentOs 7.7 (.1908) followhing the RHEL 7 instructions but, having conflicts between previously installed python componments, I basically removed all the python yum packages and reinstalled them as dempendencies of Jasmin (using pip) so my install followed the pip installation branch.
This bring me to a clean install but i started to find strange behaviours when i configured the components. Basically nothing wasnt working at all but nothing was working as expected and this is why.
Today I tried to change something in the cfg file itself so I removed every tab in the cfg file and used spaces, i searched for special characters inside the cfg file but nothing of that  was present, I search for "common pattern" of the unparsed section or "different pattern" between parsed and unparsed section.  And I compared the config classes of the working section vs the non working one but actually i haven't found the point.

**Comment by farirat** [comment]
Did you try on a fresh install of centos7.7 ?

**Comment by magojr** [comment]
If you mean I removed at all jasmin and reinstalled it, yes!
I tried also the 0.9.32 than I removed it and I reinstalled the 0.9.31 but everyime the result is the same:
It "works perfectly" because it get "default" values so every "not read" option is set as the defaults. So a fresh install works, even if I restore a completly comemnted jasmin.cfg it works but, it's not possible to configure the long list of params up here.
So actually it's in execution but, not configurable for these values.

I was wondering I dont understand the flow or the correct param to use but, going into the code, I see that the param used was the right one and the vaue was the default one, not the configured one in jasmin.cfg so I added these really basic debug log line:
       if not self.config.has_section(section):
            **f= open("/var/log/jasmin/debug.log","a+")
            f.write("Section %s not found reading string %s\n" % (section, option))
            f.close()**
            return default
        if not self.config.has_option(section, option):
            **f= open("/var/log/jasmin/debug.log","a+")
            f.write("String option %s -> %s not found\n" % (section, option))
            f.close()**
            return default
        if self.config.get(section, option) == 'None':
            **f= open("/var/log/jasmin/debug.log","a+")
            f.write("String option %s -> %s is None\n" % (section, option))
            f.close()**
            return None

Just to be sure that it's an instalaltion/os version related issue, can someone test this code on a working test system?
I just inserted the bold lines into config/tool.py and renamed config/tool.pyc in order not to use the bytecode version.
Just restarting jasmin should write the debug.log (or not if all params get read correctly).

Any help is really apreciated,
Thank you

**Comment by magojr** [comment]
[SOLVED]
The issue was that my jasmin installation does NOT create the files:
/etc/jasmin/dlr.cfg with sections:
 -[dlr-thrower]
 -[smpp-server-pb-client]
 -[amqp-broker]
and
/etc/jasmin/dlrlookup.cfg with sections:
 -[amqp-broker]
 -[redis-client]
 -[dlr]
