### ISSUE TITLE
interceptor and rate per sms

### ISSUE THREAD

**Issue by manojr2k** [jookies/jasmin#799]
Hi 

through interceptor  , how can i change the rate (price per sms ) for all the submit_sm ?

as in the example given in https://jasmin.readthedocs.io/en/latest/interception/index.html,HLR Lookup routing,  we can set the  routable.addTag(21403)

if possible give me example .

**Comment by farirat** [comment]
You may use the tagfilter in the routing to build routing rules based on tagged pdus, while you tag them into your interceptor scripts.

**Comment by manojr2k** [comment]
Can you plz provide some example

**Comment by manojr2k** [comment]
Hi Farirat

actually my question is 
through interceptor or any filter , how can i change the rate (price per sms ) for all the submit_sm  from python script ?

Regards

**Comment by hzcodertr** [comment]
example turkcell gsm operator tag id = 28603 when added this tag rate is working

**Comment by manojr2k** [comment]
can you please provide me some more info   how can i change the rate (price per sms ) for all the submit_sm from python script ?

**Comment by manojr2k** [comment]
Hi farirat

i am using docker image for testing jasmin .
i wish to implement intercepter for logging to mysql .reffering below URL
https://jasmin.readthedocs.io/en/latest/interception/index.html#enabling-interceptor

my issue is that ,in mmy docker image i not able to find  jasmind.service file in /etc/systemd 

can you please help for this ?

**Comment by magojr** [comment]
Hi @manojr2k not sure about the docker install but at the end of the Pypi installation [here](http://docs.jasminsms.com/en/latest/installation/index.html#pypi) is reported the link to the systemd files in the Jasmin code repository: [jasmin/tree/master/misc/config/systemd](https://github.com/jookies/jasmin/tree/master/misc/config/systemd)

**Comment by hzcodertr** [comment]
contact me on skype tarikogut
