### ISSUE TITLE
Not able to display french characters in SMS-MO

### ISSUE THREAD

**Issue by fpalamour** [jookies/jasmin#800]
Hey everyone,

If I reply with my cellphone the message 'e', it prints well in the log :

`[content:'e']`

But if I reply 'é', it shows : 

`[content:'\x05']`

\x05 is the equivalent of é in the GSM 03.38 table so it should be able to print the correct decoded character right ?

Then I use an http-connector to throw the received MO but the PHP code that receives the HTTP request isn't able to display the french letters. If I use the PHP mb_detect_encoding function, it says 'ASCII' for the message 'e' and 'UTF-8' for the message 'é', but even knowing this, i'm not able to display the 'é' letter. 

SMSC and I are both using data-coding 0.

Anyone has a clue what's going on ? Is Jasmin able to decode MO that contain letters with accents (with acute) ?

**Comment by magojr** [comment]
Hello @fpalamour,
I may have a solution, if you are using php over http, you should pass a "GSM3.38 encoded string", that's not a standard coding for what i know so you should change the coding manually.
I used this class: that is a part of the popular php-smpp library:
[gsmencoder.class.php](https://github.com/onlinecity/php-smpp/blob/master/gsmencoder.class.php)

Give it a try... once encoded, the string should show correct characters (at least the one that you can find in the [GSM3.38 alphabet](https://en.wikipedia.org/wiki/GSM_03.38) )

Hope it can help.
I also have a question: is there someone knowing how to send emoticons in SMS? Is it possible with standard encodings or it require UCS2? Where can I found a "table map" for it?

**Comment by fpalamour** [comment]
Thank you for your quick reply, really appreciate. I'll try that and get back with the results. 
To answer your question, I believe UCS2 uses the Unicode table. However I also believe it is an obsolete encoding. Maybe try using UTF-16.

**Comment by fpalamour** [comment]
I believe the PHP class you're mentioning is able to convert an UTF-8 string into a GSM03.38 one but I need the other way around. The Jasmin http-connector throws the GSM encoded received to my PHP that needs to convert it to utf8 to be able to read it. I've found [this](https://packagist.org/packages/benmorel/gsm-charset-converter) that looks nice but my production server doesn't meet the requirements. I guess I'll keep looking for.

**Comment by farirat** [comment]
@fpalamour don't take the encoded content from Jasmin, consider using the "binary" argument when receiving MO, you'll get a hex-encoded bytes of the content and you can encode it to whatever codec you want.

**Comment by fpalamour** [comment]
Thank you farirat for this answer, that's exactly what I ended up doing.
Cheers.
