### ISSUE TITLE
how to debug the message issue

### ISSUE THREAD

**Issue by manojr2k** [jookies/jasmin#802]
Hi Team 

i tested with below URL 
http://x.x.x.x/send?username=user1&password=test&to=919819845685&from=test&content=testsms2

I received below response  Success "30f09e8e-5479-41fb-a617-c74b20309f58"
but i don't see any log entry , can somebody guide me  how to debug the flow of message ?

i am using docker based setup 

i can see only below in log  

Regards

**Comment by hzcodertr** [comment]
look on messages log and set in /etc/jasmin/jasmin.cfg DEBUG

**Comment by manojr2k** [comment]
Ok Thanks

**Comment by manojr2k** [comment]
thanks for the reply

**Comment by manojr2k** [comment]
HI 

i am using the docker based setup , i  changed the /etc/jasmin/jasmin.cfg DEBUG as per your email .
but when i try stop and start i get below error 
 systemctl status jasmind
Failed to get D-Bus connection: Unknown error -1
