### ISSUE TITLE
Optional Parameter not allowed: Invalid option additional_status_info_text [PATCHED]

### ISSUE THREAD

**Issue by magojr** [jookies/jasmin#803]
I found a non covered (from Jasmin) optional parameter that bring to the error reported in the TItle.
I create a patch to ignore it instead of giving a critical error.
This is the full trace of the error:
_Optional Parameter not allowed: Invalid option additional_status_info_text
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/jasmin/vendor/smpp/twisted/protocol.py", line 195, in rawMessageReceived
    pdu = self.encoder.decode(StringIO.StringIO(message))
  File "/usr/lib/python2.7/site-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 1023, in decode
    self.decodeBody(file, pdu, headerParams['command_length'] - self.HEADER_LEN)
  File "/usr/lib/python2.7/site-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 1069, in decodeBody
    optionalParams = self.decodeOptionalParams(pdu.optionalParams, file, bodyLength - mParamsLen)
  File "/usr/lib/python2.7/site-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 1164, in decodeOptionalParams
    raise PDUParseError("Invalid option %s" % optionName, pdu_types.CommandStatus.ESME_ROPTPARNOTALLWD)
PDUParseError: Optional Parameter not allowed: Invalid option additional_status_info_text
CRITICAL 1338 Received unparsable PDU 000000f800000005000000000000065b000101333333333333333333333333000101536d73000400000000000000008169643a30623535666237642d666332362d346333382d396466352d353330323534323337656630207375623a30303120646c7672643a303031207375626d697420646174653a3139313231343032303120646f6e6520646174653a3139313231363131353420737461743a554e44454c4956206572723a30303020746578743a20001e002530623535666237642d666332362d346333382d396466352d35333032353432333765663000042700010504230003030000001d000e556e64656c6976657261626c6500_ 

Note. I updated the PDU to avoid the disclosure of the phone number.

**My patch**
Decoding the PDU i understood that it is a DLR with UNDELIV status.
the optional params part of the PDU is: 001E002530623535666237642D666332362D346333382D396466352D35333032353432333765663000042700010504230003030000001D000E556E64656C6976657261626C6500
IT contains:
-receipted_message_id => 0b55fb7d-fc26-4c38-9df5-530254237ef0
-message_state => 05 [UNDELIVERABLE]
-network_error_code => 030000
-additional_status_info_text => 556E64656C6976657261626C6500 (Hex notation of the plain text "Undeliverable")

So the additional_status_info_text is not giving any additional info in my case.
**The real solution should be add the parameter to the oprtional parameters list and manage it.**
My patch is adding at the line [1163 of the encoding_pdu.py](https://github.com/jookies/jasmin/blob/master/jasmin/vendor/smpp/pdu/pdu_encoding.py#L1163) 2 lines used to ignore the specific case and read correctly the DLR:
            _elif optionName == 'additional_status_info_text':
                continue_

I tested it and i can confirm that it solve the issue when the upstream SMSC send back this kind of DLR.
I hope this patch can help anyone having the same (or similar) issue and that someone more experienced than me on Jasmin can use it to create a better solution.

**Comment by phil-lavin** [comment]
This is patched at https://github.com/jookies/jasmin/pull/826
