### ISSUE TITLE
Cant receive message

### ISSUE THREAD

**Issue by chemax** [jookies/jasmin#804]
I have a jasmin with moroute and httpccm 
`jcli : morouter -l
#Order Type                    Connector ID(s)                                  Filter(s)
#0     DefaultRoute            http(HTTP01)
Total MO Routes: 1
jcli : httpccm -l
#Httpcc id        Type                   Method URL
#HTTP01           HttpConnector          POST   http://78.47.41.108:8080/newsms
Total Httpccs: 1
`
And i'm dont understand how i can send sms to jasmin and receive it on http. When i tried send msg from my test client, based on node-smpp, i'm dont see any http-request from jasmin.
How i can do it?

**Comment by hzcodertr** [comment]
tarikogut contact me on skype

**Comment by chemax** [comment]
Cannot find you, @hzcodertr https://i.imgur.com/bL5jShL.png

**Comment by hzcodertr** [comment]
give me skype name

**Comment by chemax** [comment]
chemax1987
