### ISSUE TITLE
Wrong paramenter name in jasmin.cfg

### ISSUE THREAD

**Issue by magojr** [jookies/jasmin#808]
I noticed (in a different issue debug session) that ther's a parameter named **connection_loss_failure_delay** in the CFG file ([amqp-broker] section) but the correct name searched from Jasmin is **connection_failure_retry_delay**. 
It should be renamed in the CFG file.

**Comment by fpalamour** [comment]
Also, the default http-access log file is, according to de config file http-access.log although it actually is http-access**log**.log. I believe is should be renamed in the code is it matches the shorter file name.
