### ISSUE TITLE
TagFilter and fallback to default route

### ISSUE THREAD

**Issue by SergeiFranco** [jookies/jasmin#813]
I am doing routing based on tags, and it seems if the connector for a particular route is down the message is not delivered.

Could someone please point me in direction of the documentation on how to fall back to default (or another route) if a connector is down?

**Comment by farirat** [comment]
Check the docs for the failoverover route: https://docs.jasminsms.com/management/jcli/modules.html#mt-router-manager and https://docs.jasminsms.com/management/jcli/modules.html#mo-router-manager

**Comment by SergeiFranco** [comment]
Thank you, I have solved this issue by reading the documentation (!) and using the FailoverMTRoute, which works really well.
