### ISSUE TITLE
Disconnecting SMPP client when received an unsupported query_sm [PARTIALLY SOLVED]

### ISSUE THREAD

**Issue by magojr** [jookies/jasmin#814]
As described in the title I experienced this behaviour. I don't need query_sm to be implemented but if the client send that PDU, I don't want to disconnect him, it bring to many limitation with 3rd party SMPP client software.

My solution (very basic one): I added [HERE](https://github.com/jookies/jasmin/blob/master/jasmin/protocols/smpp/protocol.py#L505) a new element "CommandId.query_sm" in acceptedPDUs

Previous of this patch I was getting into the smpps log: 
  _CRITICAL Received unsupported pdu type: query_sm
  INFO Dropped bind_transceiver bind for 'AAAAAAA'.
  SMPP 123.231.123.231 disconnected from port 2775: [Failure instance: Traceback (failure with no frames): <type 'exceptions.ValueError'>: Field is not nullable_

After the patch I've got just the low level exception from _vendor/smpp/twisted/protocol.py_ **without any disconnection**:
_ERROR    (submit_sm_event/AAAAAAA) Received a non submit_sm command id: query_sm
INFO       Application raised error 'System Error: System Error', forwarding to client. Inbound PDU was [PDU [command: query_sm, sequence_number: 3, command_status: ESME_ROK
message_id: '15c30a87-fb0d-455a-a6ff-aeadfed926af'
source_addr_ton: EnumValue(<jasmin.vendor.enum.Enum object at 0x7fcff3e3fdd0>, 5, 'ALPHANUMERIC')
source_addr_npi: EnumValue(<jasmin.vendor.enum.Enum object at 0x7fcff3e44310>, 4, 'UNKNOWN')
source_addr: 'Stenfo'
]], hex[0000003e00000003000000000000000331356333306138372d666230642d343535612d613666662d6165616466656439323661660005005374656e666f00]_

I think that the best solution may be to correctly manage the unsupported pdu type avoiding the disconnection but this one, altrough not so elegant, works... 
Any improvement is welcome!

**Comment by farirat** [comment]
query_sm pdu is not supported by jasmin.

**Comment by luza** [comment]
I would suggest to reopen the ticket as the requested server behavior also corresponds with the SMPP protocol definition guidelines. Screenshot is attached

![Image](https://github.com/user-attachments/assets/fea615fb-3e69-45aa-9ba0-6706fc7ce577)
