### ISSUE TITLE
error while running jasmind from service script

### ISSUE THREAD

**Issue by manojr2k** [jookies/jasmin#820]
HI 
i install the jasmin from source code on ubuntu .
below is the error i can see when i run the jasmind service
can any body help 

root@ip-:/lib/systemd/system# systemctl status jasmind.service
● jasmind.service - Jasmin SMS Gateway
   Loaded: loaded (/lib/systemd/system/jasmind.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2020-01-18 16:41:33 UTC; 7s ago
 Main PID: 23891 (jasmind.py)
    Tasks: 1
   Memory: 40.6M
      CPU: 629ms
   CGroup: /system.slice/jasmind.service
           └─23891 /usr/bin/python /usr/local/bin/jasmind.py --username jcliadmin --password jclipwd

Jan 18 16:41:35 ip-172-31-43-226 jasmind.py[23891]: Starting Jasmin Daemon ...
Jan 18 16:41:35 ip-172-31-43-226 jasmind.py[23891]:   Cannot start RedisClient: [Errno 13] Permission denied: '//var/log/jasmin/redis-client.log'
Jan 18 16:41:35 ip-172-31-43-226 jasmind.py[23891]:   Cannot start AMQP Broker: [Errno 13] Permission denied: '//var/log/jasmin/amqp-client.log'
Jan 18 16:41:35 ip-172-31-43-226 jasmind.py[23891]:   Cannot start RouterPB: [Errno 13] Permission denied: '//var/log/jasmin/router.log'
Jan 18 16:41:35 ip-172-31-43-226 jasmind.py[23891]:   Cannot start SMPPClientManagerPB: [Errno 13] Permission denied: '//var/log/jasmin/smppclient-manager.log'
Jan 18 16:41:35 ip-172-31-43-226 jasmind.py[23891]:   Cannot start SMPPServer: 'router-pb-factory'
Jan 18 16:41:35 ip-172-31-43-226 jasmind.py[23891]:   Cannot start SMPPServerPB: [Errno 13] Permission denied: '//var/log/jasmin/smpp-server-pb.log'
Jan 18 16:41:35 ip-172-31-43-226 jasmind.py[23891]:   Cannot start deliverSmThrower: [Errno 13] Permission denied: '//var/log/jasmin/deliversm-thrower.log'
Jan 18 16:41:35 ip-172-31-43-226 jasmind.py[23891]:   Cannot start HTTPApi: 'router-pb-factory'
Jan 18 16:41:35 ip-172-31-43-226 jasmind.py[23891]:   Cannot start jCli: 'smppcm-pb-factory'

**Comment by manojr2k** [comment]
its runningsucesssfully when i run 

sudo /usr/bin/python /usr/local/bin/jasmind.py --username jcliadmin --password jclipwd


but not runing when i run as a service script   systemctl status jasmind.service

it seems that i m missing something

**Comment by farirat** [comment]
systemd script is running with the jasmin user, ensure this user has write access to log files under /var/log/jasmin
