### ISSUE TITLE
Multiple mt-interceptors?

### ISSUE THREAD

**Issue by SergeiFranco** [jookies/jasmin#823]
I am trying to run multiple mt-interceptors and for some reason failing.
I am also questioning order by which these interceptors supposed to run? Is highest order first?

The idea is following:

first interceptor -> sets tags
second interceptor + tag filter -> makes HTTP request and drops the message (ESME_ROK).

I am successful on running first intercept (it sets the tags correctly, verified via routing table).
Second filter does not run at all.
It uses same tag filter as the mtrouter (which works).
```
jcli : mtinterceptor -l 
#Order Type                 Script                                          Filter(s)                                                        
#99999 StaticMTInterceptor  <MTIS (pyCode=import sysfrom syslog import  ..)> <T>                                                              
#10   StaticMTInterceptor  <MTIS (pyCode=import requestsimport urllib ..)> <TG (tag=10)>                                                   
#0     DefaultInterceptor   <MTIS (pyCode=import sysfrom syslog import  ..)> 
```
Will #99999 run first?
Does it suppose to run #10 once if #99999 sets the tag to 10?

**Comment by magojr** [comment]
Hello Franco,
not sure of where I read and never tried so, don't take it as "sure" but I think that the workflow is similar to the routing one: based on the order (higher first) the first row with a matching filter is the interceptor executed; no other interceptor will run so you can tag an SMS in an interceptor, than use the tag in a filter for route it. For what I know you can't run multiple interceptor.
So you should change the logic inserting in the first interceptor the logic expected to be run in the second if the tag match.

Hope it may help you

**Comment by SergeiFranco** [comment]
Thank you,
I have completely given up on jasmin doing the routing logic instead I offload everything to interceptor now.

So now all happens in one interceptor, I simply call the other interceptor from inside of the first when needed (via import).

I have also given up on MT->MO conversion, it worked, but for some reason it didn't apply mointerceptors on it. Being twisted it is very difficult to debug as well (for me).
So now I have 1 global mt_inteceptor and 1 global mo_interceptor, sometimes (on special conditions) mt_interceptor calls mo_interceptor for that MT->MO magic (probably the most requested feature).
