### ISSUE TITLE
Need Jasmin user account and Need to know SMPP server connection to SMPP client

### ISSUE THREAD

**Issue by 1Darshan** [jookies/jasmin#827]
Need a Jasmin User Account and how to create a new user account.
how to connect SMPP server in jasmin sms gateway to a third party SMPP client in redhat linux pc.
Prerequisites & Dependencies are already installed.
tell me the steps to connect SMPP server to the SMPP client using Jasmin sms gateway.

**Comment by KamuiX** [comment]
You can find everything here https://jasmin.readthedocs.io/en/latest/
