### ISSUE TITLE
How to drop messages cleanly with interceptors?

### ISSUE THREAD

**Issue by SergeiFranco** [jookies/jasmin#829]
The documentation hints that smpp_status and http_status could be used to control the routing of the message.

I am testing these with submitting the message via REST API.

I have tried setting http_status = 0 and smpp_status = 0 and I get error 500:
`{"title": "Jasmin httpapi connection error", "description": "Could not connect to Jasmin http api (http://127.0.0.1:1401): ('Connection aborted.', BadStatusLine('HTTP/1.1 0 Unknown Status\\r\\n',))"}`

http_status = 200 and smpp_status = 0:
error 400
`{"message": "Error \"Failed running interception script, check log for details"}`

smpp_status = 0 and unset http_status:
error 500 and no return.

The only thing what makes the jasmin happy is having both smpp_status and http_status unset.

The problem I am facing here is that I need to drop the message as the interceptor would submit the message to 3rd party arbitrary API based on some criteria.

If I don't drop the message it hits the default route which will deliver it via looping back to MO side and incurring cost (from upstream provider).

**Comment by SergeiFranco** [comment]
Since this forum is dead, interim solution is to create a dummy smpp connector (localhost, random unused port and random credentials), leave it disabled and hose off once in a while (cron) the queue with 
`rabbitmqctl purge_queue submit.sm.dummy`
Needs a tag filter, a route with tag filter and setting the tag at the interception.
It might cause some errors to be logged, but that is life...

Jasmin needs some /dev/null sinks in for smpp connectors.

**Comment by llibarios12** [comment]
Having the same problem.. hopefully someone can give an explanation.

**Comment by SergeiFranco** [comment]
So, since this project is dead, I decided to poke around the source code.

Here is how I drop messages without errors.

1) Set the extra={'DROP':True}

2) modify the following:

```
--- /usr/lib/python2.7/dist-packages/jasmin/managers/listeners.py.original      2020-09-10 09:31:56.078368991 +1200
+++ /usr/lib/python2.7/dist-packages/jasmin/managers/listeners.py       2020-09-10 09:23:06.850807141 +1200
@@ -576,6 +576,14 @@
                     self.log.info(
                         'Interceptor script returned %s smpp_status error.', args[0]['smpp_status'])
                     raise DeliverSmInterceptionError(code=args[0]['smpp_status'])
+                elif isinstance(args[0], dict) and args[0]['smpp_status'] == 0:
+                    self.log.info('Interceptor script returned %s success smpp_status.', args[0]['smpp_status'])
+                    # Do we have a message_id returned from interceptor ?
+                    if 'message_id' in args[0]['extra']:
+                        message_id = str(args[0]['extra']['message_id'])
+                    if 'DROP' in args[0]['extra']:
+                        self.log.debug("Dropping message, reason: 'DROP':True is set in 'extra' (this is OK)")
+                        return
                 elif isinstance(args[0], str):
                     smpp.factory.stats.inc('interceptor_count')
                     routable = pickle.loads(args[0])
```

and

```
--- /usr/lib/python2.7/dist-packages/jasmin/protocols/smpp/factory.py.original  2020-09-10 09:37:47.427327260 +1200
+++ /usr/lib/python2.7/dist-packages/jasmin/protocols/smpp/factory.py   2020-09-10 09:38:36.409133783 +1200
@@ -343,6 +343,9 @@
                     # Do we have a message_id returned from interceptor ?
                     if 'message_id' in args[0]['extra']:
                         message_id = str(args[0]['extra']['message_id'])
+                    if 'DROP' in args[0]['extra']:
+                        self.log.debug("Dropping message, reason: 'DROP':True is set in 'extra' (this is OK)")
+                        return
                     raise SubmitSmInterceptionSuccess()
                 elif isinstance(args[0], str):
                     self.stats.inc('interceptor_count')
```

This also includes the fix for the bug #884

**Comment by farirat** [comment]
Are you looking to "silently" drop a message with an ESME_ROK to the client ESME ?

**Comment by SergeiFranco** [comment]
> Are you looking to "silently" drop a message with an ESME_ROK to the client ESME ?

I am looking a way to drop messages at the interceptor (preferably) so it still sends an ESME_ROK to other end.
Alternatively it would be great to have a dummy SMPP client connector that is just sinks the messages with ESME_ROK.

At this stage I am going by with modified code from above, by setting extra variable with DROP and catching at managers/listener.py and protocols/smpp/factory.py.

A good analogy is exim's :blackhole: facility (for those familiar with mail).

**Comment by farirat** [comment]
You seems to like hard solutions for simple problems.

A backhole can be simply done by adding a smpp connector to a smpp simulator, take the smppsim for example and you'll be able to play with jasmin router to tell who goes to the backhole and who get routed to real providers, can be done in 5 minutes.

It's a matter of taste ;)

**Comment by SergeiFranco** [comment]
Hi,
The reason why I didn't go for an external smpp server as a blackhole destination is that it adds another moving part. If we have another server, it means we need to monitor that server, thus having internal feature makes more sense.

On another note #884 is not a duplicate of this issue, unless I misunderstood the problem (could you please clarify if so).
