### ISSUE TITLE
 DLRMapNotFound: Got a DLR for an unknown message id: 

### ISSUE THREAD

**Issue by KamuiX** [jookies/jasmin#834]
Centos 7.4
Jasmin 0.9.29 (from jookies rpm repo)

In my test I sent a multipart SMS (3parts) through HTTP API to my jasmin which then forwards it to another jasmin server.

I am checking messages.log and dlrlookupd-messaages.log. For submit and dlr reporting.

1) The SMS arrives and shows in SMS APP on my phone in wrong order (1-3-2). Any ideas?
   **EDIT: Seems UDH split works ok but SAR not**

2) I got DLR only for 1 part of the message the other 2 in dlrlookup-messages have the following ERROR (final) DLRMapNotFound: Got a DLR for an unknown message id:

I found many issues regarding DLR in multipart SMS but I really don't understand if there is a fix or an option to enable

**Comment by magojr** [comment]
Hello @KamuiX,
I'm not so expert about multipart messages but I also read some issue/post in the past.
About the 1-3-2 I think ther's no need to receive multipart message in the correct order, the final receiver should recompose the entire message without assume it comes in the right order from the SMPP point of vie. Consider also that gateway may queue or deliver it in different routes so, even sending it in the right order, yo cannot have any guarantee that it arrives in the same order.

For the DLR part, I also see that only a single DLR is throwed back. I'm interested to understand if ther's an easy way to get back all of them. I read somewhere that it's an implementation choice. I think it is intended to avoid to keep in memory all the DLR map data of each part of the message, keeping only one of that but I'm not sure if it's the real goal of that behaviour.

Better to wait for some jasmin staff reply on this theme.
Hope it can help!
