### ISSUE TITLE
Value (test) size 4 does not match expected 15

### ISSUE THREAD

**Issue by mexicarne** [jookies/jasmin#839]
Hello, 

we are getting this exception when trying pass the message sent to jasmin to upstream SMSC:
```python
2020-03-04 12:04:00 CRITICAL 805 Rejecting SubmitSmPDU[247c20b2-e05f-4914-a498-3187f3e7aede] through [cid:<some cid>] for an unknown error (<type 'exceptions.ValueError'>): Value (test) size 4 does not match expected 15
```

I traced it to bundled smpp.pdu package, but since it have many jasmin-specific modifications I think it's better to ask here. It looks like jasmin is not capable to resend PDU's where message text is set in message_payload optional parameter or something like that. Please clarify what's wrong here. Message dump is attached.

[1.zip](https://github.com/jookies/jasmin/files/4288193/1.zip)

**Comment by mexicarne** [comment]
@farirat any idea?

**Comment by farirat** [comment]
It's a binary pdu decoding issue, something is not encoded correctly and jasmin cant read it.

You need to have the hex representation of the pdu in the log, share it and i'll take a look

**Comment by mexicarne** [comment]
> It's a binary pdu decoding issue, something is not encoded correctly and jasmin cant read it.
> 
> You need to have the hex representation of the pdu in the log, share it and i'll take a look

I grepped all the logs the only thing is found in default-smpps_01.log.2020-03-04:
```
:2020-03-04 12:04:00 INFO     805 SMS-MT [uid:username] [cid:connector] [msgid:247c20b2-e05f-4914-a498-3187f3e7aede] [prio:1] [from:7999333XXXX] [to:7999699XXXX] [content:]```

content field (where hex representation should go) is empty.

**Comment by mexicarne** [comment]
Still the message is here as you can see from the dump. It is put not message_bytes, but into optional parameter `message_payload` instead.

![image](https://user-images.githubusercontent.com/1031992/80250384-682bf780-867c-11ea-898e-43218356fd99.png)

**Comment by mexicarne** [comment]
ping?

**Comment by disels** [comment]
I have the same problem. According to observations, in 4 cases out of 5, such an exception flies. 1 time out of 4, the message goes through normally. One and the same text can pass, it can not pass. And in the exception, the expected size is always 9. Regardless of the size of the message
