### ISSUE TITLE
Am not receiving messages on the mobile !

### ISSUE THREAD

**Issue by Sanix-Darker** [jookies/jasmin#843]
i followed all the tutorial with docker, i don't know if it's a BOUND issue, because in my column `Session` am having None or in the tutorial `BOUND_TRX`,how to fix this please ?

```shell
jcli : smppccm --list
#Connector id                        Service Session          Starts Stops
#DEMO_CONNECTOR                      started NONE             1      0 
```

**Comment by farirat** [comment]
check the logs: default-DEMO_CONNECTOR.log
