### ISSUE TITLE
DLRMapNotFound: Got a DLR for an unknown message id:

### ISSUE THREAD

**Issue by Cobram** [jookies/jasmin#844]
Hi 
Debian 9.9
Jasmin 0.9.29

I have strange situation with delivery report on messages with more than 3 parts pdu .

Direction of sending SMS's is HTTP API  to SMPP connector. 
HTTP API request: (GET /send?username=user&password=pass&coding=8&dlr=yes&dlr-url=http://localhost/dlr_jasmin.php&dlr-level=3&dlr-method=GET&from=Test&to=123123123&content=.....)

Sometimes jasmin receive it corectly and sometimes with unknown message id error. The issue is related only to SupplierA. I tried with both spliting method UDH and SAR but the issue persist.
I also tried with MT interception (Enforcing DLR) - https://jasmin.readthedocs.io/en/latest/interception/index.html
Nothing helps.

Logs on jasmin side:
_2020-03-12 14:23:43 INFO     3208 SMS-MT [cid:SupplierA] [queue-msgid:7df62d80-4c06-4509-b945-51beafb76f11] [smpp-msgid:33D7F963] [status:ESME_ROK] [prio:0] [dlr:SMSC_DELIVERY_RECEIPT_REQUESTED] [validity:none] [from:Novatel] [to:38651436453] [content:'\x000\x009\x00r\x007\x009\x008\x003\x002\x00z\x00r\x00z\x003\x008\x007\x00f\x00z\x00o\x008\x007\x00z\x003\x00f\x00d\x00z\x008\x003\x00z\x00d\x003\x00l\x00r\x00z\x003\x009\x008\x00r\x00z\x003\x00r\x009\x008\x003\x00z\x00o\x00d\x00z\x009\x00z\x003\x009\x008\x00z\x00d\x009\x008\x003\x00z\x00d\x009\x008\x00z\x00d\x009\x008\x003\x00z\x00d\x009\x008\x003\x00z\x00u\x00d\x009']

2020-03-12 14:23:44 ERROR    3210 [msgid:6C07135] (retrials: 1/2) DLRMapNotFound: Got a DLR for an unknown message id: 06C07135 (coded:6C07135)
2020-03-12 14:23:54 ERROR    3210 [msgid:6C07135] (final) DLRMapNotFound: Got a DLR for an unknown message id: 06C07135 (coded:6C07135)_

I opened TT at SuplierA. They see issue in wrong relation between request and response (like ignoring Sequence ID's).

This is log from them:

_Frame 267739 2020-03-12 14:23:42.892756
Short Message Peer to Peer, Command: Submit_sm, Seq: 18, Len: 201
    Length: 201
    Operation: Submit_sm (0x00000004)
    Sequence #: 18
    Originator address: Test
    Recipient address: 123123123
    Message length: 134

Frame 267805 2020-03-12 14:23:43.116439
    Length: 25
    Operation: Submit_sm - resp (0x80000004)
    Result: Ok (0x00000000)
    Sequence #: 18
    Message id.: 33D7F963
_______________________________________________________________

Frame 267741 2020-03-12 14:23:42.892786
Short Message Peer to Peer, Command: Submit_sm, Seq: 19, Len: 81
    Length: 81
    Operation: Submit_sm (0x00000004)
    Sequence #: 19
    Originator address: Test
    Recipient address: 123123123
    Message length: 14

Frame 267773 2020-03-12 14:23:43.028224
    Length: 25
    Operation: Submit_sm - resp (0x80000004)
    Result: Ok (0x00000000)
    Sequence #: 19
    Message id.: 06C07135_

I read documentation and Issues board many times but I didn't find any solution. Please help me.
Thx

**Comment by farirat** [comment]
what is the issue ?

**Comment by geethupendra** [comment]
Just try to update SMPP Client Connector Manager update
 
https://docs.jasminsms.com/en/latest/management/jcli/modules.html?highlight=dlr_msgid#smpp-client-connector-manager

dlr_msgid = 0 or 1

most ISP working 0 but some are not

Thanks
Geeth
