### ISSUE TITLE
Setting up Interceptor - No such file or directory

### ISSUE THREAD

**Issue by kieranhackshall** [jookies/jasmin#845]
I have setup a Jasmin server using docker on Ubuntu.

No issues sending and SMS however when setting up interceptor using mtinterceptor -a and script python2(/opt/jasmin-scripts/interception/mt-interceptor.py) I am seeing [IO]: [Errno 2] No such file or directory: '/opt/containerd/lib/mt-interceptor.py'

The file is there and has appropriate permissions.

Has anyone seen this issue or have a suggestion as to how resolve?

Thanks

**Comment by zouhirmahjoubi** [comment]
same probleme ; any help plz.

**Comment by kieranhackshall** [comment]
It seems to be an issue with the Docker install. I just installed the Ubuntu install and had no issues.

**Comment by zouhirmahjoubi** [comment]
thanks bro.
i have a prob in my smppccm  in not bind why!!
any help
2020-04-11 21:19:09 INFO     865 Reconnecting after 10 seconds ...
2020-04-11 21:19:19 INFO     865 Connecting to IPv4Address(TCP, '3.233.206.206', 2775) ...
2020-04-11 21:19:49 ERROR    865 Connection failed. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.TimeoutError'>: User timeout caused connection failure.
]

**Comment by farirat** [comment]
if jasmin is running in a docker container then system paths are obviously included within the container and not in the host system.

you need to mount the volum inside the container (-v switch).

**Comment by rakibulinux** [comment]
Hello, @farirat, How are you?
Are you able to send SMS via Jasmin? I try many ways but not able to make it working. Can you please help me to make it run successfully?
