### ISSUE TITLE
Can't Install jasmin on Debian 4.9

### ISSUE THREAD

**Issue by llibarios12** [jookies/jasmin#847]
Please find logs based on the installation done.

**Installation via APT deb package:**
> $bash: wget -qO - http://bit.ly/jasmin-deb-repo | sudo bash
> Detected operating system as debian/buster.
> Checking for curl...
> Detected curl...
> Checking for gpg...
> Detected gpg...
> Running apt-get update... done.
> Installing debian-archive-keyring which is needed for installing 
> apt-transport-https on many Debian systems.
> Installing apt-transport-https... done.
> Installing /etc/apt/sources.list.d/jookies_python-jasmin.list...done.
> Importing packagecloud gpg key... done.
> Running apt-get update... done.
> 
> The repository is setup! You can now install packages.

> $bash: sudo apt-get install python-jasmin
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package python-jasmin

> $bash: sudo apt-get update
> The repository 'https://packagecloud.io/jookies/python-jasmin/debian buster Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

**Installation via PIP**
successful, but upon enabling jasmind returns
> $bash: sudo systemctl enable jasmin
> Failed to enable unit: Unit file jasmin.service does not exist.

Appreciate your help on this. Thanks

**Comment by Hezrone** [comment]
I am having the same error. any help please....

**Comment by tinashezharare** [comment]
I have this same issue as well...
