### ISSUE TITLE
Missing log files 

### ISSUE THREAD

**Issue by canbazb123** [jookies/jasmin#851]
Hi 
Just installed jasmin and started docker but I dont see log file under var /var/log/jasmin   , i have only this ones 
[root@kannelsms ~]# ls /var/log/jasmin/
amqp-client.log             amqp-client.log.2020-03-30  amqp-client.log.2020-04-13  interceptor.log.2020-03-23  redis-client.log.2020-03-23
amqp-client.log.2020-03-23  amqp-client.log.2020-04-06  interceptor.log             redis-client.log

I need log file file for smpp to check binding issues

**Comment by farirat** [comment]
Hi

Read the amqp and redis logs in that folder and you'll note Jasmin is awaiting you to start redis and rabbitmq servers to continue the bootstrapping process.
