### ISSUE TITLE
custom Header httpccm 

### ISSUE THREAD

**Issue by lordkkjmix** [jookies/jasmin#853]
Hello,
I use jasmin but i need to connect make smpp to http request.
For that i setup a httpccm connector but i'm facing with issue.
**How to custom httpccm POST** header to **insert Bearer** or other details.
Thanks you

**Comment by SergeiFranco** [comment]
Here is how I do similar without modifying the Jasmin source:
1. Create a dummy SMPP connector (point it to non-existing port @ localhost) and route it via filter or default
2. Create an interceptor script and use python requests to do whatever I want.
3. Have a cron job nuking the queue with the messages that are no longer needed (`rabbitmqctl purge_queue submit.sm.dummy`)

httpccm are useless in Jasmin unless you have control on other end and can modify the behaviour, or other end is another Jasmin instance.
