### ISSUE TITLE
automation and portability of config - why not plain text?

### ISSUE THREAD

**Issue by SergeiFranco** [jookies/jasmin#855]
I am trying to build automation of the configuration without resorting to ugly Except (who likes working with TCL?).

I am trying to unpickle the config and I am hitting this:

`>>> cPickle.load(open("/etc/jasmin/store/jcli-prod.filters",'rb'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cPickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
`

My question, what is the simplest way to convert the pickled config into plain text (or JSON).

In my opinion (as a systems guy) the binary configs are very terrible idea in general, no major opensource projects do it, so why did Jasmin developers went that way?
This issue is made worse by having a clumsy `90 telnet interface as sole configuration method.

I am very tempted to butcher the code and dump config as json.

As of now it is not possible to automate config with things like Ansible in a clean and painless way.

In anyway, who I am kidding, this project is dead.

**Comment by SergeiFranco** [comment]
To answer my own question (again), it looks like jasmin adds a header in front of pickled data, and all I need to unpickle is to remove said header:
`                fh = open(path, 'w')                                                                                                                                                                                                         
                # Write configuration with datetime stamp                                                                                                                                                                                    
                fh.write('Persisted on %s [Jasmin %s]\n' % (time.strftime("%c"), jasmin.get_release()))                                                                                                                                      
                fh.write(pickle.dumps(self.mt_routing_table, self.pickleProtocol))                                                                                                                                                           
                fh.close()
...
                fh = open(path, 'r')                                                                                                                                                                                                         
                lines = fh.readlines()                                                                                                                                                                                                       
                fh.close()                                                                                                                                                                                                                   
                                                                                                                                                                                                                                             
                # Init migrator                                                                                                                                                                                                              
                cf = ConfigurationMigrator(context='users', header=lines[0], data=''.join(lines[1:]))   `

**Comment by farirat** [comment]
You can start reading how jasmin is persisting/loading data, here's [one](https://github.com/jookies/jasmin/blob/master/jasmin/routing/router.py#L429) and [another](https://github.com/jookies/jasmin/blob/master/jasmin/routing/router.py#L530) example.

As for integrating jasmin's api, telnet is just a UI wrapper on top of a PerspectiveBroker api, this one can be directly integrated programmatically, this is an example of adding a connector and starting it through the PB api: https://github.com/jookies/jasmin/blob/master/jasmin/routing/test/test_routing_deliver_sm.py#L96

**Comment by SergeiFranco** [comment]
> You can start reading how jasmin is persisting/loading data, here's [one](https://github.com/jookies/jasmin/blob/master/jasmin/routing/router.py#L429) and [another](https://github.com/jookies/jasmin/blob/master/jasmin/routing/router.py#L530) example.
> 
> As for integrating jasmin's api, telnet is just a UI wrapper on top of a PerspectiveBroker api, this one can be directly integrated programmatically, this is an example of adding a connector and starting it through the PB api: https://github.com/jookies/jasmin/blob/master/jasmin/routing/test/test_routing_deliver_sm.py#L96

Thank you very much for your reply.

That is a very complicated solution for a simple problem. Very hard to integrate with ansible playbook that another system engineer could pick up and understand.

I tried to see how it comes together on that line you have linked, but I do not see where it is actually gets the current config (whole thing), all I see it is instantiating a new smppc config object and adding it... In anyway all of this would have been unnecesary if the config was stored as plain text (like most of the open source software does, nginx, Apache, haproxy, etc.)

The way I will approach this is following:
1) have a python script to unpickle current config into json and store it as a file.
2) have ansible handle the json config
3) have ansible run a python script that will pickle the config (with a compatible header) and issue "load" via the telnet (or jasmin config class if I figure out how).

From end user the automation is simple: they interface with json (human readable) and run ansible. Even if ansible is out of the picture there is still benefit: the end user will read/write json and run a script to apply.

Last time I tried to use jasmin way of interfacing with the queues, and I completely given up because even though I could establish a connection due to twisted I completely lost ability to see the exception that was causing disconnect. 6hours later I decided to ditch jasmin classes, in favour of blocking Pika. I managed to do a MT->MO translator only to find out it was feeble, due to mointerceptor not running because it was already in the right queue.

My pyhton skills are not up to the task of dealing with twisted. I actually despise twisted now, after working with jasmin.

**Comment by SergeiFranco** [comment]
It looks like someone else is having similar problem: #515

**Comment by SergeiFranco** [comment]
This thing drives me insane. From my point of view it is absurd to store config as pickled classes (with a plain text header added on top). If it was just the variables I would successfully just use cPickle and JSON libraries to switch between them, but no, someone decided it was a good idea to shove classes into it. On top of that between each config pickled file, there is an inconsistency of either using dictionary, list or plain object.

I guess Jasmin devs hate their users. I digress...
 
So far I managed to covert to JSON and back to pickled config without issue (and 100% reversibility) except for one config: `/etc/jasmin/store/jcli-prod.smppccs`. The workaround for this insanity is using jsonpickle library.

I got to a problem where jsonpickle blows up on this:
```  File "/usr/lib/python2.7/dist-packages/jsonpickle/unpickler.py", line 348, in _restore_object_instance
    return self._restore_object_instance_variables(obj, instance)
  File "/usr/lib/python2.7/dist-packages/jsonpickle/unpickler.py", line 381, in _restore_object_instance_variables
    self._restore_from_dict(obj, instance)
  File "/usr/lib/python2.7/dist-packages/jsonpickle/unpickler.py", line 370, in _restore_from_dict
    setattr(instance, k, value)
  File "/usr/lib/python2.7/dist-packages/jasmin/vendor/enum.py", line 203, in __setattr__
    raise EnumImmutableError(name)
jasmin.vendor.enum.EnumImmutableError: Enumeration does not allow modification```

I got so close yet this is, what seems to be, an impassible obstacle for me.

Dear developers what is wrong with using plain text config? You already used it for jasmin.conf?

**Comment by SergeiFranco** [comment]
I have given up on unpickling the store and now attempting to get the config in textual form by using this example: https://jasmin.readthedocs.io/en/latest/faq/developers.html#faq-2-htdatpba

I am so frustrated with the design of the whole thing. This is a prefect example of OOP for sake of OOP. Yes I am not fan of OOP but I digress.

Here is the frustrating part:

If I call user_get_all() it retruns me bunch of objects. Ok I can deal with that.
I traverse objects and call it further, then I get some text values (like username, and uid) but for group the thing does not flatten for me and spits out the group object, in case of group object it is simple as there are only two attributes there (enabled and gid). Unfortunately it is not as simple as mt_credential, and smpp_credential attributres which are returned as objects. This is beyond tedious.

I haven't even got to the connectors yet (it seems it is a different class, I only explored RouterPBProxy)

I find it bizarre that Jasmin devs expect end users to be experienced python devs. 

**All Jasmin needs for the config to be manageable either of the two (or both):
a) Add import/export function to jcli
b) Store config in plain text (eg: Yaml, JSON or configparser).**

**Comment by SergeiFranco** [comment]
> You can start reading how jasmin is persisting/loading data, here's [one](https://github.com/jookies/jasmin/blob/master/jasmin/routing/router.py#L429) and [another](https://github.com/jookies/jasmin/blob/master/jasmin/routing/router.py#L530) example.
> 
> As for integrating jasmin's api, telnet is just a UI wrapper on top of a PerspectiveBroker api, this one can be directly integrated programmatically, this is an example of adding a connector and starting it through the PB api: https://github.com/jookies/jasmin/blob/master/jasmin/routing/test/test_routing_deliver_sm.py#L96

Actually this ("telnet is just a UI wrapper on top of a PerspectiveBroker api") is incorrect:
Looking at the documentation telnet has two features that PB API is missing, httpcm and filter.

This discrepancy is major enough that I created #859 .
Because at this stage there is not a clean way to export/import config out of Jasmin.

**Comment by SergeiFranco** [comment]
Could some one please explain why the below seems great idea?:


Looking into the object `EnumValue`:
```{'_enumtype': <jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>,
 '_index': 6,
 '_key': 'INTERNATIONAL'}```

What is the `jasmin.vendor.enum.Enum`?
```{'ABBREVIATED': EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 0, 'ABBREVIATED'),
 'ALPHANUMERIC': EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 5, 'ALPHANUMERIC'),
 'INTERNATIONAL': EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 6, 'INTERNATIONAL'),
 'NATIONAL': EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 4, 'NATIONAL'),
 'NETWORK_SPECIFIC': EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 1, 'NETWORK_SPECIFIC'),
 'SUBSCRIBER_NUMBER': EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 2, 'SUBSCRIBER_NUMBER'),
 'UNKNOWN': EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 3, 'UNKNOWN'),
 '_keys': ('ABBREVIATED',
           'NETWORK_SPECIFIC',
           'SUBSCRIBER_NUMBER',
           'UNKNOWN',
           'NATIONAL',
           'ALPHANUMERIC',
           'INTERNATIONAL'),
 '_values': [EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 0, 'ABBREVIATED'),
             EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 1, 'NETWORK_SPECIFIC'),
             EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 2, 'SUBSCRIBER_NUMBER'),
             EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 3, 'UNKNOWN'),
             EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 4, 'NATIONAL'),
             EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 5, 'ALPHANUMERIC'),
             EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 6, 'INTERNATIONAL')]}```

What is the `{'ABBREVIATED': EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 0, 'ABBREVIATED')`?
```{'_enumtype': <jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>,
 '_index': 0,
 '_key': 'ABBREVIATED'}```

hmm, seen this before, so what is the `{'_enumtype': <jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>`?
```{'ABBREVIATED': EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 0, 'ABBREVIATED'),
 'ALPHANUMERIC': EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 5, 'ALPHANUMERIC'),
 'INTERNATIONAL': EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 6, 'INTERNATIONAL'),
 'NATIONAL': EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 4, 'NATIONAL'),
 'NETWORK_SPECIFIC': EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 1, 'NETWORK_SPECIFIC'),
 'SUBSCRIBER_NUMBER': EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 2, 'SUBSCRIBER_NUMBER'),
 'UNKNOWN': EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 3, 'UNKNOWN'),
 '_keys': ('ABBREVIATED',
           'NETWORK_SPECIFIC',
           'SUBSCRIBER_NUMBER',
           'UNKNOWN',
           'NATIONAL',
           'ALPHANUMERIC',
           'INTERNATIONAL'),
 '_values': [EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 0, 'ABBREVIATED'),
             EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 1, 'NETWORK_SPECIFIC'),
             EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 2, 'SUBSCRIBER_NUMBER'),
             EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 3, 'UNKNOWN'),
             EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 4, 'NATIONAL'),
             EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 5, 'ALPHANUMERIC'),
             EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd14e05ad50>, 6, 'INTERNATIONAL')]}```

This is what I call OOP for sake of OOP.

**Comment by SergeiFranco** [comment]
The solution at the end was following:
For converting the config to YAML:
1. Issue persist and unpickle store files (/etc/jasmin/store)
2. Iterate list or dictionaries, if the pickled structure is not a jasmin object.
3. Instantiate "default" jasmin objects and compare the what is in the stored objects to eliminate default values.
4. If the value is another object repeat 3 (unless it is jasmin Enum, then just flatten it).
5. Build dictionaries from resulted values.
6. Build either a list of dictionary of resulted dictionaries (unless the store contained plain object).
7. Store the result as YAML (for each store file).

For converting the config to pickled Jasmin format:
1. Repeat 1 through 6 from steps for reading.
2. load YAML from the file for each store equivalent file
3. Compared to stored values with loaded YAML, skip config section if there is no difference.
4. Iterate through dictionaries or lists (unless it was a plain object).
5. Instantiate the corresponding objects with stored values.
6. If there are sub-objects repeat 5.
7. Pickle into store files with copied headers from recent persisted config (I copy the headers because the header is checked by an ugly regex in Jasmin).
8. issue load.

This was the biggest pain I ever dealt with when trying to manage the config of a piece of a software.
I ended up using telnetlib for issuing `load` and `persist` because I could not find a simple (under 10 lines) way to do it via jasmin API.

I found it bizarre that the intercept scripts (and other scripts) where stored at text in the objects. I built my parser to look at a specific variable in the script, that has path to script in question (basically a script pointing to itself on the file system) and just store the path.

Speculation: this whole thing (lack of manageable config) seems to be the result of no input from systems engineers and Unix/Linux people in general.
