### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by SergeiFranco** [jookies/jasmin#856]
In past many months I have been working to integrate jasmin, and I have encountered a few issues and questions. I haven't yet received any reply form developers, which makes me think this project is dead.

I purposely select Jasmin as the desired SMS Gateway because the project had recent updates, and appeared to be maintained. After a few months of struggling I came to conclusion that jookies have given up. Is this the case?

**Comment by EmileSteelman** [comment]
Hello Sergei,
JasminSMS Gateway as Jookies are still alive and keeping moving forward. 
Feel free to ask for support or assistance on our main email address

Now, you have the proof we are still exist, find the way to reach out. 

With regards, 
Emile STEELMAN

**Comment by SergeiFranco** [comment]
Awesome!
