### ISSUE TITLE
routable script 

### ISSUE THREAD

**Issue by canbazb123** [jookies/jasmin#857]
Hi 
I am trying configure hLr queries but where can I find sample routable scripts ? 

manager@jasminsmsc:~$ sudo python2 /opt/jasmin-scripts/interception/mt-interceptor.py 
Traceback (most recent call last):
  File "/opt/jasmin-scripts/interception/mt-interceptor.py", line 22, in <module>
    res = eurotel_ported(routable.pdu.params['destination_addr'], "@195.155.xx.yy", "195.155.xx.zz")
NameError: name 'routable' is not defined

**Comment by farirat** [comment]
What are you willing to do ?

**Comment by canbazb123** [comment]
I am trying to run hlr lookup for mt 
HLR lookup sample script includes routable function , thats why looking rouable python script

**Comment by farirat** [comment]
For hlr lookup you need to make use of the tagging inside interceptor then setup your route based on tags.

**Comment by canbazb123** [comment]
I did but when I try to run python code I got routable error , Thats why I though I need routable script as well .Dont I need routable script ? 

So following config will work ? 


manager@jasminsmsc:~$ sudo cat /opt/jasmin-scripts/interception/mt-interceptor.py
[sudo] password for manager: 
"This script will call HLR lookup api to get the MCC/MNC of the destination number"
import socket
import requests, json
import re
from dns import name, resolver, e164 # pip install dnspython

def eurotel_ported(phone, from_origin, name_server):
    origin = name.from_text(from_origin)
    server = resolver.Resolver(name_server)
    server.nameservers = [socket.gethostbyname(name_server)]
    server.port = 5390
    try:
        answers = server.query(e164.from_e164(phone, origin), 'NAPTR')
        for rdata in answers:
            if rdata.flags == 'u':
                regex = rdata.regexp.split('!')
                return re.sub(regex[1], regex[2], phone).lstrip('sip:').split('@')[0]
    except Exception as err:
        print("Error while accessing enum dns, err: %s" % str(err))
    return None

res = eurotel_ported(routable.pdu.params['destination_addr'], "@195.155.xy", “195.155.zt")

if res:
    res = res[:4]

if res == 'B001':
    print ("21401")
    # TurkTelekom
   routable.addTag(21401)
elif res == 'B002':
    print ("21402")
    # Turkcell
    routable.addTag(21403)
elif res == 'B003':
    print ("21403")
    routable.addTag(21404)



manager@jasminsmsc:~$ sudo python2 /opt/jasmin-scripts/interception/mt-interceptor.py 
Traceback (most recent call last):
  File "/opt/jasmin-scripts/interception/mt-interceptor.py", line 22, in <module>
    res = eurotel_ported(routable.pdu.params['destination_addr'], "@195.155.xy", "195.155.zt")
NameError: name 'routable' is not defined





jcli : mtrouter -l
#Order Type                    Rate       Connector ID(s)                                  Filter(s)                                                       
#102   StaticMTRoute           0 (!)      smppc(jasvdf)                                    <TG (tag=21403)>                                                
#101   StaticMTRoute           0 (!)      smppc(jastrcell)                                 <TG (tag=21402)>                                                
#100   StaticMTRoute           0 (!)      smppc(jastt)                                     <TG (tag=21401)>                                                
Total MT Routes: 3
jcli :

**Comment by hzcodertr** [comment]
bu hangi sms firması eurotelden nts mi sorguluyorsun ?

**Comment by canbazb123** [comment]
evet test platform

**Comment by canbazb123** [comment]
could you help me about query ? 
thanks

**Comment by farirat** [comment]
What help are you looking for ?
