### ISSUE TITLE
Feature discrepancy between JCLI and PB

### ISSUE THREAD

**Issue by SergeiFranco** [jookies/jasmin#859]
I decided to create new separate issue relating to #855 but different enough to warrant new issue.

When I queried how to manage config in Jasmin I have been pointed to Proxy Brokers.
I have managed to interface with PB using [this](https://jasmin.readthedocs.io/en/stable/faq/developers.html#faq-2-htdatpba) as an example.

It is all fine and dandy except there is a feature disparity between JCLI and PB. I haven't noticed it at first, but after wasting whole day on writing config parser for PB, I realised that two important features are missing from PB:
httpcm
filters
https://jasmin.readthedocs.io/en/stable/_images/jcli-architecture.png

So my question is: What is the "official" to export config in a portable, human readable way? Please don't point me to the pickled data.

**I am stumped, how this project got so far without ability to import/export config?!?**

On side note: MD5 unsalted hashes are not secure. Please use salted SHA2 (at minimum) as hash algorithm for your passwords.

**Comment by farirat** [comment]
What is the "official" to export config in a portable, human readable way? Please don't point me to the pickled data.

> Pickled data
