### ISSUE TITLE
Help :: Unable to browse the file structure to see the jasmin.config in Docker

### ISSUE THREAD

**Issue by Harunamusoke** [jookies/jasmin#860]

**Comment by farirat** [comment]
Please provide more info on this problem ?

**Comment by erwin-komaruloh** [comment]
@Harunamusoke Try to ssh to the jasmin container `$ docker exec -ti <jasmin_container> /bin/bash`. You may find what you are looking for in `/etc/jasmin/` folder. Although I don't see jasmin.config file there.
