### ISSUE TITLE
Send sms from SMSC to SMSC

### ISSUE THREAD

**Issue by disels** [jookies/jasmin#862]
There is the following scheme
**SMSC1**> **JASMINE** <**SMSC2**
connections made in smppccm
transceiver mode for each connection
Can I send a message from SMSC1 to SMSC2?
Now it turns out that all messages from SMSC1 get as it should in SMS-MO.
But they are perceived not as submit_sm, but as DELIVER_SM.
And are not forwarded to the **SMSC2** side

Please tell me where is my mistake in understanding the process?
SMS-MO only available as DELIVER_SM?

**UPDATE:** in deliversm-thrower.log  i have message 

 ERROR    516 Throwing SMPP/DELIVER_SM [msgid:f3361b16-98ae-432d-b5b9-3dc48ab4d827] to (simple 1/1)[cid:SMSC2], <class 'jasmin.routing.throwers.SystemIdNotBound'>: SMSC2.

**Comment by SergeiFranco** [comment]
I could be misunderstanding this but this looks like you need to convert mt->mo and vice-versa.

Perhaps #811 can shed some insight in mt<>mo situation...

**Comment by disels** [comment]
I think you understood correctly. I will try your solutions.
But I still have a question
in **deliversm-thrower.log** i have message

`ERROR 516 Throwing SMPP / DELIVER_SM [msgid: f3361b16-98ae-432d-b5b9-3dc48ab4d827] to (simple 1/1) [cid: SMSC2], <class 'jasmin.routing.throwers.SystemIdNotBound'>: SMSC2.`

Where and how is trying to look for SMSC2?

**Comment by farirat** [comment]
@disels is this a usecase from latin america mno ? they use deliver as submit and it's weird .. tell if it is, we already fixed this issue.
