### ISSUE TITLE
http://jasminsms.com/

### ISSUE THREAD

**Issue by LinuxDevBD** [jookies/jasmin#873]
Website not able to access not able to create billing http://jasminsms.com/

**Comment by SergeiFranco** [comment]
They forgot to renew the cert.
@farirat is the only person who used to respond, but he also disappeared. I thinks is project is abandoned.

**Comment by EmileSteelman** [comment]
Hello Guys
Like everyone here we have families and personal life to manage and Covid-19 made everyone's life harder 
Web site is now back on line

Keep sharing the passion

Your sincerely 
Emile

**Comment by LinuxDevBD** [comment]
thanks
