### ISSUE TITLE
Sms Sent but not received on the phone 

### ISSUE THREAD

**Issue by lord-zeus** [jookies/jasmin#878]
Hello guys please I'm pretty new to Jasmin 

I think I succeeded in  setting up Jasmin but when I Send Sms I do not receive it on my phone I do not really know the issue 

I receive this `Success "ef4fc74b-ed01-4da9-9530-e393aeb08553"` as the response 

please any help will be really good

**Comment by Swabuu** [comment]
Hello,

The "Success [GUID]" (HTTP code 200) is an HTTP response coming from Jasmin's HTTP API confirming that your message has been accepted by the Jasmin platform. Do not confuse this response with the DLR (delivery report) of the actual SMS message.

Jasmin needs to process your message based on the routing rules set up to determine which outgoing SMPP connection the message should be sent out via. 

If your SMS message was not received you need to look into the used SMPP-connector to troubleshoot further.
