### ISSUE TITLE
How do I redirect to external url from `http://ip:1401/send`  action in Jasmin 

### ISSUE THREAD

**Issue by selimppc** [jookies/jasmin#882]
Hi, 

I want to redirect to external url while sending SMS through Jasmin. Now I have:

```
    http://127.0.0.1:1401/send
```

I want to redirect or call external URL  while sending SMS. I mean I need to add an external api in the action of `SEND`. 

`Note: external URL will send SMS`

I could not find out the location to write some code or add configuration.  
Please share your idea so that I can solve my issue.

**Comment by KamuiX** [comment]
Just write a php script somewhere in you domain e.g. www.your_domain.com/send.php and call it. Inside there make your changes and finally "curl" the  http://127.0.0.1:1401/send with all the extra POST options.

If you want to direct expose jasmin 1401/send API then just go to /etc/jasmin/jasmin.cfg and change the below line
```
[http-api]
# If you want you can bind a single interface, you can specify its IP here
#bind                           = 0.0.0.0  <----uncomment and write the IP you need 

# Accept connections on the specified port, default is 1401
#port                           = 1401
```
Be sure that port 1401 is accesible

**Comment by selimppc** [comment]
@KamuiX , 
1. I want to receive SMS request from SMPP Client through port 2775.
2. And then forward to external HTTP URL.

**Comment by KamuiX** [comment]
1st you need to contact with your SMSC operator and enable the MO (incoming SMS) so they can route a specific phone number to you. Of course I do now know if you have any "Sim card" device that receives SMS and forward them through SMPP. 

2nd establish an SMPP connection between Jasmin and the other end.

3rd create prepare a script to receive SMS and create a http client connector to link that script. It's similar like getting DLR when you send a MT SMS. Read the below
https://jasmin.readthedocs.io/en/latest/apis/ja-http/index.html#receiving-sms-mo
https://jasmin.readthedocs.io/en/latest/management/jcli/modules.html#http-client-connector-manager

4th there are pretty easy steps in Jasmin's guide. https://jasmin.readthedocs.io/en/latest/management/jcli/modules.html#mo-router-manager Create a MO route that deals incoming messages either from a specific connector or by checking the content or the destination number etc. The route will "guide" your SMS from the SMPP connection at 2775 to the HTTP client connector...your script that will then store it.

**Comment by LinuxDevBD** [comment]
Any device (SWITCH/GOIP/SK Device) require to send sms using this format @KamuiX 

what you advice to use? We can not able to send and receive only using Jasmin SMS gateway software

**Comment by KamuiX** [comment]
You use SIM card gateways (SIM farms is the term if I am correct) 

I really don't have any experience with such devices and I really don't know what protocols they support for sending SMS. 
1) Be sure that they support SMPP and they can act like an SMSC
2) Are you sure that these devices don't come with routing functions?

Jasmin in general does the following           Input                                   Output
                                                                  SMPP--------\
                                                                                         ------------->SMPP
                                                                  HTTP--------/

So 1st verify that your SIM gateway understands SMPP.

If not I suppose the only solution is through HTTP API that the Gateway comes with. and you need to implement the entire logic on your own.
