### ISSUE TITLE
Encoding multipart / concatenated SMS does not apply to all parts

### ISSUE THREAD

**Issue by KamuiX** [jookies/jasmin#883]
Hello everybody

I made an interceptor to handle messages that come from various sources (http api or smpp) and need to pass a specific connector. The connector use a custom implementation of latin-1 so I have to 1st re-encode the 'short_message' parameter and then change the 'data coding' to 3 (DataCodingDefault.LATIN_1). 

My conversions work flawlessly but I have problem when someone sends a concatenated message using coding 0 (DataCodingDefault.SMSC_DEFAULT_ALPHABET). Because only the 1st part is "handled" by the interceptor but not the rest of the parts. below is my code for your reference. 

P.S. the conversion script ignores UCS2 encoded messages.

```
def isUdhIndicatorSet(esm_class):
    if hasattr(esm_class, 'gsmFeatures'):
        for gsmFeature in esm_class.gsmFeatures:
            if str(gsmFeature) == 'UDHI_INDICATOR_SET':
                return True
    return False

#logger.info('Got pdu: %s' % routable.pdu)

msg=routable.pdu.params['short_message']
ucode = False

# Get if SMS is concatenated
isUdhSet = isUdhIndicatorSet(routable.pdu.params['esm_class'])
if isUdhSet and routable.pdu.params['short_message'][:3] == '\x05\x00\x03':
    header = routable.pdu.params['short_message'][:6]
    msg = routable.pdu.params['short_message'][6:]

if isinstance(routable.pdu.params['data_coding'], int):
    if routable.pdu.params['data_coding'] == 0 :
        msg = gsm_decode(msg)
        routable.pdu.params['short_message'] = msg
        routable.lockPduParam('short_message')
        routable.pdu.params['data_coding'] = 3
        routable.lockPduParam('data_coding')
    elif routable.pdu.params['data_coding'] == 3 :
        msg = msg.decode('utf-8')
        routable.pdu.params['short_message'] = gsm_encode(msg)
        routable.lockPduParam('short_message')
        routable.pdu.params['data_coding'] = 3
        routable.lockPduParam('data_coding')
    elif routable.pdu.params['data_coding'] == 8 :
        ucode = True
else:
    logger.info('2')
    param = str(routable.pdu.params['data_coding'].schemeData)
    if param == 'SMSC_DEFAULT_ALPHABET':
        msg = gsm_decode(msg)
        routable.pdu.params['short_message'] = msg
        routable.lockPduParam('short_message')
        routable.pdu.params['data_coding'] = DataCoding(DataCodingScheme.DEFAULT,DataCodingDefault.LATIN_1)
        routable.lockPduParam('data_coding')
    elif param == 'LATIN_1':
        msg = msg.decode('utf-8')
        routable.pdu.params['short_message'] = gsm_encode(msg)
        routable.lockPduParam('short_message')
        routable.pdu.params['data_coding'] = DataCoding(DataCodingScheme.DEFAULT,DataCodingDefault.LATIN_1)
        routable.lockPduParam('data_coding')
    elif param == 'UCS2' :
        ucode = True

if isUdhSet and ucode == False:
    routable.pdu.params['short_message'] = header + routable.pdu.params['short_message']
```

So after I get a SMSC_DEFAULT_ALPHABET or a LATIN_1 encoded message I re-encode it using my custom gsm_encode and gsm_decode methods. and set the data_coding ALWAYS to DataCodingDefault.LATIN_1. 
Message arrives to the final recipient (terminal) and everything is ok when it's single message.  When it's multipart / concatenated the below happens.

![multipart](https://user-images.githubusercontent.com/45120618/92224699-d72b1f80-eeaa-11ea-8707-e459816b16db.jpg)

As a result the 1st part of the multi - message looks ok but the second has "character problems" because the encoding set haven't changed. 
As it seems only the 1st part gets the DataCodingDefault.LATIN_1 but the rest of the parts does not get the encoding or even does not pass through the interceptor.
How can I handle all parts of a multipart sms through the interceptor?

**Comment by SergeiFranco** [comment]
My experience with interceptors is that the multipart messages are treated by the interceptor as separate message.
So if the message comes in as multiple parts each separate part is intercepted.
This is because the jasmin/managers/listeners.py has the re-assembly of the message happened after the interception happened.

I had opposite problem where I needed to "yank" the whole message and process it externally via an interceptor, since I had only parts at a time I had to use a temporary storage to store it and reassemble.

**Comment by KamuiX** [comment]
Hi @SergeiFranco and thanks for the reply. 
I thought of the same think and I made a plain interceptor that prints "ok" whenever an sms gets intercepted.
Either if it's single SMS or a multipart SMS the "ok" prints once and that made me understood that only the first parts of the multipart gets intercepted and not the rest.

I don't know (and there is no documentation) if multipart messages arrive as a "PDUs array" to the interceptor and needs to be handled all of them in one interception.

**Comment by KamuiX** [comment]
Hooray! It was taking too long so I started search various problems about concatenated SMS in issues and I got to this thread
https://github.com/jookies/jasmin/issues/533

And thanks to user @101t that has shared the code that helped me understand how to iterate through multiple PDUs in multipart sms

```
_pdu = routable.pdu
while hasattr(_pdu, 'nextPdu'):
	_pdu = _pdu.nextPdu
```
