### ISSUE TITLE
BUG: MO Interceptor never succesful if args[0] is a dict.

### ISSUE THREAD

**Issue by SergeiFranco** [jookies/jasmin#884]
I am having issues with MO Interceptor always failing with:
```Failed running interception script , got the following return: {'smpp_status': 0, 'http_status': 0, 'extra': {}}```

It seems there is no success case if the args[0] is a dict in: /usr/lib/python2.7/dist-packages/jasmin/managers/listeners.py,starting on line 569.

it is missing:

```
                elif isinstance(args[0], dict) and args[0]['smpp_status'] == 0:                                                                                                                                                                                               
...
```

Unless I am misunderstanding it? It is being handled correctly in the /usr/lib/python2.7/dist-packages/jasmin/protocols/smpp/factory.py.

**Comment by farirat** [comment]
Duplicate to #829

**Comment by farirat** [comment]
success case is

```
elif isinstance(args[0], (str, bytes)):
```

**Comment by SergeiFranco** [comment]
> success case is
> 
> ```
> elif isinstance(args[0], (str, bytes)):
> ```

The behaviour I see if I run a simple interceptor it returns a dict as args[0] instead of bytes or string.

**Comment by farirat** [comment]
@SergeiFranco please share your interceptor script, i need to understand what you want to do

**Comment by SergeiFranco** [comment]
I simplified original script to bare minimum, yet I can 100% replicate the issue where the MO script returns args[0] as dictionary.

The test script is following:

```
from syslog import syslog
import sys
from datetime import datetime

globals()['sys']=sys
globals()['syslog']=syslog
globals()['datetime']=datetime
    
def submit(r):
    import requests
    import urllib
    params = {'username' : 'testuser',
              'password' : 'testpassword',
              'from' : r.pdu.params['source_addr'],
              'to' : r.pdu.params['destination_addr'],
              'body' : r.pdu.params['short_message'],
    }
    url = "%s?%s" % ('http://127.0.0.1:8000/testsubmit',urllib.urlencode(params))
    try:
        req = requests.get(url,verify=False)
        req.raise_for_status()
        m = "Submitted message (from: %s to: %s), Status code: %d." % (r.pdu.params['source_addr'],r.pdu.params['destination_addr'],req.status_code)
        syslog(m)
    except Exception as e:
        m = "Error submitting message; error '%s'." % (str(e))
        syslog(m)

try:
    smpp_status = 0
    http_status = 0
    extra = {'DROP':True}
    submit(routable)
except Exception as e:
    syslog("Post submit error: '%s'." % str(e))
    pass
```
The filter is following:
```
fid test 
type DestinationAddrFilter 
destination_addr 642123456789 
```

The MO interceptor is following:

```
order 666 
type StaticMOInterceptor 
filters test 
script python2(/opt/jasmin-scripts/submit_test.py) 
```

It does indeed submits a test HTTP server:

```
127.0.0.1 - - [11/Oct/2020 10:40:34] "GET /testsubmit?username=testuser&to=642123456789&body=test&password=testpassword&from=642123456789 HTTP/1.1" 200 -
```

The return type is definitely dictionary (I have added a line in /usr/lib/python2.7/dist-packages/jasmin/managers/listeners.py to do so):
```
2020-10-11 10:40:34 INFO     74486 Interceptor script return args[0] as <type 'dict'>.
```

The line in question (line # 570 in jasmin/managers/listeners.py):
```
            # Post interception:                                                                                                                                                                                                                                              
            if len(args) == 1:                                                                                                                                                                                                                                                
                self.log.info("Interceptor script return args[0] as %s." % type(args[0]))
```

**Comment by farirat** [comment]
Okay.. let's get back to the abcs.

If you need to reject a message within your interceptor then you have to set the required smpp_status and http_status values, setting smpp_status=0 wont work because that's not a rejection error, it's a success (ESME_ROK).

Returning a success status is the default behaviour, you wont need to set the *_status keys inside your interceptor.

As for passing the "extra" arg, you can't do it with a ESME_ROK status, because the routable needs to be returned back in this case.

**Comment by SergeiFranco** [comment]
I am sure you have misunderstood my issue here. Please ignore the other issue where I asked about the dropping messages. Also please ignore the 'extra' variable, it is leftover from previous testing (I successfully hacked the source to actually drop a message with ESME_ROK by setting extra variable with {DROP:True}).

The issue here regardless if extra is set or not MO interceptor returns args[0] as a dictionary, and there is no test case in the original jasmin source to handle that.

The MO interceptor processing behaves differently than MT interceptor, the MT interceptor post processing actually has a case where it tests if args[0] is a dictionary.

**Comment by SergeiFranco** [comment]
Looking at the interceptor code (jasmin/interceptor/interceptor.py, line 68):

```            if glo['smpp_status'] is None and glo['http_status'] is None:                                                                                                                                                                                                     
                return pickle.dumps(glo['routable'], pickle.HIGHEST_PROTOCOL)                                                                                                                                                                                                 
            else:                                                                                                                                                                                                                                                             
                # If we have one of the statuses set to non-zero value                                                                                                                                                                                                        
                #  then both of them must be non-zero to avoid misbehaviour                                                                                                                                                                                                   
                #  of differents apis: if we return an error in smpp, we must                                                                                                                                                                                                 
                #  do the same in http as well.                                                                                                                                                                                                                               
                if glo['smpp_status'] is None or not isinstance(glo['smpp_status'], int):                                                                                                                                                                                     
                    # ESME_RUNKNOWNERR                                                                                                                                                                                                                                        
                    self.log.info(                                                                                                                                                                                                                                            
                        'Setting smpp_status to 255 when having http_status = %s and smpp_status = %s.',                                                                                                                                                                      
                        glo['http_status'],                                                                                                                                                                                                                                   
                        glo['smpp_status'])                                                                                                                                                                                                                                   
                    glo['smpp_status'] = 255                                                                                                                                                                                                                                  
                elif glo['http_status'] is None or not isinstance(glo['http_status'], int):                                                                                                                                                                                   
                    # Unknown Error                                                                                                                                                                                                                                           
                    self.log.info(                                                                                                                                                                                                                                            
                        'Setting http_status to 520 when having smpp_status = %s and http_status = %s.',                                                                                                                                                                      
                        glo['smpp_status'],                                                                                                                                                                                                                                   
                        glo['http_status'])                                                                                                                                                                                                                                   
                    glo['http_status'] = 520                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                              
                r = {'http_status': glo['http_status'], 'smpp_status': glo['smpp_status'], 'extra': glo['extra']}                                                                                                                                                             
                self.log.info('Returning statuses: %s', r)                                                                                                                                                                                                                    
                return r
```

It appears I am failing all conditions checks because I have both smpp_status and http_status set, thus it returns a dictionary.

This is confirmed by this:
```
/var/log/jasmin/interceptor.log:2020-10-11 16:09:27 INFO     74485 Returning statuses: {'smpp_status': 0, 'http_status': 0, 'extra': {'DROP': True}}
```


Reading the documentation (https://docs.jasminsms.com/interception/index.html), it states the following:


> 
> Note
> 
> When setting http_status to some value different from 0, the smpp_status value will be automatically set to 255 (ESME_RUNKNOWNERR).
> 
> Note
> 
> When setting smpp_status to some value different from 0, the http_status value will be automatically set to 520 (Unknown error).
> 
> Note
> 
> When setting smpp_status to 0, the routing process will be bypassed and an ESME_ROK status is returned.

Interestingly last Note suggest that the message is dropped with ESME_ROK (in practice it is not). Again the dropping of the message is not the issue here. The issue here in wording "routing process will be bypassed", as it does not elaborate what actually happens to the message.

**Comment by SergeiFranco** [comment]
Sorry for the noise, I am working things out as I go.
Now I kind of understand what I am doing "wrong".
I am setting *_status variables, which then causes to return a status dictionary.
If I did not set the *_status variables, then it would return routable.
In documentation it states that routing will be bypassed if the smpp_status is set to 0. I can't figure out what actually happens to the message.

Another note: I think if the http_status is not set and smpp_status is set (regardless of the value) the http_status will be set to 520, which contradicts the documentation.
Line 83 in jasmin/interceptor/interceptor.py

```
                elif glo['http_status'] is None or not isinstance(glo['http_status'], int):                                                                                                                                                                                   
                    # Unknown Error                                                                                                                                                                                                                                           
...                                                                                                                                                                                                                              
                    glo['http_status'] = 520 
```

**Comment by farirat** [comment]
I cna see there's a difference between intercepting MT and MO in Jasmin, in MT it is permitted to return a smpp_status=0 which results in a black hole behaviour (message is not routed anywhere with a ESME_ROK returned to client), this is not permitted in MO, i don't recall the reasons, but this is maybe because there's no need for a black hole usecase in MO traffic ...

**Comment by SergeiFranco** [comment]
****

> I cna see there's a difference between intercepting MT and MO in Jasmin, in MT it is permitted to return a smpp_status=0 which results in a black hole behaviour (message is not routed anywhere with a ESME_ROK returned to client), this is not permitted in MO, i don't recall the reasons, but this is maybe because there's no need for a black hole usecase in MO traffic ...

May I ask why there is no need to blackhole specifically MO traffic?

My use case will be running an interceptor and submitting message via an arbitrary API and then dropping the message. 
Somebody else's use case could be spam control without upsetting upstream with rejection messages.
Yet somebody else might implement MO->MT conversion via interception (thus they need to drop original message).

BTW all the SMPP servers from major telcos here always return ESME_ROK, regardless if the message is valid or not.

**Comment by farirat** [comment]
You answered yourself in the latter line:
`BTW all the SMPP servers from major telcos here always return ESME_ROK, regardless if the message is valid or not.`

Obviously, Jasmin always returns ESME_ROK, unless you make interception and change the status to something else.

You need to return ESME_ROK and cut off any further routing, this is not possible this way, you can achieve it by routing MO traffic to a http endpoint that just do nothing, it's a black hole.

I used the same thing to implement many MO->MT use cases.

**Comment by SergeiFranco** [comment]
Having an http server returning 200 OK is another moving part I am trying to avoid.
Since now I know that MT does actually blackhole, that solves my MT->MO conversion questions.
Wouldn't be nice for interceptors behave the same way regardless of MT or MO?

I have two options, continue using my modified listerners.py and reintroduce the patch after every upgrade (pretty much two lines of code), or implement an HTTP blackhole just for it.

In reality if I would go with HTTP route, I would move the MO interceptor code into the WSGI script, and remove MO interception entirely. While having MT interceptor call the HTTP directly while returning smpp_status = 0. 

Which brings another question, why there is no HTTP client for the MT?

**Comment by farirat** [comment]
Would be glad seeing a PR to fix those issues, and enhancing the mo interceptor to be compliant to the mt interception logic, need to be covered by the tests as well.

Please consider 0.10 brannch as a base branch (python3).
