### ISSUE TITLE
How to see ucs2 text in logs?

### ISSUE THREAD

**Issue by sumeetb** [jookies/jasmin#886]
The UCS2 characters are printed in encoded form. How I can configure jasmin to print in text?
Its printed like this in smpp log.
short_message: '\x00b\x00c\x00d\x00e\x00f\x00g'
In message log its printed like this
[content:'.=.0.0.2.7.(.).*.+.,.-.../

**Comment by sumeetb** [comment]
@farirat Please reply

**Comment by farirat** [comment]
I don't really think this is possible, ucs2 is printed in binary format.
