### ISSUE TITLE
Service can't start after installation

### ISSUE THREAD

**Issue by jaffermbuzz** [jookies/jasmin#89]
Dear Guys,

Please help me after installation done on jasmin gateway service is not starting.

sudo /etc/init-d/ start

Reagrds,

Jaffer

**Comment by pyghassen** [comment]
Hi @jaffermbuzz can you provide some logs?
You can find them here /var/log/jasmin/twistd-jasmin.log by the way.

**Comment by fourat** [comment]
Hi,

it is **sudo /etc/init.d/jasmind start**

If it's still not working, then you probably missed a step from the installation, this one:

    sudo ln -s /etc/jasmin/init-script/jasmind /etc/init.d/

and then try to start the service again

**Comment by jaffermbuzz** [comment]
Dear Team ,

Thank you for your Support!







Best Regards,



*P* Please consider your environmental responsibility before printing this
e-mail

*DISCLAIMER: This email and any files transmitted with it are confidential
and intended solely for the use of the individual or entity to whom they
are addressed. If you have received this email in error please notify
Mobile Communications Company International. This message contains
confidential information and is intended only for the individual named. If
you are not the named addressee you should not disseminate, distribute or
copy this e-mail. Please notify the sender immediately by e-mail if you
have received this e-mail by mistake and delete this e-mail from your
system. If you are not the intended recipient you are notified that
disclosing, copying, distributing or taking any action in reliance on the
contents of this information is strictly prohibited.*
