### ISSUE TITLE
WHAT IS THE REAL ROLE OF Jasmin SMS GATEWAY ???

### ISSUE THREAD

**Issue by ChegMarcoADVANTECH** [jookies/jasmin#890]
HELLO.

I don't really understand how JASMIN SMS GATEWAY works and I would like you to explain it better.

Is it possible to use JASMIN SMS GATEWAY to send real SMS (real SMS) on mobile phone numbers (mobile phone number) without going through telephone operators or GSM network operators ???

Is JASMIN able to set up an SMS Server to send Massive SMS Campaigns to Cellular Telephone Numbers without relying on Telephone Operators or other SMS providers ???

What is really the role or the functioning of JASMIN SMS GATEWAY ???

Thank you for yor information.

**Comment by DomAmato** [comment]
**You can not arbitrarily send SMS from any program without using a telephone provider.** Thats just not how it works.

> Is JASMIN able to set up an SMS Server to send Massive SMS Campaigns to Cellular Telephone Numbers without relying 
on Telephone Operators or other SMS providers ???

No

> What is really the role or the functioning of JASMIN SMS GATEWAY ???

Jasmin can act as part of the telecom stack, but you need to connect jasmin to some telco providers SMSC which is using the SMPP protocol. You would have to contact a local telecom provider and work out some contractual agreement with them to integrate Jasmin with their SMSC. What you are describing sounds a lot like a spam campaign though and would likely get you banned from any network unless you had some kind of amazing contract with the teleco provider.

**Comment by zahmaci** [comment]
> HELLO.
> 
> I don't really understand how JASMIN SMS GATEWAY works and I would like you to explain it better.
> 
> Is it possible to use JASMIN SMS GATEWAY to send real SMS (real SMS) on mobile phone numbers (mobile phone number) without going through telephone operators or GSM network operators ???
> 
> Is JASMIN able to set up an SMS Server to send Massive SMS Campaigns to Cellular Telephone Numbers without relying on Telephone Operators or other SMS providers ???
> 
> What is really the role or the functioning of JASMIN SMS GATEWAY ???
> 
> Thank you for yor information.

**Comment by ChegMarcoADVANTECH** [comment]
> > BONJOUR.
> > Je ne comprends pas vraiment comment fonctionne JASMIN SMS GATEWAY et j'aimerais que vous l'expliquiez mieux.
> > Est-il possible d'utiliser JASMIN SMS GATEWAY pour envoyer de vrais SMS (vrais SMS) sur des numéros de téléphone mobile (numéro de téléphone mobile) sans passer par des opérateurs de téléphonie ou des opérateurs de réseaux GSM ???
> > Est-ce que JASMIN est capable de configurer un serveur SMS pour envoyer des campagnes SMS massives aux numéros de téléphone cellulaire sans compter sur les opérateurs téléphoniques ou d'autres fournisseurs de SMS ???
> > Quel est vraiment le rôle ou le fonctionnement de JASMIN SMS GATEWAY ???
> > Merci pour vos informations.
> 
> Veuillez vérifier "Architecture" sur https://github.com/jookies/jasmin . Il explique tout

Thanks for your reply

**Comment by ChegMarcoADVANTECH** [comment]
> **Vous ne pouvez pas envoyer arbitrairement des SMS à partir de n'importe quel programme sans utiliser un opérateur téléphonique. **Ce n'est tout simplement pas comme ça que ça marche.
> 
> > Est-ce que JASMIN est capable de configurer un serveur SMS pour envoyer des campagnes SMS massives aux numéros de téléphone cellulaire sans compter 
> > sur les opérateurs téléphoniques ou d'autres fournisseurs de SMS ???
> 
> Non
> 
> > Quel est vraiment le rôle ou le fonctionnement de JASMIN SMS GATEWAY ???
> 
> Jasmin peut faire partie de la pile de télécommunications, mais vous devez connecter jasmin à certains fournisseurs de télécommunications SMSC qui utilisent le protocole SMPP. Vous devrez contacter un fournisseur de télécommunications local et conclure un accord contractuel avec eux pour intégrer Jasmin à leur SMSC. Ce que vous décrivez ressemble cependant beaucoup à une campagne de spam et vous ferait probablement bannir de tout réseau à moins que vous n'ayez une sorte de contrat incroyable avec le fournisseur de télécommunications.

**Comment by ChegMarcoADVANTECH** [comment]
> Jasmin

**Comment by ChegMarcoADVANTECH** [comment]
> **You can not arbitrarily send SMS from any program without using a telephone provider.** Thats just not how it works.
> 
> > Is JASMIN able to set up an SMS Server to send Massive SMS Campaigns to Cellular Telephone Numbers without relying
> > on Telephone Operators or other SMS providers ???
> 
> No
> 
> > What is really the role or the functioning of JASMIN SMS GATEWAY ???
> 
> Jasmin can act as part of the telecom stack, but you need to connect jasmin to some telco providers SMSC which is using the SMPP protocol. You would have to contact a local telecom provider and work out some contractual agreement with them to integrate Jasmin with their SMSC. What you are describing sounds a lot like a spam campaign though and would likely get you banned from any network unless you had some kind of amazing contract with the teleco provider.


Thank you for your various interventions. But I'm still a blur. Actually, what I still don't understand is that "if I have to use the SMSC of a telecommunication network which already has its own API for sending SMS, why still use JASMIN SMS ???

How JASMIN would benefit me if I should already contact the SMSC of a telecommunication network knowing that GSM networks themselves have their own SMS API which can help me send my SMS ???

Don't you find that JASMIN is no longer useful ??? If not, what role would JASMIN play if I also contact the SMSC of a GSM operator ??? Isn't that JASMIN would be useless since GSM networks already have full SMS API ???

**Comment by magojr** [comment]
Hello, let's try to reply to your question.
The role of Jasmin in the SMS stack is similar to the role of a router in internet.
You need it to browse the web? Not at all, you can use your phone or you can use a "closed box" supplied from your internet provider (without know if it is a modem, a roter, a bridge or whatever, don't think about it, it doesn't matters).
Anyway a lot of company buy routers to manage their network properly or to manage traffic that they supply to customers.
But... no router gives you any internet access without an internet provider.
The same is for the SMS...  no telco pay millions of $ for telecom infrastructures and agreement taken with operators all over the world and "resell" it for free. You need to use the telco infrastructure to reach the end-user mobile phone by SMS so you must pay the usage of the cellular network.

So how jasmin can help?
You can have 1000 customers that buy the service with different policy/priority/costs based on your business model and you may have 20 supplier of SMS for different kind of service / destination country / speed / costs. 
Each of them has their own price model and their own limit (eg. one of them may have 30 sms/second as limit,  1 cent every request, 2 cent every sent message, 2 cent for every DLR with the sent status as billing policy;  another one 30sms/s and a flat fee of 3cent/SMS) and jasmin manage these "queue, limits, billing calculation" for you in a quite optimized way, using some well known and fast tools like Redis and Rabbit.
If your case/business can have any benefit (or not) from the Jasmin usage, it's up to your needs, nobody can tell you if a software may help you or not better than you.

For everybody thinking that Jasmin is a magic software that inject SMS directly on the destination phone for free "jumping around" the telco infrastructure...
The answer is surely and absolutelly: NO, it isn't!

**Comment by DomAmato** [comment]
> already has its own API for sending SMS, why still use JASMIN SMS ???

You wouldnt need jasmin then

> How JASMIN would benefit me if I should already contact the SMSC of a telecommunication network knowing that GSM networks themselves have their own SMS API which can help me send my SMS ???

It wouldn't

> Don't you find that JASMIN is no longer useful ???

No, as a telco we use Jasmin because not every other telco has a SMS API and its not really for general consumer use. I think what you are trying to ask is as a consumer is this the right software for me and for your use case its likely no.

**Comment by ChegMarcoADVANTECH** [comment]
OK. I get it. Thank you all for your various explanations and interventions.
