### ISSUE TITLE
How to configure the interceptor to save DLR  ?

### ISSUE THREAD

**Issue by ChenYiHsiang** [jookies/jasmin#891]
I use interceptor to  enforce DLR, and it works well. 
but I found  errors in  smpp-server-pb.log: "Found no deliverer on system_id XXXXXXX" 

is it possible to assign something like url or value  in PDU  to  save DLR ?

**Comment by farirat** [comment]
That error occur when the smpp client using system_id XXXXXXX is not bound or is bound in transmitted mode, in this case, Jasmin cannot forward the dlr back to the ESME client.

**Comment by ChenYiHsiang** [comment]
So we can enforce DLR but cannot save it, right?

**Comment by farirat** [comment]
@ChenYiHsiang when you ask for DLR you must stay connected to Jasmin to get it back, this is obvious
