### ISSUE TITLE
PLEASE HELP ME! How can I find in Jasmin the SMPP information requested by my SMS provider ???

### ISSUE THREAD

**Issue by ChegMarcoADVANTECH** [jookies/jasmin#892]
HELLO All.

Right after installing JASMIN, I created a Connector with the following commands:

> telnet 127.0.0.1 8990
> username: jcliadmin
> password: jclipwd

> jcli : smppccm -a 
> cid SMS_CONNECTOR
> host 127.0.0.1
> port 2775
> username sms_smpp
> password Jil78
> bind transceiver
> submit_throughput 980796868
> ok
> Successfully added connector [SMS_CONNECTOR]

**Start the connector:**

> jcli : smppccm -1 SMS_CONNECTOR

**Configure a simple route for sending SMS:**

> jcli : mtrouter -a
> type defaultroute
> connector smppc(SMS_CONNECTOR)
> rate 0.00
> ok
> Successfully added MTRoute [DefaultRoute] with order:0

**Configure a route to receive SMS:**

> jcli : morouter -a
> type DefaultRoute
> connector smpps(SMS_CONNECTOR)
> ok

**Create a group:**

> jcli : group -a
> gid foogroup
> ok
> Successfully added Group [foogroup]

**Create a user:**

> jcli : user -a
> username smsgtway
> password izyzk67
> gid foogroup
> uid bjsms
> ok
> Successfully added User [bjsms] to Group [foogroup]

So my provider's SMS gateway asks me for the following **SMPP informations** from the API that I would like to integrate to send SMS:

> GATEWAY NAME
> GATEWAY API LINK
> "SMS API USERNAME" or "SYSTEM ID"
> SMS API PASSWORD
> PORT

**So I would like to know, with the information I used to configure Jasmin (see at the top of this text), how to fill in the SMPP API information (_GATEWAY NAME, GATEWAY API LINK, SMS API USERNAME, SMS API PASSWORD, PORT_) of Jasmin requested by the SMS Gateway in which I would like to integrate Jasmin ???**

Thank you for enlightening me because I do not know what this information is worth in my configuration of Jasmin.

**Comment by farirat** [comment]
So, from what you did:

- Gateway name: name it whatever you want ;)
- Gateway API Link: I think this should be your IP address, i don't know why they call it API
- Username: smsgtway
- Password: izyzk67
- Port: 2775 (default jasmin smpp port)

**Comment by ChegMarcoADVANTECH** [comment]
> Donc, d'après ce que vous avez fait:
> 
> * Nom de la passerelle: nommez-le comme vous voulez;)
> * Lien API Gateway: Je pense que cela devrait être votre adresse IP, je ne sais pas pourquoi ils l'appellent API
> * Nom d'utilisateur: smsgtway
> * Mot de passe: izyzk67
> * Port: 2775 (port smpp jasmin par défaut)

Hello @farirat and great thank you

**Comment by ChegMarcoADVANTECH** [comment]
**But I would like to know How to set an "UNLIMITED" Balance to this "smsgtway" user that I created ???**

**Comment by farirat** [comment]
Using a route with rate=0 should be fine.

**Comment by ChegMarcoADVANTECH** [comment]
ok thank you.
