### ISSUE TITLE
PLEASE HELP ME! What IP Address deserves to be assigned to "host" when adding an SMPP Connector ???

### ISSUE THREAD

**Issue by ChegMarcoADVANTECH** [jookies/jasmin#898]
Hello.

I have a concern. The concern is with the creation of an SMPP Connector. I would like to know:

1 - what is an "SMPP Connector" and what is its role ???

2 - the "**host**" functionality of the "**smppccm -a**" command should NORMALLY take which IP address ??? Because I'm confused and just put my Local IP Address as you can see below with "**host 127.0.0.1**". So please tell me what address deserves to be assigned to "**host**" when adding an SMPP Connector in Jasmin ??? **Is this the IP Address of my Ubuntu Linux System ???**

**Here are the commands used to create (add) a new SMPP Connector:**

> jcli : smppccm -a
> cid SMS_CONNECTOR
> host 127.0.0.1
> port 2775
> username sms_smpp
> password Jil78
> bind transceiver
> submit_throughput 980796868
> ok
> Successfully added connector [SMS_CONNECTOR]

**THANK YOU for enlightening me please.**
**Please help me understand.**

**Comment by magojr** [comment]
Hello ChegMarcoADVANTECH,
I really don't like who usually reply on some forum "search it on google" or similar but your question sound like someone that get his new car, switch it on and ask to the car seller "Where I have to go, now?".

In reply to your question: 
they usually are the data supplied from the SMS A2P (application 2 person) provider that you choose
OR they may be another installation of Jasmin that you are using to test the connection and troughtput
OR it may be an SMPP multiplexer that you choose to put behind some jasmin installation
OR it may be a deliverability test system
OR any hardware that operates using the SMPP protocol to show or send a message

If your goal is to send an SMS to a mobile phone it should be the first.

I suggest you to understand the SMS/SMPP workflow before using a tool do do something without know what you need exactly to do.
A good starting point can be the schema at page 12 in the SMPP specs here: https://smpp.org/SMPP_v5.pdf

Hope it may help you.

**Comment by ChegMarcoADVANTECH** [comment]
Ok GREAT THANK YOU
