### ISSUE TITLE
Need Information

### ISSUE THREAD

**Issue by jaffermbuzz** [jookies/jasmin#90]
Dear Guys,

Please provide me information for below points

1. How can i use Jasmin SMS Gateway for multiple provider?

2. How can filter the subscriber number in Jasmin Gateway. Subscriber doesn't wants to recieve the multiple SMS with same.

**Comment by fourat** [comment]
Welcome @jaffermbuzz,

 1. It is what Jasmin do: to manage multiple providers. Take a look on the docs, especially when it comes to adding multiple smpp connectors, playing with routings and filters.

 2. Please give more detail, what are trying to do ?

**Comment by jaffermbuzz** [comment]
Dear Fourat,

Thank you for your support

Line 2 : How can i filter the Numbers .It doesn't wants to send the message
to subscriber 2 times.

Example: more than 1000 number in the list may be some numbers are
repeated. so, i need to filter that numbers or otherwise it wants to delete
the duplicate numbers to save my cost.







Best Regards,



*P* Please consider your environmental responsibility before printing this
e-mail

*DISCLAIMER: This email and any files transmitted with it are confidential
and intended solely for the use of the individual or entity to whom they
are addressed. If you have received this email in error please notify
Mobile Communications Company International. This message contains
confidential information and is intended only for the individual named. If
you are not the named addressee you should not disseminate, distribute or
copy this e-mail. Please notify the sender immediately by e-mail if you
have received this e-mail by mistake and delete this e-mail from your
system. If you are not the intended recipient you are notified that
disclosing, copying, distributing or taking any action in reliance on the
contents of this information is strictly prohibited.*

**Comment by fourat** [comment]
When taking it from a clean design point of view, this is a logic to be implemented outside of Jasmin, because the latter is acting as a router, it will route any message your application need to send, so you have to know what are you sending.

From another point of view, this can be done using the EvalFilter in the Jasmin router, you can write whatever filtering logic in there and Jasmin will take it into consideration when routing your messages.

**Comment by jaffermbuzz** [comment]
Dear Fourat,

Thank you for your Support.







Best Regards,



*P* Please consider your environmental responsibility before printing this
e-mail

*DISCLAIMER: This email and any files transmitted with it are confidential
and intended solely for the use of the individual or entity to whom they
are addressed. If you have received this email in error please notify
Mobile Communications Company International. This message contains
confidential information and is intended only for the individual named. If
you are not the named addressee you should not disseminate, distribute or
copy this e-mail. Please notify the sender immediately by e-mail if you
have received this e-mail by mistake and delete this e-mail from your
system. If you are not the intended recipient you are notified that
disclosing, copying, distributing or taking any action in reliance on the
contents of this information is strictly prohibited.*
