### ISSUE TITLE
PLEASE HELP US to better understand the functioning of Jasmin SMPP Server that we are trying to take in hand

### ISSUE THREAD

**Issue by ChegMarcoADVANTECH** [jookies/jasmin#902]
Hello and have a good start to the week.

**Please tolerate my repeated questions as we found out about Jasmin SMS Gateway not long ago and are trying to understand how it works. Reason why, my questions follow one another. Indeed, I still have some concerns:**

**1 -** If Jasmin is both an SMPP Server and a client, how to install this SMPP Server from Jasmin just after the installation of Jasmin itself ???
Or do you think the SMPP Server is installed by default with the installation of Jasmin itself ???
If not, what are the commands to create your SMPP Server ???

**2 -** What is the IP address and the Port to access Jasmin SMPP remotely ??? In other words, how to connect to Jasmin SMPP remotely ???

**3 -** What are the commands to create an "**UNLIMITED**" **_SMS sending_ ROUTE** via the **Jasmin SMPP Server** ???

Please help us enlighten as these points are of indescribable importance.

**Comment by farirat** [comment]
1. Upon installation you get the server/client apis up & running
2. Smpp server is accessible on 0.0.0.0:2775 by default
3. [Read the docs](https://docs.jasminsms.com/) for this point, and for the 2 previous ones as well

**Comment by ChegMarcoADVANTECH** [comment]
Ok thank you
