### ISSUE TITLE
Documentation missing?

### ISSUE THREAD

**Issue by bobsburgers** [jookies/jasmin#903]
All the links I have used for the documentation seem to be dead. 

https://docs.jasminsms.com/en/latest/
https://docs.jasminsms.com/en/latest/installation/

seems like there is a bad redirect or url issue because you can still find it here. A lot of the sites linking in have these in the url as well. 
https://docs.jasminsms.com

**Comment by farirat** [comment]
Fixed, thanks for reporting it.
