### ISSUE TITLE
Docker build image for 0.10.5

### ISSUE THREAD

**Issue by KamuiX** [jookies/jasmin#914]
Hello All,
I'm not a docker guru in any way and I am learning through jasmin.

So I tried to build a docker images for jasmin 0.10.5 so I executed the below 

root# docker build https://github.com/jookies/jasmin.git#0.10.5:docker
Sending build context to Docker daemon  15.36kB
Step 1/18 : FROM python:3-buster
 ---> 5336a27a9b1f
Step 2/18 : MAINTAINER Jookies LTD <jasmin@jookies.net>
 ---> Running in bf2f865a62a5
Removing intermediate container bf2f865a62a5
 ---> fba1aef1b263
Step 3/18 : RUN groupadd -r jasmin && useradd -r -g jasmin jasmin
 ---> Running in 637cf6a347d8
Removing intermediate container 637cf6a347d8
 ---> 1c7f302a4cdc
Step 4/18 : RUN apt-get update && apt-get install -y     libffi-dev     libssl-dev   && apt-get clean   && rm -rf /var/lib/apt/lists/*
 ---> Running in 7968793bf3a1
Get:1 http://deb.debian.org/debian buster InRelease [121 kB]
Get:2 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [243 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7906 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [7868 B]
Fetched 8396 kB in 1s (7281 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
libffi-dev is already the newest version (3.2.1-9).
libssl-dev is already the newest version (1.1.1d-0+deb10u3).
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
Removing intermediate container 7968793bf3a1
 ---> dc46251ce134
Step 5/18 : RUN mkdir -p /etc/jasmin/resource     /etc/jasmin/store     /var/log/jasmin   && chown jasmin:jasmin /etc/jasmin/store     /var/log/jasmin
 ---> Running in a8d8cc3a5615
Removing intermediate container a8d8cc3a5615
 ---> a6f943855a81
Step 6/18 : WORKDIR /build
 ---> Running in 146c74d281f7
Removing intermediate container 146c74d281f7
 ---> 1d6b603d40bb
Step 7/18 : COPY . .
 ---> 3a549bb66a06
Step 8/18 : RUN pip install .
 ---> Running in 0b6aec919fd1
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
The command '/bin/sh -c pip install .' returned a non-zero code: 1

and I'm getting the above error. Any help on this one?

-------EDIT----- 
Cloned the repo and build the image locally 
root# docker build ./jasmin -f ./jasmin/docker/Dockerfile

Now the new error is 
Step 10/18 : WORKDIR /usr/jasmin
 ---> Running in 3aa64f05bcee
Removing intermediate container 3aa64f05bcee
 ---> 5c03df7a51a5
Step 11/18 : RUN sed -i '/\[jcli\]/a bind=0.0.0.0' /etc/jasmin/jasmin.cfg
 ---> Running in bed661d70c69
sed: can't read /etc/jasmin/jasmin.cfg: No such file or directory
The command '/bin/sh -c sed -i '/\[jcli\]/a bind=0.0.0.0' /etc/jasmin/jasmin.cfg' returned a non-zero code: 2

**Comment by KamuiX** [comment]
Thanks for the 0 support. Even a guideline would have been fine.

For anyone that's having the same issues as me, just skip the "docker build" methods. The project supports docker-compose, an extra software add-on to docker that handles build and deploy of multiple images. 
1) Download docker-compose 
2) Clone the jasmin project and in root directory 
3) Be sure that python 3 is your default python command
4) Execute "docker-compose up" in project's root directory. Everything will be ready in no time.

**Comment by farirat** [comment]
Hey @KamuiX 

Packaging of 0.10 branch is still in progress, to date, there's only deb packages that are tested and available, we're working on rpm and docker, the documentation is still not updated regarding the 0.10 branch as well.

I'm noting your feedback anyway, thanks !
