### ISSUE TITLE
How to log ESME_RDELIVERYFAILURE using sms_logger ?

### ISSUE THREAD

**Issue by danielferrer** [jookies/jasmin#915]
I'm using misc/scripts/sms_logger.py to get a "cdr" of sent messages, and to get DLR status.
I'm using a interceptor script, and I want to reject some messages dinamically, according to some variables, for example I want to limit the number of messages delivered per hour.

I see that rejected messages (smpp_status > 0) are not logged using this script, I think that there's no info in AMQP queue.
Is there a way to log rejected messages ? How you think is the best wat to acomplish this task ?

Thanks in advance

**Comment by magojr** [comment]
For what I know the logger consume a queue that get enabled in cfg. Jasmin log in that queue every "transaction" intended as every sms or DLR sent/received. If the error prevent the transaction, i think (but i'm not realy sure) that it doesn't get queued. So you should log other cases into the rabbitMQ log queue also from the interceptor and from the error managment (Eg. where the error is logged into the logfile).
In the source code you probably have the queue handlers "ready to use" and it probably doesn't involve in heavy overhead.
In the interceptor I think you haven't got that handler to RabbitMQ  so it may be a bit "heavy" to connect everytime the amount of hourly SMS get passed. Use a direct mysql connection in the interceptor move the bottleneck from connecting to rabbit versus connecting to mysql, so it may result heavier....
I may miss something, so I suggest to verify if the RabbitMq handler is already present in the intercetor, in that case it may be used without slow down the overall process so much

**Comment by farirat** [comment]
The sms_logger is a passive listener of messaging traffic and can not be active (block or do whatever logics), Jasmin uses "topic" exchange type which allow you to get a cloned copy of every published message in a dedicated queue to your app (sms_logger), here's a very simple tutorial explaining how the topic exchange works: https://www.rabbitmq.com/tutorials/tutorial-five-python.html

If you need to block messages, then you need to use the interceptor: https://docs.jasminsms.com/en/latest/interception/index.html

**Comment by danielferrer** [comment]
> The sms_logger is a passive listener of messaging traffic and can not be active (block or do whatever logics), Jasmin uses "topic" exchange type which allow you to get a cloned copy of every published message in a dedicated queue to your app (sms_logger), here's a very simple tutorial explaining how the topic exchange works: https://www.rabbitmq.com/tutorials/tutorial-five-python.html
> 
> If you need to block messages, then you need to use the interceptor: https://docs.jasminsms.com/en/latest/interception/index.html

Ok, I've a simple interceptor, that returns:
`# Return ESME_RDELIVERYFAILURE
smpp_status = 254`

Interceptor runs:
2021-04-19 05:31:40 INFO     770 Setting http_status to 520 when having smpp_status = 254 and http_status = None.
2021-04-19 05:31:40 INFO     770 Returning statuses: {'smpp_status': 254, 'http_status': 520, 'extra': {}}

sms_logger script binds to "submit.sm.*" and "submit.sm.resp.*" routes to track sent messages  and to "dlr_thrower.*" to track DLRs 
What topic can I use to bind to message queue to track messages before interceptor (so I can log them) ?
