### ISSUE TITLE
How do we pass these additional parameters suggested in the SMPP specification

### ISSUE THREAD

**Issue by rahcomp** [jookies/jasmin#918]
How do we pass these additional parameters suggested in the SMPP specification?

These parameters have been made mandatory in SubmitSM 
 as per revised Indian telecom regulations, but I am unable to figure out how these can be sent in Jasmin?

<img width="599" alt="SMPP" src="https://user-images.githubusercontent.com/6967428/97636290-e8357e80-1a5e-11eb-9e62-b4ddb1d9f924.PNG">

**Comment by surinderdeveloper** [comment]
@rahcomp have you found any solution for this? me too in the same situation where I need it.
