### ISSUE TITLE
long_content_split	udh not working

### ISSUE THREAD

**Issue by mrsanvicente** [jookies/jasmin#920]
Hello everybody!

I have enabled udh at the jasmin.cfg at the [http-api] section.
long_content_split = udh
I would expect that longer messages than 160 charaters would be split?  If that assumption is correct, it is nor working.

Or how can i sent split messages with udh optional parameters?

Thanks alot!

**Comment by farirat** [comment]
How is it splitting the multiparts with your config ?

**Comment by mrsanvicente** [comment]
To be honest the only config related i found was on the jasmin.cfg
long_content_max_parts = 5
long_content_split = udh
I am testting with sms using http. and i dont see parameter related to udh/sar.  any clue?

**Comment by farirat** [comment]
You will not have any additional http parameters, Jasmin is transforming your http long message to smpp multiparts, the sar and udh are two different ways of making the parts, you will not see anything in the http api.

**Comment by mrsanvicente** [comment]
I got you.    In the config i chose UDH and my long http_api message is being sent as one message on smmp.  The spliting is not happening.  I might be missing some config?

Thank you

**Comment by farirat** [comment]
How do you know the splitting is messing ?

**Comment by mrsanvicente** [comment]
Hi Z
My test is sending an http_api sms longer than 160 characters ( maybe i am assuming this is the longest sms by default between smsc’s).  There is only one submit smpp message.

The other smsc accept it OK.  But after that at some point the message is discarded and not sent to the terminal because it is longer than 160 characters.

 While testing the other way, the other smsc sends splitted submits with udh headers.   This is the scenario to replicate.

Thanks

**Comment by farirat** [comment]
Can you share a wireshark screenshot of the long submit_sm sent to your smsc with more than 160 chars in it ?

**Comment by mrsanvicente** [comment]
Hello Farirat,

When taking the trace, i can see it is working fine.  ( The trace where i did not see the spliting was from a message  that was previusly cut by an app).
 So, sorry for the mistake.  And here i leave a picture of the trace. so everyone can see the split working.

Thanks for the help.  btw  the jasmin sms router works great.
![image](https://user-images.githubusercontent.com/5883115/99582427-b6ea0780-29a7-11eb-829d-aa6356864ad1.png)
