### ISSUE TITLE
dlr: NO_SMSC_DELIVERY_RECEIPT_REQUESTE

### ISSUE THREAD

**Issue by ratisystema** [jookies/jasmin#923]
Hello, when I try to send single sms everything is fine
![image](https://user-images.githubusercontent.com/73489523/100130421-21b1ac00-2e9c-11eb-8ab7-0987d3e95393.png)
when i want to send sms with 200 or more symbolic "sms X2 or more"
I cannot send the delivered request
![image](https://user-images.githubusercontent.com/73489523/100131050-f67b8c80-2e9c-11eb-888a-bc56ac2dc861.png)

![image](https://user-images.githubusercontent.com/73489523/100130358-0c3c8200-2e9c-11eb-9e58-1d999e6641dd.png)

**Comment by farirat** [comment]
Hello,

First, i see you're not asking for DLR: **NO_SMSC_DELIVERY_RECEIPT_REQUESTED**.
Second, that error is caused by a non-standard parameter in the DLR pdu: **more_messages_to_send**

**Comment by ratisystema** [comment]
Hello
![image](https://user-images.githubusercontent.com/73489523/100238022-24b6a600-2f49-11eb-914b-18471ad52be0.png)
![image](https://user-images.githubusercontent.com/73489523/100238083-3bf59380-2f49-11eb-8af2-99c249a15d87.png)
![image](https://user-images.githubusercontent.com/73489523/100238686-ed94c480-2f49-11eb-8162-1ad63c17704e.png)
![image](https://user-images.githubusercontent.com/73489523/100238978-45cbc680-2f4a-11eb-8d1b-efc00fd01e37.png)
I ask DLR , don't understand why in the log set NO_SMSC_DELIVERY_RECEIPT_REQUESTED. what i am not asking dlr

**Comment by hzcodertr** [comment]
use php urlencode :)
