### ISSUE TITLE
Load profile issue from jcli console. (jasmin version 0.10.5)

### ISSUE THREAD

**Issue by HariMakGit** [jookies/jasmin#924]
Dear Team,

We are evaluating jasmin sms gateway both version. (0.9.27 and 0.10.5 latest). Found some issue in load prod profile in 0.10.5 version.

For 0.9.27 
1) on jasmin deomon startup it loads prod profile correctly and working fine and data available.
2) from jcli console when use load command, it also working fine. 
3) We checked the router.log for troubleshoot.

For 0.10.5
1) on jasmin deomon startup it loads prod profile correctly and working fine and data available. (i.e user)
2) from jcli console when use load command, command executed successfully. but user data not loaded in memory. 
3) We checked the router.log for troubleshoot. and found that loading sequence of prod. profile issue. and same i sharing u log. it removes the all users. but not adding memory.
4) This issue happens while using load from jcli console.  but on jasmin restart it working fine.

Also sharing logs for ur reference.  Please find attachment
(1) router-0.9.27.txt (2) router-0.10.5.txt

There is no error in logs. But issue in loading prod profile sequence. i have highlighted user record added in user profile loading (green), then after when group profile loaded user has been removed (red). You can see attached screenshot. and also you can refer logs in router-0.10.5.txt.

We also checked with 0.9.27. this issue not happening in version 0.9.27 you can have idea of user loading sequence in  router-0.9.27.txt. 
{ 
Group loading : Line No Ref : 13 to 48
User Loading , Line No Ref : 49 to 52 
}
![image-20201106-054216](https://user-images.githubusercontent.com/46016352/100196347-be1c9280-2f1e-11eb-9752-cdd193c88fe1.png)
[router-0.9.27.log](https://github.com/jookies/jasmin/files/5595068/router-0.9.27.log)
[router-0.10.5.log](https://github.com/jookies/jasmin/files/5595069/router-0.10.5.log)

Thanks & Regards
Haresh

**Comment by farirat** [comment]
Hello @HariMakGit 

This issue is adressed through this freshly submitted PR #922 

Will be merged in next release (0.10.6).

**Comment by HariMakGit** [comment]
Hi @farirat,

Thanks for prompt response. 

Thanks & Regards,
Haresh

**Comment by memaskal** [comment]
Hello @farirat 

We observed another concerning thing. This is that the MoRouter configuration is not loaded in time 
thus leading to messages to be discarded !!!

What happened is that the  "Router_PB_deliver__sm" queue contained a couple of messages, 
then we did a restart to the Jasmin service and we observed that no MO message was thrown to
our application. 

In the router.log  we saw "No route matched this DeliverSmPDU", and later on the registration
of the MO Router, leading to the messages being purged !!!

Can you please check that PR #922 addresses this issue as well? 

![router log](https://user-images.githubusercontent.com/782005/100863093-b750cb00-349c-11eb-9e37-707368572cf0.png)
