### ISSUE TITLE
Content replacer 

### ISSUE THREAD

**Issue by mhamidawad** [jookies/jasmin#927]
Hello,
Is there way to replace signal word in message content using
Regular expression or filters 

Hello, my code is 1224
Hello, my code is \d

To 

Hello, my pin is 1224

**Comment by mhamidawad** [comment]
@farirat

**Comment by mhamidawad** [comment]
any idea?

have I write python to look up in pdu body for string and replace it

**Comment by mhamidawad** [comment]
Please help me if any one can help

**Comment by farirat** [comment]
Did you take the tour through the interception ? that's something can be done.
