### ISSUE TITLE
SMS Traffic Lost - on Jasmin Instance Crash

### ISSUE THREAD

**Issue by HariMakGit** [jookies/jasmin#928]
Dear Team,

We are performing load testing on jasmin with below scenario. 

Please find below activity we performed

Steps:

1. Customer(jmeter) sending continues 400 sms per second traffic on jasmin sms gateway. [http api]
2. Jasmin Response with 200 [success] with queue-messageid.
    [Customer (jmeter) ----> Jasmin -----> Provider]
3. Jasmin route these traffic on provider.

Problem:
1. Jasmin is processing very slow to route on provider queue [**submit.sm.<<provider>>**], mean while jasmin engine crashed and all traffic which are not routed to provider queue [**submit.sm.<<provider>>**] lost.
2. Also we have observed that when customer traffic is ongoing at that jasmin submit_sm is slow (25-30 /sec) and once customer traffic stop, after jasmin submit_sm raise up (400++ /sec).
3. Customer get HTTP 200 for all request and we get log in http-access , http-api & smppclient but message not publish on rabiitmq(submit_sm)

Any how we want to avoid traffic loss which jasmin has accepted from customer responded with queue-messageid. Please help or suggest,

Thanks & Regards,
Haresh

**Comment by magojr** [comment]
I cannot answer about the crashes (let's wait for the jasmin team), but I may ginve you an interesting point of view: are you sure you are replicating a "real world case"?
In the gigabit local network of our server farm I reproduce a single http client sending sms "as fast as possible" to a jasmin box and I cannot achieve more than 7sms/sec. Bottleneck was the http connection itself. Client and server wasn't having any load but the http connection need about 0,16-0,18 sec to be activated, used to send and destroyed everytime. It means that you need about 57 continuative active connection from customer toreach 400sms/s in http, all usin http API (probably jmeter worked at 60 connection/s). The SMPP protocol bind one single time and keep the channel open so usually customers that has a "so high" flow of SMS use SMPP for their convenience (or they should).
Consider that 400 sms/sec  = means 11 milions of sms in 8 working hours so, we are speaking about 330M sms/month or about 5 to 8 Million of $/month of traffic (supposing you are using veruy very low wholesale tarif for these big quantity that you reach).
I think that a so high budget should involve in the use of the right protocol to achieve the result and in this case HTTP API should be avoided.
An interesting stress test may be the sending of 400 sms/s to jasmin via SMPP, I'm also interested in stress test and scalability with high volume of sending.
Hope it may help even if it doesn't go inside the tech point.

**Comment by HariMakGit** [comment]
> 
> 
> I cannot answer about the crashes (let's wait for the jasmin team), but I may ginve you an interesting point of view: are you sure you are replicating a "real world case"?
> In the gigabit local network of our server farm I reproduce a single http client sending sms "as fast as possible" to a jasmin box and I cannot achieve more than 7sms/sec. Bottleneck was the http connection itself. Client and server wasn't having any load but the http connection need about 0,16-0,18 sec to be activated, used to send and destroyed everytime. It means that you need about 57 continuative active connection from customer toreach 400sms/s in http, all usin http API (probably jmeter worked at 60 connection/s). The SMPP protocol bind one single time and keep the channel open so usually customers that has a "so high" flow of SMS use SMPP for their convenience (or they should).
> Consider that 400 sms/sec = means 11 milions of sms in 8 working hours so, we are speaking about 330M sms/month or about 5 to 8 Million of $/month of traffic (supposing you are using veruy very low wholesale tarif for these big quantity that you reach).
> I think that a so high budget should involve in the use of the right protocol to achieve the result and in this case HTTP API should be avoided.
> An interesting stress test may be the sending of 400 sms/s to jasmin via SMPP, I'm also interested in stress test and scalability with high volume of sending.
> Hope it may help even if it doesn't go inside the tech point.

Thanks for sharing your view. We are also exploring to load test via SMPP.  But Main concern of traffic/sms data should not be loss once jasmin has accepted via http or smpp.

**Comment by khalilelsett** [comment]
> Dear Team,
> 
> We are performing load testing on jasmin with below scenario.
> 
> Please find below activity we performed
> 
> Steps:
> 
> 1. Customer(jmeter) sending continues 400 sms per second traffic on jasmin sms gateway. [http api]
> 2. Jasmin Response with 200 [success] with queue-messageid.
>    [Customer (jmeter) ----> Jasmin -----> Provider]
> 3. Jasmin route these traffic on provider.
> 
> Problem:
> 
> 1. Jasmin is processing very slow to route on provider queue [**submit.sm.<>**], mean while jasmin engine crashed and all traffic which are not routed to provider queue [**submit.sm.<>**] lost.
> 2. Also we have observed that when customer traffic is ongoing at that jasmin submit_sm is slow (25-30 /sec) and once customer traffic stop, after jasmin submit_sm raise up (400++ /sec).
> 3. Customer get HTTP 200 for all request and we get log in http-access , http-api & smppclient but message not publish on rabiitmq(submit_sm)
> 
> Any how we want to avoid traffic loss which jasmin has accepted from customer responded with queue-messageid. Please help or suggest,
> 
> Thanks & Regards, Haresh



> > I cannot answer about the crashes (let's wait for the jasmin team), but I may ginve you an interesting point of view: are you sure you are replicating a "real world case"?
> > In the gigabit local network of our server farm I reproduce a single http client sending sms "as fast as possible" to a jasmin box and I cannot achieve more than 7sms/sec. Bottleneck was the http connection itself. Client and server wasn't having any load but the http connection need about 0,16-0,18 sec to be activated, used to send and destroyed everytime. It means that you need about 57 continuative active connection from customer toreach 400sms/s in http, all usin http API (probably jmeter worked at 60 connection/s). The SMPP protocol bind one single time and keep the channel open so usually customers that has a "so high" flow of SMS use SMPP for their convenience (or they should).
> > Consider that 400 sms/sec = means 11 milions of sms in 8 working hours so, we are speaking about 330M sms/month or about 5 to 8 Million of $/month of traffic (supposing you are using veruy very low wholesale tarif for these big quantity that you reach).
> > I think that a so high budget should involve in the use of the right protocol to achieve the result and in this case HTTP API should be avoided.
> > An interesting stress test may be the sending of 400 sms/s to jasmin via SMPP, I'm also interested in stress test and scalability with high volume of sending.
> > Hope it may help even if it doesn't go inside the tech point.
> 
> Thanks for sharing your view. We are also exploring to load test via SMPP. But Main concern of traffic/sms data should not be loss once jasmin has accepted via http or smpp.

how did you resolve your issue?
