### ISSUE TITLE
a bytes like object is required, not str

### ISSUE THREAD

**Issue by kimseasok** [jookies/jasmin#929]
I'm using jasmin 0.10.6.

I encountered the above error message in the rest api.

Anyone, please kind advice me what to solve the issue.

**Comment by farirat** [comment]
Please provide more information to reproduce the issue.

**Comment by kimseasok** [comment]
@farirat , it occurs when send the message through the api and create filter in jcl.
Some of these issue were in my contribution.
Thus, I'll close this issue now.
