### ISSUE TITLE
[10.6]  [DEB/UBUN]  Unable to locate package jasmin-sms-gateway

### ISSUE THREAD

**Issue by EmileSteelman** [jookies/jasmin#939]
root@ubuntu:~# curl -s https://setup.jasminsms.com/deb | sudo bash
Detected operating system as debian/buster.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing debian-archive-keyring which is needed for installing
apt-transport-https on many Debian systems.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/jookies_jasmin-sms-gateway.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
root@namtelecom:~# apt-get install jasmin-sms-gateway
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package jasmin-sms-gateway
root@ubuntu:~#

root@ubuntu:~# apt-get update
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://mirrors.online.net/debian buster InRelease
Hit:3 http://download.proxmox.com/debian buster InRelease
Err:4 https://enterprise.proxmox.com/debian/pve buster InRelease
  401  Unauthorized [IP: xxxxxxx443]
Ign:5 https://packagecloud.io/jookies/jasmin-sms-gateway/debian buster InRelease
Err:6 https://packagecloud.io/jookies/jasmin-sms-gateway/debian buster Release
  404  Not Found [IP: xxxxxx 443]
Reading package lists... Done
E: Failed to fetch https://enterprise.proxmox.com/debian/pve/dists/buster/InRelease  401  Unauthorized [IP: xxxxxx 443
E: The repository 'https://enterprise.proxmox.com/debian/pve buster InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://packagecloud.io/jookies/jasmin-sms-gateway/debian buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by farirat** [comment]
What is the outcome of:
`cat /etc/issue`

?

**Comment by farirat** [comment]
or `lsb_release -a`

**Comment by EmileSteelman** [comment]
root@namtelecom:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

**Comment by farirat** [comment]
That's a debian !

Deb packages are only for Ubuntu 20.04+, from the docs:

<img width="779" alt="Screen Shot 2021-01-06 at 10 07 13 PM" src="https://user-images.githubusercontent.com/1020111/103819866-8d765f80-506b-11eb-8993-dca295b8a047.png">
