### ISSUE TITLE
How can I debug my EvalFilter code?

### ISSUE THREAD

**Issue by kimseasok** [jookies/jasmin#940]
Hello everyone!
I've been trying to create an EvalFilter which connect to postgresql and get some information such as country code, phone prefix.
Unfortunately, there is no luck.

I got the below message:

```
[2021-01-07 16:14:03,820: ERROR/ForkPoolWorker-2] [d485bb1a-d7e9-4385-bd12-aa7cd5654dc3] Error "Unknown error: name 'relationship' is not defined
[2021-01-07 16:14:03,822: INFO/ForkPoolWorker-2] Task jasmin.protocols.rest.tasks.httpapi_send[cda0964c-cfda-497c-9204-72722ba89bbc] succeeded in 0.535018092s: None
```

I've been figuring out how to solve the issue in my code, but I could not find any way to debug the code.

Anyone please kind advice me how to debug my code in EvalFilter?

My code work well when execute in the terminal, but not when adding to pyCode param

I'm using SQLAlchemy for database manipulation.

Thanks~

**Comment by kimseasok** [comment]
@farirat could you please advice how to setup debugpy with Jasmin? Or you can tell me anything else regarding the debuging?

**Comment by farirat** [comment]
evalfilter is not intended for making lookups abroad ..

better to use the interceptor.

**Comment by kimseasok** [comment]
@farirat , thanks for responding.
My purpose is only to query the database and match the source_addr with database then return result=True for the current router.
Anyway, I have another question. is it possible to get current route order in the EvalPyFilter script?

**Comment by farirat** [comment]
I don't think so, the route object is not passed to the filteR.

**Comment by kimseasok** [comment]
Thanks. 
Anyway, how about the interceptor? 
Can I access to the route object in the interceptor?
Or please advice how to pass the route object to the interceptor?

**Comment by magojr** [comment]
Hi @kimseasok, farirat, will surely be more precise than me but the advice i've ssen in the past to manage route from the interceptor is to "tag" the message and use the tag in routing.
Not sure if it may be usefull for your case but... 
[https://docs.jasminsms.com/en/latest/interception/index.html#hlr-lookup-routing](https://docs.jasminsms.com/en/latest/interception/index.html#hlr-lookup-routing)
