### ISSUE TITLE
(jasmin.cfg / smpp-server) Backup methods 

### ISSUE THREAD

**Issue by geethupendra** [jookies/jasmin#943]
Hello ,

Is there a way to set up the backup **(smpp-server)** on the **(jasmin.cfg)** file

_** let say if down the primary then send the message through the secondary server..?_

```
[smpp-server]

# SMPP Server identifier
#id					= "smpps_01"

# If you want you can bind a single interface, you can specify its IP here
#bind				= 0.0.0.0

# Accept connections on the specified port, default is 2775
#port				= 2775
```

Thanks
Geeth

**Comment by farirat** [comment]
Read the docs and find the "FailoverMTRoute" or "FailoverMORoute".
