### ISSUE TITLE
Docker Image: Redis Errors and Unable to Connect jCli

### ISSUE THREAD

**Issue by fullbuffer** [jookies/jasmin#944]
I've never used docker before, but I've followed the docker installation instructions found on the installation page (https://docs.jasminsms.com/en/latest/installation/index.html) as they seemed easy enough.  However, continuing with the next section of the instructions and trying to use the jCli doesn't seem to work.

It connects and immediately closes the connection.  I cannot find anything in the logs.

`$ telnet 127.0.0.1 8990`
`Trying 127.0.0.1...`
`Connected to 127.0.0.1.`
`Escape character is '^]'.`
`Connection closed by foreign host.`

Pulling the logs using docker doesn't yield much - though I could be doing this wrong:

```bash
$ docker logs jasmin_01
Starting interceptord
Starting jasmind
2021-01-20 15:17:47 INFO     1 Starting Jasmin Daemon ...
2021-01-20 15:17:47 INFO     1   Interceptor client Started.
```

Then getting into the container  (`docker exec jasmin_01 /bin/bash`) and checking the logs in `/var/log/jasmin`, I see the following in the redis-client.log every few seconds:

```bash
2021-01-20 15:34:46 INFO     1 Connecting ...
2021-01-20 15:34:46 INFO     1 Connection failed. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.DNSLookupError'>: DNS lookup failed: redis.
]
2021-01-20 15:34:47 INFO     1 Connecting ...
2021-01-20 15:34:47 INFO     1 Connection failed. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.DNSLookupError'>: DNS lookup failed: redis.
]
2021-01-20 15:34:48 INFO     1 Connecting ...
2021-01-20 15:34:48 INFO     1 Connection failed. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.DNSLookupError'>: DNS lookup failed: redis.
]
```

I thought that using the docker image things would "just work", but I'm more than happy to help make this work - of course, I could just be missing something easy and it will magically work - but if not, I'd like to help in any way I can and learn more about Jasmin in the process.  Cheers

**Comment by farirat** [comment]
Hello @fullbuffer 

As of v0.10 Jasmin were packaged differently, the container actually runs ONLY jasmin, you need to get redis/rabbit containers in same pod.

This is a cleaner design, based on these 10 commandments: [10 things to avoid in docker containers](https://developers.redhat.com/blog/2016/02/24/10-things-to-avoid-in-docker-containers/)

Here's a simple docker-compose.yml file you can use to start the latest 0.10 release:
```
version: "3"

services:
  redis:
    image: redis:alpine
    restart: unless-stopped

  rabbit-mq:
    image: rabbitmq:alpine
    restart: unless-stopped

  jasmin:
    image: jookies/jasmin:0.10
    restart: unless-stopped
    container_name: jasmin
    volumes:
      - /var/log/jasmin:/var/log/jasmin
    ports:
      - 2775:2775
      - 8990:8990
      - 1401:1401
    depends_on:
      - redis
      - rabbit-mq
    environment:
      REDIS_CLIENT_HOST: redis
      AMQP_BROKER_HOST: rabbit-mq
```

Just write it down in a docker-compose.yml file and spin your containers with "docker-compose up -d".

I'll update the docs with consideration to docker-compose.

**Comment by fullbuffer** [comment]
Thanks!  I’ll give this a shot. I appreciate the detailed info. You can close the ticket.

________________________________

**Comment by farirat** [comment]
I've also updated the documentation to include a simple howto, will go public when 0.10.8 is released.
