### ISSUE TITLE
Error using filter

### ISSUE THREAD

**Issue by kbadey** [jookies/jasmin#945]
Hello, we were using jasmin 0.9.27 on centos7  whithout major issue.

We would like to upgrade to 0.10.6. The installation is made with pip3.

With a basic installation, we can send message through the API. If we set up filtering (SourceAddrFilter for example) the api return an error : Error "Unknown error: cannot use a string pattern on a bytes-like object"

Here is our config : 

```
group -a
gid localgroup
ok

user -a
username localuser
password userpass
gid localgroup
uid localuser
ok

smppccm -a
cid TEST_CONNECTOR
host 127.0.0.1
port 5020
username test
password test
bind transceiver
submit_throughput 50
ok

smppccm -1 TEST_CONNECTOR

filter -a
type SourceAddrFilter
fid src2355
source_addr ^2355$
ok

mtrouter -a
type StaticMTRoute
filters src2355
connector smppc(TEST_CONNECTOR)
rate 0.00
order 10
ok
```

And the call to send a message : 
`curl -X POST "http://localhost:1401/send?username=localuser&password=userpass&from=2355&to=9640000000002&content=hello"`

And the response : 
`Error "Unknown error: cannot use a string pattern on a bytes-like object"`

Do we have to change the way our call are made or is there any issue with the filters ?

Thank you for your help!

**Comment by farirat** [comment]
hello @kbadey 

Thank you for reporting this blocking issue ! This is unfortunately a forgotten issue from the py2>py3 migration.

Will address it in the current release process (0.10.8) in high priority.
