### ISSUE TITLE
Problem sending Latin chars

### ISSUE THREAD

**Issue by juanantoniotv** [jookies/jasmin#961]
I tested sending some Latin characters like á é í ó ú, but I received 0x000064 error and the SMPP connection is reset, any idea what is the problem?, I trying to get the message content in the interceptor but does crashing before the interceptor process.

**Comment by magojr** [comment]
How are you sending the message? SMPP or HTTP? 
Using SMPP you should previowsly encode the text using GSM alphabet [https://en.wikipedia.org/wiki/GSM_03.38](https://en.wikipedia.org/wiki/GSM_03.38).
Not sureif it's needed on the web API but if you use the SMPP protocol to inject SMS you need to convert text from Latin to gsm 3.38.

**Comment by juanantoniotv** [comment]
By SMPP, but the problem is that jasmin does crash, and all my users connections are reset. I want to protect from this issue, maybe detecting the message content before processing.

**Comment by magojr** [comment]
You should check that every character is present into the 7bit gsm table or into the gsm extended table (only if preceeded from the ESC char 0x1B ).
I use the python 2 compatible version but It never crashes using the right coding (also with italian letters àèìòù) and it should works right also in the latest version.

**Comment by juanantoniotv** [comment]
Sure, in Python2 have not the problem but some users doesn't set the correct format and I have to detect and convert.

**Comment by farirat** [comment]
hey @juanantoniotv 

Is this in 0.10.8 ? do you have any log trace on the crash ?

**Comment by juanantoniotv** [comment]
> hey @juanantoniotv
> 
> Is this in 0.10.8 ? do you have any log trace on the crash ?

Yes it's jasmin-0.10.8, also have a issue when set a DestinationAddrFilter, the eval regex string didn't work, I trying many ways the regex string, but the filter blocks all messages.

**Comment by farirat** [comment]
Please send your log where i can see the crash tracebacks

**Comment by juanantoniotv** [comment]
> Please send your log where i can see the crash tracebacks

I'll try in debug mode, because jasmind service crash before write the logs (in the 1st issue when send áéíóú)

**Comment by Janai96** [comment]
just put "coding => 7" in params
