### ISSUE TITLE
Make a new tagged release

### ISSUE THREAD

**Issue by guohaolee** [jookies/jasmin#964]
Hi, 

Just wanna raise an small issue.

Looking at your tag, the last release was **v0.8.10** which is way back to 2015. 

And there are 796 new commits since then to master. 

Just wondering if you can make a new tag and release so we can have a stable version?

Cheers.

**Comment by farirat** [comment]
Hey @guohaolee 

The releases are published to rpm/deb, docker and pypi packages, there's no releases to be downloaded from github, please refer to the docs.

The last release to date is 0.10.8.

**Comment by guohaolee** [comment]
Hey @farirat 

Any reason for this for not making a release in Github? 

Cheers.

**Comment by farirat** [comment]
It is easier and more straightforward to get the releases as pypi packages (or deb, rpm, docker) ...

Every package has its own dedicated branch on github anyway, please check the branches.

**Comment by guohaolee** [comment]
Hi @farirat 

Thanks for the information. 

Just to confirm if I use branch 0.10.9 in this git repo, it will align with the package release like in https://pypi.org/project/jasmin/0.10.9/ correct?

**Comment by farirat** [comment]
true !

**Comment by guohaolee** [comment]
Thanks! closing it for now
