### ISSUE TITLE
Setting "bind_ton 1" on connector is broken

### ISSUE THREAD

**Issue by texpert** [jookies/jasmin#97]
Hi, Fourat!

My gateway told me to set TON and NPI both 1. So, I set "bind_ton 1" when creating new connector - and everything went broken - see the connector log:

system_type: ''
interface_version: 52
addr_ton: 1
addr_npi: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f3f61164410>, 9, 'ISDN')
address_range: None
]
2015-02-25 11:11:15 ERROR    1818 Bind failed [[Failure instance: Traceback: <type 'exceptions.ValueError'>: Unknown addr_ton name 1
/usr/local/lib/python2.7/dist-packages/jasmin/vendor/smpp/twisted/protocol.py:714:bindAsTransceiver
/usr/local/lib/python2.7/dist-packages/jasmin/vendor/smpp/twisted/protocol.py:609:bind
/usr/local/lib/python2.7/dist-packages/jasmin/vendor/smpp/twisted/protocol.py:365:sendBindRequest
/usr/local/lib/python2.7/dist-packages/jasmin/vendor/smpp/twisted/protocol.py:368:sendRequest
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:139:maybeDeferred
/usr/local/lib/python2.7/dist-packages/jasmin/protocols/smpp/protocol.py:224:doSendRequest
/usr/local/lib/python2.7/dist-packages/jasmin/vendor/smpp/twisted/protocol.py:377:doSendRequest
/usr/local/lib/python2.7/dist-packages/jasmin/vendor/smpp/twisted/protocol.py:356:sendPDU
/usr/local/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py:911:encode
/usr/local/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py:970:encodeBody
/usr/local/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py:1007:encodeRequiredParams
/usr/local/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py:85:encode
/usr/local/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py:254:_encode
]]. Disconnecting...
2015-02-25 11:11:15 WARNING  1818 Disconnecting...

**Comment by fourat** [comment]
Please tell the release you're using:

    $ python
    Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
    [GCC 4.8.2] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import jasmin
    >>> print jasmin.__release__

**Comment by texpert** [comment]
Python 2.7.9 (default, Dec 11 2014, 17:21:00) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import jasmin
>>> print jasmin.__release__
0.6b2
>>>

**Comment by texpert** [comment]
Moreover, prior to this, I was trying to set bind_ton and src_ton to 1, updating an existing connector. Typing ok worked normally, but then, typing smppccm -s cid_name, caused the jcli to exit without any warnings or messages...
