### ISSUE TITLE
Jasmin SMS Gateway RHEL 7.9 support

### ISSUE THREAD

**Issue by darunsta** [jookies/jasmin#970]
Is it possible to install latest jasmin-sms-gateway-0.10.9-1.x86_64.rpm to Red Hat Enterprise Linux 7.9? I have some problems to find all depends from EPEL. 

If latest Jasmin SMS releases are not supporting RHEL7 is it possible to use some older release?

**Comment by wahyuway** [comment]
I am running jasmin in RHEL environment using Docker. You should try it.

**Comment by darunsta** [comment]
Yes I started to run jasmin with Docker also

**Comment by medabdellahi** [comment]
Hi,
 I have the same problem but i don't want to use docker 
there another solution for me ?

thanks

**Comment by tarikogut** [comment]
i can install :)
