### ISSUE TITLE
How to get operator smsc 

### ISSUE THREAD

**Issue by Samuel-Momoh** [jookies/jasmin#979]
From what i understand about jasmine as an sms gateway, is it simply serve as a connection between a third party user and MNO. 
Now we know that to send sms to a specific mobile service provider their smsc host, port and user credential is required. Here is my question 
1.How do we get across to this SMSC of mobile operator?
2.Since it seems other third party sms gateway offer smsc services as a full package with an sms gateway software, where does jasmine fit in here? 
3. It is possible to implement otp on jasmine sms gateway
4.What makes jasmine so special if it does not offer full service like other sms gateway

**Comment by magojr** [comment]
Hi Samuel,
I'm not any of the jasmin staff but I can reply you.
1. You need an agreement with an upstream provider, it may be a telecom operator or another company that has agreements with various telecom operator directly or indirectly. 
2. You already answered to yourself in the question. Jasmin is a software. If you need that function, the software may do it for you. If you are paying a service that give you also the SMSC software, you probably don't need Jasmin (or any other SMSC software), you may check PROs and CONs of each one tho choose. In this case consider that in Jasmin you can setup hundred of different services, chose the best foreach case.  If yoy have "a full service"  from an upstream provider, you probably are forced to use that specific operator/service. It may be good or not... It depends on your needs and from the quality/cost of the upstream provider itself.
3. OTP stay for One Time Password so you can send the OTP using any SMSC. The SMSC is a "transport layer" so you can use it to send any text unless your upstream provider block the content for its content policy (eg. some of them block sms containing  bit.ly uls).
4. You are comparing an open source (free) software with a pay "full service" (that give you also an SMSC software), it doesn't make any sense IMHO. It's like to compare a car with a car engine...  You may compare the best car engine with the worst car but if you need to go home, you prefere the worst car, if you need to contruct cars, you want surely the best engine, they cover different needs...

Hope it may help you.
have a nice day!

**Comment by Samuel-Momoh** [comment]
@magojr Thanks you just hit the spot, exactly the answer i was looking for 😃
