### ISSUE TITLE
How to replicate Jasmin container between 2 instance?

### ISSUE THREAD

**Issue by kimseasok** [jookies/jasmin#981]
Hello Everyone.
I'm deploying jasmin using ecs.
I replicated jasmin container into 2 different and mapped /etc/jasmin/store to the same amazon EFS accesspoint.
However, when create a new user, the data didn't replicated between the Jasmin container.
Anybody, please advice me how Jasmin read and write User, Route, and other information.
Is everything is store in Redis in-memory database?
Also, any guy for high available?

**Comment by kimseasok** [comment]
@farirat, could you please help me to answer the above question?

**Comment by polyurethanegoose** [comment]
It looks like everything is kept in-memory (but not in Redis! Jasmin itself handles this data) unless you save data to disk by issuing `persist` command on admin. In your case i think that you need to
1. Create user on _server-1_
2. Issue a `persist` command on _server-1_
3. Logon to _server-2_
4. Issue `load` command on _server-2_
