### ISSUE TITLE
python-jasmin vs jasmin-sms-gateway

### ISSUE THREAD

**Issue by Sp0rN** [jookies/jasmin#985]
Hi Guys,

Couple months (maybe a year) ago we installed `python-jasmin 0.9.29` and it has been running fine.

We are trying to update it via the deb package, but according to the repo, 0.9.29 is the latest `python-jasmin`.

There is however 0.10.9 of `jasmin-sms-gateway` , is this the same package but with a new name? And if so, is there a specific process to upgrading?

**Comment by farirat** [comment]
Hello @Sp0rN 

0.9 releases are based on python2, the latest one is 0.9.29.
0.10 releases are based on python3, you can backup your /etc/jasmin and remove 0.9 then install 0.10, and restore your configs.

**Comment by Sp0rN** [comment]
Thanks @farirat !
