### ISSUE TITLE
Adding more consumers to Connector queues

### ISSUE THREAD

**Issue by ghowkay** [jookies/jasmin#987]
Hello @farirat ,
Great work on this project so far. I currently run this code in production with some customization to suite our use case. I would like to find out how i can increase the number of consumers on a connector queue for parallelism and improve message processing speeds.

Thanks

**Comment by professor93** [comment]
@farirat Please respond this question. Because I have problem with handling queues very slow. Daily transactions avg: 2-3Millions.
