### ISSUE TITLE
Missing message_id in submit_sm_resp from interceptor

### ISSUE THREAD

**Issue by gsantosgonzalez** [jookies/jasmin#993]
My provider is not recieving message_id in my submit_sm_resp. I have an interceptor for their messages where I return a 200 HTTP status and 0 SMPP status. I've tried whit extra: { message_id: x } but I don't see any message_id. Does anybody know how to send the message_id in submit_sm_resp from an interceptor? Thank you!

**Comment by nkapustin** [comment]
Hi @gsantosgonzalez , you can add `extra['message_id']=your_message_id` to your interceptor
